#!/usr/bin/env node
import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const WORK = path.dirname(fileURLToPath(import.meta.url));
const he = JSON.parse(fs.readFileSync(path.join(WORK, '_he-232.json'), 'utf8'));

/** @type {Record<string, Record<string, string>>} */
const T = {
  'baer-heitev': {
    '5#ג': `I will do. And afterward he did that thing — some say forbidden since it could be he did not violate the condition; it appears what the Rav wrote "some disagree" applies here too; if he said except meat all agree it is not a vain vow; all the more if he said except grain since grain includes the five species — end quote, Shach.`,
    '12#א': `Constraints. Shach: it appears even though he did not stipulate at time of vow — for such constraint we say he did not vow; Beit Yosef in name of Rabbi Yerucham: the river blocked means the river swelled from snowmelt — uncommon constraint; if common he should have anticipated; if not stipulated included in vow — end quote; and it appears likewise uncommon/common constraint in vows — illness we say in Gemara is common/uncommon constraint and nevertheless in vows it is constraint.`,
    '12#ב': `Money. Bach challenged this from what Rema wrote in Orach Chayyim siman 656 that he give all his money before transgressing; therefore uprooted this law here from halachah; and difficult — for here he did not transgress at all since we say he did not swear intending to squander much money — end quote, Taz; and written in responsum of Maharam Galanti: one who fixed time to pay his fellow by a set time and if he does not pay he will forbid himself meat and wine and descend from his property before the time — exempt from his oath.`,
    '12#ג': `Exempt. Taz wrote per what is written in siman 228 seif 41 that there is distinction between saying on day X and saying to day X — here too must say to day.`,
    '12#ז': `Transgressed. And written in responsum of Rashba likewise if they warned him and he did not concern himself to say at time of warning and ate — all the more when he said nevertheless I am not believed.`,
    '12#ח': `Wrote. In Semak Choshen Mishpat siman 72 s.k. 15 wrote in name of Terumat HaDeshen: if written in his handwriting that he is obligated to pay and swore on this and afterward says he only wrote thus and did not swear — if claimant admits obviously no concern for this oath at all; if he does not admit regarding money his law is like any document without oath — end quote; Shach wrote: appears this is when he gives excuse for his words; but when he gives no excuse and claims simply I did not swear — even if claimant admits he did not swear before him, since he admitted he made himself a piece of prohibition; when claimant says you swore before me — even when defendant gives excuse his claim is no claim; see Choshen Mishpat siman 73 seif 6 (see above siman 228).`,
    '14#ד': `To nullify. Taz wrote Rema's words are astonishing; difficult — for Semak there said only that if already swore his oath is nothing even without nullifying in heart; but ab initio obviously must nullify in heart and not swear falsely — see there (in Nekudot HaKesef he challenged and wrote Semak there only means if already swore; ab initio obviously must nullify in heart).`,
    '15#א': `Actually. Even though he did not nullify in heart. Taz and Shach; Mahari Weil wrote: specifically when they constrained him to give something; but swore not to reveal a matter — cherem applies.`,
    '16#ב': `One. Shach left Rema's words in doubt; in responsum of Ramban it appears even if husband from another place — see there; see Even HaEzer siman 75.`,
    '17#_': `She vowed. See above siman 231 s.k. 2 in name of Taz.`,
  },
  'beer-hagolah': {
    '7#_': `Question of Ravina from Rav Ashi there Babylonian Nedarim page 21 side 1 and 2; unresolved; Rosh and Ran wrote we rule stringently.`,
    '8#_': `Mishnah there page 27 side 1 and as explained there in Gemara.`,
    '10#_': `There in Gemara "I will prepare his feast" — as Rosh explains there (not as Bach per Rosh's opinion).`,
    '19#_': `As resolution of Rabbah there in Gemara — stringently; likewise Rambam chapter 8 of Laws of Vows; likewise Rosh and Ran; in name of Ramban and in Tosafot and Rosh there — since he changed his words the vow weakened; we say since part was released all is released.`,
  },
  'beur-hagra': {
    '1#א': `There are vows, etc. As Shmuel there 21 side 2 — language of Mishnah; Rav Yosef teaches another language; likewise Yerushalmi Rabbi Eliezer in name of Rabbi Chanina and Rashba in name of Rabbi Yochanan and Rav and Shmuel, etc. Rosh there.`,
    '1#ב': `And one who attaches, etc. As written above seif 5 side 1; Ran there s.v. naaseh, etc.; likewise Rosh there and in his rulings; see above seif 19.`,
    '2#א': `Konam on me bread, etc. Rosh there s.v. konam, etc.`,
    '2#ד': `And all this, etc. As text of Ran in Yerushalmi "he would place before this one and before," etc.; as explained there.`,
    '3#א': `One who invites, etc. or, etc. There 24 side 2 — halachah as Rabbi Abbahu; anonymous Mishnah implies even in second case; Ran there s.v. uleinyan.`,
    '4#ג': `And if he places, etc. Yerushalmi brought by Rosh there — see there; appears at first glance there specifically regarding vain oath; Tur siman 239 regarding vain oath; but Rivash explains likewise in vows as in vows of exhortation.`,
    '5#ב': `But if, etc. Likewise Tosafot Ketubot 71 side 1 s.v. shelo meha from end of Nedarim — if he said "be forbidden," etc.; likewise Hagahot Ashri there; but Rosh wrote such case does not take effect; Mordechai in Shevuot is uncertain.`,
    '5#ג': `And likewise if, etc. As written end chapter 3 of Bava Batra — possibly regarding fruits, etc.`,
    '6#ב': `And likewise, etc. As above at beginning; as written in Gemara "how is this inadvertent oath," etc.; see there Ran s.v. heih, etc.; and Tosafot Shevuot 26 side 1 s.v. et, etc.`,
    '8#ב': `Or when he said, etc. or, etc. See Rosh there s.v. if I had, etc. and s.v. I had, etc.`,
    '10#_': `He swore, etc. As "he stole my purse," etc. — must read thus explicitly as with stole; as Ran wrote s.v. uveit ha, etc.; likewise Taz.`,
    '11#_': `One who said, etc. As written; and in Shevuot there "how is inadvertent oath," etc.; as above.`,
    '12#ב': `And likewise if he commanded, etc. As written chapter 10 of Bava Kamma (117 side 1) "like purple cloth," etc.`,
    '12#ה': `And if he can, etc. and if when arrived, etc. all agree, etc. This per his view written siman 225 seif 41 distinguishing Rashba there whether obligated, etc.; he holds like second view there; therefore rules here one who swore, etc. and if he can, etc.; in second case wrote all agree, etc. — case where obligated anyway but if lender exempted would be exempt from oath as siman 228 s.k. 39 except cannot profit time for him; in constraint even if exempted nothing — like hung and gave; as responsum of Ramban brought Beit Yosef end siman 228 page 211 side 2; one who swore to pay by set time and master forced lender to extend — obligated already; there brought two responsa of Rashba exempt — case not obligated; wrote there even if exempted means extended as above extension of time does not help; or even actual exemption if king constrained — as Ramban responsum; therefore wrote here and if, etc. or, etc.`,
    '12#ז': `One who swore, etc. As written Nedarim 3 side 2; see Rosh there s.v. I will not exempt, etc.`,
    '12#ח': `And if not, etc. some say, etc. and some say, etc. See Orach Chayyim siman 108 seif 8 and Taz.`,
    '12#י': `When he, etc. As written chapter 9 of Shabbat (88 side 1) hence great disclaimer biblical; even though by God's will so there not be nullification as chapter 3 of Shevuot; Rabbi Yochanan challenged why not say they accepted again in Arvot; answer there also from constraint not to move them in desert; even though fulfilling His will great reward — all the more human constraint; difficult per Nedarim 28 side 1 since he said be forbidden, etc. — there only monetary constraint. Hagahot Maimoniyot end chapter 8 Shevuot; Mordechai chapter 3 Shevuot — see there.`,
    '12#כ': `Believed, etc. As we believe him he vowed with this intent — your heart upon you, etc.; and all openings and regrets; we say (chapter 2 Nedarim) unspecified vows to be stringent and their explanation to be lenient; vow in cherem and said in his cherem, etc.; in Nazir 11 side 1 some say I know the nazir, etc.`,
    '12#ל': `Or on, etc. but if, etc. Rashba there wrote specifically if they released him and he did not concern himself to say at warning and ate — all the more when he said nevertheless not believed, etc.; likewise Rambam chapter 2 law 12: swore not to eat and ate and they released him and said not in heart except not to leave and erred — not lashed until admits before eating he swore on eating or accepted warning and did not claim at warning or established denier — see there; Kesef Mishneh wrote it is Tosefta chapter 6 Taharot — believed by himself: how? vowed and said condition in heart — we listen; vowed and told him you did not vow and when arrived said condition in heart — not listened [likewise in Torat Kohanim parashat Vayikra "the prince who sins" chapter 7]. Raavad challenged — we say Nedarim 28 side 1 matters of heart are not matters; Kesef Mishneh answered: he expressed on lips in whisper; Hagahot Maimoniyot explained Gemara layperson and here Terumat HaDeshen; as written (side 1) vow in cherem, etc.; proof from tractate Kallah Rabbi Akiva swore and nullified in heart [but Mordechai beginning Shevuot wrote Rabbi Akiva expressed on lips; also explained like constraint and Semag explained accidentally — see there].`,
    '14#א': `Or one who swears. Meaning even to swear falsely literally as Yerushalmi asked in Nedarim — in Shevuot not found; Rabbi Yishmael taught do not swear in My name falsely — one swears to murderers cherems and tax collectors — meaning even such case; otherwise it is Mishnah; and Shach.`,
    '14#ה': `Provided, etc. Ran there s.v. how did he vow language, etc. — meaning, etc.`,
    '14#ו': `And specifically, etc. but, etc. Specifically regarding expression — matters of heart, etc.; but in responsum of Hagahot Maimoniyot and Mordechai above appears even regarding cherem specifically nullifying in heart — see there.`,
    '14#ז': `And all this, etc. therefore, etc. As siman 228 seif 20 — see there; likewise with Gibeonites as written; likewise Rosh last chapter Bava Kamma seif 6; likewise responsum general 9; as below.`,
    '14#ח': `However, etc. As last chapter Yoma (84 side 1).`,
    '14#י': `And they pay the injured, etc. As Bava Kamma seif 2; and Tosafot there s.v. what is, etc.`,
    '15#ב': `All the more, etc. Not as Maharai and Mahari Weil and their justification no proof — as seif 14 in gloss; but in responsum of Hagahot Maimoniyot above appears as their words.`,
    '16#ג': `Reuven, etc. See Choshen Mishpat there: (Collection) Reuven, etc. Shimon exempt, etc. — he did not swear with this intent and it is grievance as Kiddushin 50 side 1 one who says to agent, etc.; as Gemara in this place they are merciful, etc.; likewise in divorce another reason in this place it is fine, etc. as written. And if he swore, etc. — monetary constraint as above seif 12 in gloss. There (end).`,
    '19#_': `One who explained, etc. Rosh wrote halachah as Rabbi Yehudah — Rabbi Yosi was refuted and not compelled as Rashbam Bava Batra 53 side 2 in name of Rabbi Chanina since he only said it is difficult — not refuted; likewise Rif and Rosh beginning Berakhot; likewise Aruch; many rule thus not Rashbam but here because Yerushalmi also stated as Rabbi Yehudah as Ran and Rosh; see Rosh in his rulings we learn and Sages agree with him.`,
    '20#ב': `Some say specifically, etc. and some say, etc. one who said konam, etc. Ran there s.v. I am, etc.`,
    '20#ג': `And any condition that, etc. This belongs to second view — in any condition even without fulfillment of act; Ran there two s.v. uleinyan halachah; therefore wrote and any, etc.`,
  },
  'nekudot-hakesef': {
    '3#_': `(There s.k. 27) Challenged Rema and Beit Yosef — words astonishing how can one swear ab initio falsely; Hagahot Maimoniyot distinguishing law in seif 15 only oath not oath if already swore even without nullifying in heart; ab initio obviously must nullify and not swear falsely; also Hagahat Maimoniyot and Rabbi Yerucham end part 3 wrote in name of Geonim: community cherem or tax collector sending cherem for needs — that cherem nothing; but oath forbidden to swear falsely — end his language; Beit Yosef brings; obviously in constraint and tax collector there is death penalty if not swear as he himself wrote; nevertheless through nullifying in heart permitted as Beit Yosef wrote.`,
  },
  'pitchei-teshuva': {
    '1#_': `It is a vow. Ran wrote chapter Four Vows (Nedarim 23 side 1) s.v. who permits thus — possibly even when they establish their words (meaning they intended full vow as explained beginning that chapter) we open opening to say if you had known buyer will not give selah at all would you vow — if said no they release him; as we open here (meaning above siman 228 seif 7 even opening from body of vow, etc.) — end quote.`,
    '2#_': `My purse. Avkat Rochel of Maharit; see responsum Rosh Yosef responsum 5 page 13 his opinion like Maharam Lublin — wherever proof like explainer it counts and not like Taz — see there.`,
    '7#_': `Wrote on him document. Shach s.k. 28; see responsum Noda BiYehudah part Yoreh Deah siman 67 and part Choshen Mishpat siman 30 letter 13; Eshel Avraham: Reuven promised dowry for daughter of Levi and gave gifts and swore as customary and wants to give less because never fixed this sum and matchmaker contradicts and Reuven's son said if condition not fulfilled I am exempt from my oath and if father hung it on me what do I care — see responsum Penei Moshe 63 son believed; see responsum Rosh and Mahar A Sasson responsum 10 and Maharit siman 98; possibly since son did not ask matchmaker certainly did not care for money — some support; see responsum Ribash siman 77 brought Beit Yosef Choshen Mishpat siman 48; but this — money from prohibition we do not derive; person believed on oath to say I only swore — see there at length; see responsum Avnei Nezer simanim 42 and 43 who raised if court admits he did not actually swear certainly helps and excuse does not help like woman who said I cannot and returned, etc.; if claims truly I swore to you — some say court admission like 174; per Peri Chadash court must warn him perhaps swore not before him; per Rashba law in Heaven's hands; see Turei Even and responsum Darchei Moshe and Hagahot in name of Tanna deVei Eliyahu.`,
    '12#_': `Constraints, etc. See She'elat Yaavetz part 2 siman 9: two quarreled to blows; one took knife and stabbed heart and killed; caught by non-Jewish courts and finally acquitted on condition he swear solemn oath he was not murderer but another fled; one rabbi ruled thus to save from death by false oath and relied on Rema gloss — wrote mistake in his hand for Rema discusses if framed; even if truly gentile rapist — not liable death except zealots at act; after departed killer executed for him unlike intentional Israelite murder; even repentance no atonement for bloodshed except his blood; wrote even permissibly forbidden to save from death unless victim started fight — perhaps no death penalty — pursuer even fist blow; see there.`,
    '17#_': `If they did this because of sick person's urging. See responsum Shevut Yaakov part 2 siman 81: one vowed before first wife's death she gather men to learn with them first year after death in her house; after death difficult because rent; is there release; how many men needed; wrote even if acted per wife's urging in illness full vow; difficult per Rema since mitzvah — close even release not help since vowed per her intent and benefit for her soul like vow per friend's benefit — release not help after death against will (but seems like vow in distress unless sages see cannot fulfill or release is mitzvah as siman 228 s.k. 65 gloss and s.k. 39 responsum Ribash and Shach — not called vow in distress); regarding how many men — since did not specify number suffices to gather two — see there.`,
    '18#_': `One who explained. Opinion of Gaon Mahari Eskafa responsum Rosh Yosef responsum 5 page 13 — likewise even if not explained but proof — see there.`,
    '19#_': `He repented. Avkat Rochel of Maharit in name of Raanach: if repented and returned to evil forbidden, etc. — see there; likewise responsum Penei Moshe part 2 siman 54; see Mishneh LaMelech chapter 8 Laws of Vows law 2 disagrees — his opinion permitted since vow already nullified — see there.`,
    '20#_': `That he say to him did you vow anything. Bnei Chayei: we see nowadays all oaths whether monetary or other — when adjurer says I forgive oath or release, etc. all exempt and none challenged (Taz above siman 228 seif 39); why — by law need for money say as if received and for honor this is my honor; certainly custom as our teacher — since world accustomed when adjuring with intent that if afterward says exempt or forgiven suffices and as if stipulated and explained at oath time — end quote Maharam Keli brought Mekor Baruch siman 30 — see there.`,
  },
  'rabbi-akiva-eiger-yd': {
    '3#_': `(There seif 4) Like those who left Egypt; and saying thousand men and saw great multitude — some explain called thousand men; likewise Rashba.`,
    '13#_': `(Seif 12) Vows of constraint how. See Beit Yosef brought Ribash: Ribash (part 1 siman 287) regarding claim of constraints, etc. — not constraint except at time vow takes effect, etc. — see responsum body — three distinctions; illness bodily constraint; person believed on oath except constrained at vow time by uprooting condition; and intent thus I did not vow — difficult for then why Gemara Nedarim proof from Mishnah how acquire her rights — perhaps reason he did not vow; perhaps from person on oath; plain sugya could say illness only monetary constraint — can hire servants; also monetary constraint does not reduce person on oath; Mishnah supports intent thus I did not vow; but per Ribash astonishing.`,
    '16#_': `(There s.k. 22) And obvious. Responsum Maharit (part 1 siman 63) tends to be stringent.`,
    '18#_': `(There Shach s.k. 25) There because we knew his constraint. Responsum Mateh Yosef (part 2 Yoreh Deah siman 4) wondered — in responsum Rashba there wrote moreover even if we recognized his constraint.`,
  },
  'siftei-kohen': {
    '4#_': `Vain vows, etc. Ran wrote two types of vain vows — one with exaggeration like those who left Egypt; one without exaggeration like snake with beams on back — also permitted because we assess his intent not to forbid — if so would attach prohibition to impossible condition; rather intended vain words; one who attaches fruit prohibition to exaggerated matter (meaning excluding without exaggeration — even certainly nonexistent permitted since still vain) — e.g. fruits forbidden by oath or konam if I did not see on road like those who left Egypt and did not see so many people to say exaggeration like Egypt — fruits forbidden; as Beit Yosef; I do not plumb his depth — is there limit; one may see hundred people and say exaggeration like Egypt; Tosefta Nedarim ch.2 vain vows: if I did not count on his Passover shank weighing ten litra, if I did not drink wine worth gold dinar — end quote; difficult — Ran means specifically when saw many people and upholds words to say with multitude I saw like Egypt — since fit to say exaggeration on multitude — intended exaggeration; but if did not see multitude intent truth fruits forbidden; no proof from Tosefta — there also exaggeration saying shank heavy counted and exaggerates ten litra weight and fine wine drank; unlike few people where exaggeration inapplicable; as Ran concludes; Mishnah Nedarim vain vows permitted saying if I did not see on this road like those who left Egypt — specifically when saw great number possible exaggeration like Egypt; otherwise speaks truth fruits should be forbidden — end quote.`,
    '5#ג': `But if he said, etc. and afterward did that thing — some say forbidden since could fail condition; however Tur wrote even so vain vow; likewise Rosh chapter HaMedir in name of Rabbeinu Tam; appears what Rav wrote some disagree applies here; nevertheless appears stringent as Tosafot chapter HaMedir beginning (Ketubot 71) as Semag; likewise Hagahot Ashri in name of Maharich there in name of Rabbi Yehudah.`,
    '8#_': `When he changed his words, etc. — vow weakened; however if not changing and not establishing but simply when approached and saw father and brothers says if I had known father and brothers among them I would not vow — all the more entire vow void. Bach; likewise implied seif 9; see above siman 229 s.k. 4.`,
    '12#ב': `Or river blocked him. Beit Yosef in name of Rabbi Yerucham: river swelled from snowmelt — uncommon constraint; if common should anticipate and stipulate; if not stipulated included in vow — end quote; Darchei Moshe; thus Gemara (page 27 side 2) regarding he was constrained — revealed constraint different Rashi that ford cut off revealed constraint — sometimes not found this side and must anticipate, etc.; Rosh there; but law river blocked in Mishnah means river swelled from rain and snowmelt — uncommon — need not anticipate — end quote; appears likewise common/uncommon constraint in vows; likewise responsum Rashba siman 971 — Gemara and poskim compare vows to money and in money we hold constraint as Tosafot and poskim beginning Ketubot explained Choshen Mishpat siman 54; though Tosafot Nedarim there not apparent — because Gemara compares money to divorce and in divorce we hold even common/uncommon not constraint as Even HaEzer siman 144; but we hold first version Rava money not like divorce as poskim beginning Ketubot and chapter Mi SheAchazo — all poskim there illness is common/uncommon constraint; here Nedarim illness is constraint — certainly as we say; examine.`,
    '12#ז': `Person believed to say his oath was by constraint, etc. Appears specifically vow or swore to himself; but swore to fellow e.g. document — not believed; difficult per Rabbi Yonah ben Rosh — if said I fulfilled oath sworn to you — believed since customary to affirm oath; here constraint uncommon; also everyone would say constrained; but fulfilled — person not brazen to lie since other contradicts; Beit Yosef end siman 228 page 274 beginning side 2 responsum Rashba — nevertheless case before us swore per our intent not in what I said — other side permission and constraint as written; even though said before witnesses vowed and swore per intent — said from constraint since sister sick vowed herself to die if he does not vow — no stronger revealed constraint — end quote; implies even vow to fellow releases by constraint — there because we knew constraint; therefore though said vowed per intent — said from constraint; but if we did not know constraint at all not believed swearing to fellow saying constrained; however where circumstantial evidence — appears believed; so I think.`,
    '12#ט': `But if already, etc. Written responsum Rashba there clear likewise if warned and did not concern to say at warning and ate — all the more nevertheless not believed — end quote; likewise Rambam chapter 2 Laws of Oaths law 12; wrote further if released and said never swore or vowed this matter and after testified swore or vowed said so but mouth and heart not aligned or condition in heart on vow — not listened and lashed; similar they told him your wife vowed, etc. as below siman 234 s.k. 62; reason like saying I did not borrow as saying I did not pay as Choshen Mishpat siman 79; therefore even witnesses to later words nothing — person believed over hundred witnesses.`,
    '12#י': `Or written on him document, etc. Written Semak siman 72 s.k. 16: Terumat HaDeshen siman 326 if written in handwriting swore to pay and says only wrote did not swear — if claimant admits obviously no concern; if not admit monetary law like document without oath — see there Darchei Moshe; appears if wrote actually swore cannot excuse saying did not swear — same if witnesses in document — end quote; appears when wrote swore actually refers where claimant does not admit; when admits no concern; difficult what Semak wrote generally Terumat HaDeshen there only when defendant can clarify alone that legally claims exemption or gives excuse; but no excuse claims simply did not swear and did not affirm — even if claimant admits not sworn before him — possibly swore not before him since admitted made piece of prohibition; when claimant says sworn before him must examine even with excuse whether claim valid — all clarified Terumat HaDeshen there; likewise Darchei Moshe siman 7; see responsum Rabbi Elazar Mizrachi siman 72 and responsum Maharit part 1 siman 9 beginning page 8 and part 2 siman 200 page 214 side 3; see above siman 234 s.k. 54.`,
    '14#א': `Or one who swears, etc. Beit Yosef: though Mishnah teaches only vows — Yerushalmi says likewise swearing; wonder — Mishnah teaches dispute Beit Shammai and Beit Hillel oath — end quote Bach; difficult — Mishnah teaches only oath like vow meaning swears fruits forbidden forever if not from royal house — now when swears not falsely since can fulfill; thus Mishnah all who vow except oath — Beit Hillel those who swear; Beit Shammai also swearers; only vowed not swore; Beit Hillel also swearers; certainly as I explained; Yerushalmi proves even swearing falsely permitted — asked chapter 4 Nedarim halachah four except in vows in Shevuot not found; Rabbi Yishmael taught do not swear falsely — swears to murderers cherems tax collectors — end quote — even such permitted else without Rabbi Yishmael it is Mishnah; Beit Hillel also oath; verse do not swear falsely implies such case (found support Tosafot 19 — see there); likewise Beit Yosef and Rav below — even oath now sworn falsely permitted by nullifying in heart.`,
    '14#ו': `Therefore Zedekiah punished, etc. Per his view below seif 15 in gloss; but per death applies vow anyway — not punished; clear in rulings Maharai siman 73; likewise Mahari Weil below s.k. 40 in name — not revealing matter cherem applied — fine for Zedekiah; examine.`,
    '16#ב': `They lived in one city, etc. Difficult — responsum Ramban there Shimon may not take daughter from place even if husband elsewhere — all the more both lived one place, etc.; Beit Yosef and Darchei Moshe; see Even HaEzer siman 75.`,
    '18#_': `Forbidden to contradict their ruling. Not included in vows of constraint since not forced to accept ruling — like vowing to tax collectors by saying in heart today; but here even if constraint said since unstipulated (since) accepted cherem or excommunication applies if not accept ruling — end quote Rashbatz; meaning even vowed saying in heart today does not help since no visible constraint; examine; responsum Maharam of Lublin siman 11 wrote intent since coercion not on oath itself and not in heart today, etc. — not implied from Rashbatz; also responsum Rashbatz Beit Yosef this siman Elkana married Peninah, etc. — even constrained on vow and oath must stipulate condition in heart else must fulfill; also Maharam proof from Maharik not compelled; though Maharadakh distinction there — difficult practically poskim imply no distinction; see above seif 14.`,
  },
  'turei-zahav': {
    '2#א': `Or slightly less. Per Ran brought Beit Yosef — I do not know why wrote specifically slightly — Ran wrote: though intent three dinars seller may give less and buyer more since vow meaning only exhortation though agreed three in heart only matters of heart; however seller may not give shekel nor buyer sela since main meaning only that; some say even so vow not effective — end quote; did not forbid even per stringent except actual shekel or sela since explicitly insisted; but all not specified permitted even much more than three. Rema explains stringency in sela and shekel not precise — teaches leniency only average sum between both close to each as three; likewise slightly less or more counts average; not large sum not average but closer to one side.`,
    '2#ה': `If I decrease more than sela. Gemara (page 21) states thus: said to him more than sela and other says less than shekel — was it vow or exhortation; this and other says; or other says one of them suffices as Tur and Shulchan Aruch; Ran wrote: meaning said konam I decrease from you less than sela perutah and buyer says konam I add less than shekel perutah — can say since descended so much to precision it is vow; other language: said more than sela — said not less than five dinars and other not more than dinar — since so far apart it was vow — end quote; Rosh there seems second language; Tur and Shulchan Aruch seem first — wrote slightly less than shekel — obvious slight not great distance — must be first language; reason since language indicating precision and plausible explanation — thus Choshen Mishpat siman 83 seif 1 wrote even calculated less than perutah value — not said since calculated so much spoke truth — end quote; reason there deceives to believe judges; Gemara uncertain in vow this language whether all from exhortation friend thinks precise or not; second language wonder why divided shekel or slightly more; therefore main first explanation seems to me.`,
    '12#א': `Through much money. Maharshal challenged from Rema Orach Chayyim siman 656 if not do give all money before transgress — therefore uprooted halachah here; no difficulty — here did not transgress at all — we say did not swear to squander much money; illness in us helps here — certainly does not help nullify any prohibition for illness in us.`,
    '12#ג': `And some say not called constraint. From Agudah chapter Mi SheAchazo — derives from there page 74 originally buyer hid in walled city day twelve month so seller not find to pay so acquisition complete as written if not redeem until full year, etc.; Hillel enacted throw money to designated room break door enter — from this Agudah author: vowed act within thirty days constrained last day — end of thirty days not constraint since Hillel needed enactment — here constrained last day therefore. I see no proof — if court knew he hid last day seller's right not voided — needed witnesses all day search every house — tomorrow can say in other house with you — impossible; Hillel enacted throw money last day designated room easy matter; moreover sugya there main Hillel enactment without it we say coerced payment not payment or not in presence and payment not in presence not payment — still difficult if constraint why enactment since ready to pay only lender absent — not lost right — not matter — wants enter house immediately; enacted payment to room as giving himself can enter without buyer's knowledge; therefore seems first opinion Nissim beginning chapter Keitzad HaRegel in name of Ramah with clear Gemara proof — sensible since main payment day is last as if only that day; since constraint exempt certainly from oath and all penalties if not pay that day exempt from all — so seems to me.`,
    '12#ה': `And gives reason why said he swore, etc. See what wrote from this Choshen Mishpat siman 73 seif 6.`,
    '14#ה': `And must nullify in heart. I do not grasp Rema — why different from seif 15 all constraint of suffering — all the more death constraint no vow substance and no nullification; here obviously if not obey governor's decree constraint suffering and death — not like vowing to murderers, etc. — murderer and tax collector only seize money as Beit Yosef Hagahot Maimoniyot distinguishing seif 15; likewise responsum Rosh Beit Yosef wrote: resembles swearing to eat pork — end quote; obvious swearing to eat pork needs no nullification; also how nullification in heart here — must not think opposite mouth but condition — only case nearby fruits forbidden thinking today or other way as below if not lay tefillin; but swearing does not know so-and-so lay with gentile woman — what condition applies since truly knows — heart contradicts mouth; possibly thinks in heart I do not know if another time lay with her after gentile commanded cherem on knower; Maharshal wrote nullify in heart — Beit Yosef wrote so seems to me; compared to vowing murderers, etc. — truly not similar for reason written — needs examination.`,
    '15#_': `That oath has nothing, etc. Even though vowing murderers, etc. seif 14 requires saying in heart today I am there — murderer and tax collector do not torture and beat only seize fruits; here suffering and beatings without limit — oath entirely void even said per God's intent Beit Hillel does not help, etc. — as responsum Rosh Beit Yosef.`,
    '20#_': `Did you vow anything except to honor me, etc. Gemara page 63 asks without this reason would not be vow — would be vow of exhortation like seif 6; answers not exhortation — said to him I am not a dog benefiting from you not you from me; Rosh wrote since wants gift from him presumably also benefits him much; likewise end said as if received — Gemara said not a king benefiting you not you me; Rosh wrote presumably benefits much since demands great gift — before you this law specifically manner Rosh mentioned accustomed to benefit and likewise end accustomed to benefit him; though Tur and Shulchan Aruch did not mention — nothing missing — presumably all who vow thus accustomed as Rosh language and Levush omitted Gemara words made difficulty from logic and answered distinction receiving gift vs inviting to eat — not halachah per Gemara mentioned.`,
  },
};

function esc(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

let body = `/** Editorial translations — siman 232 (76 blocks) — Nedarim zaruzin, habit, constraint */\nexport const TRANSLATIONS = {\n`;
let n = 0;
for (const [slug, keys] of Object.entries(T)) {
  body += `  '${slug}': {\n`;
  for (const [key, val] of Object.entries(keys)) {
    body += `    '${key}': \`${esc(val)}\`,\n`;
    n++;
  }
  body += `  },\n`;
}
body += `};\n`;

const missing = [];
for (const [slug, keys] of Object.entries(he)) {
  for (const key of Object.keys(keys)) {
    if (!T[slug]?.[key]) missing.push(`${slug}\t${key}`);
  }
}
if (missing.length) {
  console.error('MISSING:', missing.join('\n'));
  process.exit(1);
}

fs.writeFileSync(path.join(WORK, '_tr-data-232.mjs'), body);
console.log(`wrote _tr-data-232.mjs (${n} blocks)`);
