/** Ribbit / lending phrase replacements for simanim 176–190 editorial pass */

export const EXTRA_RIBBIT = [
  [/ריבית קצוצה/g, 'ribbit ketzutzah'],
  [/ר"ק/g, 'ribbit ketzutzah'],
  [/ריבית/g, 'ribbit'],
  [/אבק ריבית/g, 'avak ribbit'],
  [/אבק ר"ק/g, 'avak ribbit ketzutzah'],
  [/הלואה/g, 'loan'],
  [/הלווה/g, 'borrower'],
  [/מלוה/g, 'lender'],
  [/שכירות/g, 'rental'],
  [/שכר/g, 'wage'],
  [/שכיר/g, 'hirer'],
  [/שוכר/g, 'renter'],
  [/אגר נטר/g, "watchman's fee"],
  [/משכון/g, 'mortgage'],
  [/משכנתא/g, 'mortgage'],
  [/מכר/g, 'sale'],
  [/מוכר/g, 'seller'],
  [/לוקח/g, 'buyer'],
  [/מקח/g, 'purchase'],
  [/מקח וממכר/g, 'sale and purchase'],
  [/מנה/g, 'maneh'],
  [/דינר/g, 'dinar'],
  [/זוז/g, 'zuz'],
  [/זוזי/g, 'zuzim'],
  [/פרוטה/g, 'perutah'],
  [/סאה/g, 'seah'],
  [/סאה בסאה/g, 'seah for seah'],
  [/פירות/g, 'produce'],
  [/פירי/g, 'fruits'],
  [/חטים/g, 'wheat'],
  [/יין/g, 'wine'],
  [/שדה/g, 'field'],
  [/קרקע/g, 'land'],
  [/חצר/g, 'courtyard'],
  [/דירה/g, 'dwelling'],
  [/בית/g, 'house'],
  [/ספינה/g, 'ship'],
  [/פועל/g, 'worker'],
  [/שכירות קרקע/g, 'land rental'],
  [/שכירות פועל/g, 'worker hire'],
  [/שכירות אינה משתלמת אלא לבסוף/g, 'rental is paid only at the end'],
  [/אינה משתלמת אלא לבסוף/g, 'is paid only at the end'],
  [/משתלמת אלא לבסוף/g, 'paid only at the end'],
  [/אוזלי קא מוזיל/g, 'prices are falling'],
  [/מה שפוחת לו השתא/g, 'what he reduces for him now'],
  [/נכנס תיכף לתוך הקרקע/g, 'enters the land immediately'],
  [/נכנס תיכף/g, 'enters immediately'],
  [/זוכה בה מיד/g, 'acquires it immediately'],
  [/אינו משתעבד מהשתא/g, 'is not obligated from now'],
  [/דר מיד בחצר/g, 'dwells immediately in the courtyard'],
  [/אחריות/g, 'responsibility'],
  [/אחריות הספינה/g, 'responsibility for the ship'],
  [/קוצץ לו דבר קצוב ברבית/g, 'cuts off a fixed amount in ribbit'],
  [/לא יצא מידי הלואה/g, 'did not leave the category of loan'],
  [/על אחריות/g, 'on the responsibility of'],
  [/בשובו/g, 'upon his return'],
  [/כ"ד/g, 'twenty-four'],
  [/מותר/g, 'permitted'],
  [/אסור/g, 'forbidden'],
  [/היתר/g, 'heter'],
  [/היתר רק/g, 'permit only'],
  [/אין היתר רק/g, 'permit only'],
  [/מותר להרבות בשכר הקרקע/g, 'permitted to increase land rental'],
  [/מותר לקצוב דמיו/g, 'permitted to fix its value'],
  [/להתנות/g, 'to stipulate'],
  [/לכשישבר/g, 'when it breaks'],
  [/דמי'/g, 'its value'],
  [/דמים/g, 'money value'],
  [/עשאה דמים/g, 'made it money'],
  [/לא עשאה דמים/g, 'did not make it money'],
  [/כמו ששוה בשעת מיתה/g, 'like its value at time of death'],
  [/בשעת שבירה/g, 'at time of breaking'],
  [/השער/g, 'market price'],
  [/בשער/g, 'at market price'],
  [/בשווי/g, 'at value'],
  [/מחיר/g, 'price'],
  [/יוצא השער/g, 'price went out'],
  [/לא יצא השער/g, 'price did not go out'],
  [/השתא/g, 'now'],
  [/מעתה/g, 'from now'],
  [/מהשתא/g, 'from now'],
  [/למחר/g, 'for tomorrow'],
  [/לזמן/g, 'for a time'],
  [/לשלש שנים/g, 'for three years'],
  [/שלש שנים/g, 'three years'],
  [/תוך שלש/g, 'within three'],
  [/מעובדא/g, 'from incident'],
  [/מעובדא ד/g, 'from incident of'],
  [/מוגר זוזי/g, 'rented dinars'],
  [/כלו זוזי/g, 'all the dinars of'],
  [/חולין/g, 'Chullin'],
  [/בבא מציעא/g, 'Bava Metzia'],
  [/ב"מ/g, 'Bava Metzia'],
  [/איזהו נשך/g, 'Eizehu Neshekh'],
  [/פרק הספינה/g, 'chapter HaSapinah'],
  [/פרק איזהו נשך/g, 'chapter Eizehu Neshekh'],
  [/הגהת מיימוני/g, 'Hagahot Maimoniyot'],
  [/מ"מ/g, 'Maggid Mishneh'],
  [/הגמ"י/g, 'Hagahot Maimoniyot'],
  [/ד"מ/g, 'Darkei Moshe'],
  [/נה"כ/g, 'Nachalat Binyamin'],
  [/בנה"כ/g, 'Nachalat Binyamin'],
  [/עבה"ט/g, 'Avodat HaTaharah'],
  [/תפל"מ/g, 'Tiferet LeMoshe'],
  [/נו"ב/g, "Noda B'Yehuda"],
  [/דגמ"ר/g, 'Degel Machaneh Ephraim'],
  [/ריב"ש/g, 'Rivash'],
  [/רשב"א בעל התוספות/g, 'Rashba author of Tosafot'],
  [/רשב"א בעל תוס'/g, 'Rashba author of Tosafot'],
  [/ר"ש בן אדרת/g, "Rashba (R' Shmuel ben Aderet)"],
  [/הר"ש בן אדרת/g, "Rashba (R' Shmuel ben Aderet)"],
  [/ר"ש בן אברהם/g, "R' Shmuel ben Avraham"],
  [/נמוקי יוסף/g, 'Nimukei Yosef'],
  [/ליקוט/g, 'Leket'],
  [/תוספתא/g, 'Tosefta'],
  [/הרא"ש/g, 'Rosh'],
  [/ה"ה/g, 'Hagahot HaRambam'],
  [/הלכות מלווה ולווה/g, 'Laws of Lending'],
  [/הלכות מלוה/g, 'Laws of Lending'],
  [/השוכר/g, 'hirer'],
  [/חייב בגניבה ואבידה/g, 'liable for theft and loss'],
  [/כלים/g, 'vessels'],
  [/לא היא/g, 'it is not so'],
  [/מרא/g, 'it appears'],
  [/וי"א/g, 'and some say'],
  [/מש"ש/g, 'as Rashbam explained'],
  [/אר"ש/g, "R' Shimon"],
  [/ר"ל/g, 'meaning'],
  [/בשעת מיתה/g, 'at time of death'],
  [/סברא ראשונה/g, 'first reason'],
  [/ס"ל/g, 'holds'],
  [/פירש"י/g, "Rashi's explanation"],
  [/ד"ה/g, 's.v.'],
  [/סנ"ב/g, 'siman 42'],
  [/ת"ר/g, 'baraita'],
  [/כל ימי חייה/g, 'all days of her life'],
  [/הני דיני להדדי/g, 'these laws are equivalent'],
  [/כמש"ש/g, 'as written above'],
  [/כמ"ש/g, 'as written'],
  [/כנ"ל/g, 'as above'],
  [/ע"ש/g, 'see there'],
  [/עכ"ל/g, 'end of his words'],
  [/ודו"ק/g, 'investigate'],
  [/ק"ל/g, 'investigate'],
  [/צ"ע/g, 'requires study'],
  [/נ"ל/g, 'it appears to me'],
  [/לפ"ז/g, 'accordingly'],
  [/לפ"ז קשה/g, 'accordingly it is difficult'],
  [/לכאורה/g, 'it appears'],
  [/פסקי דסתרי אהדדי/g, 'rulings that contradict each other'],
  [/סתם המחבר/g, 'Mechaber ruled without qualification'],
  [/הרב לא הגיה/g, 'the Rav did not emend'],
  [/יש מתירין/g, 'some permit'],
  [/אפי' משכיר/g, 'even from renting'],
  [/קודם הנשואין/g, 'before marriage'],
  [/נדונית חתנים/g, 'bridegroom dowry'],
  [/בע"ח/g, 'creditor'],
  [/יורשים/g, 'heirs'],
  [/צוואה/g, 'will'],
  [/מתנה/g, 'gift'],
  [/שידוך/g, 'match'],
  [/עזבון/g, 'estate'],
  [/מנכין/g, 'we deduct'],
  [/דיינים/g, 'court'],
  [/חוב/g, 'debt'],
  [/גבה/g, 'collected'],
  [/גבה את חובו/g, 'collected his debt'],
  [/ח"מ/g, 'Choshen Mishpat'],
  [/חושן משפט/g, 'Choshen Mishpat'],
  [/סי' שי"ז/g, 'siman 317'],
  [/סימן קע"ו/g, 'siman 176'],
  [/סימן קע"ג/g, 'siman 173'],
  [/סימן קס"ו/g, 'siman 166'],
  [/סימן קס"א/g, 'siman 161'],
  [/סימן ש"ח/g, 'siman 308'],
  [/ס"ק/g, 's.k.'],
  [/סק"/g, 's.k. '],
  [/סעיף/g, 'seif'],
  [/בהג"ה/g, 'in Hagah'],
  [/בהגה/g, 'in Hagah'],
  [/הג"ה/g, 'Hagah'],
  [/בס"ס/g, 'in seif 4'],
  [/בס"ד/g, 'in seif 4'],
  [/בס"ו/g, 'in seif 6'],
  [/בס"ג/g, 'in seif 3'],
  [/בס"ח/g, 'in seif 8'],
  [/בס"י/g, 'in seif 10'],
  [/בס"יא/g, 'in seif 11'],
  [/בס"יב/g, 'in seif 12'],
  [/בס"יג/g, 'in seif 13'],
  [/בס"יד/g, 'in seif 14'],
  [/בס"טו/g, 'in seif 15'],
  [/בס"טז/g, 'in seif 16'],
  [/בס"יז/g, 'in seif 17'],
  [/בס"יח/g, 'in seif 18'],
  [/בס"יט/g, 'in seif 19'],
  [/בס"כ/g, 'in seif 20'],
  [/בס"כא/g, 'in seif 21'],
  [/בס"כב/g, 'in seif 22'],
  [/בס"כג/g, 'in seif 23'],
  [/בס"כד/g, 'in seif 24'],
  [/בס"כה/g, 'in seif 25'],
  [/בס"כו/g, 'in seif 26'],
  [/בס"כז/g, 'in seif 27'],
  [/בס"כח/g, 'in seif 28'],
  [/בס"כט/g, 'in seif 29'],
  [/בס"ל/g, 'in seif 30'],
  [/בס"לא/g, 'in seif 31'],
  [/בס"לב/g, 'in seif 32'],
  [/בס"לג/g, 'in seif 33'],
  [/בס"לד/g, 'in seif 34'],
  [/בס"לה/g, 'in seif 35'],
  [/בס"לו/g, 'in seif 36'],
  [/בס"לז/g, 'in seif 37'],
  [/בס"לח/g, 'in seif 38'],
  [/בס"לט/g, 'in seif 39'],
  [/בס"מ/g, 'in seif 40'],
  [/בס"מא/g, 'in seif 41'],
  [/בס"מב/g, 'in seif 42'],
  [/בס"מג/g, 'in seif 43'],
  [/בס"מד/g, 'in seif 44'],
  [/בס"מה/g, 'in seif 45'],
  [/בס"מו/g, 'in seif 46'],
  [/בס"מז/g, 'in seif 47'],
  [/בס"מח/g, 'in seif 48'],
  [/בס"מט/g, 'in seif 49'],
  [/בס"נ/g, 'in seif 50'],
  [/בס"נא/g, 'in seif 51'],
  [/בס"נב/g, 'in seif 52'],
  [/בס"נג/g, 'in seif 53'],
  [/בס"נד/g, 'in seif 54'],
  [/בס"נה/g, 'in seif 55'],
  [/בס"נו/g, 'in seif 56'],
  [/בס"נז/g, 'in seif 57'],
  [/בס"נח/g, 'in seif 58'],
  [/בס"נט/g, 'in seif 59'],
  [/בס"ס/g, 'in seif 60'],
  [/בס"סא/g, 'in seif 61'],
  [/בס"סב/g, 'in seif 62'],
  [/בס"סג/g, 'in seif 63'],
  [/בס"סד/g, 'in seif 64'],
  [/בס"סה/g, 'in seif 65'],
  [/בס"סו/g, 'in seif 66'],
  [/בס"סז/g, 'in seif 67'],
  [/בס"סח/g, 'in seif 68'],
  [/בס"סט/g, 'in seif 69'],
  [/בס"ע/g, 'in seif 70'],
  [/בס"עא/g, 'in seif 71'],
  [/בס"עב/g, 'in seif 72'],
  [/בס"עג/g, 'in seif 73'],
  [/בס"עד/g, 'in seif 74'],
  [/בס"עה/g, 'in seif 75'],
  [/בס"עו/g, 'in seif 76'],
  [/בס"עז/g, 'in seif 77'],
  [/בס"עח/g, 'in seif 78'],
  [/בס"עט/g, 'in seif 79'],
  [/בס"פ/g, 'in seif 80'],
  [/בס"פא/g, 'in seif 81'],
  [/בס"פב/g, 'in seif 82'],
  [/בס"פג/g, 'in seif 83'],
  [/בס"פד/g, 'in seif 84'],
  [/בס"פה/g, 'in seif 85'],
  [/בס"פו/g, 'in seif 86'],
  [/בס"פז/g, 'in seif 87'],
  [/בס"פח/g, 'in seif 88'],
  [/בס"פט/g, 'in seif 89'],
  [/בס"צ/g, 'in seif 90'],
  [/דף ס"ט/g, 'daf 69'],
  [/דף פ"ו/g, 'daf 86'],
  [/דף פ"ז/g, 'daf 87'],
  [/ע"א/g, 'side 1'],
  [/ע"ב/g, 'side 2'],
  [/ע"ד/g, 'side 4'],
  [/באתרא דתנא דידן/g, 'in place of our tanna'],
  [/אל"ה/g, 'otherwise'],
  [/דאל"ה/g, 'for otherwise'],
  [/אע"ג/g, 'even though'],
  [/אע"פ/g, 'even though'],
  [/משא"כ/g, 'unlike'],
  [/הוי/g, 'it is'],
  [/הוה/g, 'was'],
  [/הוה ליה/g, 'it would be'],
  [/הוה לכתוב/g, 'should have written'],
  [/לא הוה לכתוב/g, 'should not have written'],
  [/לא אמרינן/g, 'we do not say'],
  [/אמרינן/g, 'we say'],
  [/משמע/g, 'it implies'],
  [/מסקנת/g, 'conclusion of'],
  [/פריך/g, 'challenges'],
  [/ותסברא/g, 'could it be'],
  [/זלזולי בשכירות/g, 'disparaging in rental'],
  [/מרבין על השכר/g, 'one may increase on rental'],
  [/ואין מרבין על המכר/g, 'and one may not increase on sale'],
  [/חילוק/g, 'distinction'],
  [/יש חילוק/g, 'there is a distinction'],
  [/בין פועל לשכירות קרקע/g, 'between worker and land rental'],
  [/גוף החצר/g, 'substance of the courtyard'],
  [/גופו קנוי לו/g, 'his body is acquired to him'],
  [/יכול לחזור בו/g, 'can retract'],
  [/לא בא ע"י הלואה/g, 'did not come via loan'],
  [/בחלוקה הראשונה/g, 'in first division'],
  [/כבר החזיק/g, 'already acquired'],
  [/נסתפק/g, 'was uncertain'],
  [/מודה/g, 'concedes'],
  [/נראה פשוט/g, 'it appears plain'],
  [/נראה ד/g, 'it appears that'],
  [/נראה לי/g, 'it appears to me'],
  [/לעניות דעתי/g, 'in my humble opinion'],
  [/עמ"ש/g, 'see what he wrote'],
  [/לעיל/g, 'above'],
  [/לקמן/g, 'below'],
  [/עיין/g, 'see'],
  [/עי"ש/g, 'see there'],
  [/וכ"כ/g, 'and likewise'],
  [/וכו'/g, 'etc.'],
  [/וכו/g, 'etc.'],
  [/וכ"ז/g, 'and all this'],
  [/וכן/g, 'and so'],
  [/וכן מדמי/g, 'and likewise compared'],
  [/הביאו ראיה/g, 'they brought proof'],
  [/כדין/g, 'like law of'],
  [/בטור כתוב/g, 'in Tur it is written'],
  [/ב"י כתב/g, 'Beit Yosef wrote'],
  [/כתב ב"י/g, 'Beit Yosef wrote'],
  [/כ' ב"י/g, 'Beit Yosef wrote'],
  [/כתב ד"מ/g, 'Darkei Moshe wrote'],
  [/כ' ד"מ/g, 'Darkei Moshe wrote'],
  [/כתב הט"ז/g, 'Taz wrote'],
  [/כתב הש"ך/g, 'Shach wrote'],
  [/כתב הרמב"ם/g, 'Rambam wrote'],
  [/כתב הטור/g, 'Tur wrote'],
  [/כתב הרב/g, 'the Rav wrote'],
  [/כתב הרא"ש/g, 'Rosh wrote'],
  [/כתב רשב"ם/g, 'Rashbam wrote'],
  [/פירש/g, 'explained'],
  [/פירשו/g, 'they explained'],
  [/הב"י פירש/g, 'Beit Yosef explained'],
  [/ול"נ/g, 'it appears to me'],
  [/דברים סותרים/g, 'contradictory matters'],
  [/לכשישבר אינו מחויב אלא בדמי'/g, 'when it breaks he is obligated only for its value'],
  [/עשיית הקצבה/g, 'making the fixed amount'],
  [/כמו הלואה/g, 'like a loan'],
  [/לא אמרינן דעשיית הקצבה היא כמו הלואה/g, 'we do not say making the fixed amount is like a loan'],
  [/בסיפא/g, 'at the end'],
  [/קמ"ל/g, 'it teaches us'],
  [/אם יהיה זול/g, 'if it becomes cheap'],
  [/אח"כ/g, 'afterward'],
  [/כפי אותו השער/g, 'according to that market price'],
  [/כפי השער שהיה באותה הפעם/g, 'according to market price at that time'],
  [/וליטול שכרה/g, 'and take its rental'],
  [/אם נשברה שמין לו/g, 'if it breaks they assess for him'],
  [/הטעם/g, 'the reason'],
  [/הגהת/g, 'Hagah'],
  [/°/g, ''],
  [/<br>/g, ' '],
  [/<i[^>]*><\/i>/g, ''],
];
