/** Complete manual overrides siman 101 — piece worthy of honor */
export const MANUAL = {
  mechaber: {
    '1#main': `The law of a piece worthy of honor. And it has 9 seifim: A piece worthy of honor has the law of beriah — even in a thousand it is not nullified — and even if it is forbidden in benefit, since if it were nullified it would be permitted and worthy of honor: {Rama: And even if it is forbidden only d'rabbanan it is not nullified (Beit Yosef in the name of Ramban); and if it is a doubt whether it is worthy of honor or not we follow the lenient view (Arukh general rule 25) even if it is forbidden d'oraisa.}`,
    '2#main': `It does not have the law of a piece worthy of honor unless its prohibition is on account of itself, such as nevelah and basar b'chalav; but if it became forbidden because it absorbed taste from a prohibition and there was not sixty in it to nullify it — even for one who holds the piece itself becomes nevelah — it does not have the law of a piece worthy of honor: {Rama: And even a piece that was not salted is nullified, for its prohibition is not on account of itself but on account of blood absorbed in it (there and Taz siman 110); every piece that was forbidden only on account of a peel is nullified, for a peel is not worthy of honor (view of Tosafot and Hagahot Sh"D).}`,
    '3#main': `A chicken in its feathers that was mixed with others is nullified, for it is not worthy of honor before guests as it is; and even though after it was mixed they removed the feathers — and likewise it is not considered worthy of honor unless it is cooked; and likewise a whole sheep or an overly large piece is not considered worthy of honor, for there is no custom to place before guests a whole sheep or an overly large piece; and there are those who disagree in all of this: {Rama: And so is the custom except for a chicken in its feathers, which lacks a great preparation and the custom is that it is nullified (Tur in the name of R"IF and Mordechai and Sh"D); and likewise feet or a head whose hair was not singed — but if they were already singed they are considered a piece worthy of honor even if not yet salted, and even a whole sheep is not nullified (Hagahot Sh"D); however, feet of fowl except goose feet, and likewise feet of small livestock in these countries are not considered at all and are nullified; a head of fowl is not considered and is nullified (Arukh general rule 25).}`,
    '4#main': `Fat of the stomach lining is not worthy of honor (but goose fat skin is called worthy of honor and is not nullified) (there).`,
    '5#main': `Gizzard and likewise other intestinal organs are not worthy of honor.`,
    '6#main': `This that beriah and a piece worthy of honor are not nullified — only while they are whole; but if they were cut or crushed until their form was lost they are nullified and are no longer considered; and even if they were crushed after they were mixed with the permitted food (and even after the mixture became known) (Hagahot Sh"D and Darkei Moshe, unlike Or Zarua) — and this is when they were crushed without intent to nullify the prohibition; but if one intended for that it is forbidden to crush if it is his own, and likewise for one who crushed on his behalf (and there is no distinction whether they were mixed in their kind or not in their kind) (Darkei Moshe and implication of poskim, unlike Or Zarua).`,
    '7#main': `If one piece was cut — one may not rely to say that the forbidden one was cut and is nullified and all of them shall be permitted; rather only that one which was cut is permitted in any case: if it is of the forbidden, all of them are permitted; and if it is not of the forbidden, behold it is permitted; and even if a majority of them were cut one may not rely to say that the forbidden is from the majority that were cut — rather all the cut ones are permitted and the whole ones are forbidden.`,
    '8#main': `A gizzard that was found perforated and that chicken was mixed with others — one compares the fat in the gizzard to the fat of the chicken at the place of connection of the gizzard; and if they are entirely similar one permits the others (and likewise in all similar cases).`,
    '9#main': `The head of a sheep that was found tereifah and it is unknown from which sheep it is, and one wrapped the head around the neck of one of the sheep and the pieces were found similar and aligned well — one may rely on this to permit the others.`,
  },
};
