/** Complete manual overrides siman 102 — something that has a permitted aspect */
export const MANUAL = {
  mechaber: {
    '1#main': `The law of something that has a permitted aspect. And it has 4 seifim: Everything that has a permitted aspect, such as an egg laid on Yom Tov that is fit for tomorrow — if it was mixed with others, whether whole or beaten, it is not nullified even in a thousand; and even if there is a doubt whether it was laid on Yom Tov and it was mixed with others they are forbidden; and if it was mixed with what is not its kind it is nullified in sixty (Tur and Sh"D and responsa of Rosh and R' Yerucham and Hagahot Sh"D and Rashal and Rokeach and as stated Smag and Smak in laws of Yom Tov and likewise Or Zarua general rule 26 in the name of Smag and Taz general rule 43 and not like Bach): {Rama: However, if one whitened it in food or placed it in a pot to fix the pot, such as one filled it with chicken, it is not nullified (Hagahot Sh"D and Arukh); see Orach Chayim siman 513.}`,
    '2#main': `There are those who say that they only said something has a permitted aspect when the permitting matter will certainly come in any event, or if the permitting matter is in his hand to do without loss; but something that is not in his hand and it is not certain that the permitting matter will come — it is not in the law of something that has a permitted aspect; therefore an egg of doubtful tereifah that was mixed with others is not in the law of something that has a permitted aspect, because the permitting matter is not certain and is not in his hand.`,
    '3#main': `A vessel that became forbidden through absorption of a prohibition that was mixed with others and is not recognizable — it is nullified in the majority and we do not judge it like something that has a permitted aspect (because one must expend outlay to kasher it, and all similar cases).`,
    '4#main': `There are those who say that something that has a permitted aspect does not apply where the food spoils: {Rama: This that something that has a permitted aspect is not nullified applies only if the prohibition is in existence or there is still substance of the prohibition in the mixture; but its taste is nullified (Tur Orach Chayim siman 513 and Arukh and Hagahot Alfasi end of Avodah Zarah and Mahari in the name of Mahariach); and likewise if its prohibition is not on account of itself it is nullified — therefore a piece that was not salted within three days — even though some say it is called something that has a permitted aspect since it is permitted for roasting — nevertheless it is nullified, for it is forbidden only on account of blood absorbed in it (Taz siman 110); every prohibition that was not recognizable before it was mixed is nullified even though it is something that has a permitted aspect (Arukh general rule 25 in the name of seif 3 and Mordechai chapter 1 of Shabbat); one who vowed from one matter and it was mixed afterward — for him it is called something that has a permitted aspect (there and in Maimonides chapter 8 of Nedarim and in Ran chapter 1 and Or Zarua and this is Gemara Arukh chapter 7 of Nedarim daf 59 and Yerushalmi chapter 6 of Nedarim and consensus of poskim); for it is possible to ask about his vow. Something that has permission and becomes forbidden again, such as chametz on Pesach — is not called something that has a permitted aspect (Mordechai chapter Kamma); and there are those who disagree in this (Rambam chapter 15 of Forbidden Foods); and it is only called something that has a permitted aspect if it was permitted for the one who was forbidden, but if it remained forbidden for one forever even though permitted for others, such as one who cooks on Shabbat — it is not called something that has a permitted aspect (Beit Yosef in the name of R' Yerucham in the name of Ramah).}`,
  },
};
