export default [
  `Not reached—once this opinion applies even ab initio permitted; after fact guide ben drusai as one third—majority of this view—see Aruch Hashulchan.`,
  `Forbidden—even for others until Motza’ei; if need kedei sheyeasu see sk 32 above.`,
  `On iron stand—tripod and coals underneath.`,
  `Hatmanah on coals—Mechaber holds pot-bottom touching coals is hatmanah—therefore forbidden even fully cooked mitztamek vera—siman 257 sk 7.`,
  `All while…—even pot inside sealed oven not hatmanah—siman 257 end sk 5.`,
  `That it is uncovered—not wrapped above with cloth—siman 257 sk 5.`,
  `And permitted—only general shehiyah; permitted if cooked erev ben drusai per latter reasoning.`,
  `Remove from there—Jew must avoid jostling coals when lifting pot.`,
  `Permitted for Jew—specifically pot on coals; coals around pot Jews forbidden—lifting surely stirs coals—pesik reisha igniting bottom/extinguishing top—even non-Jew some strict—Magen Avraham/Eliyahu Rabba—for Shabbat need may rely lenient non-Jew; oven open/close via non-Jew siman 259b MB.`,
  `Garuf u’ketum—but unstoked forbidden even mitztamek vera; oven even raked ketum Acharonim.`,
  `Even on Shabbat—do not think permission only erev removal return erev—teaches removal and return even Shabbat repeatedly.`,
  `While boiling—unlike other matters—reason once no longer boiling (no yad soledes) renewed cooking applies—siman 318 sk 4—Rema 318 sk 15 Magen Avraham lenient if not fully cooled.`,
  `Still in hand—never put down from removal until return—unlike bed/table interim equals ground—nullifies first shehiyah—return looks initial placement Shabbat though fully cooked—looks like cooking.`,
  `Intent to return—preserves first shehiyah if planned return before cooling; if removed without intent to return then reconsidered—initial Shabbat placement forbidden—even without ground interim—Biur Halacha cites Rishonim lenient still in hand without intent and intent while removed hands—in need may rely.`,
  `Specifically on its top—thick rim or cover spanning cavity—pot hung inside air with rim protruding counts “on top”; “inside” only when sits on kirah floor.`,
  `Inside forbidden—looks like cooking routinely—Rashba Ran; shallow kirah without cavity permitted—“inside” not applicable—fire in kirah see 318 sk 16.`,
  `In oven—even straw/gabba heated—as above.`,
  `Likewise kupach—chazarah never permitted except garuf; kupach intense vapor—raking ineffective—as sk 1.`,
  `Specifically dish…—refers to boiling return—must be fully cooked else further cooking—318 sk 4 MB there.`,
  `Even another kirah—even greater heat—still “return”; but if insulated non-heating then Shabbat moving to kirah or kirah to insulation forbidden—new act—257.`,
  `Some say all this—explaining need still in hand plus intent—but garuf u’ketum everyone agrees.`,
];
