export default [
  `On mouth of hot-water pot—even on flame.`,
  `Fully cooked—Rashba: cooked food cooled completely never “cooking” even soup; Mechaber OC 318 sk 4 like Rosh soup cooled still cooks—here pastry dry bread stuffed meat lenient even yad soledes—no soup—318 sk 15.`,
  `Not usual cooking—although initial placement forbidden even cooked hot garuf kirah—looks cooking—here intermediate pot break—no appearance—much fat solidified—strict nolad—318 sk 16 Magen Avraham.`,
  `But insulating—hot-water pot covered—even without fire forbidden sandwich pandish under cloth—hatmanah—even cooked rabbinically.`,
  `Forbidden to leave—initial Shabbat forbidden even boiling mitztamek vera—Gra.`,
  `Put inside oven—Shabbat morning put cooked dish warm—even inside oven kirah only permitted on surface—here only residual heat not Shabbat hatman—looks cooking—if Shabbat hatman inside forbidden warm cooked dish—Rema sk 2 Magen Avraham lenient all cases—ends stringent.`,
  `Completely cooled—if cooled fully further cooking applies—even weak oven might reach yad soledes.`,
  `Here—return inside oven always forbidden regardless intensity—unless heat yad soledes otherwise not called heated oven.`,
  `If heat…—must clarify heat… otherwise lenient apply—plain Rema sk 2 Magen Avraham.`,
  `And all matters—even rabbinic telling non-Jew forbidden.`,
  `Heat pot—even indirect fire—no chazarah issue—still cooking prohibition fully cooled—318 sk 4 15—Magen Avraham Shaarei Teshuva after fact permit indirect oven like lenient poskim sk 15.`,
  `Even cold—penalty wait kedei sheyeasu though no benefit—if non-Jew himself without request cold permitted—no benefit—Israel watching must protest.`,
  `Still edible—even benefited warmth after fact permitted—could eat cold—even commanded direct fire after fact don’t forbid dish.`,
  `Permitted eat—even dish unripe bitter meat edible cold permitted.`,
  `Therefore practice—refer above—forbidden tell non-Jew heat—non-Jew places cooled dish on cold oven before lighting—no prohibition—later heating winter oven permitted—intent house heat—not dish—even pesik reisha rabbinic telling permitted lenient stack—English kitchen ovens always cooking intent—forbidden—sources cited Biur Halacha.`,
  `Forbidden thus—setting pots near/along winter heater before lighting—joint placement—but telling permitted intent heat house—from leniency hot water fixed oven permit washing dishes—even command—food warming intent permitted—but pouring hot after Jew lit questionable—Jew may not pour water before lighting.`,
  `Still warm—even without yad soledes.`,
  `Permitted stand—even Jew after lit.`,
  `Near winter oven—not atop or inside unstoked—even before lighting forbidden lest later stoke boil pots—practice lenient erev hot pots—support sources Maharil—after lighting place barrier Maharil.`,
  `Law garuf ketum—where return garuf Shabbat permitted lean unstoked kirah/ovens.`,
  `Already explained—standalone—like garuf return allowed even ground before—same lean unstoked oven even preplaced on ground.`,
];
