export default [
  `Boiling – So that it is hot to yad soledes bo; otherwise it is forbidden because of cooking.`,
  `On the ground – As we saw in sk סא.`,
  `When the dish shrinks – The reason for the prohibition is that water buried in pillows and blankets does not always stay hot enough; perhaps yad soledes bo no longer applies, and putting them into the dish on the stove ends up “cooking” them. Hence the prohibition follows when the embedded hot water is usually not hot enough; today many poskim permit adding water from our urns, since urn water is very hot and certainly yad soledes. Some Sephardic poskim are strict here, yet we find Sephardic poskim who are lenient; one who is lenient may continue his practice.`,
  `Siman 318 – Clause 15: there we learn that according to the Rema there is no “cooking” in water that boiled and cooled as long as it has not cooled completely; therefore according to him one may insulate hot water to pour into a dish on Shabbat.`,
  `Patty / pie (pasteldej) – This exemplifies any dry food.`,
  `Therefore they did not decree – They did not decree here lest it look like cooking. This is unlike the empty-pot case explained in clause 3, where sometimes there is concern it looks like cooking: an empty pot only interrupts between fire and pot, but above a full pot there is no normal path of cooking. This is the source for those who permit placing on a blech on Shabbat itself, as in sk עא.`,
  `Certainly forbidden – Because of the hatmanah prohibition: hatmanah on all sides of cooked food is stricter than placing on a kirah. This hatmanah is explained at length in siman 257, clause 8.`,
  `And as explained – In clause 2; because initial placement looks like cooking.`,
  `And there is no concern for cooking – This view permits putting the dish on Shabbat itself into an oven where no fire burns inside, even though it is still hot. By “oven” the Rema means “our ovens” mentioned in clause 1, and he explained their law is like a kirah.`,
  `Completely cooled – The dish. On this view, since the oven’s heat is slight and the dish is still lukewarm, placing it in the oven on Shabbat does not look like cooking.`,
  `And some are strict – On this view there is always concern it looks like cooking; one may not put food in the oven on Shabbat even if it already cooled—and this is also the Mechaber’s view.`,
  `Forbidden – Even for the lenient view. Its law is like a regular oven: one may not put food inside even if raked and covered, even for fully cooked food.`,
  `To tell a non-Jew to do – In siman 307 we learn it is forbidden on Shabbat to ask a non-Jew to do for a Jew melacha forbidden on Shabbat; this prohibition is also rabbinic.`,
  `If it cooled – We learn one may not reheat a cooled dish lest it look like cooking; therefore one may not tell a non-Jew to do so either.`,
  `Forbidden to eat it – After the fact the prohibition applies to a dish that is biblically forbidden to place on the fire, such as a soup whose liquid cooled. Such a dish is forbidden even after the fact, because one may not benefit from melacha a non-Jew does for a Jew on Shabbat. Details are explained in simanim 276 and 325.`,
  `Even cold – Meaning the dish heated by the non-Jew remains forbidden even after it cools again. This is a novel ruling of the Rashba: we penalize one who intentionally told a non-Jew to heat food by stringently forbidding the dish from reverting to permissibility.`,
  `Still fit to eat – The dish had not completely cooled from its cooking and could have been eaten even before the non-Jew heated it.`,
  `They may eat – Because there is no benefit from the non-Jew’s melacha—the dish was already edible before he heated it.`,
  `Winter oven – An oven meant to heat the house, not for food preparation; a non-Jew may place the pot near it when it is off and cold.`,
  `That oven – Explained in siman 276, clause 5: in cold countries one may ask a non-Jew to light the oven if it is very cold, because “everyone is sick with respect to cold,” and one may tell a non-Jew to do melacha for a sick person who is not in danger.`,
  `They boil again – While the non-Jew permissibly heats the house the pots also get hot, and this involves no prohibition.`,
  `In this manner – Translation of behei guvna: for a Jew it is forbidden to place the pot even near a cold oven if the non-Jew is about to light it.`,
  `Winter oven – Next to it even when it is lit.`,
  `Regarding placing next to it – Just as one may return food to a raked-and-covered kirah, so one may initially place food next to a kirah even when it is not raked and covered, because when merely leaning there is no concern of appearing like cooking—all when the dish has not cooled, lest there be a cooking concern.`,
  `Siman 318, clause 15 – There the Rema wrote about heating moist food: “They were accustomed to be lenient if it had not completely cooled.”`,
];
