export default [
  `Even if raked—raking removes most fire yet sparks may remain; intense oven heat raises stirring concern to ignite sparks. Mechaber sounds like Tur—even straw-fed oven forbidden if raked/ketum; Rav Yehonasan in Ran agrees—yet Rambam implies straw/gabba forbid oven only when unstoked (Maggid Mishneh); Kessef Mishneh, Ran novellae tend lenient.`,
  `Where hand recoils—but if not yad soledes bo one may place even on top, even Shabbat; possibly even unstoked—since placement spot lacks yad soledes (Magen Avraham).`,
  `How much more forbidden—specifically if not fully cooked or improves beautifully; but mitztamek vera lo permitted, likewise raw pot even unstoked.`,
  `That it is a place—it resembles a kirah: kirah holds two pots; kupach holds one—narrower space concentrates more vapor than kirah, less than oven.`,
  `Law like kirah—even without raking or covering straw.`,
  `Law like oven—even raked/ketum forbidden inside, on top, or leaning.`,
  `Our ovens—opening from side and quite wide—less intense heat, treated like kirah; Tiferes Shmuel cites Rashal disagreeing—either way baker’s oven heated constantly—follow oven stringency.`,
  `If forgot shehiyah—all the more mistaken ruling.`,
  `Even mitztamek vi’yafeh—even inside oven—little benefit since anyway edible fully cooked—after fact permitted.`,
  `Forbidden—for anyone; household members forbidden since cooked for them.`,
  `Until Motza’ei Shabbat—Ashkenazi gloss implies kedei sheyeasu like sk 32 shehiyah; Rambam’s wording suggests otherwise (Pri Megadim).`,
  `Returned via non-Jew—for Jewish need.`,
  `Law like forgetting—non-Jew deliberate not worse than Jewish unintentional—thus improves beautifully permitted once fully cooked—little benefit.`,
  `If Jew returned on Shabbat—even unintentionally equals deliberate shehiyah—forbidden if improves beautifully—chazarah more stringent (active deed); Magen Avraham permits others if cooked and unintentional. Even Rema who permits ben drusai shehiyah—all forbid chazarah even fully cooked.`,
  `If mitztamek vera permitted—even ab initio returning forbidden if vera lo—after fact permitted even intentional return—no benefit.`,
  `Some say once edible bedieved—even unstoked—no stirring fear when edible—unless needs ben drusai level or chazarah Shabbat looks like cooking unstoked.`,
  `Ma’achal ben drusai—half vs third cooking—OC 254 sk 2 generally half—in pressing case possibly lenient.`,
  `Or even oven—we distinguish oven vs unstoked kirah: unstoked kirah stirring fear forbids oven even raked (heat like unstoked); what unstoked kirah permits once cooked permits oven too.`,
  `On oven surface—likewise inside oven/kirah.`,
  `Not reached—then stirring concern with peat/wood fuel and unstoked coals.`,
  `Comes to return—see next clause sk 2.`,
];
