export default [
  `Cold cooked food that the (Jewish) maid placed on the winter oven before it was lit—permitted to drink; only warn them not to repeat. Responsa Beis Ephraim 21; Shaarei Teshuva OC 24. Regarding pouring hot from first vessel (yad soledes) onto lentils and cooked cold food—many challenged erev Shabbat; Eshel Avraham OC 45 explained: in dry food there is no cooking-after-cooking; even if some cold water remains we follow majority; must avoid flipping lentils/cooked upside-down lest cooking; even if lentil weight suggests not fully cooked—concern for opinion that cooking-after-roasting applies—318 sk 5—same after roasting erev Shabbat. Seems if only poured hot erev Shabbat—but if actually boiled erev in water and on Shabbat pour water from kli rishon—permitted even to flip, dry food no cooking-after-cooking—318 sk 4. If placing roasted lentil Shabbat into hot water—put hot water in kli sheini first then lentil, lest cooking-after-roasting; if opinion holds "dyeing" in liquids—318 sk 19—pour bit of roast from sixth day to "dye" hot water then add Shabbat. See above OC 54.`,
  `Same Magen Avraham: permitted to stand them etc., even via Jew. See Shaarei Teshuva OC 4 Magen Avraham sk 42; Taz OC 54.`,
  `Same Magen Avraham: next to the oven etc., but on top forbidden since not garuf u’ketum. Rema’s wording implies even before lighting forbidden since eventually fire inside—we decree lest stir coals; practice permits—have support. Magen Avraham sk 43. Reason Terumas HaDeshen OC 55—insulation separates fire from pot. See above OC 67.`,
  `Same Magen Avraham: our ovens etc.—see above OC 18.`,
  `Same Magen Avraham: fully cooked—meaning mitztamek vi’yafeh lo and soup dish; but mitztamek vera lo—even if pot not hot permit—below 318 sk 4—Shaarei Teshuva OC 4—that follows “some say” in Magen Avraham; Mechaber forbids even mitztamek vera lo—as Shaarei Teshuva cites.`,
  `Same Magen Avraham: “so is practice”—meaning even standing pot very close to oven wall touching oven wall permitted. Shaarei Teshuva there. See Responsa Gur Aryeh Yehuda 70—olive oil in winter congealed near oven to liquefy to eat—originally edible now edible. Cited Ahavas Chesed end OC 12; Magen Avraham 328 sk 7—verify.`,
  `Know: all above permissions only winter cold when they light house fire via non-Jew—otherwise “everyone sick from cold”—siman 276 end; otherwise making fire in house mainly to heat dish—strict prohibition deserve penalty forbid even cold; one not greatly compelled to heat food—even permitted method—should be careful. Ahavas Chesed there.`,
  `Hold this rule: all leniencies in this siman only hot dish; cold dish or cold items—see siman 318 what is biblical cooking—Shaarei Teshuva end siman; Magen Avraham end siman.`,
];
