export default [
  `See above siman 257 regarding food eaten in its raw state.`,
  `So too Hagah Maymoniyot ch. 4 that one tells a non-Jew to remove them; Agur writes to forbid; below end siman 311 it implies that even a Jew may remove it.`,
  `One must analyze—for this is not called hatmanah unless one covers from above, as written below siman 257; in such a case it is not hatmanah, therefore it seems one should not dismiss R. Azriel’s words; see above siman 257 on hatmanah.`,
  `See Hagahos Mordekai 179a.`,
  `In Hagahos Mordekai fol. 179b in the name of Maharam: it is forbidden to lean a pot inside the oven near nightfall or near Barchu—even if garuf u’ketum and fully cooked—and likewise to lean on the oven wall or on top is forbidden; but if yad soledes bo does not apply there it is permitted... It appears even Rambam did not write “one does not lean on Shabbat” except according to his reasoning that chazarah is permitted near nightfall—hence he mentions Shabbat specifically—all the more so leaning; other poskim who forbid chazarah erev likewise [forbid leaning] near the oven, as Maharam; yet practice erev is lenient even for chazarah, as explained above.`,
  `I already wrote above that the practice is lenient regarding placing on the ground.`,
  `Regarding this I saw in my teacher’s house in Shirlein that sometimes their cholent cools; on Shabbat before the meal the servants light a fire near the pots so they warm well. Some remove them and place them near the fire and explain to permit because we need not fear forbidding them—presumably they are somewhat warm, close to yad soledes, and adding heat is permitted since there is no [new] cooking in them; even if they cool greatly one does not forbid them because their intent is for them; even if intended for Israel one need not fear—presumably the Jew does not want them heated if he knew they cooled completely, and when servants act it is not in his power to forbid us the food against our will; at weddings servants commonly do so and no one refrains from eating. Ritva and other gedolim permit; however it is fitting not to do so because it spreads word (avsha de-milta) and denigrates Shabbat; anything uncommon—Chazal appropriately forbade it.`,
  `It appears where they are still [warm] one need not be so concerned. Beis Yosef’s words refer only to cold items; our practice is likewise—we are stringent with cold things and lenient with things removed from the oven while the type [of food] is still as Ran described. What Beis Yosef distinguished between placing on the kirah or inside it is not mentioned in Ran—Beis Yosef invented this distinction himself, and perhaps he does not hold the distinction—see what people do. See above what I wrote on this end siman 257; Hagah Maymoniyot ch. 4 that Maharam protested placing hot water after removing it inside pillows and blankets; this seems worse than returning to the oven since it begins hatmanah because they were not there erev.`,
];
