/** worker-slot-15 — siman 576 hand fixes */
export const FIXES = {
  "beur-hagra/part-001.txt": {
    "1:ה":
      "And all the cities, etc. Mishnah chapter 3: that city, etc., and according to Tosefta; Rambam explained the same for all troubles; Levush there on these we sound in every place — but immediately, meaning not like a matter requiring proclamation; so too in Rosh, except he has both versions; so too in the gloss; what is written there regarding an incident, etc., fast without proclamation. From what is written in the Gemara 19: on all of them we sound only in that province — proclamation is explained as oral proclamation like the proclamation at the beginning regarding rains, as in siman 575; see Biur HaGra and from there it is proven there is no [sounding] in every place; so too in Tosefta chapter 2: on all of them we sound only in that province — in Syria we do not sound in Eretz Yisrael, in Eretz Yisrael we do not sound in Syria; so too in the Gemara: this maidservant and that maidservant — only that Ran settled and said what the Mishnah means “in every place” is in that province, and all Eretz Yisrael is one province, even beyond the Jordan and Ashkelon since those who left Egypt conquered it; but Eretz Yisrael and Syria not; so too maidservant and maidservant in two provinces, but in one province they fast and sound with shofar; see the gloss and Lechem Mishneh that Rambam explains like Ran's explanation of “in every place” as in Tosefta; and explains like Raavad: they sound and do not fast — meaning the surroundings; and R' Akiva is the one who said on these, meaning they sound immediately as in Rosh and the gloss; but Tosefta holds they fast and do not sound; and this is what the incident means, etc., and Tosefta is the view; his words are strained — the first part is R' Akiva and the end Tosefta. It is more plausible as I wrote that there is no [sounding] in every place; so Tosefta and in the Gemara they explain in those places where the trouble is; Ran's method as in the gloss seif 8; Tur's method like Rashi and as in seif 6.",
    "12:ג":
      "And in every place, etc. — meaning what is said regarding Shabbat: they do not fast and not with shofar but cry out orally, as written 14a: shofarot on Shabbat — who permits? If it were that they fast, it should say “fast on Shabbat — who permits?” as written chapter 2: we do not decree a fast on the congregation on Rosh Chodesh, etc., and if they began, etc.; from not mentioning Shabbat and Yom Tov it implies even if they began they interrupt; as Tosefta: communal fast we do not interrupt for written Yom Tov in Megillat Taanit — implying only for those; so Rambam and for those mentioned in the Mishnah, city that was surrounded, etc., and those in the baraita, and likewise individual, etc., and provisions and anointing; but for others even crying out is not done as written “on these,” etc.; therefore “and they do not cry out,” etc., except city surrounded, etc.",
    "14:ג":
      "And they are permitted, etc. As written 11b: there is no communal fast in Babylonia, etc.; explained as Tosafot there: they have no fasts except for other matters, and in those their law is not like communal fasts.",
    "16:ב": "And they remove, etc. As written: is this not a fast I choose, etc., undo wickedness, etc.",
    "2:ב":
      "And women are not counted, etc. From what was said: feet of men forty thousand alone from women and children as “feet of the men” alone excluding children; in Yerushalmi chapter 3 halachah 5: youths but not elders; so it says six hundred thousand feet of the people, etc., and women and children are not in their count as “lift,” etc., every male by their skulls from age, etc.; so too elders as in Bava Batra 121b: it was not decreed, etc., “and he went up,” etc., and forty thousand who were not in the count as “all your countings by all your numbers,” etc.; as in Midrash Rabbah therefore it says only the tribe of Levi you shall not count, for all who were in the count, etc.",
    "5:ג": "And if the plague spread, etc. From what is said: and it comes upon the congregation — meaning on most; and perforce as Moed Katan 26a.",
    "6:ג":
      "In every place even the distant ones. So Tur wrote and as the Mishnah reads “in every place”; as the incident, etc.; explained they fast and sound like all who sound in the Mishnah; explained in every place even the distant, as Rashi on the Mishnah there s.v. sound in every place: if they see in Spain they sound in Babylonia, in Babylonia in Spain; what the Gemara says on all of them we sound only in their province — explained like Rashi there s.v. in their province in that kingdom where all wells are there, meaning it refers only to the place stated earlier in the baraita there; but Tosefta is difficult according to Rashi's explanation who said from that baraita, etc., and repeated after the other things the Mishnah said “on these we sound in every place,” and said on all of them we sound on them only in that province, etc. — according to Ran it fits; see the gloss. There is doubt on Rama why he did not emend here and why he did not argue on Shulchan Aruch in seif 61 and 62; on Shulchan Aruch it is very difficult.",
  },
  "kaf-hachayyim/part-001.txt": {
    "1:_":
      "(1) [Seif 1] Just as they fast and sound for rains, etc. Rambam wrote beginning of chapter 1 of Laws of Fasts: a mitzvah from the Torah to cry out and sound trumpets for every trouble that comes on the congregation, as it says regarding the enemy that oppresses you — and you shall sound trumpets, meaning every matter that troubles you such as drought, plague, etc. — cry out over them and sound. This is from ways of repentance that when trouble comes and they cry out and sound, all know that because of their evil deeds harm came to them, as written “your iniquities have turned,” etc., and this causes removing the trouble from them, end of his words. What Rambam wrote “and sound trumpets” — Maggid Mishneh wrote there it is clear like Rashba that in the Temple there are two trumpets and shofar, but in the borders there is only one of them — trumpet or shofar, see there. Magen Avraham in this siman wondered why we do not practice sounding in time of trouble; Nachalat Hashulchan note 1 answered they rely on Semag who did not bring this mitzvah to sound in trouble even by hint, end of his words. And Machatzit HaShekel siman 575 note 2 wrote in Scripture it is written “in your land” — one might say not in chutz laAretz, and in Eretz Yisrael itself when not in our possession one might say not, see there; see also what later authorities answered.",
    "10:_":
      "(10) Pitum haKetoret — a wondrous practice to say it in time of plague; good to fulfill this too; I studied it day and night; the secret is that “goodly oil” for the 248 limbs in the spelling of plague; also beware of falsehood — this is a great principle, for one who speaks falsehood in time of plague is endangered, may Hashem protect us. Beit David part 4 siman 57 from Kavanot HaAri z\"l; see in Zohar parashat Vayera p. 101 in Midrash haNe'elam that forty worthy men from the city should be taken and divided to four corners of the city, ten in each corner, and say Pitum haKetoret with great intent, then verses “Moshe said to Aharon take the pan,” etc., “Aharon took as Moshe spoke,” etc., “he stood between the dead,” etc., and they did so twice and the matter ceased, see there; see also in Shaar HaKavanot discourse Pitum haKetoret what more to say in time of plague, see there.",
    "5:_":
      "(5) See in Maggid Meisharim to Maran z\"l parashat Emor p. 35d who wrote that since they surrounded R' Elazar with the four species that come to appease for water, water was aroused and came; had they surrounded again, most rains would come to the world as in the days of Choni haMeagel; therefore continuous rains of blessing came so they would not surround again. This principle shall be in your hands all the time the world is in your hands — all the time the world needs much rain, go surround the mentioned righteous and fast; for every trouble that should not come on the congregation surround them four times and fast, end of his words; it implies specifically for rain one must surround with four species because they come to appease for water; but for other troubles that should not come, one need only surround seven times. What is written “the mentioned righteous” — it seems other righteous too whom the incident was so.",
    "6:_":
      "(6) [Seif 2] So too in our time one does not fast at all during the plague, for one is weakened when not eating and drinking — the air change harms, God forbid (Magen Avraham note 2). Eshel Avraham note 1; so they said from the Ari z\"l; so there is reason in the Talmud 22; Maharam ben Chaviv in responsa manuscript siman 16; Birkei Yosef note 4 hours, note 2; see in Yoreh Deah end of siman 574; regarding Tisha BeAv see above siman 524 note 35.",
  },
  "mishnah-berurah/part-001.txt": {
    "16:א":
      "(36) And they remove obstacles, etc. — as written in Yeshayahu: is this not a fast I choose, etc., undo wickedness, etc.; see in Magen Avraham he wondered why we do not practice so — behold this is the essence of the fast, see there.",
  },
  "shaarei-teshuvah/part-001.txt": {
    "3:_":
      "(In Shulchan Aruch seif 5.) They cry out over it alone, etc. — see in Tur; see seif 11 and seif 12; the questioner challenged in responsa Shevut Yaakov part 3 siman 40 from what is proven in Bava Kama 81 that for anointing with oil they sound even on Shabbat (see in Beit Yosef in the name of Maaseh Zion who sensed this on Shulchan Aruch seif 12); see there that Shevut Yaakov answered it is proven to one who studies there that Rashi and Rambam do not have the word “on Shabbat,” see there.",
  },
};
