/** worker-slot-9 — siman 386 hand fixes (10 blocks) */
export const FIXES = {
  "beer-hagolah/part-001.txt": {
    "1:א": "(1) From Rambam's words chapter 1, and a variant in the braita Shabbos 6, and as Rashi explained there"
  },
  "beur-hagra/part-001.txt": {
    "2:ב": "(2) Partnership, etc. Tosefta chapter 6 of Mechilta: partnership of an alleyway requires that it be with them in the alleyway; eruvin of courtyards requires that it be with them in the courtyard—two who are partners one with another, whether in wine or in oil, requires that it be with them in the alleyway. And Gemara chapter 5, 2: I would say eruvin, etc.; and see Rashi there and Rama siman 1:",
    "5:ה": "(5) And not with herbs and mushrooms. Rif and Rambam. And their reason: since the Gemara there challenges the anonymous mishna 27, 1: but there are herbs, etc.; but it is very puzzling—how does it compare? If with living herbs and mushrooms, if so what does it challenge from herbs that are not mentioned anywhere that one does not make eruv with them—it should have said produce that one does not make eruv with while living as written 29, 1: wheat and barley that are not fit for eating, etc., and all things not fit for eating while alive; and if it refers to cooked herbs, etc., it is very difficult, for certainly it is food as proven in Shabbos 68, 1: anything that is food—to exclude shoots of starchy grain, etc., and its growth from the ground—to exclude herbs and mushrooms—if we do not exclude them from \"anything that is food\" it is proven they are certainly food, only their growth is not from the ground; and for eruv we certainly do not require growth from the ground, as stated there 30, 1: one makes eruv with meat and eggs, etc., and as written in seif 7; therefore it appears the essence is certainly one makes eruv with cooked herbs and mushrooms, for they are certainly food as stated, and so regarding beracha we consider them food like all foods; and if one makes eruv with legumes, etc., all the more so with herbs, etc., which are important food as written in Berachot 37, 1: if he brings artichokes, etc., and Rashi there; and so we say in general that it rises to the king's table—and there is an error in the books and a word is missing, etc.; and the essence of his proof shows from the end: all are taken, etc., and he challenges: but there are herbs, etc., that are not taken with maaser money as taught explicitly in Sifra chapter 1, section 8: from general and particular—how so, etc., even all fruit of fruit, etc., herbs and mushrooms are excluded, and the language fits well that it says \"but there are\"—that they had a known braita brought in many places in the Gemara and Yerushalmi:"
  },
  "biur-halacha/part-001.txt": {
    "5:_": "And one says one makes eruv with spices—see in the commentators who wondered at this opinion, for it is Rambam's opinion which is against the Gemara's sugya that says: if we say because it teaches in that mishna spices—and spices are not fit for eating—behold here too it teaches wheat and barley and they are not fit for eating while alive; behold the Gemara compares spices to living wheat and barley that all agree one does not make eruv with them; however in truth Rambam never mentions the law of wheat and barley [and what he wrote in Laws of Eruvin chapter 1 halacha 10: such as bread and types of grain—it is possible his intent is even while alive since he did not write cooked, and so in Beit Meir]; and it appears for Rambam it will be permitted to make eruv also with living wheat and barley, for regarding partnerships of alleyways he holds they were lenient in it, and as they were lenient that one need not specifically bread and its accompaniments—from Tosefta chapter 6 it is taught there at the head of the chapter: partnership of alleyway—how so? A person brings a barrel of wine and of oil and of grain and of dried figs and says: this is for all members of the alleyway; and accordingly one explains the sugya differently: if we say because it teaches, etc., and spices are not fit for eating—the explanation is: and for this reason it enters your mind that one does not make eruv with them; if so in that braita too it teaches wheat and barley, and they too are not fit for eating while alive, and nevertheless Rav said on it and so for eruv—behold we do not require that it be immediately fit for eating, but anything that is types of food; and the same with spices which are also designated for seasoning; and barley—and he did not bring any opinion here—it appears he holds that in this all agree one does not make eruv; and so in Sefer Or Zaru'a that wheat and barley are inferior to spices and all agree one does not make eruv—and it requires study; and see in Ma'aseh Rokeach and Beit Meir. And see in Gra's hagahot on that Tosefta where he deleted the word grain:",
    "6:_": "And raw meat, etc., and requires quantity, etc.—see in Rashba and Ritva who wondered on this, for raw meat is not fit for eating; and they answered it deals with heavily salted meat until it is not eaten because of its saltiness, and through salting it softened and became somewhat fit for eating; and Ritva further answered the Gemara's intent is not on truly raw meat but on meat that is somewhat cooked and not fully cooked [and it is supported from the sugya in Sanhedrin regarding ben sorer u'moreh that there it calls partially cooked meat \"cooked\" and not raw meat (daf 71)]—and this is fit for eating and is so called:"
  },
  "eliyah-rabbah/part-001.txt": {
    "5:_": "[5] In all types, etc. I wonder that he omitted what Shulchan Aruch wrote that even four and five types of food combine for the food of two meals (Malbush Yom Tov); and in my humble opinion he holds like Ra'avad that Beit Yosef brought, that specifically eruvin of techumin combine; and so Maggid wrote—Rashba did not decide; and it appears to me more likely that something was omitted in the printing, and the seif markers prove he skipped from 4 to 6:"
  },
  "kaf-hachayyim/part-001.txt": {
    "4:_": "(4) There—they gather bread or another thing, etc., and the reason there is a distinction between eruvin of courtyards and partnerships of alleyways: this is specifically with bread and all types of bread, and this with bread and even with other types of food and beverages—this is because eruvin of courtyards is because of dwelling, to combine their dwelling to make them one, and a person's dwelling is not drawn after wine and other beverages but after bread; but partnership of an alleyway is only to partner the domain of the courtyards in the alleyway, not the domain of the houses, and a courtyard is not a dwelling house; therefore one makes eruv with anything for recognition; and for this reason they can place it in the air of the courtyard or in a house that does not have four by four—Levush, Pri Megadim siman 1, Teshuvah Shulchan siman 2, R' Zalman siman 1; and see above siman 366 siman 7:"
  },
  "machatzit-hashekel/part-001.txt": {
    "3:_": "(s.k. 3) Like an alleyway, etc., for in any case there must be a partition between them and the gentile—meaning it must deal that between those places, between one place and its fellow, there is an alleyway for the gentile, for if not, since they sit in the circuit of one wall, why can they not participate? Or an alleyway in which a gentile dwells interrupts between them, and therefore they are forbidden to carry from one to another, as Magen Avraham wrote s.k. 1; and on this Magen Avraham challenged: if so, in any case one must divide at the end of each alleyway with a partition so the gentiles do not forbid them—and if so it is obvious that it helps, etc.; and it would have been possible to deflect that it deals when they rented domain from the gentile, so no partition is needed for the gentile, or it deals where the gentile has an opening or window open behind his house for more than two se'ah, for the gentile does not forbid as below siman 389; but since Shulchan Aruch was general it appeared strained to Magen Avraham to establish it thus:"
  },
  "magen-avraham/part-001.txt": {
    "8:ב": "(2) That he not enjoy. Even though in eruvin of techumin it is permitted—there one makes eruv only for a matter of mitzvah, and mitzvot were not given for enjoyment—and Rambam and Rashba; nevertheless in the name of most commentators they wrote that nevertheless it is permitted in eruvin of courtyards, since it appears to another Israelite; and even though he said he will not enjoy, or konam—it is permitted, for he did not intend except in the manner of his enjoyment; and see in the Gemara; and if so, what Rama wrote that regarding konam all agree—it requires study, for these are their disputes; except that according to Tur's opinion regarding konam even in eruvin of techumin one does not make eruv, for it is like hekdesh—and Rambam and those who agree with him hold the halacha is not like Rav Huna, for it follows R' Eliezer—see there:"
  },
  "mishnah-berurah/part-001.txt": {
    "1:ג": "(3) They gather bread or another thing—and even though regarding eruvin of courtyards we require specifically bread as above in siman 366, for there it is different, for eruv is because of dwelling, to combine their dwelling to make them one, and a person's dwelling is drawn only after his bread; not so partnerships of alleyways, for it is only to partner the domain of the courtyards in the alleyway, not the domain of the houses, and a courtyard is not a dwelling house; therefore anything of food suffices; and from this reason also it suffices when they place it in the air of the courtyard:"
  }
};
