/** worker-slot-13 siman 513 */
export const FIXES = {
  "kaf-hachayyim/part-001.txt": {
    "6:_":
      "(6) [seif 2] If there is a doubt whether it was born on Yom Tov or on a weekday, it is forbidden; and even if it was mixed among a thousand, all of them are forbidden. Tur. And the reason is because it is a davar she-yesh lo matirin, and anything that has a permissible use is not batel. Beit Yosef. However, nevertheless, Maggid Mishneh chapter 1 law 80 wrote that regarding its doubt when it was mixed with others, there are those who ruled that all of them are permitted; and when it teaches that it was mixed among a thousand, all of them are forbidden — it certainly refers [only] to a case of certainty, and there are those who forbid. And regarding the view of those who permit, the Rashba, z\"l, agreed (in Avodat HaKodesh, gate 5, section 4); and so it appears from the words of the Rambam, end of his words; and Bach agreed with Beit Yosef, and Taz. And so is the view of Maadanei Kodesh and Bigdei Yesha, s.k. 24. However, in Yoreh Deah siman 102, seif 1, the Shulchan Aruch ruled there to forbid; and so too Magen Avraham, s.k. 24, that one should be stringent. And so R' Zvi, section 4, Chayei Adam general rule 101, section 4, Machatzit HaShekel siman 7, section 2. However, R' Zvi wrote there that on the second day of Yom Tov one may be lenient if eggs are needed — see there. And in Chayei Adam general rule 53, section 19, he wrote that on an ordinary Yom Tov that is not after Shabbat one may permit for great need; and it implies even on the first day of Yom Tov, as long as it is not after Shabbat. And so Mishna Berurah, section 5, that in a case of loss one may rely on those who permit:",
    "7:_":
      "(7) There. If there is a doubt whether it was born on Yom Tov, etc.; and if it was mixed with others and from these with others, any mixture of the second group is permitted, because there is here a safek safeka arising from the mixtures, and all of them rule in these doubts to permit. Avodat HaKodesh there. Eliyah Rabbah, section 4; and so is the view of the Shulchan Aruch in Yoreh Deah siman 106, seif 8; however the view of our teacher Rama, z\"l, there in the Hagahah is to be stringent unless for a time of need, as Sha'ar HaTziyun wrote there, s.k. 57 — see there. And so is the view of Peri Chadash there, section 43, like the words of the Shulchan Aruch; and so is the view of Beit Levi there, section 46; Likutei Halachot Peri Megadim there, section 60; Peleiti there at the end, section 28. Eliyah Rabbah there at the end, section 18; and Peri Chadash wrote there that even according to our teacher Rama, z\"l, who is stringent, this applies to a d'oraisa prohibition, such as an egg that was born after Shabbat; but in a d'rabbanan prohibition, such as an egg that was born on Monday, even according to our teacher Rama, z\"l, it is permitted in such a case — see there. And R' Zvi in this siman, section 4, wrote that one may not permit in such a case except on the second day of Yom Tov, but not on the first day of Yom Tov; and it implies even if it is not after Shabbat one may not permit on the first day of Yom Tov; however, we already wrote that even according to our teacher Rama, z\"l, for a time of need it is permitted:",
  },
  "levushei-serad/part-001.txt": {
    "2:_":
      "(Magen Avraham, s.k. 2) muktzeh. And see Bach and Mordechai, etc., as is correct:",
  },
  "machatzit-hashekel/part-001.txt": {
    "6:_":
      "(s.k. 6) Besides, etc. — that the egg is still whole; and nevertheless, specifically, etc.; meaning, according to one opinion, if it was crushed and dissolved, since the substance of the prohibition is there, even though it is not recognizable in such a case, Shach inclined that perhaps Rama agrees it is not batel, except [only] when the egg is whole and they removed the egg from there and nothing remained except taste in general; nevertheless the Mechaber holds it is not batel; but Rama's view, etc.; and Shach there agreed with Rabbeinu Yosef, see there:",
    "7:א":
      "(s.k. 7) For appearance, etc. — even though it came to improve, etc.; for at the end of tractate Beitzah we learn: a woman who borrowed water and salt for her dough (it was brought above in Shulchan Aruch siman 327, seif 12) — the dough goes according to the feet of both of them, and they cannot bring the dough except to a place where both women can walk, for all things go according to the feet of the owners; and the Talmud challenges: let the water and salt be batel relative to the dough and the dough should go according to the feet of the owner of the flour; and Rav Ashi answers: because it is davar she-yesh lo matirin and it is not batel. And Tosafot challenged: here it is a different type in a different type, and also davar she-yesh lo matirin is batel as written in Yoreh Deah siman 102. And they answered: in their boundaries they were further stringent, etc., since water and salt come to improve the dough it is called the same type in the same type (and Taz and Peri Chadash in Yoreh Deah wrote: specifically regarding davar she-yesh lo matirin it is called the same type in the same type where it came to improve and not in another place); and therefore Magen Avraham wrote: since the Mechaber wrote 'for appearance and taste' it implies he requires both. But if he only did it for taste and it is not recognizable in appearance it is batel (that is, this is not difficult, for we hold every taste that was done only for taste is not batel, as Sha'ar HaTziyun already wrote in siman 98, s.k. 28, where the taste is not sensed it is batel, and so Peri Chadash); nevertheless one must say the Mechaber does not hold like the second answer of Tosafot mentioned above, but even when it came to improve it is called a different type, and therefore even davar she-yesh lo matirin is batel, and therefore he requires both appearance and taste:",
    "7:ג":
      "And see there in Shach, for he holds and explains thus the words of Shulchan Aruch there, that one suffices — either he did it for appearance or he did it for taste, it is not batel; and Peri Chadash disagrees regarding appearance, since it is an unresolved question that was not decided in Bava Kamma; therefore in a d'oraisa matter — namely an egg that was born on Yom Tov after Shabbat — we go stringently that appearance is a significant matter, but on an ordinary Yom Tov, which is d'rabbanan, we say appearance is not a significant matter; and see in Minchat Yaakov, general rule 74, s.k. 5:",
  },
  "magen-avraham/part-001.txt": {
    "5:_":
      "And likewise on Shabbat and Yom Tov. And if you ask: when it was born on Shabbat, behold it was completed on day six, which is a weekday, and it should be permitted — one can say: since it was concealed on Shabbat due to rabbinic [law], if you permit it on the Yom Tov that follows it, it turns out Shabbat prepared for Yom Tov and not for itself; and this prohibition is only d'rabbanan, for by Torah law even on the first [day] it is permitted, and if so [Shabbat] prepared for itself — end quote Ran. And in Yeshuot Shalom he wrote: according to what Tosafot wrote in the first chapter, that birth is considered preparation — if so it is forbidden d'oraisa on the day after it — end quote. And it seems he did not see the words of Ramban in Milchamot, who wrote that birth is considered preparation and nevertheless it is permitted d'oraisa on the second day, for the first day prepared for itself — end quote. And so in Sefer HaChinuch, that you do not find preparation d'oraisa except regarding an egg that was born on Shabbat after Yom Tov or on Yom Tov after Shabbat; and see there siman 366 and siman 507, seif 2:",
    "6:ג":
      "And mistaken (mesullat). And if the gentile knew it was born, it is forbidden to an Israelite; if he is mistaken he is not believed, for he intends to improve his sale to permit it (Mordechai). And if the eggs belong to an Israelite and the gentile is mistaken that they were born yesterday, and it is known they were born — it is forbidden to an Israelite; Yoreh Deah siman 69, seif 10 — the one who separated and Bach forbid, and Shach and Taz permit, see there:",
  },
  "netiv-chayim/part-001.txt": {
    "1:_":
      "(Magen Avraham, small seif 3.) For it is davar she-yesh lo matirin. See in responsa Tzemach Tzedek what he challenged from the Gemara in Beitzah daf 3, see there; and apparently it arose in my mind to distinguish, for according to the settled view he understood that in a rabbinic matter we do not say davar she-yesh lo matirin, for R' Eliezer in the conclusion innovated for us this law; and my teacher the Gaon, z\"l, told me: whoever confronts us, confronts us properly; for according to truth, why did Rav Ashi need to say 'doubt Yom Tov doubt weekday' — even in a rabbinic doubt we say davar she-yesh lo matirin is not batel; R' Eliezer should only have needed to [teach] in a certainty of rabbinic [law] that davar she-yesh lo matirin [applies], and he taught: and a doubt is forbidden — an egg born on Yom Tov, doubt of treifah:",
  },
  "peri-megadim/part-001.txt": {
    "1:_":
      "That is — Taz; and so Levush, that touching is permitted; and to distinguish between a lamp — there is greater concern that it will swing from an egg, or alternatively there he will tilt it; and there is reason for words of Torah even though it is pesik reisha and he does not intend; and in Shulchan Aruch, seif 3 — a standing lamp or candela candles; and see in siman 265 in Eshel Avraham; and Magen Avraham here in (2) explained that touching is also forbidden, and it will be explained there. In siman 310, letter heh; and here for the sake of permitting:",
    "3:א":
      "That was cooked — Taz; Magen Avraham on this; and Beit Yosef wrote what Ran [said] — they are the words of Rabbeinu Tam; that two matters that are a different type in a different type are batel in 60, and in the same type as well when it dissolved it is batel; and Levush brought them; and Yoreh Deah 102 in Shach for practical ruling it implies everything that dissolved in its type in any amount, and removal alone — see there and in Eshel Avraham there. And if the food will spoil until tomorrow it is not davar she-yesh lo matirin:",
  },
  "turei-zahav/part-001.txt": {
    "3:א":
      "That was cooked unwittingly. Kol Bo wrote on this: everything is permitted except the egg that one leaves until tomorrow, for we hold peeling of eggs is permitted, for it is merely the moisture of eggs [in general] and there is no taste at all; and he wrote that this was an incident in Luniel with an egg born on Yom Tov that was placed in a stew called fnadeh, and they permitted everything except the egg — end quote. And Beit Yosef wrote on this: and according to what our master wrote in the name of Rabbeinu Tam, even without taste it is permitted, for the taste is batel in 60 — end quote; explanation of Rabbeinu Tam: he holds we are not stringent regarding davar she-yesh lo matirin except when it is in substance and not taste alone. And Beit Yosef's words here are astounding, for according to Kol Bo's taste one does not need 60 to be batel, for there is no prohibition at all; and his words in Shulchan Aruch here are most astounding — why did he require 60, for he himself ruled in Yoreh Deah siman 86, seif 5, this view that mere moisture of eggs in general does not forbid at all; and it is strained to say here it deals with a pierced egg, for he should have mentioned this matter; and furthermore, Kol Bo explicitly deals with an unpierced egg, and since he refers to his words, automatically it also deals with an unpierced egg:",
  },
};
