/** worker-slot-16 — siman 626 need blocks */
export const FIXES = {
  "beer-hagolah/part-001.txt": { "3:_": "Source: Tur." },
  "beur-hagra/part-001.txt": {
    "1:ג":
      '(3) And some say etc. — all that is under the tree is as if it does not exist; and what Tosafot brought as proof from etsim is not proof, as Rabbeinu Tam wrote in those Tosafot that sekhakh above ten handbreadths is not invalid sekhakh; proof from the beginning of Eruvin — partial sekhakh above ten etc.; although if you remove it, its sun would be greater than its shade; and what they brought from one who roofs with spits — not necessarily per Tosafot who explain there "it is impossible to reduce" and answered "preferring" that thereby the air is filled — without invalid sekhakh there is measure — and this is what is written here; but if the branches are opposite etc.; and so explains the Gemara there if placed two etc.; or much sekhakh as there where sekhakh is over the whole sukkah and is abundant. Even per Rashi there Maharik already wrote if one placed valid sekhakh over invalid it is called eruv — and this is written here. Tosafot words require study — there s.v. ha they perhaps challenged Rashi; nevertheless difficult etc. Another explanation as Rabbenu Chananel and Rabbeinu Tam; here they brought proof from Rashi\'s explanation there; per explanation here not difficult on Rashi there — must say there is after what was written here Rabbenu Tam\'s explanation that above ten is not called invalid sekhakh — if so one can explain here as Ravyah.',
    "1:ד":
      '(4) Whether the tree etc. — meaning not like Raavad who wrote specifically when the tree preceded, and once he put some sekhakh and still sun greater than shade, if the tree then made shade greater than sun it is invalid even though he increased afterward — the invalid made shade and what he increased is as if it does not exist; in such a case the Gemara speaks; but if the sukkah preceded, he agrees to Tosafot; Rashba wrote his words do not appear correct for the Gemara stam teaches and proof from the Gemara\'s challenge "but it joins invalid sekhakh" and establishes "when he beat" and does not answer in such a case; although Tosafot there sensed and answered if so what to say — not a simple reason for those who invalidate, all the more Raavad who could answer we decree lest tree preceded sukkah as he answers now we decree etc.; all the more when tree shade greater than sun invalid in every case even if sukkah preceded — not like Rabbeinu Tam who validates even in such a case; therefore explains there 11a he spread a sheet because of sun that dries sekhakh etc., see Tosafot there; also infers from what we say there 11a he thinned etc. and sekhakh on top — implies specifically when he began thinning; if not it should teach the reverse; Rashba challenged — there speaks when valid sekhakh alone is not shade greater than sun and valid sekhakh does not abound over invalid from end teaching "if sekhakh was abundant" — his challenge I do not understand; but no proof for Rabbenu Tam for the mishnah there speaks when attached is not shade greater than sun alone — otherwise how say if sekhakh abundant would not help in such case as Rava said only etc. and we establish when he beat; but per those Tosafot and Raavad there would be proof only Rabbenu Tam did not divide thus between tree shade greater or sun greater — he holds in essence like Ravyah: whenever invalid sekhakh joins it is like a tree whose shade is greater; since there it teaches thinning etc. specifically beforehand — so too tree whose shade (is greater); there in Rava\'s law he holds like Ravyah that there the tree preceded as "one who makes his sukkah" etc.; Raavad disagreed since tree shade greater and mishnah of thinning — Rashba explains thinning on the sekhakh and sekhakh on it, or sekhakh on top — two teachings; Ran etc.; and this is written here; in all this we do not distinguish between etc.; and spreading sheet per Rashi there; Rashba responsa 106 brought proof from thinning already rejected; Minyanim similarly rejected as below.',
  },
  "biur-halacha/part-001.txt": {
    "1:ו":
      'One must lower etc. — stam here not like Rambam who requires cutting specifically; without cutting even if most is valid sekhakh it does not help except lowering alone suffices. Know Bach\'s view to be concerned for Rambam — permit only with cutting because attached is significant, not like other invalid sekhakh nullified in majority; Riaz in Shiltei Giborim also holds thus see there; see Avodat Yisrael rejected Mahariaz — no proof see there. Now we merited light of Rabbeinu Chananel who wrote explicitly on Gemara\'s answer "when he beat" meaning cut branches — exactly Rambam\'s explanation; later found Hilchot Rietz Geon same; therefore certainly l\'chatchila proper to heed Rambam as Bach — must cut them; thereby permitted even without shaking per poskim of Rambam.',
  },
  "machatzit-hashekel/part-001.txt": {
    "2:ב":
      '(2) Valid etc. — Tosafot and Rosh siman 631 etc.; that we taught 15a one roofing with spits or bed poles (invalid for sekhakh) if gap between them as their width and placed sekhakh in the gap — valid. And indeed Tosafot per their view 22b challenges mishnayot — taught chapter 1 shade greater than sun valid; implies if sun and shade equal invalid; chapter 2 taught sun greater than shade invalid — implies equal valid; answers here from above here below; Rashi if above sekhakh and air equal invalid; below if shade and sun equal valid per Rabbeinu Tam from his difficulty: if standing above sees sekhakh and air equal valid; below looking up sees above sekhakh and air equal invalid because air has no substance vision grasps less looking up — air seems smaller; sekhakh has substance not so diminished — looking up though air and sekhakh seem equal perhaps air more than sekhakh therefore invalid; hence dispute Rabbeinu Tam above equal valid, Rashi such invalid; Rosh agreed Rashi see there; Magen Avraham wrote indeed Tosafot per their view — they hold air and sekhakh equal valid; therefore properly proved from roofing with spits if gap as width valid; not that invalid sekhakh joins because sekhakh alone is sukkah measure — gap between them; even removing spits valid measure remains covering half with valid sekhakh; Rosh holds like Rashi air and sekhakh equal invalid; removing spits air and sekhakh equal invalid per Rashi thereby sun greater than shade; still validate via spits joining invalid sekhakh — so too in tree.',
    "2:ה":
      '(5) In any case requires study to settle Rosh\'s words etc. — suffices with valid alone; per Rosh not — suffices valid alone for he holds like Rashi here air and sekhakh equal as above; nevertheless still difficult Tosafot\' challenge 8b s.v. ha joins etc. — challenged one making sukkah under tree as in house invalid; Rava taught only tree whose shade greater than sun, sun greater than shade valid; Gemara challenges if sun greater what of it — joins invalid with valid; answers Rabbenu Ephraim when he beat and mixed; Tosafot wrote therefore when sukkah shade greater besides tree we do not say joins even without beating; bring proof from spits if gap etc.; therefore difficult for Tosafot — what challenge joins — perhaps case sukkah shade greater without tree; end. Per their view whenever air and sekhakh equal that is valid measure — proved from spits: where valid measure exists even also invalid alone valid measure — not say joins — there invalid sekhakh is valid measure for half covered with spits as taught if gap; if remove valid, spits and air equal; still taught valid because valid alone has measure; what difficulty for Tosafot — properly challenges joins — must be no valid measure alone; if exists valid even tree shade greater still valid as proved from spits; Maharsha 10 Tosafot s.v. poras challenged — if valid sekhakh precedes even invalid has measure; since valid alone has measure valid; but mishnah under tree implies tree precedes — Tosafot hold if tree alone has measure even also valid alone has measure still invalid; therefore properly difficult what challenge joins — perhaps valid alone has measure see there; this enough to settle difficulty there; from spits proved if valid has measure even also invalid has measure even invalid precedes still valid as taught roofing with spits if gap — language implies began with spits left air gap then filled with valid sekhakh Rashi there; difficulty returns for Tosafot on challenger\'s difficulty joins; stretch to say Magen Avraham holds other answer Maharsha if tree shade greater still invalid sukkah under sukkah — Maharsha rejected; better for Tosafot Magen Avraham\'s "perhaps when placed above" fits Rosh; Tosafot also descend rank if law when placed together if valid has measure valid even mostly invalid has measure — if so invalid over valid suffices to validate when valid has measure and invalid not full measure; if invalid also full measure what is in valid does not help — then properly difficult; Rosh does not accept Magen Avraham\'s reason — still difficult Rosh\'s words as Magen Avraham concluded; Tosafot no difficulty for wording — per their view air and sekhakh equal is valid measure; therefore no difficulty what Tosafot wrote since if you remove spits suffices with valid see there.',
    "2:ו":
      '(6) He establishes it "preferring" — there on mishnah of spits Gemara asks let it be refutation of Rabbah bar Rav Huna — we say breached like closed, Rabbenu Ephraim permitted Rabbah bar Rav Yitzchak forbidden; invalid sekhakh law is air and breach for this; answers Rabbah bar Rav Yitzchak when entering and exiting; Rashi valid sekhakh enters and exits in gap therefore air more than spits — valid sekhakh majority; challenges but possible to reduce; Rashi\'s text and explains thought answer entering exiting forcedly if impossible to reduce air and spits equal — therefore challenges but possible to reduce; answers preferring — not because impossible to reduce but case he prefers placing more valid sekhakh than spits; Tosafot challenged Rashi — one difficulty all exchange only for Rabbah bar Rav Huna yet we hold Rabbenu Ephraim breached like closed permitted — difficult exchange not aliba the halakhah; therefore text "but impossible to reduce" — difficulty both Rabbenu Ephraim and Rabbah bar Rav Huna since impossible to reduce and fill gap with valid sekhakh remainder air; this air joins spits — for Rabbah bar Rav Huna establishing entering exiting majority valid now equal; Rabbenu Ephraim not establishing entering exiting holds breached permitted — now breach greater via air joining; answers for all preferring; covers all air and some valid on invalid end.',
    "2:ח":
      '(8) And the halakhah is the opposite — Rosh concluded thus; possibly text should read so. And perhaps when placed above it detracts more — meaning when valid and invalid placed together; when placed above one could lean to view in Shulchan Aruch invalid upper nullifies lower; Rosh learns gradually since with spits valid and invalid together valid even without full valid measure — with invalid above lesser rank still fit to validate when valid alone has full measure.',
  },
  "mishnah-berurah/part-001.txt": {
    "3:ג":
      '(3) But if the tree its sun greater than its shade etc. — then the shade is as if absent and it is not called sukkah under the tree.',
  },
};
