/** worker-slot-12 — siman 485 hand translations (22 keys) */
export const T = {
  "baer-heitev/part-001.txt|1:א":
    "(א) Forbidden — since it applies to matzah of rabbinic origin, it also applies to matzah of a mitzvah. And we compel him to request annulment of his oath. Bach — and see Yoreh De'ah siman 236.",
  "baer-heitev/part-001.txt|1:ב":
    "(ב) He receives lashes — for it is a vain oath, since an oath does not take effect on a matter of mitzvah. And if he swore regarding maror and the four cups, his oath takes effect since they are d'rabbanan. And likewise if he said \"Konam be my eating matzah upon me on Passover night\" — it is forbidden, for a vow takes effect on a matter of mitzvah; see Yoreh De'ah siman 239. And we compel him to request annulment of his oath or his vow, as stated in seif kaf alef and below. The Rav author of Rosh Yosef was uncertain: if one said an oath not to eat matzah without specification and afterward explained that his intent in what he swore was only on Passover night — what is the law? See Yad Ephraim at length there.",
  "beer-hagolah/part-001.txt|1:_":
    "Yerushalmi in chapter 3 of Shevuot, and the Rif and Rosh wrote it at the end of Pesachim, and as Ran explained there.",
  "beur-hagra/part-001.txt|1:_":
    "(א) He said, etc. — Taz and Tosafot Shevuot 24a s.v. ela. And R' Yehuda explains, and so Ramban, Ran, and Rivash in siman 59 and siman 398; see Ran and in Milchamot at the end of chapter 3 of Shevuot.",
  "biur-halacha/part-001.txt|1:_":
    "Oath that one will not eat matzah on Passover night — see in Mor U'Ketzia who wrote that if one said he will not eat this matzah, it is forbidden even if he has no other matzah, and they annul his oath for him. And know that if he said he will not eat any matzah of Passover, the oath takes effect inclusively per the view of most poskim, even though he mentioned Passover explicitly; and therefore one should examine per those poskim that the time for eating matzah is from the Torah only until midnight — if so, when one says he will not eat matzah on Passover night, behold he includes the time of exemption with the time of obligation and the oath takes effect inclusively and it is not a vain oath, unless we strain to say that since he mentioned matzah of Passover night his intent is only on the hour when people fulfill the mitzvah of matzah and not afterward — and that is strained, for per that view he would be permitted to eat after midnight; this requires further study.",
  "chok-yaakov/part-001.txt|1:א":
    "(א) Forbidden to eat matzah — the reason is that then his oath takes effect inclusively on the rest of the days, which are permitted matters together with forbidden matters that are sit and do not do, even in a d'oraisa prohibition; and see in Shevuot in Tosafot daf 24 s.v. ela that they distinguish — Tosafot in the name of Rivba on another matter, whether if one mentions Passover in the oath then his oath does not take effect even inclusively, unlike when he does not mention the name of Passover. And Ra'avad in Sefer Temim De'im in his hasagot on Ba'al HaMaor to Pesachim siman 245 divides further on another matter, whether his oath takes effect before the obligation of matzah — since the prohibition was already included with the permitted, his oath takes effect; but if the prohibition already applied, such as if he swore on Passover itself, this is not inclusive but begins in prohibition — end of his words; and see Yoreh De'ah siman 236.",
  "chok-yaakov/part-001.txt|1:ב":
    "(ב) On Passover night — for then there is here inclusion of a permitted matter, and this is per R' Yehuda in Tosafot there, unlike per Rivba as I wrote that even inclusively his oath does not take effect in such a case. And one should not challenge that even if he said on Passover night there is also inclusion of permitted matters, namely rich matzah; and one may say that since he mentioned Passover night his intent is specifically on what one fulfills on Passover, namely matzah, as Rivash wrote siman 398 brought in Beit Yosef Yoreh De'ah siman 256 in Hagahat Shulchan Aruch there seif kaf tet zayin (and see in responsa Maharit part 14 siman 47 who questions Rivash on this); but if he did not mention Passover night, it is possible that even rich matzah is within his oath; and it is explained in Yoreh De'ah that unspecified vows are to be stringent and their releases to be lenient; and see Magen Avraham what he challenged here on Eliyah Rabbah, and I already wrote above siman 473 that this is not a challenge at all on Eliyah Rabbah.",
  "chok-yaakov/part-001.txt|1:ג":
    "(ג) He receives lashes and eats — and if he swore not to eat maror or the four cups, the later authorities agree his oath takes effect since they are only d'rabbanan; but we compel him to annul his oath, as explained above siman 418 and siman 470. However Levush wrote there that R' Yehuda holds an oath does not take effect without inclusion even on a d'rabbanan mitzvah that has Torah support — his words have no basis or foundation in the general rule, as Shach expanded and challenged him in Yoreh De'ah siman 256 seif kaf yud alef; and see what I wrote above siman 472 seif kaf tet and further that it is possible there is no Torah support here, as Sha'agat Aryeh wrote at length, unlike Maharash Halevi in responsa part 14 siman 12 who followed Levush on this — see there.",
  "eliyah-rabbah/part-001.txt|1:_":
    "(א) On Passover night, etc. — but if he said Konam upon me on Passover night, it is forbidden, for a vow takes effect on a matter of mitzvah; see Yoreh De'ah siman 239. Bach wrote: one who swore he will not eat maror or will not drink the four cups on Passover night — since it is d'rabbanan, his oath takes effect and we compel him to request annulment of his oath; and if he swore affirmatively, we do not compel him, but it is fitting he should request annulment of his oath.",
  "kaf-hachayyim/part-001.txt|1:_":
    "(א) [Seif 1] He said an oath that he will not eat matzah, etc. — and the reason is because the oath came to nullify the mitzvah of sit and do not do inclusively; therefore this oath, since it takes effect on matzah of the whole year, also takes effect on matzah of Passover night — Beit Yosef in the name of Ran. Taz seif kaf alef. Magen Avraham seif kaf alef. Chayei Adam letter alef.",
  "machatzit-hashekel/part-001.txt|1:_":
    "(Seif kaf alef) Matzah, etc. — since it takes effect, etc., meaning inclusion of permission and mitzvah; we hold it takes effect on sit and do not do. Nevertheless we compel him that he should request annulment of his oath and eat matzah of mitzvah, as Shach wrote in Yoreh De'ah.",
  "magen-avraham/part-001.txt|1:א":
    "(א) Matzah without specification — if so, since it applies to matzah of rabbinic origin, it also applies to matzah of mitzvah; and it appears to me that one who did not recite the Haggadah on Passover night has no compensation, for it is written \"for this\" — I did not say except at the hour when matzah and maror are placed before you; and it is written \"in the evening you shall eat matzot\" — from here onward is permission, as Eliyah Rabbah wrote, unlike Peri Chadash.",
  "magen-avraham/part-001.txt|1:ב":
    "(ב) He receives lashes and eats, etc. — for it is a vain oath, since an oath does not take effect on a matter of mitzvah; but if he says Konam be my eating matzah upon me on Passover night, it is forbidden, for a vow takes effect on a matter of mitzvah; see Yoreh De'ah siman 239.",
  "mechaber/part-001.txt|1:main":
    "The law of one who swore not to eat matzah, and it has one seif: If one said an oath that he will not eat matzah without specification, it is forbidden to eat matzah on Passover night. If one said an oath that he will not eat matzah on Passover night, he receives lashes and eats matzah on Passover night.",
  "mishnah-berurah/part-001.txt|1:א":
    "(א) That he will not eat matzah without specification — whether he said this before Passover or said on Passover night itself, since he did not say in his oath that he swears only on matzah of mitzvah but includes in his oath all matzah and not specifically matzah of this night alone, his oath takes effect, for an oath takes effect inclusively on permitted matters together with forbidden matters of sit and do not do; and nevertheless the poskim wrote it is a mitzvah to annul his oath so he can fulfill the mitzvah of eating matzah.",
  "mishnah-berurah/part-001.txt|1:ב":
    "(ב) On Passover night — for since he said Passover night, presumably his intent is on matzah of mitzvah alone.",
  "mishnah-berurah/part-001.txt|1:ג":
    "(ג) He receives lashes, etc. — because of a vain oath, for an oath does not take effect on a matter of mitzvah; and nevertheless if he said Konam be my eating matzah of mitzvah upon me, it is forbidden to eat matzah, for a vow takes effect on a matter of mitzvah. If he said an oath that he will not eat maror of mitzvah, it is forbidden to eat maror, for maror in our time is d'rabbanan and an oath takes effect on a d'rabbanan mitzvah; and the same if he said he will not drink the four cups. And nevertheless we compel him that he should request annulment of his oath; and the same if he said an oath that he will not eat matzah on the second night, which is also d'rabbanan for us who are expert in fixing the month — it also takes effect and is forbidden, only that here too one should compel him to request annulment of his oath.",
  "peri-megadim/part-001.txt|1:_":
    "Without specification — Taz. But in a positive commandment it does not take effect inclusively in Torah law, and even in d'rabbanan — see Yoreh De'ah 236 seif hei and Taz there letters yud alef and yud bet; and it implies even one who swore on Passover night itself — all Passover matzah is permission not to eat all days of Passover, then the oath takes effect; see there in Beit Yosef and Shabbat in the Gemara that one obligated in bread — not so siman 488 in Magen Avraham alef and siman 418 and 470 seif gimmel. And if he included rich matzah, it takes effect inclusively; but without specification rich matzah is not included since he mentioned Passover night — his intent is on what one fulfills on it; therefore he receives lashes and eats — see Yoreh De'ah 256 seif vav and Shach yud zayin. And that it is not inclusive of two kezayit — for without kezayit flour it is not matzah — see Eliyah Rabbah. And this requires further study: rich matzah without any water at all — if one placed matzah upon it, perhaps it is entirely not subject to leavening, and only with a little water one may say it is within matzah — see siman 471. And if it is difficult: one who swore by inclusion that takes effect and sits alone with no one to annul his oath — let the positive commandment of matzah come and push aside the oath; one may say it is a positive commandment one can fulfill through negligence — see Tosafot Eruvin 100 s.v. matan and Tosafot Kiddushin 38a s.v. de'ikriv; for where one swore on a kezayit of matzah and that he will not drink, one may say it is inclusive and there is no distinction between one kezayit and two kezayit, and all the more inclusion of rich matzah. And on the first night of Sukkot one who swore he will not eat bread — it is a positive commandment. And below seif alef and bet, and from the Mechaber's conclusion here and Yoreh De'ah it implies even if standing on Passover night and mentioning explicitly, whatever is inclusive takes effect. And if he has only half a kezayit of matzah he is not obligated to eat — responsa Shavut Yaakov part 2 siman 18, and it is simple; and if so the oath takes effect on it. And if he swore he will not eat a kezayit in the first meal, one may say it takes effect and he eats as usual; one may say we decree because of the first meal — see Tosafot Kiddushin there and Taz. Haggadah is a positive commandment, and even if he has no matzah and maror — see siman 454. And Rashi in Chumash (Shemot 13) explained \"for this\" — Pesach, matzah, and maror; and in Pesachim 116 and in Rambam chapter 6 law 1 and siman 488 and Eliyah Rabbah in Magen Avraham alef it is explained further.",
  "rabbi-akiva-eiger/part-001.txt|1:_":
    "Seif alef — matzah without specification is forbidden to eat. And one who says an oath that he will not eat in the sukkah of mitzvah — even though all seven days except the first night are permission, we do not say since it takes effect on the rest of the days, for on the rest of the days it also does not take effect, for even though he can eat casually outside the sukkah, nevertheless since he eats fixed meals in the sukkah it is a mitzvah and is called swearing to nullify the mitzvah — Tashbetz part 1 siman 100. And in Chokhmat Shlomo that also on the eighth they sit — if so the language \"sukkah of mitzvah\" includes the eighth as well; and one may say it is inclusive since it takes effect on the eighth — this requires further study.",
  "shaarei-teshuvah/part-001.txt|1:_":
    "Forbidden — Ba'er Hetev; and see in Shach Choshen Mishpat siman 73 seif kaf yud alef who wrote the reason that inclusion helps here to nullify the mitzvah, for in the middle of the year the obligation of matzah and sukkah has not yet applied to him at all — see there in Taz in Hagahat Chacham Tzvi; one may say he challenged Shach on this and wrote that if one said matzah without specification, even if standing on Passover nights it is forbidden to eat, etc. — see there; and see in the Acharonim there who wrote to reconcile Shach's words; and see in Kaf HaChayyim to Sefer Ketubot in Even HaEzer siman 218. (And I wrote there that initially it was difficult for me what Chacham Tzvi wrote from Tosafot Shevuot — Shach is not dealing with the matter of the essence of the oath taking effect, for regarding that there is no place for Shach's distinction, for now there is no mitzvah; nevertheless when we judge the oath's taking effect on Passover nights, then it is already a mitzvah; therefore Tosafot needed to divide on another matter, to say the oath takes effect only regarding whether one must fulfill the oath or must fulfill the mitzvah he is sworn and standing upon; and in truth the punishment of the oath depends on which preceded — Shach wrote regarding matzah that since there is no obligation now, the oath preceded when there was no obligation, and when the obligation arrives the oath's taking effect was already — therefore Shach did not mention from Tosafot Shevuot at all, for they deal with the essence of oath taking effect, and the matters are clear as I explained in its place, and here I shortened. And what Ketzot HaChoshen wrote — Ra'avad's words in Temim De'im — Kaf HaChayyim brought here, and this is not Shach's intent; also what he wrote that Rav R' Chasdai in responsa of Rivash is like Ra'avad — it is not so, as explained in responsa of Rivash, for it is explained there his reason is because even though it includes on what is not mitzvah, nevertheless the essence of the oath is on a matter of mitzvah, and he brings an oath not to eat matzah on Passover night — even though it includes entirely, nevertheless the essence of the oath is on matzah of mitzvah, and this Rivash rejected there — see there; and also the proof from an oath not to sleep, etc. is astonishing, for there since the oath he uttered cannot be fulfilled it is void entirely, unlike there where one swore not to sleep, etc.; and likewise in matzah, for we hold that on a matter that is not mitzvah it takes effect well — one may say that through inclusion it takes effect also on mitzvah, and in this Ran and Rivash deal, and I explained well in its place, with Heaven's help.)",
  "turei-zahav/part-001.txt|1:_":
    "Without specification, forbidden to eat, etc. — for the oath to nullify the mitzvah of sit and do not do takes effect inclusively, meaning since it applies to the whole year it also applies on Passover night.",
  "yad-ephraim/part-001.txt|1:_":
    "In Magen Avraham seif kaf alef — matzah without specification, because it is an inclusive prohibition since it takes effect, etc. — so it should read.",
};
