/** siman 379 — 20 blocks R1-R10 */
export const FIXES = {
  "baer-heitev/part-001.txt": {
    "1:_": "In the house. And Tosafos daf 76 wrote that even if they placed the eruv in one of the houses adjacent to the courtyards, if one of the houses of these courtyards — the three houses — they need not give an eruv, for they all become a gatehouse for that courtyard that passes the eruv through them to the other courtyard. Magen Avraham.",
  },
  "beer-hagolah/part-001.txt": {
    "1:_": "Gemara Eruvin 75",
    "2:_": "There on 7 and the inquiry and its resolution",
  },
  "eliyah-rabbah/part-001.txt": {
    "1:_": "[1] In the middle house etc. And Tosafos daf 76 wrote that even if they placed the eruv in one of the houses adjacent to the courtyards, or even in one of the houses of these courtyards — the three houses — they need not give an eruv, for they all become a gatehouse for that courtyard that passes the eruv through them to the other courtyard:",
    "2:_": "[2] [Levush] he stopped him etc. From here there is a contradiction to the custom in some places that they place eruvin in the synagogue and the houses of the Kutim interrupt between them and the eruv, and they cannot carry to the synagogue to the place of the eruv (Perishah). And see siman:",
  },
  "kaf-hachayyim/part-001.txt": {
    "1:_": "(1) [Seif 1] Open to one another. And the houses are also open to the courtyards adjacent to them:",
    "2:_": "(2) There. And he places his eruv in the middle house. And Tosafos wrote that even if they placed the eruv in one of the houses adjacent to the courtyards, or in one of the houses of the courtyard — these three houses — they need not give an eruv, for they all become a gatehouse for that courtyard that passes the eruv through them to the other courtyard. Magen Avraham siman kuf alef. And see Tosafos, Rashi, and Rabbenu Tam. And he wrote in Ma'orei Or part Be'er Sheva daf 115a that this is reasonable, since the authors of the Shulchan Aruch in Beit Yosef and Darkei Moshe did not mention the words of Tosafos, it is a blindfold (s.v.). However, in Etz Chaim siman 377 s\"k 19 he wrote that according to Rabbeinu Yerucham it appears he disagrees with this law and holds that for each house they only give one gatehouse, see there. And the Kaf HaChayim brought this:",
  },
  "machatzit-hashekel/part-001.txt": {
    "1:א": "(Siman kof alef) In the house etc. — adjacent to the courtyards, so it should read. Meaning that one courtyard placed its eruv in the third house, and likewise the courtyard opposite it placed its eruv in that same house adjacent to its courtyard; if so, the two eruvin are placed in one house. Or the two courtyards placed their eruv jointly in one house from the houses of one courtyard — at any rate, the two eruvin are placed in one house:",
    "1:ב": "that they all become etc. — meaning this refers to the sifah — when they placed their eruv in a house from the houses of the courtyard. If so, all three houses become a gatehouse for the courtyard that passes its eruv over the three houses and places its eruv in the other courtyard. And in the reishah, where one placed in the third house far from its courtyard, if so, two houses become a gatehouse and the third is where they place the eruv:",
    "2:א": "(Siman kof bet) In the house etc. And if we consider it as a full house etc., so it should read — meaning that each house adjacent to a courtyard is considered a gatehouse for the courtyard adjacent to it, since this house did not give to the eruv and the adjacent courtyard placed its eruv in the second house. If so, the house that did not give to the eruv interrupts between it and its eruv, and it cannot bring its eruv to its courtyard. Rather, it is certainly considered a gatehouse for it — so how can it be considered a full house regarding the second courtyard? They are two contradictory matters:",
    "2:ב": "And even though in siman 393 etc. — meaning that we rule that the house acquires the eruv. Therefore if the eruv was valid in the house and afterward was eaten, it acquired. And he wrote there: if an agent from two houses placed an eruv on behalf of one of the owners and it was eaten in the middle of the night, and at that same time when the first eruv was eaten he placed an eruv on behalf of the other — both acquired the eruv. For regarding the first that was eaten we say that night had already come and it was valid all night, and regarding the other who placed at that time we say that night had not yet come. And even though they are two contradictory matters, since this matter is d'rabbanan:",
    "2:ג": "And in Yoreh De'ah siman 111 — meaning thus, that we should not ask why both are forbidden, for it is impossible to permit both since they are two contradictory matters; at any rate, one of them should be permitted, and say that the house in which the eruv was placed is a full house, and regarding the other it is truly not an eruv since the house interrupts, as Magen Avraham wrote above. On this see Yoreh De'ah siman 111, where he wrote there: if there are two pots, one of permitted and one of forbidden food, and before them two pieces, one of permitted and one of forbidden food, and one piece fell into each pot and it is not known into which pot the forbidden or permitted piece fell — if it was a d'rabbanan prohibition we say: the forbidden fell into forbidden — double prohibition — and the permitted into permitted. And he wrote there seif 5: but here there are two pots both of permitted food, and before them two pieces, one of permitted and one of forbidden, and one piece fell into each pot — both are forbidden, for either way one became forbidden, and whichever we remove, specifically regarding one of them that was forbidden we say the forbidden fell into forbidden and we do not add prohibition to it; which is not so when both are permitted, that at any rate one must be forbidden — what is the reason from this to that. Therefore both are forbidden. The same applies here. And see there Shach in the small seif 11:",
  },
  "magen-avraham/part-001.txt": {
    "1:_": "In the middle house. And Tosafos wrote that even if they placed the eruv in one of the houses adjacent to the courtyards, or in one of the houses of this courtyard — the three houses — they need not give an eruv, for they all become a gatehouse for that courtyard that passes the eruv through them to the other courtyard:",
    "2:_": "In the gatehouse. And if we consider it as a full house, then each courtyard interrupts between it and the house where it placed its eruv (Tur). And even though in siman 393, seif 3, we rule a rabbinic doubt leniently — we say where they contradict one another, there the matter is not recognizable; here those houses stand before us, and if we make this courtyard a house and that one a gatehouse, if so it is like a monkey riding a camel (Gemara). And see Yoreh De'ah siman 111:",
  },
  "mechaber/part-001.txt": {
    "1:main": "Laws of courtyards and houses between them. Contains 2 seifim: Two courtyards with three houses between them opening into one another, wishing to make a joint eruv — one courtyard comes through the house adjacent to it and places its eruv in the middle house, and the second courtyard does likewise. They are then permitted in all three, since each house adjacent to a courtyard counts as a gatehouse for it and need not contribute bread, and the middle house is the house in which the eruv is placed and also need not contribute bread.",
    "2:main": "Two courtyards with two houses between them, where they did not make a joint eruv but each made its own eruv separately — and one came from his courtyard through the house adjacent to it and placed his eruv in the house adjacent to the other courtyard, and the other did likewise, also placing his eruv in the house adjacent to the first courtyard — they have not acquired an eruv, since each one placed his eruv in the gatehouse of the other courtyard.",
  },
  "mishnah-berurah/part-001.txt": {
    "1:א": "(1) Open to one another — and they are also open to the courtyards adjacent to them. And it teaches us that although generally if one house does not contribute a portion in the eruv, it itself is forbidden to carry, and it also restricts the courtyard residents — here it can occur that none of the three contributed a portion in the eruv, and nevertheless all are permitted to carry, such as if the owners of the two courtyards place their eruvin in the middle house, for the reason he concludes:",
    "1:ב": "(2) And they are permitted in all three — meaning they are permitted to carry in those houses and the houses in them, even though they did not contribute a portion in the eruv:",
    "1:ג": "(3) Counts as a gatehouse for it — after the courtyard residents pass their eruv through it to the middle one. And some wrote that the same applies if both placed the eruv in one of the houses adjacent to the courtyards, or in one of the other houses in these two courtyards — these three houses need not give an eruv, for they all become a gatehouse for that courtyard, since they pass through them to place the eruv in it:",
    "1:ד": "(4) And need not contribute bread — as explained in siman 366, seif 2:",
  },
};
