/** Hand EN — siman 590 remnant bad_mt (R1–R10) */
export const FIXES = {
  "beer-hagolah/part-001.txt": {
    "3:ד": "(4) Stated in the name of Rivash and Ribash — source.",
  },
  "chokhmat-shlomo/part-001.txt": {
    "1:_":
      "(Section 4) But three shevarim and teruah of tesharat need not be done in one breath, etc. NB: this is the view of Rabbeinu Tam; the reason the poskim wrote in his name is that groaning and wailing cannot be done in one breath. Initially we did not know whence Rabbeinu Tam knew this from reasoning alone to be lenient in concern of d'oraisa. It appears well: Bach and Taz wondered how R' Eliezer could be in doubt whether groaning and wailing — behold we see the tanna of the mishnah and baraita only disagree whether this or that, but from Torah we should say both are required. One may say: certainly both are called teruah — groaning is called teruah and wailing is called teruah; and since both are called teruah and Torah wrote teruah generically, if so exclude one from it — perforce the Torah's intent is both; but this is for the law of performing the teruah itself — one can say exclude one and both are required, as we say generally in such cases. But for the measure of tekiah that we establish as teruah, certainly one teruah or the other suffices; if so one tanna says one and one tanna says one and they do not disagree — this teaches us for the measure of shevarim one suffices, and this teaches us for the measure of teruah one suffices. If one says each alone is teruah only because exclude one requires both, then for measure of tekiah one of them suffices; but if each alone is not called teruah except together, then for measure of tekiah we need both; since we see each tanna only took one, perforce one type suffices; therefore no room for doubt that both are required — therefore if each alone is teruah only because exclude one requires both, then certainly one must do them in two breaths, and on the contrary one must do so since each is a separate matter; but if only together they are teruah, then they must be in one breath — and this is R' Eliezer's doubt whether groaning and wailing are done only in one breath — if so no room for doubt that both are required, for perforce the tannaim disagree as he said above and both did not require both — no room for doubt both are required; or perhaps in groaning and wailing they are done in two breaths and one may say each alone is teruah but nevertheless both are required because of exclude one — if so again the tannaim do not disagree only from one to one; and measure of tekiah suffices in one type; perforce if doing tesharat from R' Eliezer's safek one must do them in two breaths not one, for if in one breath perforce he holds one alone is not teruah except together — then again no room for this doubt, for perforce from the tannaim' words to the contrary; and if we are in doubt about both, perforce each alone is like teruah alone only because exclude one requires both, therefore must do them specifically in two breaths; and from Bach and Taz's difficulty he was compelled to say thus — requires study well.",
  },
  "kaf-hachayyim/part-001.txt": {
    "2:_":
      "(b) Stated there. And every plain tekiah before it, etc. — gemara daf 33b. Whence plain before? It is written vehaverata shofar teruah — Rashi 34a: vehaverata means plain, implying passing one sound. Whence plain after? It is written ta'aviru shofar — Rashi: behold passing beginning and end and teruah written between them. They also bring another baraita: we need plain before and plain after — from ve-takeatem teruah, plain before it; from teruah yitke'u, plain after it — see there.",
  },
};
