/** eliyah-rabbah, kaf-hachayyim, smaller commentators */
export const chunkC = {
  "eliyah-rabbah/1:_":
    "(1) [Levush] And there are those who say one is obligated, etc. Shulchan Aruch ruled stam like this view; Kesef Mishneh chapter 4 agreed even without kezayit within k'dei achilat peras since there is a kezayit of chametz one transgresses bal yera'eh. Magen Avraham: if min b'mino such as flour in flour nullified in majority d'oraisa permitted even to retain d'oraisa — end of his words; if transgressed and retained — if remembered within Pesach destroy d'rabbanan; if not see end siman 447 after Pesach. Olat Shabbat: fat from a dish with only taste not substance transgresses bal yera'eh — ta'am ke'ikar d'oraisa — end of his words; my brother-in-law in Chok Yaakov: ta'am ke'ikar only for eating not retaining; d'rabbanan forbidden to retain; if transgressed permitted in benefit after Pesach.",
  "eliyah-rabbah/2:_":
    "(2) But a thing, etc., that also prohibition, etc. Nokshah forbidden to retain though rabbinic as end siman 447 — must say mixtures were lenient more than nokshah b'eyna — not like Olat Shabbat.",
  "eliyah-rabbah/3:_":
    "(3) And likewise kilyor, etc., permitted to retain, etc. But in eating forbidden to all — Rambam deals where there are not sixty. This resolves my brother's wonder on Maggid regarding Ra'avad — if Ra'avad here he should have written hasagah end chapter 4 when nullified in sixty — what Levush seif 4 wrote — see there — end of his words.",
  "eliyah-rabbah/4:_":
    "(4) And melogma, etc. — poultice of flour and figs chewed on a wound; or chews wheat; deals with putrefaction unfit even for dogs like mold; but if fit for dogs though unfit for man — obligated to destroy.",
  "eliyah-rabbah/5:_":
    "(5) [Levush] Before its time, etc. After its time must burn to dust; only if leavened before putrefaction or molded; but putrefied before leavened — even after its time permitted to retain for prohibition did not apply.",
  "eliyah-rabbah/6:_":
    "(6) Clothes, etc. Nevertheless forbidden to spread on table; all the more forbidden to put flour in them on Pesach; women's scarves fixed with flour remove at eating lest crumble into food (Magen Avraham).",
  "eliyah-rabbah/7:_":
    "(7) That there is no form, etc. Terumat HaDeshen: not outside; though bal yera'eh even in hiding — chametz nokshah different (Chok Yaakov); Levush concluded: unfit for dogs, etc. — see seif 6.",
  "eliyah-rabbah/8:_":
    "(8) [Levush] And there are those who permit in mixture, etc. At first glance wonder on theriac — plainly chametz mixture; must say only theriac which is a mixed thing; but where chametz form stands as mentioned — forbidden to all; not precise why say nullified in sixty — not applicable; it appears to exclude intentional mixture to retain — forbidden as 447 seif 2 explained there.",
  "eliyah-rabbah/9:_":
    "(9) That there are, etc., nullified, etc. My brother challenged in Chok Yaakov 447: Tur ruled does not revive — still ruled Rambam's law in theriac; must say agrees theriac revives since chametz substance inside not well mixed as Rosh Yosef — end of his words. I found in Perishah explicitly Tur does not hold like Rambam in theriac — brought only to prove distinction eating vs revival; likewise explicit as Rama and Levush in Maggid end chapter 4 — those who permit below permit here; Kesef Mishneh 447; Taz wrote in theriac not nullified because ma'amid — Poskim above escaped him — see 447 s.k. 10.",
  "eliyah-rabbah/10:_":
    "(10) Beer, etc. If mixed in something else judged like other chametz mixture.",
  "eliyah-rabbah/11:_":
    "(11) If he established, etc. Davar hama'amid not nullified even in thousand; likewise pouring chametz, beer, or burnt wine to make sharp — even after cheese made and established in stomach — l'ta'amai not nullified; even retained after Pesach forbidden Nachalat Sheva 35. Chok Yaakov: davar hama'amid and l'ta'amai rabbinic — nevertheless like b'eyna forbidden if retained after Pesach; possibly no worse than less than sixty chametz passed Pesach — cast benefit to Dead Sea as 447:11; Magen Avraham in Ramban — all forbidden; in great loss lenient in benefit to sea — end of his words. Wonder: Ramban only forbidden to retain, if transgressed and retained not found forbidden since rabbinic; Maharam Lublin forbids dough leavened in beer lees passed Pesach — different for lees b'eyna; found in Amar Kol of Ravyah: honey leavened in beer lees forbidden to retain; if transgressed forbidden after Pesach — eating d'oraisa like paste — end of his words. Plainly if also permitted honey both causes permitted; if alone leavened see Yoreh De'ah end 87. L'ta'amai only when much given until taste as Yoreh De'ah end 98. Davar hama'amid needs power to leaven. Radbaz: cheese in stomach from chametz vessel — forbidden to eat, permitted to retain — only if stomach constantly in chametz vessel as Yoreh De'ah end 87 (Magen Avraham); needs study — nosen ta'am lifgam after constant contact; possibly sharp — not clear there; see 447:5 fat in chametz vessel. Magen Avraham in Ramban responsum 8: honey cooked now fourth or fifth from honey leavened in beer lees — forbidden; likewise Ra'avan 72b. I wondered in Eliyah Zuta end 447 why he permitted Knesset HaGedolah to make third milk from chametz — see there at length; for halachah may be lenient if transgressed and retained.",
  "kaf-hachayyim/1:_":
    "(1) [Seif 1] Chametz mixture they transgress, etc. — one does not receive lashes for bal yera'eh and bal yimatzei unless he acquired chametz on Pesach or leavened so an action occurs; if he had chametz before Pesach and Pesach came and he did not destroy but left in his domain — though he transgressed two lavin he does not receive lashes d'oraisa for no action was done — he receives makat mardut. Rambam chapter 1 law 3 and method of correction for one who transgressed — see above siman 434.",
  "kaf-hachayyim/2:_":
    "(2) There. Chametz mixture they transgress, etc. — Shulchan Aruch follows Rambam chapter 4 who ruled like R' Eliezer: lav on chametz mixture, nothing on chametz nokshah — therefore did not write they transgress on nokshah like mishnah Elu Overin; likewise below 447:12 — see there; nevertheless l'chatchila forbidden to retain on Pesach. Chayei Adam letter 2; if retained not forbidden after Pesach as below 447:12 — see there.",
  "kaf-hachayyim/3:_":
    "(3) And Maggid Mishneh wrote there Rambam ruled chapter 1 no lav in eating chametz mixture unless he ate a kezayit of chametz within k'dei achilat peras (three eggs as Rambam chapter 1; Shulchan Aruch — some say four eggs as above 468:3 and 472:4 — see there); certainly per his words here too one transgresses only in mixture with kezayit within k'dei achilat peras — this is primary. Some Geonim hold even with less one transgresses; I saw one who explains Rambam so — though no lav in eating obligated in destruction for kezayit of chametz is there though mixed in many olives — see there; likewise our Rabbi in Kesef Mishneh: for this no distinction whether kezayit within k'dei achilat peras or not — see there. Olat Shabbat letter 1: as Ran and primary. Magen Avraham s.k. 1; Rabbi Akiva Eiger letter 1; Chayei Adam letter 1: agreement of Acharonim like Poskim even without kezayit within k'dei achilat peras transgresses bal yera'eh; Makor Chayim letter 1; Gra 7 letter 1; Chayei Adam klal 121 letter 1; only min b'she'eino mino not nullified d'oraisa in majority per ta'am ke'ikar d'oraisa; min b'mino (e.g. flour of sour produce in flour not leavened) nullified d'oraisa in majority permitted to eat — all the more to retain d'oraisa; d'rabbanan forbidden to retain lest eat on Pesach — destroy; if transgressed permitted after Pesach (even in eating — Gra 13) since no ben yomo (as below 447 and 466 Acharonim). Where sixty — even min b'she'eino mino likewise. Chayei Adam there; Chok Yosef letter 1; see below 447 letter 244. Wheat flour with barley flour etc. is min b'she'eino mino. Rabbi Akiva Eiger letter 1.",
  "kaf-hachayyim/4:_":
    "(4) And if no substance of chametz only taste (e.g. dish cooked in one vessel with chametz absorbed taste without substance — Gra) — Olat Shabbat: forbidden to retain on Pesach and transgresses ben yomo; Chok Yosef agrees; Chayei Adam: Poskim' implication not so; even ta'am ke'ikar d'oraisa only for eating from mesharet not bal yera'eh; concludes in any case forbidden to retain d'rabbanan — destroy if found within Pesach; if transgressed no prohibition; permitted in benefit; eating prohibition only general stringency; likewise all permitted d'oraisa to retain — d'rabbanan forbidden l'chatchila — burn within Pesach d'rabbanan; if transgressed permitted. Makor Chayim letter 1; Gra 7; Chayei Adam klal 121 letter 1.",
  "kaf-hachayyim/5:א":
    "(5) Olat Shabbat further: also cooked in ben yomo vessel (cooked today in pot that cooked chametz today) — stringent not to retain on Pesach — see there; Chayei Adam disagreed — no stringency — permitted to retain — see there; Makor Chayim; Gra 8; Chayei Adam klal 121 letter 1; Chatam Sofer responsum 108: in sharp forbidden to retain — other matters permitted — see there. Makor Chayim: only if not kavush within Pesach in chametz vessel — poured to Pesach vessel — meaning vessel fit for Pesach use not used hot for chametz only cold as below 451:22 — see there; see Har HaCarmel 14: preserves or fat standing in chametz pots permitted to retain — see there; brought Sha'arei Teshuvah letter 1.",
  "kaf-hachayyim/5:ב":
    "(5) And if cooked or pickled on Pesach even in vessel not ben yomo — must destroy. Chayei Adam there. This per those who forbid ta'am lifgam on Pesach as below 447:10 in gloss; per Shulchan Aruch there permitted even in eating as explained there in our words — see there letter 241 for practical halachah.",
  "kaf-hachayyim/6:_":
    "(6) Tur: whatever not forbidden in eating d'oraisa permitted to mix l'chatchila and retain. Semag likewise; Tosafos beginning Pesachim: forbidden — Rabbanan did not distinguish. Magen Avraham s.k. 1; Shulchan Aruch's view — see there; see below 447 letter 241.",
  "kaf-hachayyim/7:_":
    "(7) In min b'mino even moist in moist less than sixty permitted to retain. Chametz that establishes — even b'dieved forbidden after Pesach. Magen Avraham here and 447:11. Makor Chayim letter 1.",
  "kaf-hachayyim/8:_":
    "(8) There. They transgress, etc. — Israel with mills grinding all year semolina, etc. — must destroy all; if not transgresses bal yera'eh and bal yimatzei. Radbaz responsa printed in Furth 489 from author letter 2.",
  "kaf-hachayyim/9:_":
    "(9) Such as morayis and Babylonian paste, etc. — Babylonian paste: they crumble bread crumbs to leaven; Median beer: barley and water leaven. Tur. Morayis also has chametz mixture. Levush.",
  "kaf-hachayyim/10:_":
    "(10) There. Such as morayis and paste, etc. — all through water mixture for otherwise fruit juice does not leaven. Rif, Rosh, Bach, Beit Yosef. See below 462.",
  "kaf-hachayyim/11:_":
    "(11) There. And all the like, etc. — red vinegar, Egyptian olives, all in mishnah beginning Elu Overin. Chayei Adam letter 4.",
  "eshel-avraham/2:_":
    "That putrefied. From this Eshel Avraham forbids his questioner with recurring headache to leave a kilyor of chametz and spices on his temples even if less than kezayit within k'dei achilat peras.",
  "eshel-avraham/4:_":
    "To eat it. Even per those who permit in 447 — here agree lest chametz inside establishes it — Taz; Chayei Adam: no doubt his doubt removes Ra'avad's certainty.",
  "eshel-avraham/5:_":
    "To destroy them. See Baer Heitev s.k. 11 in Maharam of Lublin. Taz challenged Yoreh De'ah 87: cooked in stomachs permitted in sixty — likewise here nullify kezayit for se'or has power in ma'amid to give taste on Pesach; Rashal holds davar hama'amid permitted to retain; Rashba and great Poskim forbid; therefore Ramban forbids cooking mei einayim cooked all year when first was sour with beer lees — this fourth or fifth — Ra'avan 72b.",
  "eshel-avraham/7:_":
    "Nullified when not in kneading place. Peri Chadash; Rosh: did not elaborate these laws for Israel scrape all chametz even a trace; Taz challenged — we are obligated per Tosafos lest eat — his words strained.",
  "eshel-avraham/9:א":
    "Permitted. Per Maggid Mishneh likewise se'or; Ra'avad: different — fit to leaven; also designated for kneading or coated in clay — prohibition not nullified.",
  "eshel-avraham/9:ב":
    "To retain. D'oraisa permitted in eating — even on Yom Kippur exempt eating unfit food; only d'rabbanan decreed equating it to fit food — Rosh.",
  "levushei-serad/1:_":
    "There and it is nullified in sixty — end of his words. The words \"end of his words\" are out of place — should read \"beforehand\"; but for R' Eliezer forbidden — should read \"but for R' Eliezer therefore forbidden.\"",
  "levushei-serad/2:_":
    "Magen Avraham s.k. 9: davar hama'amid even in thousand not nullified, etc. — see Machatzit HaShekel klal 79 s.k. 3.",
  "levushei-serad/3:_":
    "Taz s.k. 4: some lenient to drink on last Yom Tov mei einayim, etc. — see Kenesset Yisrael 87:14.",
  "netiv-chayim/1:_":
    "(Magen Avraham s.k. 1) Since it began to leaven therefore burn — note: meaning burn afterward when it became chametz as Bach ruled full chametz made on Yom Tov destroyed on Yom Tov — see below 446 s.k. 1. Rashba holds like other Poskim who forbid burning on Yom Tov — must explain Rabbanan did not distinguish.",
  "netiv-chayim/2:_":
    "(Taz s.k. 1) And proof for this. Note: Tur's language should be corrected — certainly regarding mixtures he wrote only no lav in mixtures — implying d'oraisa prohibition exists; what he wrote \"only rabbinic prohibition\" follows on nokshah; if we derive from everything — nokshah too should be rabbinic; one may say reasonable to establish mixtures as prohibition since b'eyna d'oraisa forbidden — half measure applies.",
  "netiv-chayim/3:_":
    "(Magen Avraham s.k. 14) And wonder on Tur. Note: to me the key: Tur forbids eating because he designates it even for one who does not hold that view — nevertheless forbidden in eating lest not charred well; but regarding mixture he follows his conclusion 447 end permitting to mix l'chatchila to retain — likewise 442 in Rif's method; this is the \"some say\" Rosh brought — however Magen Avraham strained to learn how forbidden in benefit is proven from not writing permitted in eating — appears first view: morayis permitted in eating because full chametz through mixture permitted in benefit after Pesach and charring before its time even b'eyna permitted in benefit and charring through mixture adds one lenient level permitted even in eating — disagrees — if so greater novelty charring before its time permitted in eating; therefore Tur's words are correct.",
  "rabbi-akiva-eiger/1:_":
    "Magen Avraham s.k. 7: not more advantageous than moldy bread; Makor Chayim wondered — moldy bread deals with disqualified from dog; he wrote should read not more than nokshah through mixture — see there.",
  "rabbi-akiva-eiger/2:_":
    "Seif 7: if kezayit in one place; if reduced from kezayit — Yerushalmi asks if nullified or since visible must destroy all.",
  "rabbi-akiva-eiger/3:_":
    "Seif 8: whatever they asked — remove thread; even if dry — by removing not taken; Gemara challenges: if moist would peel all as one — even dry obligated to destroy — Yerushalmi.",
  "shaarei-teshuvah/1:_":
    "They transgress. Baer Heitev; see Magen Avraham's challenge from se'or must burn; Chidushei E.H.; Makor Chayim; Keter Kehunah; Beit Efrayim 30 to establish Magen Avraham; Penei Yehoshua 15: one forgot to destroy candied sugar coating of nuts and fruits within Pesach — craftsmen say they cook sugar in water and coat — flour needed — possibly 60 with water; only chametz nokshah; agreed chametz nokshah may retain — see there; I have doubt perhaps flour leavened before sugar melted and water causes leavening without syrup mixture — if sugar already cooked in water then flour added perhaps like raisin wine siman 462; Chacham Tzvi disagrees there — not 60; Acharonim nokshah requires destruction d'rabbanan — if remembered within Pesach must destroy — no leniency to retain; if craftsmen put flour only when water boils well — slight leniency from chalitah — see below 434 s.k. 3; Chayei Adam: no absorbed-vessel prohibition on Pesach — Har HaCarmel 14 permits retaining preserves or fat in chametz pots — see there.",
  "shaarei-teshuvah/3:_":
    "And all the like. Baer Heitev; Chacham Tzvi 20: burnt wine from malts forbidden d'oraisa — though taste changed essence is malts for burnt wine; like very rotten fruit unfit alive eaten by cooking in water or honey and sugar — though taste changed in cooking they remain; see there; Penei Yehoshua 101 for kiddushin elaborated Shevut Yaakov 10:191; Beit Efrayim 49 responsum to Gaon R' Yehoshua on preserving burnt wine as mere zei'ah; Be'er Yaakov debated with colleagues — see responsa Mishna Berurah 64 — seemed unwilling to fix halachah to permit from zei'ah even with nullification; Beit Efrach what Gaon wrote in name of author of Ahavat Chametz on malts sale — malts is chametz nokshah — see there; thus Chacham Tzvi's opening implication d'oraisa transgression ben yomo not necessary — all per many Poskim nokshah rabbinic; nevertheless there I explained all per circumstance if spoiled until entirely unfit except b'dieved — Chacham Tzvi may deal with malts whose taste changed yet still somewhat fit after grinding — not implied from rotten fruit comparison — requires study.",
  "shaarei-teshuvah/7:_":
    "Visible. Baer Heitev; Gilyon Maharsha klal 4 siman 11: custom on hats covering garment inside — coat with soft batter near two eggs, attach outer garment, sew, place on heat until dry as hat — no chametz concern though dough reached se'or category since action done and nullified and covered with stitches — see there; responsa Rav Zuskind Rothenberg (questioner cited Taz siman 432) resolves: do not challenge from hiding — here not visible outside nullification helps; Terumat HaDeshen: reason not visible outside is chametz form nullified — see there.",
  "shaarei-teshuvah/11:_":
    "In vinegar. Baer Heitev; Penei Me'irot 107 wondered on Magen Avraham s.k. 9 in Ra'avan (in Penei Me'irot and Sha'arei Yosef copied Ramban — error) — even fifth honey leavened in beer lees forbidden; Yoreh De'ah 112 and 115 in R' Yehuda permit after three times; Penei Me'irot 2:75 also on Magen Avraham — wrote thus to permit one careful about chadash (I lacked heart to permit retaining on Pesach; retaining appears permitted — see there; Sha'arei Yosef 2:77 rejected — they lenient only in their bread and milk which are light prohibitions — not chametz which is stringent — therefore stringent even in retaining; if transgressed and retained may permit benefit after Pesach combining reason some Poskim write that now all nullify — do not be so stringent — see there; see below 447 s.k. 14 on Baer Heitev from Bach responsum; see 448 regarding beer lees on eve of Pesach.",
  "yad-ephraim/1:_":
    "There in Magen Avraham s.k. 8: per Tur se'or must burn — Acharonim already challenged: on Yom Tov forbidden to burn; they resolved Tur follows his brother R' Yechiel 446 without nullification forbidden; here se'or cannot be nullified forbidden in benefit not in his domain to nullify. In my opinion: per Tosafos Pesachim 5 — though may benefit from ash, since cannot benefit at start of destruction forbidden; at start of destruction could benefit if leaves more wood — this and that cause; but Magen Avraham 445: even zuz gavra forbidden in chametz; therefore here while still se'or and nokshah — nokshah nullified in 60 Pesachim 105b — nevertheless if establishing cause is d'oraisa prohibition not so stringent in benefit; also mishnah se'or burn may be like Chachamim who permit even facing it without permitting cause — permitted even at start of destruction for nokshah nullified in 60; even per Shach ash forbidden — was bread's enhancement; for Chachamim who permit facing fire since flame from coal and coal forbidden for them — nevertheless mishnah se'or burn is like R' Yehuda chametz by burning; mishnah teaches one who eats exempt; which is se'or like grasshopper horns — see there — R' Yehuda; if so may burn and benefit; Tosafos s.v. bashelah on coals — distinction coals l'chatchila forbidden; all the more facing fire for Rabbanim forbidden l'chatchila; here se'or itself only rabbinically forbidden in eating — permitted in this case l'chatchila — all the more with permitting cause.",
  "yad-ephraim/2:_":
    "There deals if kezayit within k'dei achilat peras, etc. — law not precise; truly Gemara establishes Rabbanan argue R' Eliezer on paste because no k'dei achilat peras — Magen Avraham means there proved when no k'dei achilat peras permitted to Rabbanan though essence so; he resolved: Rashba only where essence so rabbinically forbidden; Gemara there d'oraisa; requires study — Gemara where Rabbanan argue is for eating and if no k'dei achilat peras eating not combined; not like Rashba on retaining — if his intent from why Rabbanan argue on paste — Gemara intended per R' Nachman mishnah like R' Eliezer and Rabbanan argue on mixture; therefore Magen Avraham challenged from kezayit — even without kezayit since essence so; should have challenged plainly on establishment that mishnah even like Rabbanan agree when essence so; Gemara requires study; Magen Avraham and R' Yehuda wrote: but mixed intentionally — meaning fixed method is so — not nullified in 60 even before Pesach — like Rashba; there implies even not initially intentional to retain — forbidden since essence is through chametz.",
  "yad-ephraim/3:_":
    "Taz s.k. 4: already practiced to beware chametz mei einayim of Pesach in lees of mei einayim or those vessels — should read thus. Established in vessel, etc.",
};
