export const t = {
  "1:א": `Mishnah Eruvin 22, and like R' Akiva there`,
  "1:ב": `In the Mishnah, and like R' Yosi`,
  "1:ג": `There`,
  "1:ד": `There in the Mishnah`,
  "2:א": `There`,
  "2:ב": `In the Gemara 24, and like Rav Nachman there in the name of Shmuel`,
  "2:ג": `There — R' Yehonatan`,
  "2:ד": `There in the Gemara 24 — an inquiry, and it was resolved`,
  "3:_": `From the implication of the Gemara from what R' Chisda [said] there 35`,
  "4:_": `Plain`,
  "5:_": `There in the Gemara`,
  "6:_": `There, and the first version, and like Rava`,
  "7:_": `There 25, and like Rava, Raavad, and Razah`,
  "8:א": `There, and like R' Sheshet, the Rosh, and Rambam chapter 6`,
  "8:ב": `There — an inquiry, and it was resolved`,
  "9:א": `There in chapter 14, like R' Nachman, and likewise the Rosh, and so it appears from Rambam's words in chapter 15`,
  "9:ב": `There, and the latter version leniently — the Rosh and Rambam in chapter 15`,
  "10:_": `Tur, according to the view of R' Meir`,
  "11:א": `There, like Rava`,
  "11:ב": `There, like Amemar`,
  "11:ג": `There, in the explanation of Rashi`,
  "12:א": `There 25, and like Rava, and like the textual reading of Rambam in chapter 15, and as the Rosh wrote according to the view of Or Zarua`,
  "12:ב": `There — the textual reading of Ersilei, and like the explanation of Rashi`,
  "13:_": `There, and like the explanation of Rashi`,
  "14:_": `There, like that incident of the orchard keeper, like the explanation of R' Chaim`,
};
