export const t = {
  "1:א": `Shabbos 125, a statement of R' Yochanan`,
  "1:ב": `In Rashi's explanation there`,
  "1:ג": `There Tosafos in the name of Rabbeinu Tam, the Rosh, and the Ran, and Shulchan Aruch`,
  "2:א": `Eruvin 102, in the name of Rav Assi, and the Rif wrote in chapter 16 of Shabbos`,
  "2:ב": `There also in the name of Rav`,
  "2:ג": `Ritva in the name of Tosafos who were precise from Rashi's language`,
  "3:א": `Shabbos 138, braisos that Abaye cites from what is stated regarding a storehouse`,
  "3:ב": `Tur in the name of Tosafos there`,
  "4:_": `Ran and Halachot Gedolot in the name of Rashba`,
  "5:_": `There in Shabbos from what is stated regarding the folding chair`,
  "6:_": `Beitza 33`,
  "7:_": `Tur in the name of Tosafos and the Ran in their name there in Beitza`,
  "8:_": `Shabbos 138, Rambam in chapter 22`,
  "9:_": `There 137 in the Mishnah, even according to R' Eliezer`,
  "10:_": `There 138, and Rambam there regarding the roof, and as the Rif explained`,
  "11:א": `There and in Eruvin 102, and Rambam there`,
  "11:ב": `Rambam there, and see in Maggid Mishneh Halachot Gedolot there in the name of Rashba, and Beit Yosef brought it`,
  "12:_": `According to Rambam there per his explanation of what is stated regarding enlarging on Shabbos there`,
  "13:א": `There 139, and Rambam there`,
  "13:ב": `Ran there and Halachot Gedolot in the name of Rashba:`,
};
