export const t = {
  "1:א": `Chullin 15, and Kesubos 34, and Bava Kamma 61, and per R' Yehuda; the Rif and the Gaon and Rambam in chapter 6, and the Rosh and Shulchan Aruch`,
  "1:ב": `Chullin 15, and per Rav Dimi`,
  "3:א": `Shabbos 98 in the mishnah like the first tanna of R' Yossi; the Rif and Rambam chapter 9`,
  "3:ב": `There 39`,
  "3:ג": `There 146 in the mishnah`,
  "4:א": `Tur and Rosh from the words of Rashi in his commentary "lest it boil" 34`,
  "4:ב": `According to the Tur, and so it is implied from the words of Rambam in chapter 9`,
  "4:ג": `There 145 in the mishnah, and they explain it in the gemara such as R' Abahu's chicken`,
  "4:ד": `There in the mishnah`,
  "5:א": `Tur in the name of R' Eliezer of Metz, and Semag from that which we rule that they do not go out in cooked after baked, in Pesachim 41`,
  "5:ב": `Mordechai in chapter 3 of Shabbos in the name of Ravyah`,
  "6:_": `Shabbos 51 in a braisa, and Rambam in chapter 4 of the Laws of Shabbos, and as the Rav HaMaggid explained there and Beit Yosef brought in siman 257`,
  "7:_": `R' Yitzchak in Halakhot Gedolot brought both views and did not decide`,
  "8:א": `There in the name of the great authorities that thus wrote the Rosh`,
  "8:ב": `There`,
  "8:ג": `There`,
  "9:א": `Shabbos 42 in the mishnah and in the gemara there`,
  "9:ב": `There in the gemara and per the latter wording, the Rif and Rosh and Rambam in chapter 22, and Tosafos`,
  "9:ג": `Tur; Tosafos wrote — one who is stringent, blessing shall come upon him`,
  "10:_": `Rabbeinu Tam, and likewise we lean toward the words of the Rosh, and likewise is the view of Rabbenu Yerucham in chapter 22`,
  "11:_": `Shabbos 42 in a braisa, and Rambam wrote in chapter 22`,
  "12:א": `There 41 in the mishnah and in the gemara`,
  "12:ב": `There in Tosafos`,
  "13:_": `Shabbos 40 in the incident of R' Yitzchak bar Avdimi`,
  "14:א": `There 40 in a braisa`,
  "14:ב": `There in the gemara`,
  "14:ג": `Ran there in the name of the Yerushalmi and in the name of R' Yitzchak and other decisors`,
  "15:_": `With the agreement of all the decisors, even those who are stringent regarding something that has broth`,
  "16:_": `Rambam and Semag and Semak and Rabbeinu Yerucham, and likewise Rabbenu Yerucham in chapter 21 according to Rashba`,
  "17:_": `Tosafos on Shabbos 48, incident of Rabbah and R' Zeira in the house of the Exilarch, and Ran there`,
  "18:_": `Ran in the first chapter of Shabbos 18, the established reading of "uprooted ibis" and "buffeted"`,
  "19:_": `Kol Bo`,
};
