export const t = {
  "1:א": "Mishnah in Eruvin chapter 10, as Rashi explains there",
  "1:ב": "Rashi chapter 6 and Tosafos there in that chapter",
  "1:ג": "There 28 — there are two versions; and Rif and Rosh ruled like the latter version that it is permitted",
  "1:ד": "Shabbos 100, and like R' Chisda and Rabba bar Rav Huna",
  "1:ה": "Rambam in chapter 6; and so wrote Hagahot there in the name of Rav Hai; and Ran in chapter 11 of Shabbos",
  "1:ו": "Rambam there",
  "1:ז": "Shabbos 100",
  "2:א": "So Tosafos and Rosh on that which we learned: a pit between two courtyards, etc., in Eruvin 66",
  "2:ב": "Mordechai in chapter 11 of Shabbos and Hagahot in chapter 15 of the laws of Shabbos",
  "2:ג": "There in Mordechai",
  "2:ד": "There",
  "2:ה": "Hagahot Mordechai chapter 10",
  "3:_": "Tur, and not like R' Dimi",
  "4:_": "Beit Yosef",
  "5:א": "Mishnah in Eruvin chapter 7, as Rav explains and as Rashi explains there in the first explanation",
  "5:ב": "As Rav Sheshet explains there",
  "5:ג": "Explanation that the upper one uses through the lower one by descent — therefore they forbid her",
  "5:ד": "Tur from the implication of the Gemara there",
  "5:ה": "There, and also from the implication of the Gemara",
};
