export const t = {
  "1:א": `Shabbos 43`,
  "1:ב": `There, and like R' Yehuda ben Lakish`,
  "1:ג": `It appears from Rashi's words there and from Rambam's words in chapter 27 and Ran and Rosh`,
  "1:ד": `There`,
  "1:ה": `There, and like Rav`,
  "1:ו": `Tosafos and Rif and Rosh (and see below seif 28)`,
  "2:א": `Rambam chapter 26`,
  "2:ב": `Tur, and likewise Rashi there`,
  "2:ג": `Tur in the name of Ramban, and so wrote in Torat HaAdam that thus it appears from Rambam's words in chapter 26`,
  "2:ד": `There in the name of Ramban`,
  "2:ה": `Mordechai in chapter 3 of Shabbos`,
  "3:_": `Ramban there`,
  "4:_": `Mordechai in chapter 3 of Shabbos in the name of Rav Avigdor`,
  "5:א": `Rabbeinu Yeruham in Netiv 28 part 1`,
  "5:ב": `Shabbos 142, and like Rav Asi`,
  "6:א": `There 43`,
  "6:ב": `Rambam's wording in chapter 26`,
  "7:_": `There 121 in the Mishnah`,
  "8:א": `Tosafos there 42, and Rif and Rosh there`,
  "8:ב": `Kilayim chapter 2`,
  "8:ג": `Tosafos there on Shabbos 50`,
  "8:ד": `There in the gemara, and not like these rabbis who forbid there:`,
  "8:ה": `There in Tosafos`,
  "8:ו": `Ra'avad there`,
  "8:ז": `There 141, Mishnah 6, as Rashi explains`,
  "9:_": `There 123:`,
};
