export const t = {
  "1:א": `Eruvin 5, in the name of Rav Ami and Rav Asi; Rif and Rosh.`,
  "1:ב": `Thus []`,
  "2:א": `There.`,
  "2:ב": `Thus) (`,
  "2:ג": `There, and.`,
  "3:א": `There, 7 — alleyway.`,
  "3:ב": `Thus [] courtyard [] public domain.`,
  "3:ג": `Rosh there, from that which R' Zeira.`,
  "3:ד": `Thus public domain alleyway public domain [] courtyard [].`,
  "3:ה": `Thus alleyway public domain [] courtyard [].`,
  "3:ו": `Thus alleyway public domain [] courtyard [].`,
  "3:ז": `Thus alleyway [] courtyard [].`,
  "3:ח": `Meaning: that it appears like a long alleyway extending to the public domain opposite it.`,
  "3:ט": `Thus alleyway public domain () courtyard ().`,
  "3:י": `For sometimes the individual will take counsel and build houses for himself, and it becomes an alleyway that terminates at its side and is forbidden.`,
  "3:כ": `Tosefta in the name of R' Yehuda, and so too Rosh and Tur. And see above in siman 328.`,
  "4:א": `There in the Gemara, 8.`,
  "4:ב": `Rav, and R' Chiya, and R' Yochanan.`,
  "4:ג": `There, 9, and Rav.`,
  "4:ד": `There.`,
  "5:א": `Shabbos, chapter 1.`,
  "5:ב": `Rosh there:`,
  "6:_": `Beitzah 30.`,
  "7:א": `Mishnah Eruvin 94, and R' Yosi, and Rif, and Rosh, and Rambam in chapter 17.`,
  "7:ב": `There in the Gemara, 95.`,
  "7:ג": `Terumat HaDeshen.`,
  "8:_": `Mordechai, chapter 7 of Eruvin; Hagahot Maimoniot, chapter 7.`,
};
