export const t = {
  "1:א": "Shabbos 128 mishnah",
  "1:ב": "there in the gemara in explanation of the baraita",
  "1:ג": "there in the gemara",
  "2:א": "Avodah Zarah 26",
  "2:ב": "Tur from the words of Tosafos there",
  "2:ג": "according to Beit Yosef)",
  "3:_": "Shabbos 129, and all the amoraim to be lenient; Tur in the name of Ramban in Sefer Torat HaAdam",
  "4:_": "there in Shabbos",
  "5:_": "Eruvin, and Rambam wrote in chapter 2 of Hilchot Shabbat",
  "6:_": "Shabbos 129",
  "7:א": "there",
  "7:ב": "there 128 mishnah, and according to R' Yosi",
  "7:ג": "there 135 baraita",
  "7:ד": "there in Tosafos and the Rosh",
  "8:א": "there baraita, and there",
  "8:ב": "there Tosafos, Rosh, and R' Yehuda in chapter 9",
  "9:_": "there 123, and according to Rav Sheshet, and according to Rashi's explanation",
  "10:_": "there 147",
  "11:_": "according to R' Chananel's explanation of that which Rav Sheshet said above",
};
