export const t = {
  "1:א": `Beitzah 29a — this regarding several amoraim who hold thus; and likewise Ri'f and Rosh and Rambam in chapter 6 of Laws of Shabbat`,
  "1:ב": `Shabbos 19`,
  "1:ג": `Rambam there, and he wrote likewise that it is from the Yerushalmi`,
  "1:ד": `Tosafos and Rosh and Ran at the beginning of Shabbos`,
  "1:ה": `Tosafos there 19, and Rosh and Ran and Mordechai there`,
  "2:_": `Haggahot Maimoniyot chapter 6 in the name of Or Zarua`,
  "3:_": `Ri in part 12`,
  "4:א": `Tur in the name of Rabbeinu Tam and Rashba in a responsum and Haggahot Maimoniyot — he explains that Ravyah would whip one who ate it on Shabbat, end of his words`,
  "4:ב": `Tur in the name of his father the Rosh in chapter 3 of Beitzah`,
  "4:ג": `Haggahot Osheri there and Semak and so decided Beit Yosef`,
  "5:א": `Tur in the name of Sefer HaMitzvos that some forbid, and likewise the Tur and Rabbeinu Tam, end of his words`,
  "5:ב": `There`,
  "6:א": `Beitzah 24 and Eruvin`,
  "6:ב": `Semak and Terumah`,
  "7:א": `Beitzah 24, braisa, and according to R' Yehoshua`,
  "7:ב": `Ri'f`,
  "7:ג": `Tur in the name of Semag`,
  "8:א": `From what is stated in Beitzah 25 and Eruvin 40`,
  "8:ב": `There`,
  "8:ג": `Ri'f and Ran and Semag and Mordechai, end of his words`,
  "8:ד": `Ri and likewise Rosh`,
  "8:ה": `Ran`,
  "8:ו": `Rosh in chapter 4 of Eruvin`,
  "9:_": `Rashba according to the view of Ri'f and the Geonim, and likewise Ran in chapter 2 of Beitzah and in chapter 22 of Shabbos, and likewise in chapter 2 of Laws of Yom Tov`,
  "10:א": `Shabbos 122, mishnah`,
  "10:ב": `There, braisa`,
  "10:ג": `Ran in chapter 3 of Beitzah, and as the conclusion of Tosafos and Rosh`,
  "10:ד": `Tosafos there 25, and likewise Mordechai in chapter 22, end of his words`,
  "11:א": `There, braisa`,
  "11:ב": `There in the gemara`,
  "11:ג": `There, and according to Rava`,
  "12:_": `Haggahot Mordechai chapter 14 in the name of R' Meir`,
  "13:_": `Rosh, and likewise Tur`,
  "14:א": `Shabbos 151`,
  "14:ב": `There, and as Ran explains in the name of the Gaon and Rambam in chapter 7`,
  "14:ג": `Rambam there`,
  "15:א": `There, mishnah`,
  "15:ב": `Agreement of most poskim`,
  "15:ג": `Tur as Tosafos explain there, and likewise the view of Ri'f and Rosh, and likewise Rambam in chapter 7, end of his words`,
  "15:ד": `Tur and Rambam`,
  "16:_": `Ri'f and Rambam there`,
};
