export const t = {
  "1:א": `Shabbos 143 in the mishnah and in the gemara`,
  "1:ב": `There`,
  "1:ג": `There, in the establishment according to Shmuel that R' Yehuda concedes in this`,
  "1:ד": `There, a braisa in s.v. "and so," and likewise wrote Ri'f and Rosh and Rambam in chapter 28, and Semag`,
  "1:ה": `There, and like R' Yehuda, and as he explains there; and gemara 144`,
  "2:א": `I pointed to it above in siman 226 seif 5`,
  "2:ב": `Tur in the name of the author of Terumat HaDeshen, and likewise Semag and Semak, that a prohibition that was never recognizable, as here, is nullified even in a davar sheyeish lo matirim`,
  "3:_": `There`,
  "4:_": `Shabbos 145 like Rav — Ri'f and Rambam in chapter 1, and Tosafos there`,
  "5:א": `Tur in the name of R' Yosef`,
  "5:ב": `There — Mordechai and Semag did not bring except the words of Rabbeinu Tam`,
  "6:_": `Responsum of Rosh and R' Yitzchak in Orach Chayim`,
  "7:א": `Shabbos 145`,
  "7:ב": `There, like Shmuel — Ri'f and Rambam in chapter 28`,
  "7:ג": `Ri'f in his name, and like R' Yochanan`,
  "8:_": `Beit Yosef from the implication of the gemara there`,
  "9:א": `Shabbos 51, a braisa`,
  "9:ב": `Ran there, and most of the poskim`,
  "10:_": `Tur in the name of R' Avraham ibn Ezra`,
  "11:_": `There, and likewise wrote Tosafos and Rosh there`,
  "12:_": `There, in the name of the author of Terumat HaDeshen`,
  "13:_": `Tur in the name of Maharam of Rothenburg`,
  "14:א": `Tur in his name`,
  "14:ב": `There`,
  "15:_": `Shabbos 41, in the incident of the house of the Exilarch, and per Rashi's explanation, and likewise Rambam in chapter 22`,
  "16:_": `There 148`,
  "17:_": `There 143 in the mishnah`,
  "18:א": `He explained: the hole surrounding the faucet`,
  "18:ב": `Tur in the name of the Aruch, and likewise R' Yitzchak agreed in one place on this of Shabbos 118`,
  "18:ג": `Tosafos 113 and Rosh there, and Mordechai in chapter 2 of Shabbos in the name of R' Yitzchak, and Semag and Terumat HaDeshen`,
  "18:ד": `Beit Yosef from the implication of everyone's words in it`,
  "19:_": `Shibulei HaLeket in the name of the author of Yere'im`,
  "20:_": `There, in the author of Yere'im:`,
};
