export const t = {
  "1:_": `I pointed to it in siman 319 seif 6`,
  "2:א": `Shabbos 108 in the mishnah and as the first tanna, and as Shmuel explains there in the gemara`,
  "2:ב": `There`,
  "3:א": `There`,
  "3:ב": `Rambam in chapter 23`,
  "3:ג": `There in the gemara`,
  "3:ד": `There, as Chizkiyah in the name of Abaye`,
  "4:_": `Terumat HaDeshen and in the name of Or Zarua, and likewise they wrote in his name in Hagahot chapter 2, and he brings proof from the Yerushalmi`,
  "5:_": `Shibulei HaLeket in the name of the Geonim`,
  "6:_": `Tur in the name of Rav R' Shimon`,
  "7:_": `Shabbos 148 like Rava — Ri'f, Rosh, and Rambam in chapter 21 of the Laws of Shabbos`,
  "8:_": `Likewise there, in the name of the Tosefta`,
  "9:_": `Tosefta chapter 4`,
  "10:_": `Rivash in a responsum`,
  "11:_": `Rashba in a responsum`,
  "12:_": `Shabbos chapter 4, and per Rashbam's explanation — they brought it in chapter 28, and Semag, Ran, and Mordechai there`,
  "13:_": `There 95, in a braisa, and like the Sages`,
  "14:א": `There 125, in a braisa, and like R' Yosei son of R' Yehuda — Ri'f, Rosh, and Rambam in chapter 21`,
  "14:ב": `There, in Rambam according to his textual version`,
  "15:_": `There 140, the conclusion of the gemara`,
  "16:א": `There`,
  "16:ב": `Tur in the name of the author of Terumat HaDeshen:`,
  "17:א": `Shabbos 139, mishnah "if it is permitted to strain" — see siman 319 seif 19`,
  "17:ב": `There 140, braisa`,
  "18:א": `There, braisa, and as the first tanna; and the mishnah is a lone opinion of R' Yosei`,
  "18:ב": `There in the gemara`,
  "19:א": `I pointed to it above in siman 252`,
  "19:ב": `Tur in the name of Rambam in chapter 21 of the Laws of Shabbos, and likewise he wrote in a responsum:`,
};
