export const t = {
  "1:א": `Beitzah 29, mishnah, and according to the first Tanna, as Rabbah explains there`,
  "1:ב": `Ran there, and thus the words of the Rambam in chapter 4 of Yom Tov appear correct`,
  "2:_": `The same law in chapter 9 of Yom Tov in the name of the Yerushalmi`,
  "3:_": `Beitzah 29, mishnah`,
  "4:א": `There, in the braisa`,
  "4:ב": `The dispute between the first Tanna and Rashba, and there are variant textual readings there, and the Rosh wrote that one must be careful with both of them, and so too the Rambam there`,
  "5:א": `There, in the mishnah`,
  "5:ב": `There, in the gemara, folio 30`,
  "5:ג": `Tosefta there`,
  "6:_": `Shabbos 108, in the braisa`,
  "7:א": `Thus the Rosh proved from the words of the Ri'f, and so it is implied from the words of the Rambam in chapter 4 of Yom Tov`,
  "7:ב": `Rosh, and the same law there in the name of the Rashba`,
  "7:ג": `Beit Yosef`,
  "8:_": `R' Yehuda in Terumat HaDeshen`,
  "9:א": `Shabbos 50, braisa`,
  "9:ב": `There, and Rashi explained: because it is a psik reisha that R' Shimon concedes`,
  "10:_": `Mordechai in the name of Sefer HaMitzvos:`,
};
