export const t = {
  "1:א": `Shabbos 74, and Rambam in chapter 1`,
  "1:ב": `Tosafos, and likewise Rabbeinu Chananel, and Rambam there`,
  "2:_": `There, Abaye's establishment`,
  "3:_": `Rambam: there`,
  "4:_": `Rambam chapter 8 of the Laws of Shabbos`,
  "5:_": `Shabbos, the statement of Chizkiyah, and per Rambam's explanation, and in chapter 1`,
  "6:_": `Beitza 12, Shabbos 138, and per the Sages`,
  "7:_": `There and there`,
  "8:א": `There 141 in the mishnah`,
  "8:ב": `There in Rashi's commentary`,
  "9:א": `There 137 in the mishnah`,
  "9:ב": `There 139 in the mishnah and per Rashi there`,
  "10:א": `There, Ze'eiri's statement`,
  "10:ב": `Tur, and per the words of Rashba that Tosafos wrote in Shabbos 102`,
  "10:ג": `Tur in the name of Rambam chapter 8`,
  "10:ד": `There, Ze'eiri's establishment of the braisa of Rashbag`,
  "10:ה": `Rambam there, and Beit Yosef wrote that he holds that the meshameret they spoke of there is not meshameret strictly speaking but rather he says it is permitted to guard it`,
  "11:_": `There in the gemara`,
  "12:א": `There in the mishnah`,
  "12:ב": `There and in the gemara`,
  "13:_": `There`,
  "14:_": `There`,
  "15:_": `There in the mishnah and in the first explanation in Rashi`,
  "16:_": `The Rosh in a responsum`,
  "17:_": `Rambam chapter 8, as the Rav HaMaggid wrote that it is from the Tosefta`,
};
