export const t = {
  "1:א": `Shabbat 150.`,
  "1:ב": `Eruvin 38 and 39.`,
  "1:ג": `Shabbat there in the Mishnah.`,
  "1:ד": `There in the braita 138a.`,
  "1:ה": `There in Tosafot per the books' reading that Tosafot brought there.`,
  "2:_": `There in the braita to resolve the Tosefta's reading that one may not wait at dusk.`,
  "3:א": `There in the Mishnah.`,
  "3:ב": `There in the braita.`,
  "3:ג": `There and like R' Yosi and like R' Yehuda who do not dispute.`,
  "3:ד": `Per Rabbenu Tam's explanation in ch. 24 Laws of Shabbat.`,
  "3:ה": `Per the Ran's explanation.`,
  "4:א": `Bava Metzia 58.`,
  "4:ב": `Rif and Rosh ch. 23 of Shabbat and Rambam ch. 26 and ShP.`,
  "5:א": `Mordechai end of "Even though" in the name of R' Baruch and Tur siman 485.`,
  "5:ב": `There in Mordechai in the name of R' Shmuel because of a mitzvah; and Beit Yosef from that of Pesachim 54 — there is no sign of blessing — thus there is no prohibition.`,
  "6:א": `Shabbat 103 and Ketubot 5.`,
  "6:ב": `Tur in the name of Rambam of Rothenburg and other poskim.`,
  "7:א": `Tur in the name of Avi HaEzri and Maharam of Rothenburg.`,
  "7:ב": `There in the name of Maharam.`,
  "8:א": `There in the Gemara.`,
  "8:ב": `Tur and R' Yona in Iggeret HaTeshuvah per the Mekhilta.`,
  "9:_": `Mordechai ch. 3 of Shabbat and ShP.`,
  "10:_": `R' Yerucham in section 12 in the name of the commentators.`,
  "11:_": `Bava Kamma ch. 6 and Gittin 8.`,
  "12:_": `Rashba in a responsum.`,
  "13:_": `Responsum of Rivash and the Ran agreed.`,
  "14:_": `Beit Yosef from the words of Tosafot Shabbat 4 and Eruvin 32, Gittin 41, and elsewhere for the final resolution that a great mitzvah is different (supplement laws pertaining to this matter in the next siman).`,
};
