export const t = {
  "1:א": `Shabbat 57 in the mishnah and Gemara`,
  "1:ב": `Tur in the name of Rabbeinu Tam, the Rosh, and the Ran there`,
  "1:ג": `Rashi there`,
  "1:ד": `There in the Gemara`,
  "2:א": `There like Rav Yosef according to Rabbah`,
  "2:ב": `There in the mishnah and as Ravina explains there`,
  "2:ג": `There in the mishnah and as R' Avahu explains there`,
  "2:ד": `There 64 in the mishnah`,
  "3:א": `There 57 in the mishnah regarding koveles, and as R' Avahu explains`,
  "3:ב": `The Rif there`,
  "3:ג": `There 23`,
  "4:א": `There in the mishnah`,
  "4:ב": `There 29`,
  "5:_": `Like Shmuel and Rav Ashi who taught leniently`,
  "6:_": `There in the Gemara and per Rashi's explanation see there`,
  "7:_": `There in the mishnah 57 and in the Gemara 59, and in one version in Rashi's explanation`,
  "8:א": `There and there`,
  "8:ב": `Rashi there, and Tosafot, and Shulchan Pesak`,
  "9:א": `There 62`,
  "9:ב": `The Rosh and Rav Ada there 60`,
  "10:א": `There 62`,
  "10:ב": `There 57`,
  "11:_": `There 62`,
  "12:א": `There 64 and like the Sages`,
  "12:ב": `There in the Gemara`,
  "12:ג": `The Rosh there`,
  "13:_": `There in the first baraita`,
  "14:א": `There 64 in the mishnah`,
  "14:ב": `There in the baraita`,
  "15:א": `There 57 and like Abaye`,
  "15:ב": `There 64 in the mishnah and in the Gemara 65`,
  "15:ג": `Tur in the name of Semag and Shulchan Pesak per Beit Yosef's explanation there`,
  "15:ד": `There 64 in the mishnah`,
  "15:ה": `There in the Gemara 65`,
  "15:ו": `There 64`,
  "15:ז": `Tur in the name of R' Yitzchak and Shulchan Pesak`,
  "15:ח": `Rambam in chapter 19 from that which Rav Yosef according to Rav Yehuda in the explanation of birit etc.`,
  "15:ט": `Likewise from the implication of Rashi's explanation there`,
  "16:_": `Tosafot 57, and the Rosh, and the Ran`,
  "17:_": `R' Yerucham part 9 in the name of Ramban and Rashba, and the Rav HaMagid in chapter 19 in the name of Rashba`,
  "18:א": `There 64 and Rav — the Rif and Rambam in chapter 19`,
  "18:ב": `Beit Yosef from the implication of Rashba that the Magid brought in chapter 19, and Mordechai chapter 4 of Shabbat in the name of R' Yitzchak`,
  "18:ג": `Tur and Tosafot in the name of R' Daniel 64`,
  "18:ד": `Tosafot there in the name of Rabbenu Shar Shalom`,
  "18:ה": `There in Tosafot and the Rosh and the Ran there`,
  "18:ו": `Tur in the name of Baal HaTerumot and Semak there in Tosafot in the name of Rabbenu Baruch`,
  "18:ז": `There and Baal HaTerumah`,
  "18:ח": `The Ran per the view of Rabbeinu Tam, and Beit Yosef brought in siman 301`,
  "18:ט": `Mahari Abuhav`,
  "19:_": `Mordechai chapter 4 in the name of R' Yitzchak`,
  "20:א": `There 65 in the mishnah and per Rashi's explanation`,
  "20:ב": `There from that which the father of Shmuel`,
  "21:א": `There in the mishnah`,
  "21:ב": `So it is in the Tur before us, but in Rashi and Aruch except the eyes`,
  "22:א": `There in the mishnah`,
  "22:ב": `There in the Gemara and Rashi's explanation there`,
  "22:ג": `Rambam in chapter 19 per the Tur's version, and Beit Yosef in the name of the new Rambam books`,
  "23:_": `There in the Gemara — it was asked and not resolved; teiku — Torah law stringent, rabbinic law lenient — the Rif and the Rosh`,
  "24:_": `There 66`,
  "25:א": `55`,
  "25:ב": `There 94 in the mishnah`,
  "25:ג": `Rashi's explanation of the mishnah in the name of Yesh Mefarshim`,
  "26:א": `There in the mishnah`,
  "26:ב": `Tosafot 57 and the Rosh there`,
  "26:ג": `Tosafot chapter 5 and the Rosh and the Ran there`,
  "27:_": `Kol Bo and the responsum of Ribash`,
};
