export const t = {
  "1:_": `Plug. And even on a skylight on the roof permitted — for adding to a temporary tent is permitted (Tosafos). R' Yehuda HaLevi ruled that before the deceased dies it is permitted to close the window so that impurity not enter the house; but after his death it is forbidden to close it, for it is considered as fixing. And Magen Avraham's view is to permit even after he died — see there. And to tell a non-Jew to close it is shevut deshevut — see siman 307 seif 5; and see in responsa Mahariv siman 65:`,
  "2:_": `And a rod — that one inserts it by the door in the wall — is somewhat like a bolt; but a rod with which one crushes olives — even though one locks with it — nevertheless it is called a utensil whose melacha is forbidden, so it is implied from Rambam:`,
  "3:_": `Beneath it. And if from the outset one made a hollow in the ground where the bolt's head will be, so that he does not add a hole in the ground — there is no prohibition. Furthermore, it appears to me that if one makes an iron ring in the middle of the bolt-bar and one grasps it when opening and closing — it is considered as making for it a handle and is permitted even when it is not tied and hanging. Taz see there:`,
  "4:_": `There is not. And the same applies to a window plug — if it is not made to open except at distant times — it is like a permanent tent (Rosh end of Eruvin):`,
  "5:_": `And they do not. And Bach is lenient even with one board if it is made for frequent entry and exit; and Rambam is even more lenient. Magen Avraham:`,
  "6:_": `Even. From this one can learn that one must protest what people customarily do at meals — removing the window by a non-Jew on Shabbat — and this is a great prohibition, since the Jew is liable for a chatas it is forbidden through a non-Jew due to shevut; and all the more so those who take the curtains from the windows; and even Jews are accustomed to do this and do not know that there is chatas liability in this. Taz:`,
  "7:_": `The law. And likewise the stender in the synagogue on which they place bound books. And Magen Avraham wrote that our cups made with grooves around and tightened forcefully — forbidden for everyone; and Beit Yosef wrote loose and not loose — also forbidden; and it is implied from the poskim that all these utensils — permitted to handle them — and they decreed only on a candelabrum whose manner is to be disassembled as written at the end of siman 279; and the same applies to everything similar; but something whose manner is not to be disassembled — permitted to handle; and Taz wrote the pewter cisterns we have that contain solder — since their primary use is through disassembly always — it is not called completion of melacha even if he drives the solder in forcefully — see there:`,
  "8:_": `With long beams. And an ordinary piece of wood — even though it was prepared for handling — forbidden to support it under the beam, for it is like a beam. Magen Avraham:`,
  "9:_": `One who drives. And likewise one who drives wood into an axe and likewise one who removes driven wood — liable for demolishing if he intends to fix. Rambam. Magen Avraham:`,
  "10:_": `By hand. And through a non-Jew permitted if there is great need — in every matter it is shevut deshevut (Taz); and Bach wrote specifically straw, but something that he nullifies there — forbidden, for there is concern of leveling furrows. And Magen Avraham wrote — it appears to me specifically here where he comes to fix the courtyard it is forbidden, for it is like building; but through a non-Jew permitted, for one may cover spit with dust as written at the end of siman 310, since he does not intend building:`,
};
