export const t = {
  "1:א": "And they desecrate. Therefore when she reaches the ninth month she should prepare everything from erev Shabbat so they not desecrate Shabbat (Sefer Chassidim siman 328 [495]).",
  "1:ב": "And they kindle. And Tosafos wrote that here an expert is not required as is required for a sick person on Yom Kippur, for here the woman in childbirth can become endangered more through fear — she may fear that perhaps they are not doing properly what she needs — than a sick person is endangered from hunger.",
  "1:ג": "Tied. And if she needs oil she should bring it in a vessel tied in her hair, for it is better to do carrying through a change than to add another prohibition of squeezing. Beit Yosef.",
  "2:א": "Non-Jew. Even Ishmaelites who are not idolaters; nevertheless Karaites are permitted since they observe Shabbat (Knesset HaGedolah, Magen Avraham). But in Gan Eden VeRimmonim Chayei Adam general rule 3 siman 1 he wrote that this ruling is not correct — see there at length.",
  "2:ב": "Shabbat. For there is no hatred so they can say that one who does not observe Shabbat — they do not desecrate for him; the gemara implies that if there is concern for hatred it is permitted if there is no Shabbat desecration. Magen Avraham.",
  "3:_": "One of these. It appears to me that this is regarding matters that can be done here without delay — therefore they do not desecrate Shabbat for this until one of these occurs; but regarding calling a skilled midwife these time measures do not apply, for they are closer to birth than the time for the midwife's arrival; rather from when she feels somewhat, even in doubt, it is permitted to call her. Taz.",
  "4:_": "They desecrate. And if a skilled midwife and doctor say she does not need it — they listen to them, for many women in childbirth do not have hot food made for them every day; and so is practiced now that they eat yesterday's hot food (Beit Yosef, Rama). And if her friends say she needs it and there is no skilled midwife or doctor — even if she eats ordinary people's food we say she is not aware at the moment, and if she eats cold food she will be endangered. Rashba, Magen Avraham.",
  "5:_": "And died. See Magen Avraham and Yad Ephraim.",
  "6:_": "Day. For according to all who say so, for thirty days there is danger to the infant from cold. And if it is impossible through a non-Jew they do it through an Israelite since there is danger in the matter.",
  "8:_": "To move him. And in Agudah he wrote specifically when there is a husband and he explained; but from doubt we move any infant, and so too Beit Yosef. Magen Avraham — see there.",
  "9:_": "That were dislocated. And specifically on the day of birth; but afterward forbidden. Tur and later authorities — see there.",
  "10:_": "Become distorted. And in Rosh chapter 17 he wrote that even to wrap him to straighten his limbs is permitted forever. And it implies that for an infant whom they do not wrap on a weekday and his limbs became distorted — it is forbidden to wrap him on Shabbat. Magen Avraham.",
};
