export const t = {
  "1:_": `Song. And the same applies to anything that is in the manner of song, as is written siman 339 seif 3. And so Yeshuot Shmuel: any sound-maker not intended for joy, such as a sun-clock that jingles for the synagogue and the like — permitted, end of his words. And if they place water in a holed vessel and drip into a metal vessel so that a pleasant sound is heard — forbidden, for this is like a musical instrument. And for a sick person it is permitted. And if he drips forcefully so as to awaken the sleeping — even for a healthy person it is permitted, for it is not like a musical instrument that acts pleasantly and gently; if so, all the more so these bells on the curtain have no prohibition, for his intent is not that they sound pleasantly and gently. And furthermore, since for a sick person it is permitted, all the more so for a matter of mitzva. And furthermore, nowadays there is room to be lenient as is written siman 339 seif 3 in the gloss, and so Knesset HaGedolah is lenient because it is for the need of a mitzva that the people hear and stand, for likewise for dancing it is also permitted for the need of a mitzva as is written siman 339. And Taz in Yoreh De'ah siman 282 s.k. 2 forbids here too and wrote one should protest them, see there. But they already were accustomed to be lenient as is written. And furthermore, that one who opens the curtain does not intend for sound at all. Magen Avraham see there`,
  "2:_": `Strike. And there are places where they take another utensil to strike on Shabbat`,
  "3:_": `To repair. See Magen Avraham who raised that it is forbidden to say to repair the musical instrument, rather to say to the gentile that he play, see there (and in Sefer Orach Chayyim) he sided to permit, and it is in Maharil that once the ruler decreed they should not play with musical instruments and he commanded to bring bridegroom and bride to another city to make the wedding there in order to play with musical instruments. And Radbaz part 1 siman 332 wrote that in his land they were accustomed to forbid telling a gentile to play, nevertheless if the gentile came and played on his own they do not protest him, and by law it is permitted to tell him on erev Shabbat that he play on Shabbat since the Israelite himself is forbidden only on account of a decree, and if there is concern for evasion one should make a fence also in this. Knesset HaGedolah see there`,
  "4:_": `Regarding clapping. Explanation: since we are not expert in making musical instruments, by law it would be permitted to play with musical instruments, therefore in any case speech to a gentile is permitted, and in any case forbidden to tell a gentile to repair the musical instrument, as was stated. Magen Avraham`,
  "5:_": `And throw. For Rosh Hashana to drive away birds — Rashi. And it is possible that in our time, when there is no Rosh Hashana, it is permitted to pat, for it is a decree for a decree. Magen Avraham`,
  "6:_": `Fairly and unfairly. Meaning "even" or "odd" in German`,
  "7:_": `To cover them. And Rashal ruled that it is forbidden to cover them`,
  "8:_": `To move it. And specifically when he placed it in a place where it is repulsive to him, as is written siman 308 seifim 136–137. Magen Avraham`,
};
