export const t = {
  "5:א": `Twilight. See Magen Avraham who raised that if he was born a quarter-hour before nightfall it is a safek, and if born before that they circumcise on the sixth day; and if born on Shabbat a quarter-hour before night they circumcise on Shabbat erev Shabbat; and in Radbaz siman 282 he wrote: an infant born on erev Shabbat after sunset of the sun before three medium stars appeared — if the matter is doubtful whether he was born before the end of sunset or after the end of sunset and before three stars appeared — since there are three doubts, it is deferred to the tenth [day] erev Shabbat; and see at the end of Sefer Darkei Noam, large pamphlet from Milchamot Mitzvah, with all details of laws and many distinctions at length. And see in responsa Bach siman 154. And Maharam Schick siman 41:`,
  "5:ב": `When he is already circumcised. Requires study why they do not practice now to examine afterward. And it appears to me as Bach wrote in Yoreh De'ah siman 264 that one must see him circumcised even not at the time of erection on erev Shabbat; and likewise if he was not seen circumcised not at the time of erection — they circumcise on Shabbat. And requires study whether one may rely on this to desecrate severe Shabbat (Magen Avraham). (And see in Shach Yoreh De'ah end of siman 264 and see Yoreh De'ah siman 263 that if there is a pressed foreskin, meaning the skin is very stuck to the flesh — it overrides Shabbat; and in responsum Mahari Beit siman 89 he wrote that if there are tzitzin impeding the milah — it overrides; and in Agudah chapter R' Eliezer of Milah he wrote: one born circumcised on Shabbat — good to circumcise him on the day after, from which it implies he holds there is no prohibition when circumcising on Shabbat; but requires study, for the gemara is arranged in Shabbos 135 that it does not override Shabbat, and it is a great stretch to explain Agudah on another matter on erev Shabbat; and Rif is in doubt on it, and so Maharil — see in Sefer Eliyah Rabbah):`,
  "6:א": `Scalpel. See what is written in siman 310 s.k. 3 whether one may move the scalpel after milah, and see Magen Avraham:`,
  "6:ב": `He tells a non-Jew. See siman 266 seif 6 regarding the law of carrying out the infant, and see Magen Avraham:`,
  "7:_": `He shall not mix them. Beit Yosef wrote that for other sick people too it is forbidden to mix on erev Shabbat:`,
  "9:_": `And they bathe. And he shall not wring a sheet, for it is like laundering; or a non-Jew puts the sheet into the water; and if the hot water spilled — he tells a non-Jew to bring water heated for the non-Jew, and he shall not tell a non-Jew to heat for him — Beit Yosef wrote in Yoreh De'ah siman 267 in name of Rashbetz that an infant who was ill and was not circumcised at its time and recovered — they do not circumcise him on the fifth day, lest they need to desecrate Shabbat on the third day of his milah; and also on the sixth day they practice prohibition on erev Shabbat; and see there Shach and Taz; and see in Knesset HaGedolah. And Magen Avraham wrote: and it appears to me that in our time when they do not bathe him — there is no concern for this, for it is not common at all that they would desecrate Shabbat for him; therefore one should not be lax in a mitzvah matter on erev Shabbat:`,
  "10:_": `He shall not circumcise. And it appears to me that likewise if he circumcised but never performed priyah — forbidden to perform priyah on Shabbat; and one reason for them — Magen Avraham. And see in responsum Chatam Sofer siman 158. A mohel who comes to circumcise on Shabbat and says he already circumcised once on a weekday — he is believed and need not bring proof. Shemuel is believed siman 19. And see in Yoreh De'ah siman 266 that two mohalim should not circumcise one milah on Shabbat — one circumcises and one performs priyah — rather the one who circumcises himself performs priyah; and see there Taz s.k. 11. And they practice according to the ruling of Shulchan Aruch; and see Dvar Shemuel siman 64:`,
};
