export const t = {
  "1:א": `ten deep, etc. For at this measure it becomes a domain for itself and is karmelit even in a courtyard; but if it is not ten deep or not four wide it is not karmelit and is like a domain standing there — if in reshus harabbim it is reshus harabbim, and if in reshus hayachid it is reshus hayachid.`,
  "1:ב": `partition. But the partitions of the courtyard that are suspended and pass over it do not help, since they were not made for the sake of water — Rashi; and see Magen Avraham.`,
  "1:ג": `sunk. To distinguish between water outside which is karmelit and water inside.`,
  "1:ד": `in the middle. Meaning at the side of entrance and side of exit he made a partition the width of an amah, except he did not make the partition on the entrance side all in one piece but in two pieces, for in the middle of the partition he left open space; and similarly on the exit side partition; and he did so so that at that open place the water flows; if that open place is not three by three it is lavud — see Taz.`,
  "2:א": `to draw. Even though it is ten deep and four wide, since it entered the courtyard and does not exit from it, it is like a pit in the courtyard and the partitions of the courtyard permit it; unlike a water channel that enters and exits and divides a domain for itself and is karmelit — Raavad and Ritva; see Beit Yosef and Taz.`,
  "2:ב": `in the courtyard. For sometimes the water sinks and the partition is visible; but in the house the partitions are not visible.`,
  "2:ג": `in the courtyard. Meaning it is forbidden to carry in the courtyard; and if the tongue of sea is ten deep it is considered a partition and permitted to carry in the courtyard; but forbidden to draw from it since there is no partition on it between it and the water outside, for it is breached fully and the sea is karmelit — Raavad and Rosh. Taz wrote: in those places where a river is adjacent to courtyards it is obvious that it is forbidden to draw water, for he fills water from karmelit to the courtyard which is reshus hayachid, and an eruv does not help for this; and many stumble in this — end of his words.`,
};
