export const t = {
  "1:א": `That it is excessive bother — see Biur HaGra that for this reason the Mechaber omitted the reason of Tosafos there s.v. mah hu to bring them up, for he holds like the other poskim who did not distinguish between one who designates a place and one who does not designate, for even where he designates a place it is also permitted; nevertheless it is possible that also for the Gra if the place is designated such that no person can enter there — even from reshut harabbim it is forbidden — as Hagahot Ashkenazi holds and Magen Avraham brought; for he himself wrote initially that Shulchan Aruch brought according to Rashi's explanation, and Rashi there itself s.v. hakha implies that he too holds like Hagahot Ashkenazi:`,
  "1:ב": `For this too is not, etc. — And even though there are two d'rabbanan prohibitions here — muktzeh handling and also from karmelit to reshut hayachid — nevertheless human dignity overrides them [Yeshuot Yaakov]:`,
  "4:א": `Clod of earth — see Me'iri that if it is a hard clod like stones that is not fit to crumble — permitted; and therefore the Gemara is precise in saying like Babylonian peelings that are soft:`,
  "4:ב": `Even on a weekday — in the Gemara it states it is a greater novelty on Shabbat erev:`,
  "4:ג": `Due to danger — And that he did not mention the reason lest sorcery dominate him as above siman 3 — because in this seif the law is also included regarding Shabbat and regarding Shabbat the primary reason that one may not wipe with earthenware is due to danger; for due to this it is stated in the Gemara that it is preferable to wipe with a clod even though it is muktzeh rather than wipe with earthenware even though it has the status of a utensil:`,
  "9:א": `In a ploughed field, etc. — see Taz who wrote it is first ploughing and stands for sowing, and he explains Rashi there in the Gemara; and it implies that in an ordinary field not yet ploughed or in second ploughing after sowing we are not concerned about leveling furrows; and although the essence of the prohibition of leveling furrows applies in all cases [and it is not mentioned anywhere in Gemara and poskim what difference this makes] nevertheless they only decreed lest he come to level furrows in a ploughed field; and the reason as Mishna Berurah wrote — in first ploughing furrows are common; and it appears to me this is the intent of Peri Megadim in Mishbetzot Zahav section 3, for otherwise his words are very puzzling:`,
  "9:ב": `And if it was, etc. — see Peri Megadim that in another's field forbidden also in second ploughing after sowing; and in Bava Kamma daf 81b it implies it depends on the fall of dew erev:`,
};
