export const t = {
  "1:_": `(1) That he turn it, etc. And if he was alive at bein hashemashos permitted to move the bed afterward, for it did not become a base (Rosh); and Mordechai permits even if he was dead at bein hashemashos, for the bed did not become a base for the corpse, for he need not place him on it but on the ground (Magen Avraham):`,
  "2:_": `(2) A corpse lying in the sun, etc. Or in a place where the relatives cannot sit with him (Agudah chapter Kirah); Beit Yaakov responsum siman 151 challenged on "some say" that Rama wrote Yoreh De'ah siman 372 that some say a priest is forbidden to guard in a relative's house due to disgrace, for they only permitted for burial need — behold here disgrace of the corpse is stricter than burial, for burial is forbidden on Shabbat and disgrace of the corpse to move him from sun to shade is permitted — end of quote; and there is no difficulty, for moving is only a d'rabbanan prohibition, and even to take out to reshut harabbim as he wrote in seif 2, unlike burial which is a melacha d'oraisa; and even for burial through Kutim there is a distinction between the rabbinic prohibition of burial and the rabbinic prohibition of moving; and further, behold Ramban wrote the reason Magen Avraham brought seif 13 due to honor of the dead lest they say Shabbat was desecrated for him; and for practical law Nekudat Kesef wrote the custom is to guard as Tosafos Nazir wrote: when there is no Jew to move, a priest [moves] from sun to shade; and what Beit Yaakov expanded to challenge there — it does not exist as the examiner will see, and one need not expand:`,
  "3:_": `(3) In that domain, etc. And Bach is lenient to take out from private domain to karmelit, and so Shiltei Giborim wrote in the name of Riaz; and this agrees with "some say" even if it has not yet smelled foul, etc., in seif 2:`,
  "4:_": `(4) [Levushei Serad] And so they did not permit, etc. One must say "and so it appears to me they permitted here," etc. (Levushei Yom Tov); and his words are puzzling, for the words of the gloss as their plain sense are correct that they did not permit through Kutim except in fire or a corpse in a house that smells foul:`,
  "5:_": `(5) [Levushei Serad] But if it smelled foul, etc. It implies permitted even from bed to bed; and in Tur and Bach it is explained forbidden, for they were stricter in moving than in taking out:`,
  "6:_": `(6) [Levushei Serad] However if, etc. And according to the Tur if it is close to smelling foul, even if they have a place to go out permitted to take him out so it will not smell foul (Magen Avraham); and in my humble opinion it is possible he concedes to this that it is forbidden, for they only permitted concern lest it smell foul and they be disgraced when they cannot go out; and so appears from Rama and Levush, for the "some say" mentioned above is the Tur's view, and even so he ruled it forbidden:`,
  "7:_": `(7) [Levushei Serad] Except by means of a loaf, etc. And if there is no loaf forbidden according to the Tur, for they did not permit the prohibition of moving without a loaf (Magen Avraham); and in my humble opinion it is possible the Tur concedes here that it is permitted due to human dignity, and they only said when there is a loaf or infant — whatever can be fixed, they fix:`,
  "8:_": `(8) [Levushei Serad] And some say on the contrary, etc. And the first reasoning appears to me primary, for so Rashba and Ran decided, and so ruled in Sefer Tzeda LaDerech and Sefer Zichron to the Gaon R' Yosef Cohen:`,
  "9:_": `(9) And some permit, etc. Bach wondered on Shulchan Aruch, for Rambam and Tur themselves conclude Ra'ah forbids — end of quote; and in truth so is the law, and so Rabbenu Yerucham ruled Netiv 28, and so appears in Shibolei HaLeket that he brought; and nevertheless it appears to me Shulchan Aruch's view is that since some say that for us who have no reshut harabbim one may rely to be lenient — and it is simple that for one who forbids it is forbidden also without an infant; and greater still Perishah wrote that also Rambam did not permit except by means of an infant, for we say the corpse is secondary to the infant — requires study:`,
};
