export const t = {
  "1:_": `(1) And even wheat, etc. See siman 311 seif 8 and 336 seif 6:`,
  "2:_": `(2) [Levushei Serad] Some say, etc. So Rama wrote, except he wrote "some say" without vav — implies possibly the first reasoning also agrees to this:`,
  "3:_": `(3) [Levushei Serad] But in attached [produce], etc. The same law applies to nolad (Knesset HaGedolah), and so implied siman 517:`,
  "4:_": `(4) A thing that spoiled, etc. Such as dried fig and raisins that were fit at bein hashemashos and spoiled today when rain fell on them and became repaired when the sun dried them:`,
  "5:_": `(5) [Levushei Serad] Since it was muktzeh, etc. Specifically things completed by heaven, such as dried fig that are completed only by sun; but a thing completed by man, such as dates with water on erev Shabbat that are not ready until Shabbat night when they acquired wine taste — permitted; see Beit Yosef:`,
  "6:_": `(6) [Levushei Serad] And further possible, etc. So Terumat HaDeshen wrote siman 67; requires study from touching a corpse in siman 311 seif 7 which is for the corpse's need; see Ramban chapter Shoel mishnah 5 — requires study; and practically it seems siman 308 seif 5 that even touching for muktzeh need is permitted; and so Magen Avraham beginning siman 513; see end siman 265:`,
  "7:_": `(7) [Levushei Serad] Whether for its body, etc. Similar to extinguished candle I wrote siman 279 that all poskim hold even for its body, etc. forbidden, unlike Hagahot Ashiri who permitted (Beit Yosef); requires study, for above Beit Yosef cited Hagahot Ashiri on candle that it is forbidden; see what I wrote there seif kaf 5; and on Perishah who copied Beit Yosef's words unlike Hagahot Ashiri who permitted extinguished candle for its body — you must say more [that he wrote] upon it even if it was not on it at bein hashemashos; deals where gentile or child placed intentionally for Jew; if forgetting — shake; see siman 309 seif 4:`,
  "8:_": `(8) However for its body, etc. So Beit Yosef wrote; Magen Avraham disagrees — forbidden even for its body; Perishah similarly compared to muktzeh due to monetary loss who is particular on it; see beginning siman 308; he challenged Beit Yosef himself end siman 309 what Tashbetz wrote: if pocket on corner — forbidden to wear on Shabbat — end of his words; possibly even without coins inside it deals according to Rabbenu Tam on bed designated for coins — necessarily like wearing it is for its body and place as Levush wrote; therefore sewn pocket — and harder on what Magen Avraham seif kaf 6 on pocket wrote permitted to place thing inside and take — for its place permitted even for Ra'ash since not particular; see Bach seif 8 siman 266 — Tashbetz held garment secondary to coins, see there; it seems Beit Yosef end siman 309 was omitted; and practically it appears to me the general rule: whether bed or pocket, even designated for coins — all that is not particular to place other things in it — permitted for body and place:`,
  "9:_": `(9) [Levushei Serad] Or move, etc. This he added himself; in Beit Yosef and Rama they mentioned only lest it come out; if so for us without public domain permission — lenient for need; and obvious if possible to shake coins — shake, for it deals on Shabbat:`,
};
