export const t = {
  "1:_": `[1] In the special vessel, etc. The explanation is that they measure and sell with it:`,
  "2:_": `[2] [Levush] But I have not seen, etc. And in Hagahot Ashiri he wrote that they are accustomed to place a ring or a thing that is not muktzeh in the measure:`,
  "3:_": `[3] [Levush] There, measure, etc. Yam Shel Shlomo and Shelah were stringent about this to admonish the people in this, and likewise Taz; and I say there are several reasons to be lenient as written in seif 7; and even one who fears Heaven should be stringent in this — nevertheless the people have whom to rely on; one should not say the expression "sell to me" (Shelat Gibborim):`,
  "4:_": `[4] [Levush] Such as if he says a kav, etc. And according to this what he wrote afterward "but in any case permitted" — it is permitted to mention the name of a measure if he does not mention the amount he already had; and so it appears to me is Rama's explanation, and the reason is as he concluded: since their measure and sale-price are known; but Olat Shabbat explained that it deals with one who says "fill this vessel for me," but to mention the name of a measure is forbidden — and Nachalat Tzvi ruled likewise, and I did not delve to the end of their minds; and what Nachalat Tzvi wrote that Bach explained thus — he did not examine closely, for Bach explained thus in Tur because it appears to him there is no distinction whether sale-price is known — but for Rama certainly permitted; again the book Magen Avraham was printed and wrote thus explicitly in name of Darkei Moshe:`,
  "5:_": `[5] [Levush] In the measure of wet goods, etc. Rama did not mention salt and dry goods; and in truth now also in liquids their measure and sale-price are known, and Rambam wrote likewise, and on this the world relied to be lenient; and Taz expanded to wonder from the gemara that one should not mention the name of a measure — implying that as soon as one mentions the name of a measure it is forbidden; and it appears to me there is no difficulty, for one may say it deals when one's measure and sale-price are not known; also other proofs can be pushed aside; and nevertheless one who fears Heaven should be stringent as above; and see siman 504 s.k. 31:`,
  "6:_": `[6] And even if not. This is Olat Shabbat's language; so wrote Tur; but Ran wrote: he should not bring them in a basket to give three or four, but he brings them on his shoulder — one or two; from his words it implies specifically in order to lighten the burden he may do so — until here; and he did not examine closely that Tur in siman 571 also wrote like Ran; rather it appears to me thus is his explanation: where it is possible to change in order to lighten the burden — he should do so; and where it is impossible to change, such as barrels or a bag full of fruits — he changes as he wrote there seif 10 that their way is to carry on the shoulder — he carries them before him; their intent is as I wrote; and similar where he changes, etc.; and with this is also resolved what he wondered at the end of siman 571 — examine this:`,
  "7:_": `[7] And some say, etc. This is from Tosafos at the beginning of chapter HaMevi; and it is explained there specifically in a house where they do not see; but outside in a place where carrying is permitted and people see — forbidden; and so wrote in Sefer Avodat HaKodesh:`,
  "8:_": `[8] For the need of the day, etc. It implies that even on Shabbat night it is permitted to rinse for the need of the morning meal or also for the third meal. And Rokeach wrote: they rinse ten cups so that if he needs one he drinks:`,
  "9:_": `[9] All day, etc. And if it is clear to him that he will not drink anymore — forbidden (Maharil):`,
  "10:_": `[10] And some forbid, etc. Bach's view: even for the need of Shabbat it is forbidden to immerse — unlike Levush (Olat Shabbat); and I wonder, for from Levush too it is clear thus, and he did not permit for the need of Shabbat except at twilight as above siman 261:`,
};
