export const t = {
  "1:_": `[1] [Levush] In all clapping etc. — it implies specifically in clapping and dancing they are lenient and not in rattling nuts and other matters; and so it is possible to explain the words of Rama; and so Taz wrote in Yoreh De'ah siman 282; and see above at the beginning of siman 338; and even in clapping and dancing not in a place of mitzvah Yam Shel Shlomo wrote one should not permit except because of "leave them":`,
  "2:_": `[2] One does not judge etc. — one does not arrange sessions of claims on Shabbat etc. one should not cancel the tamid unless to accept regarding a claim of virginity or a claim of the community (Acharonim). Yerushalmi: "in all your dwellings" — from here for courts not to judge on Shabbat (Sefer HaChinuch parashat Vayakhel); and to Magen Avraham this was omitted and the reason in Sefer HaChinuch is that Hashem wanted to honor this day that everyone find rest on it, also sinners and those liable — parable to a great king who called the people of the country one day for a feast etc.:`,
  "3:_": `[3] And one does not separate etc. — for this resembles dedicating those fruits he separated; and furthermore it helps that it is like fixing; and if he separated its law is like cooking on Shabbat in siman 318; and in any case he fixed the fruits (Rambam chapter 23); and see siman 322 s.k. 12; l'chatchila one should be very careful because several transgressions come from this (Magen Avraham):`,
  "4:_": `[4] He should not have etc. — Olat Shabbat wrote and it appears according to Rama who permitted to bring a virgin to the chuppah on Shabbat for one who has no wife and children — the same law permits him to have intercourse with a widow on Shabbat; and requires study for practice since there is danger as Maharil wrote — until here. And it is not correct that Rama and Levush permitted in chuppah except because of great human dignity and because of loss of the feast, as Rama wrote in responsum siman 125; and see siman 424:`,
  "5:_": `[5] [Levush] They seclude etc. — specifically after the chuppah, for before the chuppah it does not help and it is also forbidden for betrothed man and betrothed woman to seclude (Meshech Binyamin). Furthermore there they wrote one requires only seclusion for complete intercourse but he should not yet have intercourse; furthermore there that some communities practice to seclude even a bachelor marrying a widow because some question that our chuppah does not acquire even in a virgin — and so it is correct — until here; and this deals with a place where they have intercourse first on Shabbat in siman 280. Maharil wrote: if immersion of a widow falls on Shabbat night she should not immerse also at Motzei Shabbat and should wait until the second night; and Chelkas Mechokek siman 60 permits to immerse and to have intercourse because even handing over by the father to the husband's agents acquires; and his words do not appear as explained in Meshech Binyamin there; and so Magen Avraham challenged him. And it appears if her immersion falls on Motzei Shabbat she is permitted — and so ruled my grandfather of blessed memory; and to bring her in on erev Shabbat when she is impure is also permitted for he does not have intercourse with her on Shabbat:`,
  "6:_": `[6] To float etc. — specifically in a river; but in a vessel it is permitted as was explained in seif 2 (Bach):`,
  "7:_": `[7] Tied etc. — and it must be that a tie at one end is in the boat and the other on dry land (Binyamin Zev). One person had a large debt with a gentile and it became known he is ill — forbidden to rent him a small boat to go to him because the harm is not certain lest he not die or lest he command to pay (R' Yosef Levi 32); and Magen Avraham wrote that even if the harm is certain it is forbidden, for even for a mitzvah matter it is forbidden in siman 513 seif 6:`,
};
