export const t = {
  "1:_": "And they desecrate, etc. Therefore when she reaches the ninth month she should prepare everything from erev Shabbat (Sefer Chassidim).",
  "2:_": "[Levush] And even if the women, etc. It requires study — for they need to kindle a lamp to see what she needs (Magen Avraham); and as the Levush settled — there is no need to see; also what he asked — they will say in her presence that they kindled the lamp and she will be settled — is not difficult at all, for when they do for her what she needs she will sense from the handling.",
  "3:_": "[ג] Vessel, etc. Even oil she should bring in a tied vessel and not place oil in her hair and squeeze afterward (Beit Yosef).",
  "4:_": "[ד] [Levush] Who observe, etc. Therefore they deliver Karaites since they observe Shabbat (Knesset HaGedolah); and it appears specifically in a matter without Shabbat desecration — such as when she sits on the birth-stool, for the fetus was already uprooted to emerge, for before that he is liable for uprooting something from its growth.",
  "5:_": "[ה] To desecrate, etc. Specifically in matters that can be done here without delay; but regarding calling a skilled midwife from when she feels somewhat, even in doubt, it is permitted to call her (Taz).",
  "6:_": "[ו] All three days, etc. And we do not count from hour to hour as written siman 317 (Magen Avraham); and from Issur VeHeter HaAroch beginning general rule 59 it does not imply so; and below it will be explained.",
  "7:_": "[ז] [Levush] If it appears, etc. It implies that presumptively they do not desecrate; and from Shulchan Aruch it does not imply so; and perhaps the Levush wrote only to exclude also her friends — we say she does not need and they do not desecrate; but when her friends do not know they desecrate; and so Nachalat Tzvi; and likewise when her friends say she does not need and she is silent they desecrate; and so Bach ruled.",
  "8:_": "[ח] [Levush] Presumptively they desecrate, etc. Even if her friends do not know; but when they say she does not need they do not desecrate since she is silent; and when she says she does not need and a doctor says they need to — they do not desecrate — so Bach wrote; and in Shiltei HaGibborim chapter Mefanin he is uncertain also in this; therefore one should be lenient; and so it appears in responsum of Radbaz siman 66 that they desecrate; and greater than this it appears to me that even if she eats ordinary people's food we say she is not aware at the moment; and though Rashba in Beit Yosef wrote on the law that within three days — perhaps the act was so; and further Bach brings clear proof from Eruvin daf 68 — perhaps she is out of her mind — meaning she does not know what she eats; and there it was after three as Taz wrote; and in truth Taz was not precise — for Rashi explained there it deals even after seven, and they warmed through Kutim; and what Taz wrote when her mind is clear it helps if she eats cold — is not implied in the gemara; and so Bach and Ran in the name of Ramban chapter Mefanin — rather in all women they permit from this reason. And it is obvious that if the woman in childbirth is sick even after seven she is no worse than any other sick person.",
  "9:_": "[ט] For woman in childbirth, etc. And for a sick person through Kutim it is permitted even without danger if he needs a bonfire; and if there is danger if he says he needs it it is permitted even through an Israelite when impossible through Kutim (Bach).",
  "10:_": "[י] Doubt, etc. Olas Shabbat asked: behold doubt of life-threatening danger is resolved leniently as above seif 5; and he answered that here it deals with matters that are only the infant's distress; but in a place of danger even in doubt of seven months they desecrate — until here; and it requires study in Yoreh De'ah siman 266 seif 11 — it implies even in danger they do not desecrate as written in the gemara there; and the essence of his wonder appears to me: since hair was not completed, presumption is that he is an eight-month infant; and see siman 331 seif 3; and Magen Avraham answered that above it deals when her months were completed.",
  "11:_": "[יא] Or doubt, etc. Specifically when she immersed and her husband was with her once and left; for if not so it is doubt and permitted; therefore we are accustomed to move any infant (Agudah chapter R' Eliezer). That distresses her, etc. And specifically not into a cup or pot as above siman 328 seif 34.",
};
