export const t = {
  "1:_": `(1) (Levush) And the same applies if not, etc. So the Beit Yosef wrote in the name of Rashi, and it requires study — for Tosafos, s.v. cholkim: since no post of four remained, it is like the beginning of an alleyway and requires a post of four amos. And so it appears from Rabbeinu Yehonatan and the Tur, and so ruled the Bach, Levushei Yom Tov, and Magen Avraham.`,
  "2:_": `(2) That many people do not pass through, etc. Rashi explained: for example, when it is breached toward a filthy place or a place spoiled with mud at openings, and all the more so if ridges of three or four handbreadths thick remained on the face of the breach that are not comfortable to pass through.`,
  "3:_": `(3) To one standing in the alleyway, etc. It requires study — for one standing in the alleyway never sees the side-sections (Magen Avraham). And in the Prisha he wrote that he found in the Tur on parchment: "to one standing in the courtyard."`,
  "4:_": `(4) Visible — not from that, etc. And when there are three between them we do not say lavud (Shulchan Aruch, daf 9).`,
  "5:_": `(5) (Levush) For that case is different, etc. So one must say according to the Beit Yosef like Rashi. But according to the explanation of Chokhmat Shlomo and Tosafos, there is no difficulty, as he wrote in siman 363, seif 13.`,
  "6:_": `(6) Both beneath the beam, etc. So the Shulchan Aruch wrote because the Beit Yosef emended the Tur's words — but he holds the Rosh is like the Rambam who forbids even with a beam. But Levushei Yom Tov wrote that in chapter 1, siman 8, it appears he holds the Rosh permits with a beam — until here. And according to this, there is no need to emend the Tur, and so it appears to me as the main view — for I found in the Agur, siman 745, that he copied the Tur's words for halachah that he holds the Rosh permits. And in our version I also found in Rabbeinu Yerucham, student of the Rosh, daf 94. And Tziyun LaDerech ruled thus, and it is known that Tziyun LaDerech follows the Tur. And so it appears in Shiltai Gibborim. And what the Rosh wrote "and so it is reasonable" appears that he refers to rejecting the Rabbad's first proof and not to the main law — easy to understand. And since later authorities perhaps are lenient thus, we rule thus, especially since I explained that this is the view of the Rosh and Tur. And also since it is a d'rabbanan matter.`,
  "7:_": `(7) (Levush) And if the beam is four wide and fit to receive plaster — for everyone it is permitted, for the opening of the ceiling descends and closes.`,
  "8:_": `(8) Whether open to a karmelit, etc. It implies that in an alleyway, even open to a karmelit, it is forbidden — and even according to us who have no public domain, and even in our tzurat hapetach, since it is very high we have no recognizable distinction.`,
};
