export const t = {
  "1:_": `[1] Or to dwell, etc. — for guards dwell only by day and sleep at night in their houses (Bach):`,
  "2:_": `[2] And their essence, etc. — and the same law applies if they are not ten high where they connect to the tree but in the middle are ten high and made like an arch; and it appears to me that where they are ten high they must be four wide, for otherwise it is karmelit:`,
  "3:_": `[3] That it is not made for dwelling, etc. — and if he filled with straw for dwelling as written siman 358 seif 2, even if he did not plant the tree for that purpose, if the majority of the partition is of straw it is considered enclosed for dwelling (Magen Avraham):`,
  "4:_": `[4] But if it was there, etc. — such is the language of the Tur; but Tosafos and the Rosh did not write to permit except specifically in mats that they spread, for without them everything is reshut ha-yachid from the mats; and even though Beit Yosef wrote that the Rosh's explanation is like Ran — it does not appear to him at all, for behold the Rosh wrote "and they joined two," etc., and these are only to remove the prohibition of residents, not to make reshut ha-yachid; therefore it does not appear to him to rule except like Tosafos and according to the plain words of the Rosh (Levushei Yom Tov); and so agreed Bach, Nachalat Tzvi, and Magen Avraham; and he added that even if it fell on a weekday and was restored and made on Shabbat intentionally it is forbidden:`,
  "5:_": `[5] And they joined together, etc. — behold Taz wondered on Bach who emends "reshut ha-yachid" in place of "reshut ha-rabbim"; if so, what is "and they joined together"; and in my humble opinion it is possible to uphold and explain "and they joined" — the vav is in place of "or," and requires study:`,
  "6:_": `[6] [Levush] And not for dwelling from where, etc. — it is explained that even beneath it one may not carry:`,
  "7:_": `[7] [Levush] So that they not sway, etc. — for they sway without intent; but for a person one need not that he be lying down (Maggid Mishneh chapter 17 of Laws of Shabbos); and presumably even though a person sways, nevertheless since he sways only with intent it is a partition that can stand — and this is not like Magen Avraham who expounded at length unnecessarily; and it appears to me that in siman 363 seif 3 regarding a person, tying is required so that he not lie down and not be ten tefachim high:`,
  "8:_": `[8] [Levush] And people, etc. — even slaves and maidservants (R' Yonasan); and the same applies to minors:`,
  "9:_": `[9] In less than three, etc. — Bach questioned: behold stam a person is an amah wide and it is standing exceeding breach even if there is more than three between them; Magen Avraham answered that the feet are not three tefachim, and even his width is not full, for in the place of his sitting it is an amah — if so he is less than an amah, for an amah in an amah one does not sit:`,
  "10:_": `[10] And he did not know, etc. — intentionally — so wrote Beit Yosef in the name of R' Yonasan; and Taz wondered, for Rav Chisda who makes with his hand is like intentional — see there where he expounded; and he did not look at R' Yonasan himself who resolves this in his own words, that it turned out by his hand — it does not harm us, his intent is to be considered in a partition made intentionally, for behold Rav Chisda did not arrange the people by his hand but they came of themselves, gathered there to wonder at him or to comfort him, until here. Nevertheless the essence appears in the reason of knowing, as wrote Orach Chayyim in the name of Rashba, for all the more so when he knows they will be lenient and treat Shabbos lightly; and so it appears in Avodat HaKodesh; and according to this even in the matter explained in seif 3 that it is permitted intentionally, it is possible here it is forbidden:`,
  "11:_": `[11] And he should not make, etc. — it implies another person makes from them a partition:`,
  "12:_": `[12] He should not stand, etc. — it appears to me that Rambam explained what is challenged in Eruvin 44, "and that of R' Nehemiah" — according to his view Nehemiah knew; but Rashba who permits in this explained like Rashi that those standing knew; and so is the implication of the poskim; and so it appears in siman 394 seif 12; and so is the essence; and Magen Avraham did not address this:`,
};
