export const t = {
  "2:_": "Seif 2, even in a matter. For otherwise it would not enter R' Yosef's mind to permit. Tosafos there.",
  "4:_": "Seif 4, all. As the girsa of the Rif.",
  "7:א": "Seif 7, and they cut — as R' Nissim explained Shabbos 129b; and there 'and R' Nissim said,' etc. — all that is stated, etc.",
  "7:ב": "Unless. As R' Yehuda in Yevamos chapter 2; and it requires study, for from there it implies the halacha is not like R' Yehuda unless she remained thirty days — for we rely on Rashbag alone; and see Even HaEzer siman 4 in Hagahah; and some say specifically, etc., and it is as I wrote that we rely only when both are present, as many do; and the words of Tur and Bach there require study — for in ordinary births there is no view that completion is required; and see below siman 331 seif 3; and Rambam and Shulchan Aruch hold that there they spoke only of a definite eight-month infant as I wrote, but in an ordinary case we rely on Rashbag alone as written in Shabbos 136a that the halacha is like Rashbag in ordinary births; and see Tosafos there and there; and it appears to me that even Tosafos and Rosh have no difficulty except regarding moving him and circumcising him — for circumcision has no prohibition as written there, only because of moving; in that we rely on R' Yehuda alone; and it requires study.",
  "7:ג": "Or doubt. In the gemara 135a and in Tosafos there s.v. ben — he wrote that it is permitted in such a case.",
  "8:_": "Seif 8, and likewise she. Even a definite eight-month infant because of distress, like opening a boil.",
  "9:_": "Seif 9, they straighten. According to Rashi's explanation Shabbos 123a and Rav Sheshet; and so Tosafos there s.v. asovei — that this is not lefofei, for R' Nachman himself permitted there Shabbos 129b; and so Rashi there s.v. melapefin; and therefore it is also not vertebrae of the spine that dislocated one from them — for they taught they only set as written here in Shulchan Aruch, and Rashi and Tosafos there and there did not distinguish between day of birth or afterward; and there 147b s.v. bechumrei Rashi wrote it deals after the day of birth — for if on the day of birth we say there 129 'all that is stated,' etc.; and it must be that Rashi retracted from what he wrote at the end of Mefanin that this was not asovei — for R' Nachman said that on the day of birth even setting is permitted; and so the Rosh at the beginning of chapter Kol HaKelim — asovei is lefofei, and after time, etc.; and at the end of Chavis he also wrote as Rashi there that on the day of birth everything is permitted; if so lefofei is always permitted like Rav Sheshet; and 'they straighten' is specifically setting on the day of birth. Taz, Bach, and Magen Avraham. And Shulchan Aruch chapter as Tosafos and as Rashi explained in chapter 25 and chapter Mefanin — and 'they straighten' is always permitted, for asovei is not lefofei; and this is what is written here 'they straighten,' etc., and in seif 10 'permitted,' etc., and there is no distinction between them; and so it appears in the gemara, for it says asovei and does not contradict lefofei as in other places; and that which they do not set — he did not write at all because he was uncertain — for according to Tosafos there is no distinction between day of birth or afterward, for always forbidden; and for the Rosh on the day of birth permitted; and as Rashi wrote at the end of Chavis; and so Ran; and from Rambam's words who did not distinguish — from this always forbidden like Tosafos; nevertheless even for the Rosh lefofei is permitted, even to straighten limbs — and this is asovei that is permitted forever. Magen Avraham s.k. 19.",
};
