export const t = {
  "1:א": `Seif 1 "one who ties" etc. All is the wording of Rambam and per the Rif's explanation there in the gemara:`,
  "1:ב": `For example. The mishnah and as stated in the gemara "rather a sailor's knot" etc., and from that it says "the sailors" and not "the ships" — learn that it speaks of a craftsman's [knot]; and likewise "the camel-drivers" is camel-drivers and also permanent, as stated in the gemara:`,
  "1:ג": `"And the knots" etc. Gemara in both of them on 112:`,
  "1:ד": `"But." There. Rabbinically and per the Rif's explanation:`,
  "1:ה": `"And some disagree." Per Rashi's and Rosh's explanation:`,
  "1:ו": `And some say etc. permanent. He holds only regarding prohibition; and likewise what he stated "and some are lenient" etc., and Ra'AM, and he learned from that which is stated [regarding] people of Mahoza and a sandal that goes out with two [knots] — specifically on that day, and the first reasoning he learned from that which we say there rabbinically; and he explained in Seder HaTefillah that they change [shoes] every day of the week in their shoes until Shabbos; and see Rashi s.v. "kitra" and s.v. "in Dehumreta":`,
  "1:ז": `"And a knot that is not" etc. For example [the case of] people of Mahoza and sandals that go out with two [knots], per the Rif's explanation:`,
  "1:ח": `"How if it broke." There "a strap broke" etc.:`,
  "1:ט": `"It broke." 113a "a rope of a bucket that broke" etc.:`,
  "1:י": `"Or that he tied." Mishnah there "they tie" etc.:`,
  "1:כ": `"Or that he tied." There "a camel-driver's knot" and specifically of a craftsman as stated above from that it adjoins "the sailors":`,
  "1:ל": `"And likewise all." A shoe and sandal that are exempt:`,
  "1:מ": `And every knot. Beit Yosef wrote that thus [wrote] the Rif, and it is in Dehumreta "their straps"; and it is the mishnah general rule of R' Yosi etc., and therefore of a craftsman; and likewise there "what is a knot" etc. "if we say" etc., and there "you have" etc., and "what is it" etc.:`,
  "1:נ": `"And some say." Per the Rif's and Rambam's explanation:`,
  "1:ס": `That it is two. For otherwise they come [to say] "the knot is" from that which we say there on account of two, and he tied them — and if so, he would be liable for tying; rather [it means] with one knot. R' Eliyahu Mizrachi:`,
  "1:ע": `And the same law applies as stated above, and likewise regarding etc. And it is the mishnah there "and just as he is liable" etc.:`,
  "1:פ": `And nevertheless it appears. That they did not decree shvus in a place of pain, as stated in siman 327 seif 9 see there:`,
  "1:צ": `And that which we require. Like in two stitches there:`,
  "2:א": `Seif 2 "slipped out" etc. Tosefta chapter 12, and Avodah Zarah, and so in our gemara chapter 4 R' Chiyya permitted to return a leather [strap] etc., and Tosafos there s.v. "this one is new," and so too Hagahos Maimoniyos there in the name of the Geonim:`,
  "2:ב": `"And specifically." As stated 122b "lest he drive [it] in" etc. Tosafos:`,
  "3:א": `Seif 3 "even if" already etc. As Rashi stated there s.v. "from its neck." For behold etc. but otherwise not, and see Hagahos Maimoniyos there:`,
  "3:ב": `"And therefore" etc. that there is not. From that which we say on Yom Tov 41b "he permits but not" etc., and Rashi wrote because it is not permanent and nevertheless it does not remove etc.:`,
  "3:ג": `And some permit etc. For there nevertheless the tying stands for permanence, and see Hagahos Maimoniyos that the Rav of Magdeburg challenged on what he stated "what is the difference" etc. "this is joining" etc. — it implies that if the neck-[closure] were joining it would be forbidden; but there is no building in vessels and no demolition in vessels, and he explained the opposite: "this is joining" — meaning joining of a barrel's neck is joining, and its work is already finished, and there is truly no building and demolition in vessels, and there is also no final hammer blow, for its work is already finished; but opening the neck-[closure] is not joining, for it needs opening and one is liable for the final hammer blow. And this is according to Rashi's and Ra'AM's view that there is no building in vessels at all, and one is not liable on vessels except for the final hammer blow; and see above siman 314 and Hagahos Maimoniyos chapter 11 siman 130 in the name of Ra'AM:`,
  "5:_": `Seif 5 "and even." That one knot is nothing, as stated in seif 1:`,
  "6:א": `Seif 6 "one may move." There "Kuvean vessels" etc., and the Rif and Rosh wrote, and we establish it with a rope of a weaver:`,
  "6:ב": `"And we are not concerned." Tur and per Rashi's explanation and per the second wording in Tosafos:`,
};
