export const t = {
  "2:א": `Seif 2 — homeowner who has, etc. Mishnah and Gemara there, for example, etc.`,
  "2:ב": `And he lent them. Rashi.`,
  "2:ג": `Or rented them. Rambam and Hagahot Asheri.`,
  "2:ד": `Due to, etc. The Tur's wording, and as I wrote on this 2 and 8:1 regarding minor matters — hat, cup, etc., and ladder of Tyre and Babylon. And see above siman 372, seif 8 and seif 10.`,
  "2:ה": `Prohibition. There chapter 6:1, Tosefta, etc.`,
  "2:ו": `Even for the sake of. There — tevel and lamp, and they are not carried even, etc., as stated in Shabbos 124:1 — this applies when there is, etc.`,
  "2:ז": `Since they all became, etc., and therefore. As stated in seif 8.`,
  "2:ח": `And if the houses are not. There — for example Bonius, etc. And see Rashi there, and as above.`,
  "2:ט": `And some say. Like brothers in seif 5 — he inferred from what is taught "he does not restrict him" — in the Rif's version, and Rosh and Rashi imply that regarding others he does restrict.`,
  "2:י": `But if. Magen Avraham.`,
  "3:א": `Seif 3 — if the partitions. Gemara there.`,
  "3:ב": `Within three handbreadths. The same applies, and Gemara there 79:1.`,
  "3:ג": `Even if they are, etc. There — according to the first version of those who dispute regarding partitions reaching the ceiling. And it must be that they are of curtains — for otherwise what is "and they agree" as Tosafos wrote there, s.v. b'machitzot.`,
  "3:ד": `If the courtyard residents. Gemara there, and Tosafos explain the distinction — even according to Beit Hillel in such a case.`,
  "3:ה": `And the house. As above in siman 366.`,
  "3:ו": `And similarly if. From the Mishnah of brothers.`,
  "3:ז": `They divided it. From that Mishnah.`,
  "3:ח": `Even if. For otherwise Beit Shammai agree, as stated in the Gemara as above.`,
  "3:ט": `If some of them. Mishnah there: when some of them, etc.`,
  "3:י": `And if there were, etc. From what it asks "obvious" — and see there in Tosafos.`,
  "3:כ": `But one who has. For he is no worse than his tenant and gatherer there 64:1. And see Tosafos there and Magen Avraham.`,
  "4:א": `Seif 4 — courtyard residents. There 72:2 — Mishnah: the brothers, etc., and Gemara: we learn from sleeping place, etc. It implies that if they eat at their father's table literally, all need no eruv — and here he divides three matters that the Mishnah distinguishes when, etc., but, etc., or there are not, etc.`,
  "4:ב": `And similarly if, etc. For the Rambam and Shulchan Aruch copied the Mishnah's wording "at one table," etc. And the Rav wrote: he disagrees — even each at another table, since they are in one house, as stated regarding five groups, etc.`,
  "4:ג": `And even though, etc. There 102:1. And see there Rashi, s.v. ve'ilon — we learn it is not permanent, for a permanent tent restricts. And there 26:1 — clearly, etc.`,
  "5:_": `Seif 5 — therefore the brothers, etc. There — we learn from sleeping place, etc., and as above.`,
  "6:_": `Seif 6 — if there are not. There 73 — obvious, etc. It implies they are all equal with brothers.`,
  "8:א": `Seif 8 — the guest. Tosefta, as stated at the end of 371, and Gemara 69:2.`,
  "8:ב": `Except. Tosefta chapter 5, Ksidra. Until, etc., and Tosafos there, s.v. ushlehem, in the name of the Yerushalmi.`,
  "8:ג": `And he and they. Like nullifying one's domain in siman 380, seif 2. And even. There — five relative to one, etc. It implies regarding guests even in such a case they do not restrict.`,
  "8:ד": `And specifically, etc., but. As above in siman 366, seif 2.`,
};
