export const t = {
  "1:א": `Seif 1, whether dry, etc. — Rambam's language; and Maggid Mishneh wrote he relied on what is written "Rav found in a valley" etc.; and so the Magid.`,
  "1:ב": `And one does not hang, etc. — there.`,
  "1:ג": `Climbed, etc.; and if, etc. — there 30b: here, etc.; and another version, etc.; and Maggid Mishneh explained even if he climbed before Shabbat intentionally to sit there on Shabbat — permitted to descend; and he wrote in every case; but Tur wrote specifically when he intended as written; and some say, etc.`,
  "1:ד": `And specifically, etc.; but. Shabbos 45a; and there 154a — reason of inserting, etc.; Eruvin 32, 33, 34.`,
  "1:ה": `And all this, etc.; but. There 34; and Rashi Shabbos chapter 2 on "and he does not wipe with a pebble" etc.; but Rambam's and Shulchan Aruch's language "one does not use attached" etc.; and see Bach and Taz.`,
  "2:_": `Seif 2, even from one side — unlike two sides per Rabah there.`,
  "3:_": `Seif 3, that water them — Moed Katan 2b — for plowing and sowing.`,
  "4:_": `Seif 4, and if it is — per the Mishnah of Shevi'is 2.`,
  "6:_": `Seif 6, and it is, etc.; and also — see siman 311 seif 8 what is written there.`,
  "8:א": `Seif 8, whether, etc. — Gittin 7b Rashi on "earth of earthenware need not be holed"; Tosafos there on flowerpot wrote the reverse; their proof from what R' Zeira said: holed flowerpot on pegs, etc.; though the boat is not holed; Menachos chapter 4 — flowerpot or flowerpot: here holed, etc.; boat or boat: here wooden boat, etc.; since it does not say boat is also holed — no manner to be holed; even unholed earthenware is like holed; Tosafos there and there wrote reverse; proof from Gittin 21a they wrote on earthen flowerpot holed — implies earthenware requires holed; Shabbos 95b five measures in earthen vessel, holed like a small root — pure from preparing seed; plain flowerpot everywhere is earthenware; they explain reverse: boat is wood therefore no hole needed; see Tosafos Gittin and Menachos; initially Rabbenu Tam was accustomed, etc.; Shabbos chapter 1 — this, etc.; see Rashi on parfisa holed flowerpot, etc.; concern for both explanations; therefore even unholed forbidden whether, etc.; Yerushalmi 40 per Rashi; Rosh brought in laws of Orlah; Tur Yoreh De'ah siman 494 — Yerushalmi Orlah end law 2: one who plants in unholed flowerpot is liable for orlah; R' Yosi said because roots spread; R' Yonah extracts language earthen vessel stands before roots — Rosh there; see Yerushalmi whether also considered holed for seeds; see there; but Rambam chapter 10 wrote perforated; and Noda B'Yehuda and Shulchan Aruch Yoreh De'ah there: plain flowerpot even unholed.`,
  "8:ב": `Branch — 124b.`,
  "11:א": `Seif 11, soaking, etc. — requires study, for in Zevachim 94b they say exempt; and if so even flax seed should be liable for sowing; Rambam and Shulchan Aruch siman 340 seif 12 wrote for kneading; see Gemara there; and so Magen Avraham challenged.`,
  "11:ב": `And permitted — see siman 321 seif 11.`,
  "13:א": `Seif 13, therefore, etc.; but, etc.; and if. Shabbos there.`,
  "13:ב": `And permitted — there 153b; and in gauza, etc.; Sukkah 25b one who makes his sukkah between trees, etc.`,
  "13:ג": `Provided — Shabbos 154a — here in a basket, etc.`,
  "13:ד": `Pit, etc. — Eruvin 100a.`,
  "13:ה": `And we are not concerned, etc. — Tur.`,
};
