export const t = {
  "1:א": `Siman 1 on her head — excluding on her neck as Gemara and seif 2 state.`,
  "1:ב": `And if they are — as stated seif 26.`,
  "1:ג": `And there is — Bach pressed and it appears to me the concern is lest immersion occur etc. therefore loosen erev Shabbat — forbidden Shabbat and permitted; this is what he means until she loosens — no difficulty stam and may not immerse in them — only if he said stam there would be no concern that necessarily he had to permit erev Shabbat. Yoreh Deah siman 198 chapter first kas.`,
  "1:ד": `And if — Yoreh Deah there wrote per Raavad only hollow meshwork as there teichi chalilta.`,
  "1:ה": `Soiled etc. — chapter latter wording per Geonim stringent as one says; Tur likewise; Rambam and Shulchan Aruch ruled first wording because Rav holds first wording.`,
  "1:ו": `When removes — here wrote per Rashi; Yoreh Deah there wrote per Rashi's teachers.`,
  "2:א": `Seif 2 but on katlah — braita there and as Ravina stated.`,
  "2:ב": `Like tzitz measure — Rif.`,
  "2:ג": `And not etc. — and it is also. And it is. Mishnah and Gemara there.`,
  "2:ד": `Lest remove etc. — Gemara there 59b and 65a Abaye said etc. see there.`,
  "2:ה": `And some say — Rashi on mishnah s.v. b'zman etc.`,
  "2:ו": `In braid etc. — Rashi.`,
  "3:א": `Seif 3 and wide — as we say Chullin 138a wool cap on head etc. Rif.`,
  "3:ב": `Tzitz measure — Shabbat 63, Sukkah 5.`,
  "3:ג": `Namely — there kelia peruchi; Rif there explained and his girsa there kelah peruchi.`,
  "4:_": `Seif 4 and Rabbenu Tam — from Sotah why what are brides' crowns of city.`,
  "5:א": `Seif 5 kelilah etc. — as Gemara conclusion and forty not like Rashi s.v. kelilah permitted.`,
  "5:ב": `She places it etc. — Rashi.`,
  "5:ג": `Whether etc. — as above and latter wording and as Rif explained.`,
  "7:_": `Seif 7 on katlah — Taz s.k. 4 in name Tosafot and see there 57b s.v. here.`,
  "8:א": `Seif 8 because — Rashi.`,
  "8:ב": `And in place — see 328 but etc. and Magen Avraham there.`,
  "9:א": `Seif 9 if fastening — per Rashi there s.v. tahorah and Tosafot s.v. since and so from Rosh there on challenge v'tehei k'birit etc. holds like Rashi — need not all Bach's and Taz's and Magen Avraham's presses — see Rosh who wrote more appears to explain etc. and now etc. — meaning per Rashi simple challenge why compare to birit — certainly won't uncover hair; per Tosafot not uncover immediately no question — must challenge from birit as explains per Rashi challenge due uncovering hair; for Tosafot's challenge on Rashi v'tehei — since still tied on one leg anklets not fallen per second answer — only unperforated as Beit Yosef in name poskim see there — and unperforated etc. — Gemara per second answer mishnah fastening hair yet unperforated specifically. Must be as said Shulchan Aruch composite Rashi and Tosafot in Gemara challenge holds like Rashi — if Tosafot view as Taz Magen Avraham even not ornament permitted since fastening — even perforated should permit fastening — unperforated is burden only because fastening — his view like Rosh.`,
  "9:ב": `And if etc. forbidden — is burden as Tosafot s.v. limai; afterward challenges etc.`,
  "9:ג": `Forbidden — only needle she adorns with as wrote gold plate etc.; otherwise liable chatat as s.v. there is burden and her way of carrying — even perforated way of carrying as Tosafot 11b — all the more unperforated as Tosafot s.v. there accustomed to carry etc. as ring 62a sometimes etc. all the more here.`,
  "11:_": `Seif 11 and it is etc. and it is. Gemara there and Rashi.`,
  "12:א": `Seif 12 since it is — wording of Rashi's teachers.`,
  "12:ב": `And all the more — Rosh there; for one view in Rashi on mishnah it is false tooth as mishnah.`,
  "13:א": `Seif 13 since they mock etc. — Rashi.`,
  "13:ב": `And in other — Tosafot 57a s.v. bameh and you asked etc. and one may say etc. as stated but may go out in cloak etc.`,
  "14:_": `Seif 14 elder in child's — girsa Tosafot this and that — all the more this; Rif and Rosh have our girsa.`,
  "15:א": `Seif 15 may go out — 54b and would be like amulet etc. per Rashi s.v. chumarta.`,
  "15:ב": `And tight — Rosh; must be explains not like Rashi — for Rashi both explanations need not tight only explains and teaches ramy etc. why dispute and that doesn't challenge from mishnah — Tosafot Pesachim 102b s.v. mitibi etc.`,
  "15:ג": `Lest fall — Tosafot s.v. uvamokh as siman 301 seif 13.`,
  "15:ד": `Even — Gemara there per Rashi and R' Chananel Gaon; Raavad explains refers to cotton in ear — this is what he means made for herself etc. — no difficulty even — Yerushalmi explicitly there.`,
  "15:ה": `And in all in name etc. — mishnah and Gemara there.`,
  "15:ו": `And provided — Tosafot there whether refers to all those or not; Beit Yosef wrote in Rambam and Rivan 40 like Rif there only on latter end — so from Tur wording since includes with chumarta like expert amulet permitted as Tosafot 57a s.v. bameh — why needed there etc.`,
  "15:ז": `And in ankle houses — learn from birit — likewise Hagahot Maimoniot.`,
  "15:ח": `And may go out etc. — from challenge these etzba'ah tamei but from may go out doesn't challenge.`,
  "15:ט": `And it is — Rambam there; per his view anklets because loose; birit and etzba'ah fixed therefore permits etzba'ah too.`,
  "15:י": `And some — Rashi explains only because remove on leg not uncovering leg see there — not precise — per Rashi even on leg forbidden — only on hair permitted.`,
  "16:_": `Seif 16 in all that — necessarily if remembers etc. as amulet 61a and why needed teach amulet there thought forbidden as seif 26 and provided etc.`,
  "17:_": `Seif 17 some forbid — Yerushalmi brought Rosh 10 story R' Gamliel etc. — meaning in hand on finger — if literally in hand why say this etc. — all ornaments liable chatat if carry in hand as lest remove etc. see Gemara 62b may not go out key in hand etc. even rabbis agree there even gold forbidden as Yerushalmi all permit there and Rosh — all the more iron is burden as siman 301; said even in courtyard as Yerushalmi and second version seif 18 who are forbidders here Ramban and Rashba; in hand permitted as Magen Avraham two songs etc. likewise all vessels etc.`,
  "18:א": `Seif 18 all they forbade — Rav stam tanna like him Rif and Rambam.`,
  "18:ב": `Unjoined courtyard — Rambam per Tosafot there if also joined courtyard forbidden — should have said even in house; certainly decree if permit unjoined will permit erev Shabbat other things forbidden unjoined but joined no need; nevertheless.`,
  "18:ג": `Except — likewise bathhouse seif 3 as Tosafot 57b.`,
  "18:ד": `Namely — Rashi.`,
  "18:ה": `And some say all — Ran and Magen Avraham in name Ramban Rashba explain all courtyard — otherwise what does he say 46b mishnah songs and rings etc. — even wearing permitted; first version unjoined courtyard dwelling there Ran; teaches to exclude R' Nechemiah 124b said in Libni courtyard but etc. per Rashi Eruvin 69a s.v. chumarta; I say etc. they said Moed Katan 12b R' Yehuda Nesiah went out etc. why angry etc. taught songs etc. if per their view even joined forbidden and mishnah in joined — what proof — on contrary forbidden; as Tosafot Eruvin s.v. kiwan and Shabbat 46 s.v. v'amar rather unjoined courtyard; R' Yehudah went in joined and brings proof permitted joined courtyard from permitted carry there as above and Tosafot there their explanation chumarta etc. see there.`,
  "18:ו": `And some say all — explains R' Chanina bar Shason in scribes' tract follow lenient as Avodah Zarah per their view courtyard courtyard unjoined as above.`,
  "18:ז": `Nowadays — there in Tosefta.`,
  "18:ח": `And some said — as 148b and ch. 4 Yevamot 30a and Tosafot Shabbat 55a s.v. v'af al gav and see siman 248.`,
  "18:ט": `And some derived — see 334 seif 10 gloss and some etc. siman 357 seif 3 gloss.`,
  "18:י": `And some further — proof from kelilah per them.`,
  "18:כ": `Nevertheless — refers second version in such case even Rava two admit; plain even courtyard forbidden as Yerushalmi even R' Chanina b'shem only matter without chatat liability but chatat matter even courtyard forbidden Gemara ch. 6 in name R' Yoel — slight proof for Rabbenu Tam unjoined courtyard — can reject.`,
  "18:ל": `And some etc. — for Rabbenu Tam siman 301 seif 9.`,
  "18:מ": `Therefore etc. — Beit Yosef meaning for Beit HaTefutzot there in ornament permitted.`,
  "18:נ": `Nevertheless — meaning even first view as Tosafot s.v. v'af al gav and all views unperforated not fastening not ornament at all liable chatat as seif 9 see there.`,
  "19:א": `Seif 19 requires — 123a.`,
  "19:ב": `Unless — like stone seif 22.`,
  "20:_": `Seif 20 and likewise — there in mishnah.`,
  "21:_": `Seif 21 from inside — Tur girsa error should be except eyes see there ch. 1.`,
  "22:_": `Seif 22 she designated — otherwise forbidden as siman 308 seif 22.`,
  "23:א": `Seif 23 if — Gemara Avodah Zarah 6a.`,
  "23:ב": `If for erev Shabbat — Tur.`,
  "24:א": `Seif 24 and in weight — per R' Meir because Abaye weighs against him.`,
  "24:ב": `And even — there.`,
  "25:_": `Seif 25 and for this reason forbidden to smear — Rashi 94b s.v. v'chein hapokesset; Rambam explains per first explanation wrote may not grow hair of head nor pokess because like building — this is Rashi's first explanation; nevertheless Semag wrote Yerushalmi pokess liable for dyeing Semag explains second explanation; Beit Yosef; likewise Tosafot Moed Katan 9b s.v. pokess; meaning Yerushalmi does not explain our Gemara but mishnah in two explanations above; Yerushalmi disputes Gemara there they said dyes because scribe as Gemara thought.`,
  "26:_": `Seif 26 some forbid — explains there and Shabbat limai chazi; Tosafot explains limai chazi to go out since not ornament nor garment.`,
  "27:א": `Seif 27 forbidden to comb — Niddah 67b woman combs erev Shabbat etc.; She'iltot because cannot comb Shabbat; see Rosh end Niddah Tzedekhi missing Raavad explanation combs large see there.`,
  "27:ב": `Impossible etc. but permitted — Shabbat ch. 1 50b and Rashi there.`,
};
