export const t = {
  "1:א": `Seif 1 planted tree. So explained Rosh:`,
  "1:ב": `Permitted. For not like Rav who holds like R' Yehuda — Shabbos 19b and other places, and see Tosafos there s.v. these etc.:`,
  "1:ג": `That it is muktzeh etc. 157a and as stated at the beginning of the chapter How Do We Roast — wherever Rav Acha and Ravina disagree etc., and see Rif and Rosh chapter 3 of Shabbos there 44a:`,
  "2:א": `Seif 2 there is no food at all. Rambam's wording — that in a thing that has no food there is muktzeh even according to R' Shimon, such as muktzeh because of monetary loss as stated there 157a and in siman 308 seif 1, and likewise a thing that is not a utensil as stated 124a, and even R' Shimon concedes on Shabbos even though he permits on Yom Tov — see Rosh in chapter 4 of Yom Tov seif 12 and Rabbeinu Tam's explanation etc., and R' Shimon permits like everyone etc. there, and like coins on Shabbos 44b that even R' Shimon concedes, and bundles 47a and see Rashi there s.v. permitted and s.v. but, and siman 308 seif 7, and likewise bones and peels as Tosafos stated 143a s.v. bones:`,
  "2:ב": `Detached. According to chapter 3 of Yom Tov 24b and Rashi there s.v. if there is etc.:`,
  "2:ג": `Fit etc. Rashi 45a s.v. there is no muktzeh — that in a thing that is not fit even R' Shimon concedes, like salted fish as stated 128a and see there Tosafos s.v. fish etc., and one could say etc., and siman 308 seif 32, and likewise everything similar:`,
  "2:ד": `Muktzeh for Shabbos. To exclude Yom Tov, for we rule like R' Yehuda:`,
  "2:ה": `That dates etc. Shabbos 19b:`,
  "2:ו": `Permitted etc. on Shabbos. Rambam's wording, and he intended for what Rif wrote at the end of 19 — we find for the rabbis etc. who hold like R' Shimon that there is no muktzeh, and as R' Nachman said a goat for its milk etc. and dates that are being pressed etc., and we do not hold thus here etc. For these matters that are a goat for its milk etc. — on Yom Tov they are forbidden, and matters that are fit to eat from them on Shabbos, such as dates that are being pressed — permitted to eat from them on Shabbos — see there:`,
  "2:ז": `And still. Rashi — that without this he is liable because of uprooting something from its place of growth:`,
  "2:ח": `The bundles. Rashi:`,
  "2:ט": `That they are putrid. Tosafos and Rif and Rosh and Rambam in the name of Yerushalmi:`,
  "2:י": `And since. To exclude wheat etc. and dates etc. that one by one are in them, and as stated there — for R' Shimon has no need etc.:`,
  "2:כ": `Seif 11 that there is not. Meaning — what is forbidden because of this, as stated in Yerushalmi a gentile does not need this, but a thing that is forbidden because of being attached there is no distinction, as stated in chapter 3 of Yom Tov 24b and see Rashi s.v. if there is etc., and likewise everything similar:`,
  "3:א": `Seif 3 between etc. Tosafos 27a s.v. rather. And see above etc. and on Shabbos 43a s.v. while they are. Alternatively etc.:`,
  "3:ב": `But a thing. There in the gemara — this is what it means: if they seized it etc.:`,
  "5:_": `Seif 5 but if. Gemara there:`,
  "6:_": `Seif 6 provided. Yerushalmi, and Rosh brought it in chapter 1 of Yom Tov, and Magen Avraham, and likewise Terumat HaDeshen — and he learned from Tosafos' words that they distinguish regarding moving from the side — thus, and this is what Magen Avraham wrote, and siman 311 seif 8; and I omitted what was written in the previous book regarding permitted to anoint etc., and it is the arranged Mishnah Shabbos 151a — they did not permit a dead person except a loaf and a child because of human dignity as Ran wrote, and from this Mishnah we learn permission to touch muktzeh; and Terumat HaDeshen strained himself to learn from Eruvin chapter 4 1a, and therefore it entered his mind to distinguish, but the essential ruling is as Maggid Mishneh wrote — that he must not shake the egg, and as stated in siman 265 seif 3, and it is forbidden to touch a lamp etc. even though etc. — nevertheless it is forbidden lest etc.:`,
  "7:א": `Seif 7 and even for need. For if from sun to shade even R' Shimon concedes, as Tosafos stated 36a s.v. this R' Shimon, and gemara 142b — they taught only regarding forgetting etc. — meaning only for the need of the object itself etc., 40 — that when placing it is forbidden whether for the need of the object itself or for the need of its place, and likewise there 1a Mishnah for the need of the object itself, braita for the need of its place, and specifically when there is also a permitted matter, but without this it is forbidden — and see Tosafos 44b s.v. this that this one does not drag etc.:`,
  "7:ב": `And the same law applies to everything. There regarding a barrel and a basket and a basket before chicks 43a:`,
  "7:ג": `But if etc. even if he designated it etc. There — not like Rav, for he holds like R' Yehuda as stated above, unlike at the beginning where we rule like R' Yehuda in this, as stated 157a:`,
  "7:ד": `And there are those who forbid. Tosafos there s.v. this in the name of Rabbeinu Tam, as stated 123a — all agree etc., and meaning even R' Shimon as stated 157a, and he proved thus from what we say 128a that in muktzeh of moving Rav holds like R' Shimon. Rosh. And meaning in muktzeh that a person designates from his mind, for there it says and Rav holds like R' Yehuda, and even in muktzeh of moving — and see Tosafos 19b s.v. these:`,
  "7:ה": `Unless he performed an act with it. For it nullifies the thought of designation, and likewise the act, as stated at the end of chapter 25 of Kelim, and specifically he performed an act with it as stated there:`,
  "7:ו": `However. Magen Avraham and Hagahot R' Akiva Eiger wrote according to Rif there — that from sun to shade even for the first time it is forbidden:`,
  "7:ז": `And likewise in a pouch. 44b Tosafos s.v. one does not drag etc.:`,
  "7:ח": `Permitted to move etc. As above:`,
  "7:ט": `But one may not wear it etc. For one who goes out with bundled coins in his garment is liable, and everything forbidden to go out with is forbidden even in the house to wear, as stated 64b, and a person — anything that is a burden, and as stated in siman 303 seif 18 — see there:`,
  "8:א": `Seif 8 such as a coal pan. Rashi there:`,
  "8:ב": `And the reason for permission etc. and if not needed etc. 142a — and let them fall etc.:`,
  "8:ג": `Or if. There in the braita for the need of establishing it:`,
  "8:ד": `And if. There Mishnah for the need of the object itself:`,
  "8:ה": `And likewise if. There — the reading "and to shake them" — shake:`,
  "8:ו": `And all this not so etc. There 2b — and they did not say a loaf etc., and see there in Rosh:`,
  "9:_": `Seif 9 a box. We learn from the above:`,
};
