export const t = {
  "1:א": `Seif 1 "From pursuing." Shabbat 150a and 113a; and see Rashi there s.v. mimetza.`,
  "1:ב": `Examines etc. Or. Eruvin 38 and 39.`,
  "1:ג": `And likewise. We learn from the above.`,
  "3:א": `Seif 3 and he may tell. There in the braita "one may wait at dusk to supervise" etc. — meaning he tells his fellow to supervise, and as stated "and they tell him" etc.`,
  "3:ב": `Tomorrow. See there Tosafot s.v. le'olam.`,
  "3:ג": `And if impossible. 150a.`,
  "3:ד": `And some forbid. For it is permitted only when there is a matter permitted in reshut ha'rabbim, such as "go" etc. — if there were watchmen etc.; but otherwise forbidden, for a gentile who brought flutes is forbidden. Ran and see Magen Avraham.`,
  "4:א": `Seif 4 and he should not say. Tosefta end of Shabbat at the conclusion of the braita "one who hires" etc. "and he should not say" etc. but "give me wages for ten days" — and likewise for weekly hire.`,
  "4:ב": `And if he hired him. So explicitly there in Mordechai who said it appears like Shabbat wages even though he pays in absorption since a day is added day by day.`,
  "5:א": `Seif 5 forbidden. As in the preceding book.`,
  "5:ב": `And some. As stated in seif 6 and as stated Pesachim 50b that it appears like Shabbat wages.`,
  "5:ג": `And if he hired them. See Magen Avraham and as stated in seif 4.`,
  "6:_": `Seif 6 and specifically. As above in seif 3.`,
  "7:א": `Seif 7 permitted. 157a, 2b.`,
  "7:ב": `Such as. Rambam in his explanation there.`,
  "7:ג": `And to whisper etc. As stated above siman 328 note 45; and Yerushalmi ch. 14 of Shabbat halacha 3 — they whisper for the eye, bowels, snakes, and scorpions, and pass over the eye on Shabbat.`,
  "7:ד": `And nevertheless etc. Mekhilta parashat Yitro: "Six days you shall work and do all your melacha" — is it possible for a person to do all his melacha in six days? Rather Shabbat comes as if all your melacha is done.`,
  "9:א": `Seif 9 forbidden. For even a gentile who brought flutes is forbidden.`,
  "9:ב": `But a sick person etc. As stated in the chapter "One who became ill" they acquire for him on Shabbat etc.; and see Tosafot there.`,
  "11:א": `Seif 11 for it is not forbidden. And it is shevut di-shevut as stated regarding milah that they permitted only shevut di-shevut; and as stated siman 307 seif 5.`,
  "11:ב": `And because of. Gemara there.`,
  "12:א": `Seif 12 permitted. To announce — for matters of Heaven and it is a mitzvah matter.`,
  "12:ב": `Since it is. See Magen Avraham; and in Beit David he wrote in the name of R' Yehuda etc.; and as stated 157a they release vows even not for Shabbat need — see there.`,
  "12:ג": `But. There like "they are asked about vows" etc.`,
  "13:_": `Seif 13 to announce etc. and if not. Specifically in such a case it is forbidden for it is like a decision; but otherwise permitted as with the Sicarii who said in Yerushalmi they would announce on the twelfth month four Shabbatot; and likewise a rebellious wife in "Even though" in the Gemara; and Rivash wrote therefore they would send to her before the announcement from weekday and they did not say so within the announcement — she would know etc. — for in such a case it is forbidden.`,
  "14:א": `Seif 14 one to whom they sent etc. Tosafot Shabbat 4a s.v. vechi etc.; and that which was taught etc. this case is different etc.; and one can say etc.; and like both resolutions of Tosafot — and it is permitted only without negligence and a great mitzvah; therefore he said specifically that they took her out, and specifically in such a case — unlike siman 328 seif 10 where even though it is a great transgression nevertheless they do not desecrate Shabbat for her, for there is no mitzvah greater than keeping Shabbat — unlike this case to bring her into the Jewish people. Behold Rashba in a responsum forbids and wrote they permit only where the prohibition was done through him, as in ch. 3 of Eruvin — and these are the beginning of Tosafot Shabbat's words; but Tosafot conclude there that for a great mitzvah it is permitted as above; and in the second version they wrote where there was no negligence it is permitted. Rashba follows his view that he wrote in his novellae there, first version of Tosafot that a great mitzvah is different, and wrote "it appears to me" etc. half-freed slave has no concern of "you shall serve" because of the aspect of freedom in him; and that of a maidservant half-freed through whom a prohibition was done — there since many stumble it is certainly a public mitzvah, different as stated explicitly in "The sender" and ch. 3 "they ate." Behold the Mechaber ruled like Tosafot as above; see siman 328 seif 10 in the gloss where he forbids there — this works as above; and Avodah Zarah and Taz and Magen Avraham elaborated on this.`,
  "14:ב": `They coerce him. As there.`,
};
