export const t = {
  "1:א": `Siman 61 — from the Torah. 6a:`,
  "1:ב": `And throwing and passing. 96a, 6a, 99b etc.:`,
  "1:ג": `And the Sages. There:`,
  "1:ד": `But one standing etc. And not like Ben Azai; and likewise the anonymous Mishnah 91b is not like him; and in the last chapter the Gemara is strained regarding a long threshold and "others say" etc. — investigate etc.; and they did not immediately establish it like Ben Azai; and that which R' Yochanan said and Ben Azai agrees regarding throwing — not that he holds like him, for Rabbah also holds not like him as written in Kesubos 31 and as Tosafos wrote there — see there:`,
  "1:ה": `Some forbid. As Rabbina wrote Eruvin chapter 7b and like R' Yochanan 76a and there 101b:`,
  "1:ו": `And some permit. As the first answer — except at the sides — and like R' Yochanan, Abaye, R' Chanina, and R' Ashi — all hold like the first answer; and Shabbat 101a and see Rashi s.v. "but" etc. and Tosafos s.v. "R' Yochanan" etc.; and it is difficult etc.:`,
  "2:א": `Siman 62 — from the Torah. 96b:`,
  "2:ב": `And the Sages. 6a:`,
  "2:ג": `And permitted. 8b it is, and its eruv in karmelit — Eruvin 67b, 101b, 90a — two etc.:`,
  "3:א": `Siman 63 — and therefore. Tosafos there s.v. "and what" etc.:`,
  "3:ב": `Provided. 101b — and if it has four etc.:`,
  "3:ג": `Or if there are. Meaning the door is one partition and another partition from the side — unlike those opposite each other as written siman 361 seif 2 in the gloss and we say etc.:`,
  "3:ד": `That they are. For with less than four even four complete partitions are not reshut ha-yachid as written in Shabbat from the leniencies of reshut ha-yachid etc.; and as we wrote siman 345 seif 9; and likewise the partitions etc.:`,
  "3:ה": `And a lintel etc. As written siman 361 there in the gloss; and some say etc.:`,
  "3:ו": `And even if. Meaning it is makom patur as we wrote seif 9:`,
  "3:ז": `Since. Meaning it applies specifically when it is three high; but without three, in any case it is like the domain before it for it is not makom patur as we wrote there; but it is not so since it has three partitions it is not reshut ha-rabbim and also not karmelit as we wrote there seif 9 and likewise the partitions; and even according to Rambam that with three partitions it is not reshut ha-yachid — nevertheless here it is not karmelit since it is less than four; and Tosafos Shabbat 9a s.v. "even though"; and it deals where they stand etc.; and there s.v. "within" etc.; and if you ask etc.; and one may say etc.:`,
  "3:ח": `And likewise if. As we wrote siman 345 seif 14 — and reshut ha-rabbim that is roofed:`,
  "3:ט": `And likewise our roofs. Meaning even if there are partitions, "the edge of the ceiling" is impossible since it is sloped as written siman 361 seif 2; and it is etc.; and even if the partitions are four wide as written siman 345 seif 14 and corner projections etc.; and as Tosafos wrote there s.v. "even though"; or one may say it is considered outside etc.:`,
};
