export const t = {
  "1:א": `Seif 1 "permitted." It is according to Rava at the end; Rosh and Rambam, not like the Ri'f:`,
  "1:ב": `And this is [so]. As is stated "fill this vessel for me" — it is in the measure of the buyer, and likewise in the measure of the seller, as is stated [in the commentaries], people are accustomed etc.:`,
  "1:ג": `But to measure. As is stated in the mishnah that he would fill his measures from erev Yom Tov etc. Ran:`,
  "1:ד": `And there are [who disagree]. As is stated regarding R' Yehuda that he should not fill it, and the same applies to us in such a case:`,
  "2:א": `Seif 2 "permitted." Yerushalmi: R' Elazar said to R' Mana, "Fill this vessel for me," and tomorrow we will measure it:`,
  "2:ב": `But. Gemara there:`,
  "4:א": `Seif 4 "there — money." According to the textual reading of the Ri'f in [the view of] the first Tanna: sum of purchase; and as the Ran wrote, the wording is not "sum"; and as is stated, neither of these two may one stipulate — one may not fix a price etc.; and as Rashi wrote s.v. "sum of purchase," money; and Tosafos wrote there s.v. "that not." And it is difficult etc.:`,
  "4:ב": `And not the sum of a measure. According to the textual reading of Rashi in the words of the first Tanna: sum of a number:`,
  "4:ג": `And not the sum of a number. According to the textual reading of R' Chananel in [the view of] the first Tanna: sum of a number — to say "behold" etc. Tosafos there, and the Tur cited all the explanations to be stringent, and so too the Rosh; and it appears to me there is a printing error in the Shulchan Aruch and it should read there "measure," and as Rashi wrote s.v. "sum of measure" etc.; and so too the Rambam that he should not mention to him the name of a measure nor the sum of a number; and so too the Tur above: it is forbidden to mention to him the name of a measure etc.; and as Rava stated in the gemara; and so it appears from his concluding to say "behold" etc., and not so regarding a measure:`,
  "4:ד": `And likewise regarding the sum of money. Beer HaGolah — they explain "sum of purchase" as is stated regarding sum of a number:`,
  "4:ה": `And likewise regarding the sum of a measure. So too Darkei Moshe, and he learned from the words of Beer HaGolah that the same applies to sum of a measure:`,
  "4:ו": `And even though. As is stated, one may not fix [a price] etc., as above:`,
  "4:ז": `That is etc. For an animal — its purchase price is not known; Beer HaGolah there, and Darkei Moshe learned similarly regarding a measure, for he writes there also in such a case:`,
  "5:א": `And the like of this. There in the gemara Rava enacted etc.:`,
  "5:ב": `Even if there are not. Rashi there s.v. "that they dwell in the storage attic" etc.:`,
  "5:ג": `For example. Rashi:`,
  "5:ד": `And some say. As is stated in Shabbos 127a, and Tosafos distinguished in chapter 4 of Yom Tov between Shabbos and Yom Tov — that on Shabbos, since one does not move except from one storage nook to another, it is permitted and is not like a weekday matter; and therefore to minimize carrying it is preferable, unlike on Yom Tov where one takes it outside; and the first version is the Tur's ruling that one should not distinguish, because when he puts the jugs in the basket it is a weekday matter, as the Ran wrote, and in siman 371 seif 8, chapter — in a gloss some say these:`,
  "7:א": `It is permitted to immerse. So it appears from the words of the Ri'f in chapter 2 of Yom Tov, folio 18a, that he brought the version of R' Yosef and Rav Beivai:`,
  "7:ב": `And there are those who forbid. The Rosh, and he wrote that the version of Rabbah and Rava is primary, see there:`,
  "7:ג": `And some say. And he gives it as a gift etc. For it is permitted in such a case, as one transfers ownership of a lulav on the first day of Yom Tov of the festival, and one transfers ownership of one's flour to others and they acquire from him — even on Shabbos, Mordechai, chapter 2 of Yom Tov:`,
  "7:ד": `And he shall return. As is stated in Avodah Zarah 75b:`,
  "7:ה": `And if it is. Chapter 2 of Yom Tov, there — they draw with a bucket, and there is no distinction regarding a bucket, as is stated in the Yerushalmi there: R' Hoshaiah taught — a person may fill an impure vessel from the cistern and deceive regarding it and immerse it:`,
  "8:א": `Seif 9 "cup." From what we say there, 21b — and we move them by means of a cup; from this it follows that the cup itself is fit [for use]:`,
  "8:ב": `Seif 10 "there is not." As is stated in siman 308 seif 12:`,
};
