export const t = {
  "1:א": `Seif 1 "and other birds." There — in a house, since it is roofed he is liable for other birds, and likewise for a pit in such a case where it is roofed there:`,
  "1:ב": `"They." Per Rashbag, for we rule there like him:`,
  "1:ג": `"But." Chapter 3 siman 1, 107a:`,
  "2:א": `Seif 2 "or sick." So the Rosh and Tur wrote, and they did not distinguish as they distinguished in the gemara — they explain like R' Chananel and Rambam that because of heat he is liable, and as stated in Hagahah and "one who incites" etc., and Magen Avraham note 4; and therefore they concealed that an unspecified sick [animal] is sick from heat:`,
  "2:ב": `"And some say." Avodah Zarah 18b, and all of them there — moshav leitzim, and see Rashi there:`,
  "3:א": `Seif 3 "but forbidden." Yom Tov 36b:`,
  "3:ב": `"Therefore." As stated regarding bees in seif 4:`,
  "3:ג": `"Small." Magen Avraham:`,
  "3:ד": `"And some are lenient." Tur wrote, and it is possible [to explain] regarding a hive that is small and the bees are trapped in it — meaning even when one opens it; and furthermore that the place itself also has no prohibition except when intentional. And it appears to him like the sugya of Shabbos 43a, but on Yom Tov 36b, 40a there is no distinction:`,
  "4:_": `"And likewise he." Beitza there:`,
  "5:_": `Seif 5 "and if the door." There — "to what is this similar" etc., and per Ran there in the gemara — exempt and permitted:`,
  "7:_": `Seif 7 "and scorpions." There — from what is he exempt etc.:`,
  "8:א": `Seif 8 "even though" etc. There 2b:`,
  "8:ב": `"Unless." Chullin 46b:`,
  "8:ג": `"That not." There:`,
  "8:ד": `"Or unspecified." Tosafos s.v. "hatsadan" see there:`,
  "8:ה": `"And for Rambam." There — who is the tanna etc., and he ruled like R' Yehuda as stated in Eruvin 46b. But all the poskim explained this like R' Shimon, for Rava holds like him there 41b, and as Tosafos stated 3a s.v. "hatsad" etc. see there; and Shmuel holds like him there 42a, and several mishnahs [are] like him:`,
  "9:א": `Seif 9 "called." Tosafos 12a s.v. "perhaps" per Rabbeinu Tam's explanation:`,
  "9:ב": `"Unless." As stated above regarding one who splits a boil and hunting a snake:`,
  "9:ג": `"And its stinger." Specifically its stinger, as stated from [the case of] one who splits a boil — specifically in the pain that comes:`,
  "9:ד": `"And forbidden." There — meaning even in such a case that even a snake is forbidden to kill, rather specifically those that kill, as stated in seif 10 — not like Rabbeinu Tam who permits, and they brought it in Mordechai and likened to other harmful creatures in seif 10 — and it is not [so]; and per Rambam's view one who kills it is liable:`,
  "9:ה": `"And even." Tosafos 12a s.v. "takes." And regarding a flea even the first tanna concedes:`,
  "9:ו": `"And one who delouses." Per the first tanna, and as Rav Huna stated the halacha; and Rambam and Rosh distinguished between delousing from a garment where they permit there, and so in the Rif:`,
  "9:ז": `"But." Rosh — from that which Rabbah said "breaks off" and per Rashi, and R' Natronai said to his daughter — from delousing — and it should read thus:`,
  "10:א": `Seif 10 "every animal." Per Rashi there. And even though in the gemara he only said five kinds — rather everything is according to place and time, and this is what Rambam wrote "every" etc.:`,
  "10:ב": `"And even intentionally." Nevertheless Ran — from that which he said "a hornet — I kill" etc., from which [we learn] even intentionally:`,
  "11:_": `Seif 11 "that does not intend." Per Rashi there, and even though Ran wrote here also like by snake in seif 10, and so several poskim; and Rashi goes to his view that he also wrote by snake "that does not intend." Beit Yosef did not want to rule like their words since it is only because of repulsiveness, and see Ran:`,
  "12:א": `Seif 12 "permitted." Even though all Shabbos exemptions are exempt but forbidden — here nevertheless permitted, as stated in chapter 3 of Yom Tov 24a and see there in Rosh in the name of Baal HaItur and see there, and what is stated in the mishnah of Shabbos exempt — because it taught first liable, and as stated there 37a "and because" etc. Hagahos Maimoniyos:`,
  "12:ב": `"Forbidden." And even liability for a sin-offering is in it, as stated in Yerushalmi there, and he said forbidden because of the latter clause — even in a courtyard if etc., and there certainly he is not liable since now he does not need a trap, and as stated in Yom Tov there "this one is lacking" etc., and see Hagahos Maimoniyos:`,
  "12:ג": `"And some say forbidden." As stated above that all Shabbos exemptions are exempt but forbidden; and Yom Tov is different because of simchat Yom Tov they permitted. Hagahos Maimoniyos, and above siman 308 seif 49 what is stated there; and it appears to me there is no need to distinguish, for even on Yom Tov it is forbidden and it is not permitted except geese and chickens as stated above that they are not accustomed to multiply etc., and the mishnah [speaks] of other animals and birds; and this is what the gloss stated "but cow and horse" — for even though they are permitted in them l'chatchila, and all the more so other etc.; and this is what [it stated] regarding a cat etc. — meaning it is not like geese and chickens since they are accustomed to multiply, and so forth:`,
  "12:ד": `"But cow." Yerushalmi, and as stated above:`,
};
