export const t = {
  "2:א": `Seif 2 — even if not. Like R' Chanan there — R' Huna, son of R' Yitzchak, holds like him. There, 5:2. And see in the Rosh.`,
  "2:ב": `Only four. There, in this they agree with R' Huna.`,
  "3:א": `Seif 3 — if not. There, here, etc.`,
  "3:ב": `And even, etc., and even. There, 8:2.`,
  "3:ג": `And provided. 9:2.`,
  "3:ד": `Even if not. 1:2. And according to Rabbah who says, etc.`,
  "3:ה": `And such as. There, 1.`,
  "3:ו": `In the manner of, etc. Magen Avraham. And siman 363, seif 9.`,
  "3:ז": `And if it was breached. Tosafos, s.v. be'irvu. And R' Yehuda explains, etc.`,
  "4:א": `Seif 4 — but. There, from that which chapter 2, 24:2.`,
  "4:ב": `Both. Rambam. And see Rosh there.`,
  "5:_": `Seif 5 — but at. According to the opinion in Eruvin 42:2.`,
  "6:_": `Seif 6 — since. He intended what was written in siman 428, seif 2 in the gloss — and specifically, etc., and like the early authorities' version in Shabbos 37 — but it is not so; rather, this is how it stands in the conclusion. And this applies in d'rabbanan matters, but not in d'oraisa. And see Ran.`,
  "7:א": `Seif 7 — and some say, etc. There, 94:1, and as stated there 17:1. And see there Tosafos, s.v. irav, etc.`,
  "7:ב": `And all this. See Tosafos there 95:2, s.v. de'asa. Even though regarding ships, etc.`,
  "7:ג": `And if. There, 35:1.`,
  "8:_": `Seif 8 — an alleyway in which they made a partnership. Magen Avraham. And above siman 372, seif 2. And according to this, 7:2, and the Mishnah and Gemara there, and Tosefta chapter 6: partnership of an alleyway requires that the eruv chatzerot be with them in the alleyway; eruv chatzerot requires that it be with them in the courtyard, as stated in the Gemara chapter 5:2, and Rashi there.`,
};
