export const t = {
  "1:א": `Seif 1 person — rule Canaanite slave three: (1) circumcised accepted mitzvot like ger tzedek except ger obligated all man's mitzvot slave woman's mitzvot; (2) toshav slave like ger toshav; (3) gentile slave like gentile of world — both not circumcised like gentile and ger toshav explained below.`,
  "1:ב": `On rest etc. — Yevamot 48b "that rest" — circumcised slave.`,
  "1:ג": `Circumcised immersed — we hold R' Yosi there 46 and R' Yochanan not ger until circumcise immerse — same slave one law; there like Binyamin etc.`,
  "1:ד": `And accepted — per Rif there requires acceptance since they say 48b didn't want etc.; see Rosh end 38 and Ivra and end Shabbat.`,
  "1:ה": `Customary for slave — Chagigah ch. 1 since all mitzvot slave etc.`,
  "1:ו": `But if — Keritut 9a braita etc.; Rashi ger toshav etc.; law like R' Shimon there.`,
  "1:ז": `Only accepted etc. — Avodah Zarah 64b like sages; see Rashba 59 at length.`,
  "1:ח": `Likewise etc. permitted — Keritut there.`,
  "1:ט": `But not etc. — Keritut there and Yevamot there "son of your maidservant" as below.`,
  "1:י": `Forbidden all Israel — from "for himself" specifically; also similar ger toshav no master — therefore for all Israel exclude "for himself" specifically.`,
  "1:כ": `Tell him — specifically speech; herein differs from master as below.`,
  "1:ל": `If didn't accept — nevertheless Rashba name from Yevamot "son of your maidservant" on uncircumcised slave — explains such case since didn't teach like Keritut "toshav slave"; also verse unnecessary — included in ger toshav.`,
  "1:מ": `Therefore — melacha prohibition no difference other gentile — other gentile speech forbidden Shabbat 150a; likewise for master as below; other gentile prohibition rabbinic only as wrote; here d'oraisa as Yevamot there — difference as wrote.`,
  "1:נ": `Needs etc. — there 129a.`,
  "1:ס": `And likewise — Beitzah 6a; see there 22a.`,
  "1:ע": `And some etc. — meaning complete gentile equal toshav slave and forty even other Israel speech forbidden Mahari Abuhav; Avodah Zarah dispute permit — Torah only warned master as Yevamot; Keritut compared to ger toshav only toshav slave as wrote — therefore sick needs permitted other Israel tell him all not master — "some dispute" on even gentile etc.; likewise Eshel Avraham though Beit Yosef didn't bring Avodah Zarah disputants.`,
  "1:פ": `Nevertheless etc. other Israel provided — all divisions explained Shabbat 151a if doing etc.; need not stop even etc.; not better than minor commanded on rest nevertheless evident not on intent need not stop as wrote Shmuel minor etc.; minor doing etc.; otherwise permitted; other Israel even there gentile etc. gentile on own intent etc.; same slave even minor commanded on rest on own intent permitted; Shmuel no difference gentile of world and slave — mishnah law; gentile don't extinguish; speech forbidden as wrote; don't extinguish for master even without speech forbidden on intent as wrote there gentile on intent — meaning since Israel doesn't tell him gentile begins himself siman 247 seif 4 like cutting on own intent; for master on master's intent as seif 6.`,
  "1:צ": `Provided not benefit — as 122a; if for Israel forbidden though gentile on own intent permitted extinguishing here Israel benefits Shabbat forbidden — seif 276 seif 1 gloss no difference etc.; all six divisions explained mishnah permitted for himself; gentile who lit etc. may use etc.; but not for master like minor; minor who comes etc.; forbidden all Israel; don't extinguish for him; other Israel etc.; don't extinguish; provided not; if for Israel forbidden; sixth law nevertheless if doing etc. Gemara Shmuel minor etc. as above.`,
  "1:ק": `Therefore etc. — meaning this view permitted even tell master unlike "some dispute" above.`,
  "1:ר": `Every slave etc. — Shabbat 58a Shmuel said kavul etc. who said etc. challenged etc. not one and one etc.`,
  "1:ש": `If slave made etc. — Tur omitted holds conclusion follows this reasoning R' Levi said this etc. contradicts not etc. therefore first also resolved thus returned first version holds no difference master's and own.`,
  "2:א": `Seif 2 and where — included in "for himself" — can say work with me I won't feed you as Gittin ch. 1.`,
  "2:ב": `Provided discreetly etc. — even renting bathhouse to gentile forbidden called on his name; all the more here not called more on name doing in Jewish house — Gemara start Shabbat see there.`,
  "3:א": `Seif 3 gentile — 123a.`,
  "3:ב": `He is hired — Moed Katan 12a was hired Shabbat — implies there even Shabbat permitted see there.`,
};
