/** siman 451 part 1 — batch b: machatzit-hashekel, magen-avraham, turei-zahav, beer-hagolah, baer-heitev */
export const HAND = {
  "baer-heitev/10:_":
    "To kasher them. It is simple that if they salted them without hagalah it is permitted, for salting does not apply to vessels — see seif 26, Magen Avraham there, that salt is not called a sharp substance unless very salty. Bach and Taz are stringent not to kasher baskets at all, lest there be chametz between the holes.",
  "baer-heitev/11:ב":
    "In hagalah. So too is practiced. Magen Avraham wrote: those pans in which they bake cakes require libun.",
  "baer-heitev/12:_":
    "B'dieved. For we do not say its absorption travels through the whole [vessel]; and even if its absorption travels, nevertheless it is like kli rishon. Kaf HaChayyim wrote b'dieved one does not forbid even if he stuck it into hot food, for we do not establish an issur; and like kli rishon — see there. Magen Avraham ruled: if he stuck the side that was not kashered — forbidden — see there. Taz ruled: in a knife one should be stringent even b'dieved if he cut with a knife whose handle was not kashered in hot food on Pesach, since certainly he touched the handle at the time of use with the knife — not so other vessels — see there. Magen Avraham wrote: it appears to me that what is written \"we do not forbid b'dieved\" means if they already used them; but l'chatchila it is forbidden to use them even during Pesach if impossible to kasher.",
  "baer-heitev/13:א":
    "Solder patch. Every solder patch in this seif means what was fixed by adhesion of piece on piece with nails; but in a solder patch made on a pewter vessel where they drip a pewter piece from heat — all absorption burns and what remains in existence [is permitted]. Also when repairing a silver spoon and the like, they place a silver piece there — then the craftsman puts the spoon in fire first, and therefore there is no concern. Taz, Kaf HaChayyim. Old vessels coated in pewter, like copper vessels — R' Eliyahu Mizrachi Chayei Adam siman 43 ruled no hagalah is needed since pewter interrupts — they are like new vessels. Magen Avraham wrote: accordingly even if coated with old pewter, for pewter itself becomes white. See in Knesset HaGedolah who elaborated to bring dissenting views; he wrote some great ones of the land are stringent on themselves; in any case it seems good in the eyes of God and man to immerse after pewter coating without a blessing — end of his words. See Yoreh De'ah siman 120. Peri Chadash Orach Chayyim ruled hagalah is required after pewter coating, and so is practiced in Jerusalem — see there.",
  "baer-heitev/13:ב":
    "The issur. Then even though the absorption of the issur preceded, it is permitted once the place of the solder became white. Bach wrote: it appears to me where absorption of issur preceded — one must libun the place of the solder — see there. Magen Avraham wrote: therefore it appears where absorption preceded the solder patch, one must place so many coals until sparks fly from it — not so if the solder preceded absorption, light libun suffices as written in this seif in the gloss. Kaf HaChayyim disagrees with Bach and Magen Avraham and upheld as the Mechaber's wording implies. If it became white thus or removed the solder once after kashering again — permitted to kasher thus with the solder each time, since it is no longer called absorption of issur preceding the solder; all this when the solder adheres well with no crack between the body of the vessel and the solder — otherwise even if the solder preceded, one needs libun or removal of solder or widening the crack so it can be scraped. Kaf HaChayyim.",
  "baer-heitev/14:_":
    "Forbidden. Per the Mechaber's view siman 447 that nitelaf is permitted on Pesach — it must be as the practice to forbid in covering even if not ben yomo, as explained in Yoreh De'ah siman 93.",
  "baer-heitev/16:_":
    "To whiten. Acharonim wrote: in our countries they never grind chametz in them, only saffron and spices — therefore hagalah suffices; nevertheless it is good to practice stringency to grind everything before the 14th. See there. And if they ground in our mortar with spices and put them in a dish — requires study whether to forbid b'dieved. Magen Avraham — see there.",
  "baer-heitev/18:א":
    "In a sifter. But one must buy new ones; and if he transgressed and sifted with it via scrubbing well with hagalah — one does not forbid even during Pesach, since per the Mechaber even l'chatchila this suffices. So too where water came on the sifter that was not scrubbed well first, even on part of it — it has no remedy to use on Pesach — Maharil. Magen Avraham wrote: it appears even where there is no new sifter, better that flour not be sifted. Kaf HaChayyim disagreed and wrote it is known that all where flour was not sifted have broken and whole wheat and the dough or matzah would be forbidden; but this sifter b'dieved helps with scrubbing well and hagalah, all the more if sifted before Pesach when cancelled — therefore in time of pressure it is correct to do so even l'chatchila. One asked me offhand that his custom is to wash the sifter well after Pesach to keep it for next year, and he sifted chametz flour for Pesach. I permitted what he sifted b'dieved, for even if we say adhesion remained from last year — it is hardened chametz and nullified in sixty even during Pesach. Kaf HaChayyim — see there.",
  "baer-heitev/18:ד":
    "The stitches. Meaning also what is on the edge of the bag that is the seam; Magen Avraham wrote: so too one should practice with cloths on which they make matzot — if wanting to use them a second time, not what they turn them over, for chametz oozes and goes from side to side; rather one must undo the stitches to launder well. If he acted b'dieved and made matzot on the sheet without any laundering, if during Pesach — even b'dieved one should forbid; but if he turned the sheet or laundered it even without undoing stitches — one need not be stringent b'dieved. So too regarding bags: if laundered and did not undo stitches and put flour inside — no prohibition b'dieved. Kaf HaChayyim — see there.",
  "baer-heitev/19:א":
    "Peel. In Ashkenaz language schievel; its use is by fire — therefore hagalah does not permit it. Taz wrote: if one keeps this Pesach peel for another year — no kashering needed; so too a trough in which they knead matzot — one who is stringent to kasher it did not act well, lest he come to err and kasher a chametz peel — only scrape it well. Magen Avraham in the name of Darkei Moshe in the name of Mahariv wrote it requires hagalah — see there; Kaf HaChayyim agreed with Taz. If one took matzah in a peel used all year — if clean, peeling the matzah suffices. If not clean, since used all year for cakes with fat — all forbidden per Magen Avraham. If chametz matzah was threshed in it — forbidden to thresh more; must bring another — Hagahot Maimoniyot and Shelah. If he did not bring another — all need peeling. All this deals with matzah that became full chametz. But doubled and puffed matzah, since it is itself a stringency as written siman 461 — suffices to forbid the peel l'chatchila but not other matzot — Magen Avraham. Kaf HaChayyim wrote: greater than this I saw by Maharatz Maharash — he did not forbid the peel when puffed or doubled matzah remained before him, because it is considered like b'dieved, since in most bakings one will not be forbidden because of puffed or doubled, and each time would need a new peel; also the oven would be forbidden and require relighting — Torah is sparing of money — see there; see siman 461 seif 3.",
  "baer-heitev/19:ג":
    "New. The author of Imrei Noam wrote in his siman 5: an incident where they baked 180 matzot in a peel and were unsure if new or old used for chametz — in these matzot there is no concern of chametz prohibition — see there.",
  "baer-heitev/1:ו":
    "In a kiln. I was asked regarding pottery vessels that remained after burning — if it is permitted to use them on Pesach, since it is known this is more than returning to the kiln — and I permitted; nevertheless everything depends on the circumstances.",
  "baer-heitev/20:_":
    "To pour. Mahariv siman 193 ruled pouring does not help — only kasher via white-hot stone or burning torch and pour boiling water on it. Acharonim wrote in the name of Maharil: even after hagalah if anything spilled on it on Pesach — do not lift it at all to eat; and even after hagalah do not use anything hot on them except via interruption of cloth or board or rags — all excessive stringencies, for the stringency of hagalah suffices, and so is practiced. Kaf HaChayyim: Taz wrote siman 492 women practice not to use on Pesach a pot into which they poured boiling water on the kashering stone, because chametz smell entered — yet there is no smell or taste, no issur at all on Pesach; Kaf HaChayyim upholds the custom l'chatchila but b'dieved certainly does not forbid.",
  "baer-heitev/21:ג":
    "And b'dieved. The reason is yeast in wine is nitelaf; and per what we hold nitelaf is forbidden on Pesach — therefore one may not be lenient except to pour from it before Pesach into a Pesach barrel; specifically wine whose yeast gives nitelaf; but in mead one may not be lenient unless the barrels are not ben yomo; but in a yayin nesech vessel even not ben yomo — forbidden, for it improves taste. Magen Avraham and Kaf HaChayyim — see there; see Taz.",
  "baer-heitev/22:ג":
    "The oven. Acharonim agree b'dieved the food cooked in it is permitted; and if time of pressure when impossible otherwise — considered b'dieved; nevertheless in any case scrub the oven well on all sides and heat it well, then plaster with clay the place the pot sits, finger-thickness — except if he placed matzah there or other things as it is without a pot while boiling — then forbid even b'dieved; see Magen Avraham, Taz, and Kaf HaChayyim.",
  "baer-heitev/24:א":
    "Dyed. Even dyed in saffron or what is called in foreign language malt. Maharil and Mahariv.",
  "baer-heitev/24:ב":
    "In pewter. Practiced in some places that a Jew stands over it during the work.",
  "baer-heitev/2:א":
    "From bricks. See Magen Avraham that bricks burned in a kiln like ours have every law of pottery vessels. Kaf HaChayyim wrote except we are not so concerned for them, and possibly heating helps for them even within our ovens per my view. But bricks dried in the sun have the law of earthenware vessels. See there.",
  "baer-heitev/3:א":
    "Kasher them in hagalah. Specifically the Pesach knife, or from meat to milk or vice versa; not so knives of [other] issur — they require libun even if there are no crevices, whenever one wants to use them in hot [food], as explained in Yoreh De'ah siman 121 seif 7. See in Peri Chadash there that he ruled even in knives of issur hagalah suffices even l'chatchila. Kaf HaChayyim wrote: it appears to me the main [rule] l'chatchila is as Shulchan Aruch ruled there, and so too in Or U'Mussar; however b'dieved one does not forbid if they kashered and used it in hot [food].",
  "baer-heitev/3:ב":
    "Boiling. Magen Avraham wrote to insert the knife into it; but one may not kasher it via a white-hot stone.",
  "baer-heitev/3:ג":
    "On a whetstone. The same applies in a case where removing rust suffices. Bach and other Acharonim wrote: because one must also kasher the handle; therefore if the handle is fixed with small nails hagalah does not help, for there are many crevices at the place of the nails — and the same applies whenever there are two parts in its handle. The same if part of the handle is in the corner or the handle is glued to the iron with glue — one may not kasher it, for we are concerned lest it split; libun too does not apply to a handle unless it is entirely iron. Since most knives are this way, therefore it is proper that the smith establish [the rule]: if possible to make new ones they are preferable. See Taz.",
  "baer-heitev/3:ד":
    "Rust. Meaning one need not sharpen except to remove rust; but if they sharpen well in a manner that removes some of the iron, as explained in Yoreh De'ah siman 121 — it is like libun. See in the gloss there. Rust means what we call rust in foreign language. But a black or red stain in some place of the vessel, and especially pots and pans — there is no concern, and one may kasher; and as an advice one should whiten that place if impossible by scraping. Taz — see there.",
  "baer-heitev/3:ה":
    "Libun. And with libun one need not remove rust, for fire burns everything.",
  "baer-heitev/4:ג":
    "Those who are lenient. Taz and Magen Avraham forbid even b'dieved if they did not libun it so much that sparks fly from them. See there.",
  "baer-heitev/5:א":
    "To pour. One must be careful that the stream not stop in the middle; and one need not pouring a second time — Acharonim.",
  "baer-heitev/6:א":
    "With rinsing. So too b'dieved if they did not kasher the bowls in kli rishon — they also do not forbid. And if it is known that within twenty-four hours they used it in kli rishon, even though its main use is in kli sheini — they require hagalah in kli rishon specifically, per all views. And rinsing means to scrub them first well in water to remove all adhesion on it, and afterward rinse in water as explained in Yoreh De'ah siman 121.",
  "baer-heitev/6:ב":
    "White-hot. So too is practiced regarding kashering tables and benches; and one dries the table so the water will not congeal. Acharonim. And siman 492 seif 2 in the gloss. Bowls that have rims and protrusions like buttons and flowers — when one cannot pass the stone over all of it — they have no remedy except to put it in a pot; and likewise a knife one may not kasher with a stone. Magen Avraham.",
  "beer-hagolah/14:ב":
    "there; and so too Hagahot Maimoniyot in Laws of Hagalah from Mishnah end of chapter 20 that they kasher",
  "beer-hagolah/17:א":
    "Tur, and so too Hagahot Maimoniyot in chapter 5",
  "beer-hagolah/19:ב":
    "Hagahot Maimoniyot chapter 5 and Terumat HaDeshen from words of Semag",
  "beer-hagolah/1:ה":
    "in the Gemara there",
  "beer-hagolah/22:א":
    "from this [that] Shmuel [said in] Pesachim 36 — as the girsa of the Rosh there",
  "beer-hagolah/22:ד":
    "as the girsa of the Rif there, as the Ran explained there",
  "beer-hagolah/23:_":
    "in the Gemara there",
  "beer-hagolah/26:א":
    "the Ran in chapter 2 of Pesachim",
  "beer-hagolah/26:ב":
    "Rashba in responsum",
  "beer-hagolah/27:_":
    "Mordechai end chapter 2 of Pesachim",
  "beer-hagolah/2:_":
    "in the Gemara there",
  "beer-hagolah/3:א":
    "in the Gemara there",
  "beer-hagolah/3:ג":
    "the Rosh there in chapter 2 of Pesachim, and he brought proof from Sifri",
  "beer-hagolah/4:א":
    "baraita end Avodah Zarah 77b; the Rif and Rosh brought it in chapter 2 of Pesachim; and so the majority of poskim equate the law of chametz to other issurim",
  "beer-hagolah/5:א":
    "in the baraita in Avodah Zarah, and the Rif and Rosh brought it in chapter 2 of Pesachim",
  "beer-hagolah/5:ב":
    "Tosafot in Shabbos 39 in the name of R' Yitzchak",
  "beer-hagolah/6:_":
    "the Rif and Rambam in chapter 5, and Ran and Rashba in responsum",
  "beer-hagolah/8:_":
    "the Rif in chapter 2 of Pesachim and Rosh there",
  "beer-hagolah/9:_":
    "Tur in siman 492 in the name of his father the Rosh, and Tosafot end Avodah Zarah, and Shach",
  "machatzit-hashekel/11:ב":
    "Rashba holds called issur absorption since chametz named on it — we hold like Rashba there.",
  "machatzit-hashekel/16:_":
    "(s.k. 16) Within, etc. siman 25 — what Magen Avraham wrote there regarding geshmaltz outside.",
  "machatzit-hashekel/19:_":
    "(s.k. 19) Perhaps, etc. horn, etc. Sefer Eliyah Rabbah Mahariyat: what we call pearl mother-of-pearl — strong hard — not like horn melted from heat — end; Taz s.k. 16 rust — hinders only with substance; blackness or redness generally and what we call red plastic — no concern — Kaf HaChayyim likewise.",
  "machatzit-hashekel/1:א":
    "(s.k. 1) And permitted, etc. Some want proof from Tosafot Pesachim 74a: Rav — chametz pots on Pesach break; Shmuel — leave until after Pesach, cook in it not in kind and not not in kind; Gemara challenges Rav — R' Yehuda chametz after Pesach passed forbidden Torah, not in kind in amount — why break until after Pesach and cook not in kind? Answer: decree lest cook in kind. Tosafot s.v. leave them: challenge — Rav: chametz taste in pot considered something — not customary use much together — nevertheless we learn do not nullify issur l'chatchila; R' Yosef: here if Rav holds nitelaf permitted (safeik AZ whether Rav permits nitelaf) — though nitelaf l'chatchila forbidden — two leniencies nitelaf and not in kind in such case nullify l'chatchila; R' Yitzchak: pottery no remedy — considered b'dieved; pottery not ben yomo nitelaf forbidden l'chatchila though no remedy — here only amount — b'dieved. Therefore want proof for us who hold Shmuel — also not in kind nullified, no decree — still these pots only absorbed amount — because do not nullify issur l'chatchila like one Tosafot view; but absorbed much — forbidden do not nullify, etc.",
  "machatzit-hashekel/1:ב":
    "Per Rav who ruled R' Yehuda — chametz after Pesach passed forbidden Torah; we hold Shmuel and R' Shimon — not forbidden except fine for violating bal yera'eh. Not so these pots — permitted to leave as head s.k. 7 — even in mixtures forbidden to leave — if left, since no bal yera'eh violation — nullified in sixty — all the more pots — therefore permitted even if absorbed — permitted cook l'chatchila — no nullifying issur — no issur at all.",
  "machatzit-hashekel/20:ג":
    "In vessel no nullification — as YD 92:5 drop milk on pot — Semak safeik spreads whole vessel — Shach s.k. 18 there.",
  "machatzit-hashekel/20:ד":
    "As seif 27 — safeik do not establish issur; if certainly used baskets for chametz — Rama seif 11 even hagalah ineffective; from this Kaf HaChayyim challenged Taz s.k. 15 wonder.",
  "machatzit-hashekel/20:ו":
    "Siman 96 Yoreh De'ah and Shach s.k. 16.",
  "machatzit-hashekel/21:_":
    "(s.k. 21) Permitted, etc. what difference fat, etc. though pan other issurim Rabbenu Yosef Karo YD 121:4 requires libun — Shach: implies Rabbenu Yosef Karo chametz since permitted absorption lenient; therefore pan meat to kasher for milk or vice versa — permitted absorption — hagalah enough like chametz; responsa Maharam Padua 96: divide other matter — as use so kasher — if use via hot — issur fell via fire and hot — kasher via hot hagalah expels via fire and hot; if use via fire without hot — absorbed via fire alone — kasher libun expels fire alone; chametz pan fried in fat or milk — whatever — that substance not chametz itself; though chametz absorption — nevertheless as fried in water though water received chametz taste now frying — anyway chametz absorbed in pan via fire and fat permitted itself — law absorbed via fire and fat as absorbed fire and water — hagalah suffices; issur pan non-Jew fried even in fat/milk — mostly what gentiles fry forbidden themselves — that fried substance absorbed pan fire alone — example meat fried via fat — fat also issur — even only issur fat in pan — needed libun — why less because also meat — therefore gentile pan libun; therefore fat pan fried dough in milk to kasher for meat or meat pan fried in fat for milk — though permitted absorption — still libun like gentile pan — see Magen Avraham 499:11 custom world not kasher milk vessel for meat or vice versa.",
  "machatzit-hashekel/24:א":
    "(s.k. 24) Does not, etc. not travel absorption, etc. Or U'Mussar plain meaning: absorption at time of issur in vessel did not spread only where used — Magen Avraham later clarifies not so.",
  "machatzit-hashekel/24:ב":
    "As YD 92:5 brought Shach s.k. 18 Semak drop on pot wall — safeik Dam Chatat spreads whole vessel — here safeik spread whole vessel — safeik go stringent — YD 92:1 one view: if milk spoon in meat pot or vice versa — no sixty only opposite part inserted — must not expel from side not inserted.",
  "machatzit-hashekel/24:ג":
    "As YD 92 — proof wrote above repeated words.",
  "machatzit-hashekel/24:ד":
    "Thus resolved, etc. Tur Rashba: vessel needing libun must whiten whole — it appears only if used whole; if knows used only part — part kashered too — as absorbs so expels; Rabbenu Yosef Karo: from Rosh implies even part used — whiten whole — Rosh gentile knife custom fire — fix wick in burning milk candle, flip meat on coals — Rosh: appears suffices whiten knife tip — gentiles custom use tip on fire; though part hot — whole hot issur spread — since Israel not use on fire — suffices; Rabbenu Yosef Karo: not permitted libun where used fire only because Israel not use knife on fire — implies use on fire forbidden; why Tur dispute father Rosh — not bring Rosh at all.",
  "machatzit-hashekel/24:ו":
    "Bach and Taz other reason permit handles — way touch dirty hands to vessel handles — therefore Taz stringent knife handles even b'dieved if not kashered handles — see Kaf HaChayyim.",
  "machatzit-hashekel/27:א":
    "(s.k. 27) Places, etc. requires study — intent Tur wrote pan or pot with solder patch not released via hagalah because absorbed under solder not expelled via hagalah — clear there only when absorption preceded solder; solder before absorption — hagalah helps as absorbs so expels; Rabbenu Yosef Karo: Rashba responsa hagalah expels here as there — concerned under solder pieces issur body — issur body substance not kashered via hagalah — therefore custom place coals on crack places burn issur body if exists then hagalah; wood — widen as Shulchan Aruch — therefore Rabbenu Yosef Karo Shulchan Aruch from Rashba; Shulchan Aruch absorption before solder — coals on solder place; solder before absorption — no coals — deals very adhered after solder impossible chametz enter under solder — Taz s.k. 18; understood Rashba disputes Tur Rosh Ravyah — even absorption before solder hagalah helps solder not barrier — expels under solder (or expels other side without solder — Peri Chadash Rashba) — concerned in existence under solder entered before solder placed — in existence hagalah ineffective — therefore coals on solder burn prior chametz under solder; Magen Avraham: avoid dispute Rashba Tur — explains Rashba only solder before absorption not so adhered — concern after solder chametz entered under — though all agree solder before absorption hagalah helps — solder place concern chametz in existence — no hagalah — therefore coals (not libun coals — would need many sparks — rather few coals like libun Rama seif 4 — only burn chametz under solder); absorption before solder — Rashba did not speak — presumably agrees Tur no hagalah with few coals — solder blocks cannot expel under solder.",
  "machatzit-hashekel/27:ב":
    "So Bach, etc. Rashba deals only before solder; absorption before solder Rashba agrees hagalah ineffective — Bach own reasoning whole vessel libun — we hold as use so kasher — used without solder cannot hagalah with solder on.",
  "machatzit-hashekel/27:ג":
    "So Or U'Mussar, etc. Chemdat Moshe proof Or U'Mussar before solder needs libun — elaborated Bach Magen Avraham erred Or U'Mussar intent — my view: bring opposite proof anyway libun helps — thought requires specifically as use so kasher — used via boiling — libun ineffective though libun better — room error — proof Or U'Mussar libun helps — proven Or U'Mussar — same proof Tur metal pot heat fill coals permitted — perhaps Or U'Mussar same solder law — lesser therefore proof Or U'Mussar.",
  "machatzit-hashekel/27:ד":
    "Therefore it appears when absorption preceded, etc. Magen Avraham disputes Rabbenu Yosef Karo in two — also disputes Bach — Bach absorption before solder must whiten whole vessel; Magen Avraham suffices whiten solder place — nevertheless agrees Bach in two main points.",
  "machatzit-hashekel/27:ה":
    "What is written until burns issur body and if preceded, etc. — appears misprint must reverse — if solder before absorption light libun suffices; until burns issur body — Magen Avraham Rashba deals solder before absorption still requires coals — light libun; therefore Rashba until burns issur body — ineffective where libun — only burn in existence under solder cracks.",
  "machatzit-hashekel/27:ו":
    "Vessels, etc. further since pewter interrupts, etc. Peri Chadash disagrees agrees first reason — therefore Acharonim solder in Shulchan Aruch — piece on piece nails; if melted pewter sealed hole — hagalah helps even absorption before.",
  "machatzit-hashekel/27:ח":
    "And YD 120 immersion — coated vessels inside or outside immerse without blessing (outside and inside — Peri Chadash immerse bless) — though vessels themselves no immersion new — coating requires immersion — old vessels though immersed — if coated lead or pewter immerse again for coating; if Israel lead — see there his law.",
  "machatzit-hashekel/2:ב":
    "Possibly practiced thus, etc. Taz agreed Bach all pottery Pesach — but permits keep Pesach vessels all year — not concerned perhaps chametz use — even if used — on Pesach nitelaf; must be: did not also permit Pesach chametz vessels lest vessels used 13th night or 14th morning — Pesach starts night 1 or next morning still ben yomo — not so Pesach vessels — unlikely mistake use 13th night — since otherwise only mistaken use — concern 13th night remote.",
  "machatzit-hashekel/3:ב":
    "Not like Beit Yosef who wrote since Rambam forbids even kli sheini — perhaps Tur agrees; must be Tur mentions pouring for Rabbenu Yitzchak is not precise.",
  "machatzit-hashekel/3:ג":
    "It appears to me even Rambam, etc. Not like Rabbenu Yitzchak; Darkei Moshe agrees — at least Rambam forbids kli sheini that does not exist.",
  "machatzit-hashekel/3:ד":
    "If so necessarily deals with use via pouring — we hold as use so kasher as seif 5 — cannot deal with actual kli sheini — kashering also suffices in kli sheini.",
  "machatzit-hashekel/3:ה":
    "And in pottery wrote also such as bowls — also means use via pouring not kli sheini — though wrote all pottery used for chametz between kli rishon such as bowls — pouring also called kli sheini as above.",
  "machatzit-hashekel/3:ו":
    "So Rabbeinu Yosef Karo omitted kli sheini law — apparently retracted — holds specifically used via pouring — from this no proof Rama \"some forbid\" — Mechaber permits; known Rama sometimes if not explicit writes \"some say\" — proves from Rabbenu Yosef Karo not bringing Rambam forbids kli sheini — though in his book Beit Yosef Tur language like Shulchan Aruch Tur holds kli sheini forbidden because Rabbenu Yosef Karo Rambam forbids kli sheini — avoid dispute Rambam/Tur — say Tur not precise kli sheini too — Shulchan Aruch should not conceal and allow error pouring only — truly retracted — Tur specifically pouring — Rambam too as Magen Avraham.",
  "machatzit-hashekel/3:ח":
    "For Rashba, etc. Though we find none stringent Pesach more than other issurim forbid kli sheini — nevertheless Rashba, etc.; what Kaf HaChayyim wondered how say Rabbenu Yosef Karo kli sheini not forbidden — he wrote seif 5 vessel used — if kli sheini kasher in kli sheini — must mean actual kli sheini — how use via pouring written afterward vessel used via pouring — already resolved Magen Avraham s.k. 13 there and all l'chatchila; s.k. 1 — Rabbenu Yosef Karo l'chatchila kasher also kli sheini use — here pottery no remedy hagalah — b'dieved — Magen Avraham holds Rabbenu Yosef Karo relies main law kli sheini no kasher — nevertheless Magen Avraham needs settle matter — stringent Rashba — see Peri Chadash YD 98 stringent all year kli sheini.",
  "machatzit-hashekel/4:ב":
    "For explicitly in Gemara, etc. Pesachim challenges: Rav break pots — taught do not plug oven in attic — if plugged all bread forbidden lest eat with milk until heat oven — heated permitted; so pots permitted via heating? Answer both Rav and baraita pottery — baraita heated inside therefore heating helps; pot custom heat outside — not; challenge heat pot inside permitted? Answer: concern perhaps crack, etc.",
  "machatzit-hashekel/4:ג":
    "Make Temple oven of pottery, etc. Oven of Temple metal — thought reason sin-offering cooked — if pottery break each time — challenge make pottery — cook sin-offering then heat — heating helps as taught do not plug oven — answer: not make pottery — do not make sacred vessels of pottery.",
  "machatzit-hashekel/4:ד":
    "Speaks of tumah, etc. They challenged: Torah testified pottery never leaves rim — but leaves via kilns? Rabbenu Tam: not considered leaves rim — since heated becomes new vessel — Rabbenu Tam: challenge tamei oven why break — since new vessel make heating? Rashba: pot not custom heating — returning kiln new faces; oven always heated inside — not new faces — needs breaking — Tosafot.",
  "machatzit-hashekel/4:ה":
    "To make it like new vessel — so it must be.",
  "machatzit-hashekel/4:ו":
    "What Tosafot AZ regarding issur, etc. Tosafot there on pottery never leaves rim — challenge return kilns — Rabbenu Tam: not considered leaves — opposite like new vessel new faces — challenge: if new vessel — oven and stove break Torah said — why return kilns? Rabbenu Shimshon: certainly pots not custom heating — but oven/stove issur via heating — not leaves returning kiln — not called new vessel — Tosafot opened challenge oven break — implies challenge tumah as Pesachim — from answer: oven/stove issur via heating — explains issur heating/kilns ineffective — Magen Avraham: intended explain taught Pesachim 120b oven heated orlah peels — new breaks — finished via first heating issur — no remedy except break; also challenge kilns new faces — should permit kilns not break — answer: finished via issur — no remedy that oven; heating oven not new faces — first oven — ineffective; but expel issur absorption — Tosafot AZ agree heating oven helps.",
  "machatzit-hashekel/4:ח":
    "For Gemara says, etc. Until heated — baraita do not plug oven in attic, etc. above.",
  "machatzit-hashekel/4:ט":
    "Further it appears in bricks, etc. Bach stringent oven even kilns ineffective — nevertheless concludes all this specifically pottery oven/stove; brick pad from bricks and clay — internal heating helps — Tosafot view.",
  "machatzit-hashekel/4:כ":
    "Earthenware vessel law. Did not find explained earthenware law — we do not hold thus — stone vessels siman 8 metal law; Kaf HaChayyim 461:3 what we call oven — plaster clay finger-thickness below sides above; some whiten oven with coals — appears from Magen Avraham new oven certainly pot law — filling coals concerned; Peri Chadash 461 dispute Rambam Tur Rashba — see there.",
  "machatzit-hashekel/4:ל":
    "Rather, etc. So girsa — rather if metal — even this — my heart pounds — since custom make from fine material foreign language — coals ruin much — perhaps also concerned — requires study.",
  "machatzit-hashekel/6:א":
    "(s.k. 6) Kasher them, etc. Gemara implies: Ravina to R' Chisda — these Pesach knives how? I make new; if possible for you; not possible? Like new — handle clay (not burn at libun), iron in fire, then immerse boiling — conclusion both (handle and iron) in boiling kli rishon. Simple meaning R' Chisda answered like new — initial intent when said I make new — like new: handle clay, etc. — possible for anyone; for R' Chisda no difference possible/impossible — always like new; therefore halakha both in boiling applies possible and impossible — even possible suffices boiling.",
  "machatzit-hashekel/6:ב":
    "Holds this is Gemara meaning, etc. For impossible — so R' Chisda intent: since said possible I make new — without possible do like new; but possible — actual new; though conclusion boiling — may apply only impossible; possible should make new as R' Chisda — also for R' Chisda difference possible/impossible — same per halakha conclusion — see Taz.",
  "machatzit-hashekel/6:ג":
    "As YD 121: why knife from non-Jew needs libun — non-Jew uses on fire; chametz lenient — Israel not customary use knife on fire though sometimes — Mechaber goes other vessel majority use as seif 16; we stringent Rama gloss there — nevertheless rely permitted absorption chametz this — Kaf HaChayyim, Peri Chadash YD lenient even issur knife hagalah — nevertheless new preferable.",
  "magen-avraham/11:ג":
    "And practiced to whiten them. So too Levush siman 17; and so in Darkei Moshe — this gloss applies here; but in some books this gloss is in seif 16 regarding mortar — see Bach and Hagahot Semak there.",
  "magen-avraham/12:א":
    "Do not forbid b'dieved. For we do not say absorption travels through whole vessel, as Yoreh De'ah 121:6 (Darkei Moshe); Or U'Mussar ch. 58: kasher pot handle; b'dieved little concern, especially wood chip inserted whole into pot requiring kashering; also we hold vessel forbidden in part requires kashering whole; if spoon tip entered issur and kashered part and stuck in food — food permitted, spoon needs kashering again and insert whole in pot — end of his words. It appears specifically if stuck the part kashered; even if absorption spread whole vessel per YD 92 — we do not say it expels from side not inserted, as siman 94; but if stuck side not kashered — forbidden, as YD 92:5 drop of milk on pot; Darkei Moshe \"does not travel absorption\" means does not expel — see YD 121 on Tur. What is written \"do not forbid b'dieved\" — if already used; l'chatchila forbidden during Pesach if impossible to kasher.",
  "magen-avraham/13:ב":
    "Place coals. Requires study — Rashba not so except when solder preceded absorption, concerned substance in existence; Bach: when absorption preceded solder, coals do not help — must libun whole vessel; Or U'Mussar ch. 58:19. Therefore when absorption preceded solder — place many coals until sparks fly — \"until body of issur burns\"; if solder preceded absorption — light libun as seif 4 gloss. Old pewter-coated vessels — some require hagalah afterward; R' Eliyahu Mizrachi CA 43: no hagalah needed — like absorption preceded solder; concludes no hagalah — pottery needs light libun unable to touch other side; melted lead is like light libun; pewter interrupts — like new (even old pewter whitens); Hagahot Maimoniyot, Shelah siman 461; YD 120 immersion — above s.k. 24.",
  "magen-avraham/16:_":
    "Mortar. Tur wrote they regularly grind spices and sharp things with bread crumbs — some say requires libun like sourdough house; he ruled hagalah suffices as s.k. 22. Bach: our mortars need hagalah lest chametz absorbed via spices; do not whiten with coals lest crack — copper scrap; chametz stringency — grind spices before Pesach — nitelaf in nitelaf of permitted; even hagalah unnecessary as s.k. 1 barrel; if not — grind on 14th when kashering. World practices Rama to whiten; it appears law is with him even books say practice to whiten — but our mortars never have chametz, only saffron — hagalah enough. Bach grind before 14th after hagalah — nitelaf in nitelaf — study: sharp substance — nitelaf in nitelaf not effective YD 95; possibly mere stringency; sometimes cut ginger in meat knife and grind in mortar then eat with milk — beware, cut ginger only in new knife. If ground spices in our mortar in dish — study forbid b'dieved — suspicion knife cut; this suspicion we do not forbid b'dieved as seif 10 baskets — salting also sharp — see end and YD 96, Shach — ginger not called sharp per some — see there.",
  "magen-avraham/17:ב":
    "Not to use. Practice as said hagalah does not help sourdough house; if after hagalah place sheet or cloth to interrupt — permitted hot matzot as Semak 222 (Bach); deals putting hot matzot inside; do not be lenient to knead even with interruption; Semak concludes: correct to plaster with clay as siman 442 — see there.",
  "magen-avraham/18:ג":
    "Via laundering. Per Shach YD 138:8 — not suffice rinsing but full laundering as siman 442; however Tosafot and Hagahot Ashri end AZ imply cold suffices rinsing; Bach 453: chametz even undoing stitches laundering ineffective — chametz sticks — see there; however Piskei 447 lenient; Terumat HaDeshen intent likewise — scrape chametz well; cloths for matzot — forbidden second use even rinsing — dough sticks — laundering required; turning over insufficient — chametz oozes through.",
  "magen-avraham/19:_":
    "Not effective, etc. Because issur absorbs via fire itself: Maharam Rotenburg responsa 177 permitted matzah on peel used all year not scraped, brought to oven — peel bottom; may be so for matzah; wheat in salted meat — all forbidden. Levush permits peeling; even real chametz on matzah — remove place as siman 461 — not like Rashal who forbids siman 447:1. If regularly bake with fat — forbids all if not clean; fatty substance forbids all; if washed well — peeling suffices — vessel absorption we are not stringent whole vessel YD 104:5; all the more not ben yomo siman 447:10; YD 94:8. Terumat HaDeshen: even peeling and hagalah not effective on peel; Darkei Moshe Mahariv: peel threshed last year needs hagalah; Hagahot Maimoniyot: sour matzah threshed — forbidden to thresh more — bring another — Shelah; Epi Ravrevei: sour removed, mixed with others — nullified — logic absorbed issur does not leave without gravy — only first bread in existence; if mixed nullified — Or U'Mussar 39; we hold YD 105:7 vessel expels without gravy — Or U'Mussar; difference: first matzah all forbidden if grease concern; without grease — remove amount; others only peel after first cleaned; if mixed — nullified not davar shebeminyan — not issur from itself, only by mouth; Pesach not nullified siman 447:9 — Acharonim. All this: matzah became full chametz; doubled puffed — stringency siman 461 — forbid peel l'chatchila not other matzot — Hagahot Maimoniyot, Shelah.",
  "magen-avraham/1:א":
    "And permitted to leave them. Some say for chametz that became mixed it is forbidden to leave it, for there it appears though not recognizable; but absorption in a vessel is not visible and common (Ra'avad); so too Rabbeinu Yeruham; and so in the Ran. Some want to bring proof from Tosafot that specifically if they used them a little chametz is permitted, but if they used them much — forbidden; they did not examine well, for Tosafot [speaks] so per Rav, but we hold like R' Shimon — even if they used them much, permitted to leave them since not in existence; and therefore permitted afterward to cook in them l'chatchila.",
  "magen-avraham/1:ב":
    "And hide them, etc. Those who place vessels atop wall heights for decoration — even ten cubits high — forbidden (Bach); possibly they practiced thus because not ben yomo; and even if used, the majority permit as siman 447 seif 10; all the more so those whose main use is kli sheini or cold, like flasks — no concern; one who is stringent — see Radbaz vol. 1 siman 35.",
  "magen-avraham/1:ג":
    "Even in kli sheini. Meaning even if he did not pour from the pot into it, only poured from pot to kli sheini and then placed this vessel into it. Darkei Moshe wrote: per Tur it absorbs only via kli rishon or pouring; but kli sheini not — not like Beit Yosef. It appears even Rambam forbade only pouring regarding metal vessels used in kli sheini like bowls and cups — pour boiling water on them; bowls' use is via pouring. Furthermore from \"pour boiling water\" it implies hagalah must be via pouring; therefore it deals with use via pouring; and what is called kli sheini is because after pouring into it it is kli sheini. So too Rif; and Rabbeinu Yosef Karo omitted kli sheini law — he retracted. See siman 447 seif 3; already practiced to kasher everything; but b'dieved if used in a vessel known never used in kli rishon — requires study, for Rashba in Terumat HaDeshen is stringent all year in kli sheini and ruled peeling required — therefore at least on Pesach practice like him.",
  "magen-avraham/1:ד":
    "Lest it crack. Bach wrote it implies in pottery oven heating helps, not concerned for cracking; however in Tosafot Pesachim ch. 2 and Avodah Zarah ch. 2 — pottery oven even returned to kilns does not help; therefore even internal heating does not help; so we rule. He was not precise, for Gemara explicitly states this and that in pottery oven — heating inside, etc.; we hold like this answer; so too in Zevachim 95-96 — make Temple oven of pottery, etc. Tosafot who wrote heating does not help speaks of tumah — if became tamei, heating does not make it like new vessel; but for issur, once issur expelled — suffices. So too the Gaon in Chadashim. Tosafot Avodah Zarah regarding issur deals with oven heated with orlah peels; so too Tosafot Zevachim explicitly — see there. However Maharil wrote: not called kilns unless heated 2-3 days — see s.k. 22. Levush wrote to be lenient with heating and slight plastering; in any case heat well until whitened — then no worse than pot full of coals; here no concern for cracking; also Gemara explicitly says until oven is heated — does not require kilns; we establish in pottery. Further: bricks burned in kiln have all law of pottery — thicker; if boiling spilled — no remedy except libun; sun-dried brick has law of earthenware. See Tur Yoreh De'ah — earthen and stone vessels like pottery; we do not hold thus.",
  "magen-avraham/20:_":
    "In which they hide food. Plain boxes need no hagalah (Bach, not Beit Yosef). Darkei Moshe: no need boards; Maharil: place rags after hagalah — practiced lest chametz in existence.",
  "magen-avraham/21:א":
    "Via pouring three days. As yayin nesech law — use cold as YD 135:2. Agudah: cold-use vessels like flasks better pouring than kashering with hot vessels. Bach stringent: do not use beer barrel at all — grooves, impossible scrape — chametz in existence — Rosh Austria forbid all wood vessels especially barrel — Rashal, Maharam Lublin, Maharash Hursh; mead barrel — hagalah permitted though cooked in pot twenty-four hours — nitelaf in nitelaf permitted; see siman 447:5 we do not say nitelaf in nitelaf in chametz — nevertheless beer barrel clearly lenient; Levush: beer open staves scrape well; wine burn — hagalah ineffective — see Maharil.",
  "magen-avraham/21:ב":
    "And b'dieved if, etc. Chametz taste nullified in sixty before Pesach since permitted absorbed — need not estimate whole barrel; also nitelaf; also yeast in wine is nitelaf — Mordechai; Terumat HaDeshen: reason damage — see there; per siman 447:10 forbid nitelaf on Pesach — must be: if put wine or honey before Pesach — permitted to drink on Pesach if estimated before to Pesach barrel; wine even ben yomo permitted — yeast nitelaf as YD; mead not damage — if ben yomo even before Pesach forbidden without sixty against chametz — siman 447:5; Terumat HaDeshen: yayin nesech barrel even not ben yomo all forbidden — eye sees improves taste — YD 137:69 wine — see siman 447:5.",
  "magen-avraham/22:ד":
    "On the oven. Same on tiles — custom put crusts and chametz pieces — pottery never leaves rim — not kilns (Maharil): put iron beneath, use on Pesach; per s.k. 1 not kilns; heating ineffective — heated outside s.k. 2; Bach 446: study forbid b'dieved food in pot on hot oven — we hold issur does not spread rim to rim; also our ovens only clay on top — replaster new clay finger-thickness — chametz does not spread through clay; partial ovens pots all around cover above — if placed for pot with food on Pesach — clearly forbidden as pot inside hot pottery — certainly eating — not so — no chametz trace — received from Maharash Hursh; Maharam Lublin responsa 107: winter oven pot inside Pesach — excessive stringency — no posek except Mahariv — suffices forbid l'chatchila not b'dieved; appears no spread rim to rim YD 92:8; even if chametz in existence — peeling suffices no gravy — pot forbidden food permitted siman 9; if cover above — hand not scalded in steam above — if inside oven even scalded in cover permitted — oven already heated — not intended to kasher — b'dieved permitted as above.",
  "magen-avraham/23:א":
    "In glass coating. Possibly means Mordechai: coated in glass coating — permitted hagalah in metal; so Levush; must be coated actual glass; what is called glaze even glass coating — hagalah ineffective — no substance, only color — Rambam: vessels smeared/shiny like glass forbidden; Tosafot AZ 33; YD 120.",
  "magen-avraham/23:ב":
    "And some places. Because hold in hoops — return only to oven merely heated — not kilns unless 2-3 consecutive days (see s.k. 1). Responsa: even those receiving little tin from other pots forbidden; reason return kilns permitted — hoop tin burns — craftsman not concerned burn more; fully coated — concerned not ruin tin; Gaon: should forbid all year lest old vessels coated — permitted because perhaps not ben yomo — stricter Pesach; responsa: not recognizable absorption — concern non-Jew used; Darkei Moshe Mahariv: ask craftsmen how made — like first reason; now some places Jew stands over work; second reason — be stringent.",
  "magen-avraham/23:ג":
    "Even if new. Lest coated old or dyed — Maharil: do not use dyed vessels in saffron.",
  "magen-avraham/26:א":
    "And so is custom. B'dieved do not be stringent (Darkei Moshe): if cold use — permitted even without hagalah; if hot use — b'dieved hagalah helps; if chametz stood twenty-four hours — law as hot use s.k. 6; all the more those putting yayin nesech for preservation — unlike vinegar — YD 135:8 many lenient vinegar not so chametz — end.",
  "magen-avraham/26:ב":
    "Does not damage. Do not use important vessels in boiling; if poured boiling — Mordechai ch. 3: cooked in part of vessel — absorption does not travel whole vessel — study Tosafot Zevachim 91; Terumat HaDeshen; YD 92 — we hold Tosafot Zevachim stringently travels whole vessel — see s.k. 2.",
  "magen-avraham/27:א":
    "That they roasted, etc. — permitted. Chametz taste nullified before Pesach (Mordechai); even dissenters siman 447:4 agree no known chametz here (s.v.); see there 3; siman 10 — in vessel we do not nullify issur — here safeik do not establish issur was chametz. If roasted once molasses or other chametz and did not whiten between — forbidden.",
  "magen-avraham/3:ג":
    "Still boiling. Heated — some practice white-hot stone on knife and pour boiling as s.k. 6; appears incorrect on knife — stone sits well in stone vessel, not knife.",
  "magen-avraham/3:ד":
    "And grease, etc. Grease stuck in existence — if open stitches and scrape well perhaps permitted siman 8.",
  "magen-avraham/4:ג":
    "Some are lenient, etc. Mordechai, Hagahot Maimoniyot — libun milk to meat as siman 499:5; chametz requires serious libun as pan — only Darkei Moshe: Or U'Mussar chametz permitted absorption — light libun enough chametz; siman 447:5 Rashba issur absorption — b'dieved forbid if not libuned so much.",
  "turei-zahav/10:_":
    "Baskets they salt. Third view: concern chametz in existence in holes — Maharil — even hagalah ineffective — wonder Shulchan Aruch agreed second lenient view — Maharil correct — in existence hagalah ineffective — should rule forbid even with hagalah — Moharach agrees.",
  "turei-zahav/13:_":
    "As it absorbs so expels. Mordechai: even without hagalah before adhesion seemed permit — concern strong adhesion loosens Pesach expels beneath; wonder what hagalah before adhesion helps — concern chametz entered in adhesion in existence — hagalah only for expelled taste not Pesach in existence; therefore only very adhered adhesion impossible chametz enter — must place burning coals burn chametz — Beit Yosef Rashba responsa; solder piece on piece nails; pewter drip from heat burns all in existence; silver spoon repair — fire first — no concern; Tur 100 hard: after use before Pesach kasher as absorbs so expels — then provided parts without cracks — else chametz in existence.",
  "turei-zahav/16:_":
    "Some stringent to whiten mortar. So girsa — Rashi: mortar like sourdough/charoset house — hard leaven — hagalah ineffective; mortar ground all year sometimes crumbs with fat pepper — small mills — Tur, R' Yitzchak: sourdough house hagalah helps; Mordechai ch. 20 great one demonstrated: dedicated stomach-salt pan — washed, hagalah, milk curdled without rennet — taught hagalah ineffective charoset house; Terumat HaDeshen 130, Piskei 182 resolve: not nitelaf but stomach water strength — Tosafot all meat: rennet in hide, fill coals whiten until thread burns — great one challenged lest crack like pottery above — Moharach disputes; Rama stringent whiten — siman 447:7 unripe grapes pounded in mortar chametz-like Pesach — difference: not use mortar itself on Pesach — pounded before Pesach even expels via pressure Semak small expulsion nullified before Pesach — not on Pesach itself in amount — all agree spices pounded before Pesach permitted; even Rashi if hagalah first — Rama stringency whiten — siman 22 proves do all possible; gentile mortars lighter chametz to matza — Terumat HaDeshen.",
  "turei-zahav/17:_":
    "Even via hagalah. Beit Yosef: impossible scrape clean — hidden crack chametz — therefore careful not kasher Pesach vessels held flour, barrels Russian sovina drink — lest chametz in existence; if held water before Pesach — no worse than old liquids Rama below — undoing stitches laundering helps.",
  "turei-zahav/19:_":
    "Peel. German schievel — fire use — hagalah does not permit — customary. Keep this Pesach peel next year — no kashering; trough knead matzot — heard some kasher next Pesach — unknown reason — this Pesach bakes daily without kashering — perhaps less careful scrape next year than Pesach itself — lost by winning: viewer thinks chametz peel kashered for Pesach — better not kasher — scrape well each Pesach carefully; righteous walk in them.",
  "turei-zahav/1:א":
    "And good to lock in a room, etc. From here Moharach challenged those placing chametz tin vessels above unreachable place — must lock in room; height does not help as Shabbos candle even ten cubits — rabbis did not differentiate; appears those keeping Pesach vessels all year high — no concern forget bring salt and use chametz — if cook later on Pesach only nitelaf — mere Pesach stringency — they did not decree lest not differentiate.",
  "turei-zahav/1:ג":
    "See Yoreh De'ah siman — there explained occasional use permitted if rinsed first.",
  "turei-zahav/21:א":
    "Permitted in hagalah. Pottery never leaves rim — only absorbed via fire; cold — hagalah suffices — not coated not coated; Tur R' Yoel: from this support YD 105:1 impossible pressed like cooked — vessel absorption nitelaf else stringent cold here pressed like cooked — certainly not less than many days wine — Mordechai below: do not estimate whole barrel — sleeping spoils — etc.",
  "turei-zahav/21:ב":
    "Or via pouring, etc. Tur: end AZ pouring not better than hagalah; YD 138:7 contradiction pouring vs hagalah — resolved: pottery Torah testified hagalah ineffective — not master whole vessel — pouring better; other vessels hagalah better in short time — less absorption — here cold use not pottery testimony — hagalah better.",
  "turei-zahav/21:ד":
    "And b'dieved if, etc. Mordechai ch. 20: yeast taste nullified sixty before Pesach — does not return Pesach — do not estimate whole barrel — unknown how much leaves — here permitted absorption therefore estimate what expels nullified sixty; all absorbed in vessel sleeping spoils — R' Yitzchak: nitelaf Pesach permitted. Beit Yosef: most poskim do not hold permitted-absorption helps chametz — wondered already proved siman 4 we hold this — Beit Yosef siman 4 spits Rosh baraita libun — proves not this view — no proof — there chametz in existence on spit.",
  "turei-zahav/22:ב":
    "But via hagalah, etc. R' Yitzchak permits all in hagalah — seif 16 mortar — Rama silent — halakha so; why brought mortar stringent whiten practiced — seems ruled l'chatchila Rashi — certainly not — Rama relied on mortar to learn mortar above — not here primary — other vessels no libun wood pewter — Rama left lenient.",
  "turei-zahav/27:_":
    "Old spit, etc. See siman 4; here Shulchan Aruch ruled lenient first view seif 3 regarding returns.",
  "turei-zahav/3:א":
    "Knives — kasher in hagalah, etc. Gemara: Rav Huna to Rava — Pesach knives how? New ones. If possible for you, not for everyone? Like new — handle in clay, iron in fire, then immerse in boiling — halakha both in boiling kli rishon. Why Pesach specifically? Why not all year kashering? Why \"knives in Pesach\"? Why \"for me\" more than others? Why \"if possible for you\" — law depends on possible? It was obvious boiling helps knives — Ravina stringent more than other vessels — frequent chametz/matza use, hidden cracks — proper extra caution beyond law — \"how do we do\" — counsel; \"for me new\" — I am stringent, not relying on minimum law; \"if not possible\" — counsel for impossible — like new: iron in fire; Gemara concludes both in boiling — libun in fire for iron is piety; piyyut clear: knife used for chametz for guests — if new, praiseworthy; if not, kasher in boiling — legally boiling enough, new knives better.",
  "turei-zahav/3:ב":
    "All rust. \"Only gold and silver\" — must remove rust — what we call rust has substance from sheltered place — when scraped like dust; concern chametz substance under rust — hagalah not for in existence; sometimes black/red stain on vessel especially pots — no substance, only appearance — may kasher after scraping all possible; else one city cannot kasher; therefore if crevices in knife — seif concludes; without crevices only if cannot remove black — no concern — hagalah after scrape; still whiten that place — advice.",
  "turei-zahav/3:ג":
    "Requires libun, etc. Libun need not remove rust — fire burns all — YD 121.",
  "turei-zahav/4:_":
    "Such as spits, etc. Baraita end AZ for other issurim; Rif brought in ch. 20 — chametz too needs libun — used via fire; Ran: even permitted absorption — hagalah enough; chametz named issur — absorption called; Beit Yosef: Rosh also brought baraita ch. 20 — question: we hold chametz nullified before Pesach permitted siman 447:4; hagalah time siman 492 — permitted absorption; spits Mordechai ch. 20 — roasted unsalted meat Pesach permitted — nullified before Pesach — siman 27; pan fried chametz permitted hagalah siman 461:1 — why libun spits? Must be chametz in existence on spit like oven bread without gravy — needs libun Rosh; lenient Rama brought Mordechai — not only spits but other absorbed permitted like milk/meat — light libun to scald both sides or burn straw — permitted absorption via fire — light libun not less than hagalah; Rama here chametz Pesach — permitted absorption; if chametz actually on spit like oven without gravy — certainly Mordechai agrees full libun — Rama left law on lenient side unlike mortar where possible to whiten — other vessels wood/pewter no libun on Pesach if use like sourdough house — Rama left on lenient as lenient view.",
  "turei-zahav/5:א":
    "Rather must pour, etc. Pouring at least helps since use also via pouring; vessel used via fire — not kasher via pouring, only kli rishon.",
  "turei-zahav/6:א":
    "Kasher bowls — appears stringency because masses do not distinguish mostly kli rishon or sometimes. Rama: so all things like ladles — ladles stricter — often turned in pot at fire.",
  "turei-zahav/7:_":
    "Horn-handle knives. Maharil: same horn handle fixed with glue — cannot kasher — concerned glue ruins.",
  "turei-zahav/9:_":
    "Explained siman 492.",
};
