/** siman 451 part 1 — mishnah-berurah (47 remaining blocks) */
export const HAND = {
  "mishnah-berurah/1:ד":
    "(4) All year — and the same even if they used them for chametz during Pesach, b'dieved scrubbing well suffices and it is permitted to keep them until after Pesach, as explained above at the beginning of siman 447 [Chok Yaakov and Levushei Serad]; and in Peri Megadim he questions if one cooked in them on the seventh of Pesach in Eretz Yisrael or on the eighth of Pesach for us in chutz la'aretz while the vessel is still ben yomo — whether one may not use it — see there.",
  "mishnah-berurah/1:ה":
    "(5) Even those they make etc. — meaning that then they have absorbed much chametz, and if one cooks in them after Pesach certainly there will not be sixty against it; nevertheless it is permitted. The reason: we hold chametz after Pesach is permitted from the Torah and is forbidden only due to the penalty that the Sages penalized for having kept the chametz; but they penalized only on the chametz that exists in substance, not on what is absorbed in the vessel; therefore it is permitted even l'chatchila to cook in them afterward.",
  "mishnah-berurah/1:ס":
    "(15) Even cold — meaning even if they rinsed and scrubbed well, we are concerned lest one come to use it with hot food; and see Yoreh De'ah siman 121 that the same applies to other prohibitions; therefore one should be stringent in our matter even on erev Pesach after midday.",
  "mishnah-berurah/1:ע":
    "(16) And see Yoreh De'ah siman 121 — where it is explained that by temporary use it is permitted if one rinsed and scrubbed first; and see above at the end of siman 452 and in Mishna Berurah there.",
  "mishnah-berurah/2:ב":
    "(18) And if they filled with coals etc. — the reason is that ordinary kuvia do not tend to crack, and therefore one need not be concerned lest he be cautious with it and not whiten it well. Bricks burned in a kiln have the law of pottery vessels, and if boiling chametz was poured on them they have no remedy except libun as is its law, and as will be explained in siman 461 [nevertheless libun helps for them even within our ovens, for we are not as concerned for them as for pots]. But bricks dried only in the sun have the law of earthenware vessels and hagalah helps for them; and if baking or roasting was done on them, their use is through fire and they require libun as stated.",
  "mishnah-berurah/3:ג":
    "(21) On a whetstone — and the same applies with anything else that removes rust.",
  "mishnah-berurah/3:ה":
    "(23) If it has crevices — and for this reason Acharonim agreed that a knife whose handle is attached with small nails — hagalah does not help, for there are many crevices at the place of the nails; how much more so if the body of the handle is made from two glued parts with a slight gap between them to insert the knife blade — for usually one cannot scrape there well. Sometimes there is a flaw between the blade and handle and one cannot clean that place well unless one removes the handle from the blade [Peri Megadim]. And if the knife handle is glued to the grip with adhesive — hagalah does not help, for since the adhesive deteriorates in boiling water, one must be concerned lest he be cautious with the adhesive and not boil the water well; likewise if the handle is made of horn — hagalah is not effective, for horn deteriorates in boiling water and one must be concerned lest he be cautious with it [Acharonim].",
  "mishnah-berurah/3:ו":
    "(24) And requires libun — meaning one places burning coals on that place; and with libun one need not remove rust, for fire burns everything.",
  "mishnah-berurah/3:ח":
    "(26) It has no remedy through hagalah — because one cannot scrape it well from inside unless one opens the stitching and scrapes well, and then even hagalah is not required. A vessel whose mouth is narrow and has rust there that cannot be removed — hagalah does not help for it [Acharonim]. They also wrote that anywhere hagalah is required, peeling with artisan tools does not help, for absorption exits from wall to wall, and artisan tools help only where peeling is required.",
  "mishnah-berurah/4:א":
    "(27) Through fire — meaning without water, such as a spit and skewer on which one roasts chametz directly [and even though when roasting on meat they coat it with fat or grease the face with fat, this slight moisture does not prevent the fire from fully dominating it, and it is not comparable to a pan explained below in seif 11]; and since the body of the chametz touches them during roasting and there is no liquid between them to carry chametz taste into the spit and skewer except through fire heat alone — chametz taste is absorbed in them; therefore it is not expelled from them through hagalah in boiling water either, except through fire heat, for as it absorbs so it expels. But if one knows he did not roast chametz on it, only that he roasted meat with unsifted salt — hagalah suffices, even l'chatchila.",
  "mishnah-berurah/4:ב":
    "(28) Require libun — I will precede with a brief introduction and will need it in several places. Know that the Gemara teaches that specifically prohibited matter absorbed in a vessel through fire requires libun; but permitted matter absorbed through fire, even if later forbidden — such as kodshim meat roasted on a spit over fire, even if ultimately the absorption in the spit became notar — nevertheless kashering that spit requires only hagalah; and poskim dispute regarding chametz absorbed in a vessel: some say this too is called hittira belia, for when chametz of the roast was absorbed in the spit during the year it was permitted, and therefore hagalah suffices; according to them, all vessels whose use is through fire for Pesach need only hagalah. Others say: specifically notar at the time of absorption — there was no notar on the meat at all, therefore it is called hittira belia; but chametz — at the time the spit was used with chametz, chametz was on the absorption, and now too it is called chametz, only now the prohibition was retroactively aroused on account of this chametz — this is not called hittira belia, for chametz is absorbed within and it is still chametz and falls under issura belia, and libun is required. Most poskim agreed to this, and therefore the Mechaber ruled like them; nevertheless one should not infer from this law to other places, for sometimes where there are other grounds to be lenient we combine also the view of poskim who hold chametz is called hittira belia.",
  "mishnah-berurah/4:ו":
    "(32) And the practice follows the first view etc. — for according to our law the main rule is like the Mechaber's view that chametz is called issura belia, and therefore requires proper libun so sparks fly from it; and even b'dieved one should forbid if they used it on Pesach before libun to that degree or through hagalah [Taz and Magen Avraham]; however, in a place of great loss or prevention of Yom Tov joy, and it is not ben yomo from when chametz was used in it, one may rely b'dieved on poskim who hold chametz is called hittira belia, and it suffices that they kashered through hagalah or light libun.",
  "mishnah-berurah/5:ב":
    "(36) That one stirs with it in a pot — according to one view brought in Tur Yoreh De'ah siman 121: an item whose use is in kli rishon on the fire must also be kashered in a kli rishon standing at the fire specifically; and this spoon with which one stirs the pot while it is still on the fire requires kashering in this manner also [Peri Chadash and Chayyei R' Akiva Eiger].",
  "mishnah-berurah/5:ז":
    "(41) To pour on it etc. — and one must be careful that the stream not stop; and know that pouring helps only for something whose use was also through pouring; but a vessel whose use was through kli rishon cannot be kashered through pouring except through actual kli rishon.",
  "mishnah-berurah/5:ח":
    "(42) That have cracks etc. — due to concern for chametz b'eyna, for hagalah does not help; and likewise below s.k. 63 — see there.",
  "mishnah-berurah/6:ב":
    "(46) Such is their kashering — nevertheless, if it is known that within twenty-four hours they used it for chametz in actual kli rishon, even though its main use is always through pouring or in kli sheini — they require hagalah in kli rishon specifically, according to all views; and if through fire — libun is required.",
  "mishnah-berurah/9:_":
    "(58) And he is not concerned — will be explained below in siman 452.",
  "mishnah-berurah/10:ג":
    "(61) And good to kasher them — through pouring from kli rishon; and even though explained below in siman 18 in the gloss that hagalah does not help for them — that refers to where they are used for chametz all year and chametz crumbs commonly adhere in the holes; not so here. All this is l'chatchila; but b'dieved, even if they did not kasher them and salted meat in them on Pesach, it is permitted to eat the meat, even if one knows chametz was absorbed in the baskets through salting — for salt does not expel what is absorbed inside the vessel.",
  "mishnah-berurah/11:ה":
    "(67) However it suffices for him etc. — meaning by law; and in Peri Chadash he sides that by law libun is required — see there; and see in Biur Halacha.",
  "mishnah-berurah/13:ה":
    "(76) Until it burns etc. — for the first reason: due to chametz b'eyna, light libun suffices, that the straw burns from outside — in this certainly the chametz b'eyna burns, as above in the gloss regarding other cracks. For the second reason, severe libun is required — one should place many coals on that patch until sparks fly from it, then certainly the absorbed prohibition in the vessel burns. It appears that when not ben yomo one may rely to be lenient. All this is regarding a patch that is like a plate attached to the vessel with nails as is common in pots; but a patch attached through fire, as is done on a pewter vessel that is holed, where they drip melted iron — they are kashered through hagalah and one need not place coals on the patch even if absorption of prohibition in the vessel preceded, for through pewter heat all substance of prohibition beneath burns if it exists there; and absorption beyond the patch is expelled through hagalah, and the patch does not hinder at all, since attached through fire heat it becomes like one actual vessel [Acharonim].",
  "mishnah-berurah/14:ג":
    "(82) And if they placed it on Pesach etc. — even if the cover was washed well so there is no concern for chametz b'eyna, nevertheless it is forbidden due to exudation of absorbed chametz within that descends and mixes in the cooked food through the steam rising from the cooked food to the cover when it is boiling; and on Pesach its prohibition is in any amount. If they placed it on erev Pesach after six hours, then if there are sixty in the cooked food against the entire cover — permitted; and likewise if the cover is not ben yomo from when chametz pots were covered with it — permitted in time of pressure according to all, for it gives taste for spoilage on erev Pesach is permitted; not so on Pesach — even if not ben yomo it is forbidden according to Rama above in siman 447 seif 10 in the gloss.",
  "mishnah-berurah/16:ה":
    "(90) To whiten l'chatchila, however it suffices for him etc. — meaning that by law hagalah alone suffices like the first view; but the custom is to whiten it (until a straw etc. burns); therefore in a place where libun is impossible, such as in a wooden vessel, hagalah suffices if it is smooth and has no crevices. Acharonim wrote that our small mortars, in which they never grind chametz all year, only saffron and spices — hagalah suffices l'chatchila even for metal ones; nevertheless hagalah is required, lest perhaps before Pesach some chametz in any amount entered and was absorbed through sharpness of the spices ground afterward; and it is a mitzvah from the preferred to hagelah and grind everything before Yom Tov. B'dieved, even if he did not hagelah at all and ground spices in it on Yom Tov and put them in cooked food — Acharonim side to permit the cooked food, and especially if not ben yomo; certainly one should not be stringent b'dieved from a doubt lest a chametz crumb mixed in the spices ground in it, or that he cut ginger etc. with a chametz knife — for we do not establish a prohibition from doubt. All this is in a mortar where there is only concern for absorption of a little chametz; but in a hackmesser whose practice is to cut onions with a chametz knife and place it in meat and cut the meat very fine with the hackmesser — one may say that even b'dieved it is forbidden [Chayei Adam]; and indeed as practiced, they also put a piece of wheat bread with the onions and cut everything together very fine — then it is absorption of actual chametz together with sharpness of the onions; certainly one may not be lenient. Magen Avraham wrote: one should be careful not to cut ginger only with a new knife; and those who are not careful in this cause damage, for they cut ginger [which is a sharp substance] with a meat knife and grind it in the mortar, and the mortar becomes absorbed with meat, and afterward they grind spices in it and eat with milk.",
  "mishnah-berurah/17:ג":
    "(94) Not to use on Pesach etc. — and the reason: because one cannot scrape and clean them well so nothing of chametz remains in some crack not visible to the eye; and for this reason they are careful not to kasher for Pesach barrels in which they kept a drink made in the Russian lands from subin water (called wasser in Yiddish), lest chametz b'eyna remained from the subin; unless they kept water in it some time from the beginning — then it is permitted to kasher it, for the water that stood in it rinsed and removed all chametz adhering to it; nevertheless one must return and clean well before hagalah [and likewise vessels in which they keep flour all year — they also practice not to kasher them for this reason]; and see in Chayei Adam who wrote that this applies specifically to a vessel made from one piece; but those made from many boards like our vessels — it is known filth enters between board and board — for these hagalah does not help even after soaking in water several days; and see below s.k. 131 in Mishna Berurah.",
  "mishnah-berurah/17:ד":
    "(95) They knead on them — and if occasionally, poskim imply they practice hagalah.",
  "mishnah-berurah/18:ב":
    "(99) For all other kneading vessels — and regarding hagalah he did not mention in this seif, for he already explained above in seif 17 that if they kneaded in it all year it requires hagalah; and here he teaches us that we should not say it suffices with hagalah alone; or that here it deals where they knead in it only occasionally, that by law hagalah is not required.",
  "mishnah-berurah/18:ה":
    "(102) Called reib eizen — for sometimes they crumble chametz bread on it, and it is impossible that some crumb did not remain inside its holes; and also the temecha (called charain) that they dragged on it all year and cut with a chametz knife — and temecha is a sharp substance and chametz taste was absorbed in it; and afterward when they grind on it, chametz taste is found in it; and in this, even b'dieved one should forbid if they used it on Pesach, even if they used it cold, such as crumbling matzah on it [and how much more so charain, which is a sharp substance]; and even if they scraped it well beforehand, because it is impossible that a chametz crumb or charain crumb that was absorbed from chametz did not adhere to it. But when they used it on erev Pesach — there are distinctions: if they used it only with matzah on erev Pesach, even if a chametz crumb mixed in it — they are nullified in sixty within it and it is permitted to eat until night [but when night arrives the crumb returns and is reawakened and forbids in any amount, as explained in siman 467]; and if they crumbled charain on it on erev Pesach, which is a sharp substance — sixty is required against all the reib eizen, for the whole becomes chametz through absorption absorbed from the charain crumbled on it and cut with a chametz knife as stated; and if not the whole — forbidden.",
  "mishnah-berurah/18:ט":
    "(106) Through laundering — meaning in hot water, ashes, and beating [Acharonim].",
  "mishnah-berurah/18:י":
    "(107) All the stitching in them etc. — see below in seif 452 seif 66 and in Mishna Berurah there.",
  "mishnah-berurah/18:כ":
    "(108) Before laundering — and one must also scrape there first with a knife well the chametz found there [Magen Avraham and Shulchan Aruch HaRav]. They also wrote that the sheet on which they make matzot, which must be replaced between kneading and kneading — meaning after the measure of a mil as below in siman 459 — if one wants to knead on those same sheets again, complete laundering as stated is required, and rinsing alone does not help, for dough adheres to them; and how much more so it does not help if one wants to turn them to the other side, for chametz oozes and goes from side to side; and also the stitching in the middle of the cloth must be undone. B'dieved, if one transgressed and made matzot on the sheet without any laundering — if during Pesach, even b'dieved one should forbid; but if he turned the sheet or laundered it even without undoing the stitching — one need not be stringent [Kaf HaChayyim and Shulchan Aruch HaRav].",
  "mishnah-berurah/19:ב":
    "(109) That it does not help — because it absorbs from chametz through fire without any liquid; and to whiten it is impossible, for it is of wood; and see in Ateret Zekenim who wrote that all this is l'chatchila, but b'dieved if one used a chametz peel for matzah after hagalah — it is permitted.",
  "mishnah-berurah/19:ג":
    "(110) Hagalah — and even peeling with artisan tools beforehand also does not help. B'dieved, if one removed hot matzah from the oven with a chametz peel — if the peel was not clean but had visible chametz filth, it forbids on the underside of the matzah kedei netilah, which is the width of a thumb (and according to what we practice to bake thin matzot — the whole is forbidden); and if they baked chametz cakes with fat on this peel — the whole matzah is forbidden, for through the fat the chametz spreads throughout [and specifically during Pesach; but before Pesach until night that little b'eyna on the peel is nullified in sixty]. But if they rinsed the peel beforehand and there is no chametz b'eyna on it, only what was absorbed in it — it forbids only kedei kelipah, whether they used it beforehand with fat or without fat, for prohibition absorbed in a vessel cannot forbid more than kedei kelipah. If one removed chametz matzah with a Pesach peel and afterward threshed other matzot in it and they were forbidden through the peel, and afterward these mixed with many other kosher ones — all are forbidden, for it was already explained in siman 447 that on Pesach dry is not nullified in dry; and even if mixed on erev Pesach, nevertheless it returns and is reawakened during Pesach and forbidden to eat on Pesach [and only on erev Pesach it is permitted to feed them to a child]; and some say that since it was forbidden only from absorbed matter it does not return and is reawakened on Pesach; and all this is with full chametz. But in a peel from which they removed doubled or puffed matzah — it suffices to forbid the peel l'chatchila, but b'dieved it does not forbid; and more than this Kaf HaChayyim wrote: if one cannot easily find another peel, it is permitted l'chatchila to remove matzot with it, for otherwise one would always need a new peel and it would be like b'dieved; and if they were in doubt about the peel whether it was chametz or new — all the matzot are permitted.",
  "mishnah-berurah/20:ב":
    "(114) To pour on them etc. — from kli rishon; and Mahariv siman 193 ruled that pouring does not help, because sometimes one places hot pashida on it and it is as if used in kli rishon; rather one should kasher them through a white-hot stone and pour boiling water on it and roll to another place and pour so the boiling water goes over all of it [and with this it suffices even if the boiling water is from kli sheini, for it boils on the board and is like kli rishon]; and then it is permitted to place even hot matzah on them; and b'dieved it is permitted through pouring alone; and see above in seif 66 in the gloss and in Mishna Berurah there.",
  "mishnah-berurah/20:ג":
    "(115) Boiling water — and some wrote that one should place on them additionally a cloth or board as interruption, lest chametz b'eyna still adhered to it; and see in Ateret Zekenim who concludes that thus one should practice with boxes and magadim, for it is nearly impossible to purify them so nothing remains between the adhesions; but on simple tables one need not be stringent; and see below in siman 452 seif 1 and 2 in Mishna Berurah there.",
  "mishnah-berurah/21:ג":
    "(118) Three days — meaning one fills it with water, even cold, over all its edges, and lets it stand inside twenty-four consecutive hours or more; and afterward pours out the water and fills it with other water and lets it stand inside twenty-four consecutive hours; and afterward pours them out and fills it with other water and lets it stand inside twenty-four consecutive hours; and these three above need not be consecutive, but even scattered, as explained in Yoreh De'ah siman 135; and even in mead, pouring helps, as stated in Yoreh De'ah. And know that Shach's view in Yoreh De'ah siman 135 s.k. 133 is that for other prohibitions one may not be lenient through pouring three days if the prohibition was pickled in a permitted vessel above, for we hold pickled is like cooked; and in cooked, according to all, pouring does not help even in other vessels that are not pottery — see there.",
  "mishnah-berurah/21:ו":
    "(121) If they put in them — and they stood there above, it is like pickled and taste of the lees entered — nevertheless it is permitted, as below, for otherwise it is obvious it is permitted.",
  "mishnah-berurah/21:ז":
    "(122) Wine or honey — see Magen Avraham and Kaf HaChayyim that there is a distinction between wine and honey: in wine, even if the barrel is ben yomo from absorption of lees — permitted b'dieved, for lees in wine gives taste for spoilage; but in honey-water it is not for spoilage unless the vessel was not ben yomo from absorption of lees; but if it was ben yomo and the honey-water stood in it above — even b'dieved forbidden to drink on Pesach. But several Acharonim agreed that even in honey-water it is permitted even if ben yomo, for the reason that pickled is not called such until it stood above, and then the absorption in the vessel becomes for spoilage and is permitted b'dieved. And know that in all aspects of this b'dieved permission it applies only when they poured the wine and honey from the barrel before Pesach and put it into a Pesach vessel — for the wine and honey were already permitted before Pesach, for before Pesach taste for spoilage is permitted; but if the wine and honey remained in the barrel until during Pesach — forbidden, for in our lands we practice to forbid taste for spoilage on Pesach, as above in siman 447 seif 10 in the gloss; and poskim wrote that if they put something sharp like vinegar in it, even if not ben yomo — forbidden, for through sharpness it improves taste. Poskim also agreed that if the vessel was of yayin nesech — forbidden b'dieved even if not ben yomo, for our eyes see it gives taste for improvement. Behold Levush implies that even if hagalah was done, what was put into it is forbidden even if not ben yomo, because our eyes see taste and smell remained even after hagalah; however, if smell of yayin nesech is not detected, hagalah helps b'dieved so as not to forbid what was put into it; nevertheless, as soon as one remembers, one must pour the wine into another vessel.",
  "mishnah-berurah/22:א":
    "(124) That they used them for chametz cold — meaning they used them for dry chametz, or even for something moist but did not stand there above, and it was not a sharp substance; for if it stood inside above, it becomes like pickled inside, even in other vessels, and requires hagalah or pouring, as below s.k. 131.",
  "mishnah-berurah/22:ה":
    "(128) Baked matzah — cold; and the same applies to other cold things, even moist, if they rinsed first; and specifically by temporary use and not fixed use, as below in seif 61 in the gloss.",
  "mishnah-berurah/22:ח":
    "(131) But through hagalah etc. — permitted, both to knead in it and to use them with hot food. And behold, all this is from essential law; but according to what Rama wrote above in seif 17 that the custom is not to use kneading vessels because one cannot scrape — certainly one should be stringent also in a sourdough starter container. And if it is of metal, Rama already wrote above in seif 90 regarding a mortar that poskim equated it to a sourdough starter container — they practice l'chatchila to whiten it; and how much more so in an actual sourdough starter container.",
  "mishnah-berurah/22:ט":
    "(132) One should not use them for matzah even cold — one should not use them for matzah except cold: such is the girsa of Bach and Peri Chadash; and some read \"even cold.\" That which is written at the beginning of the seif that cold is permitted — applies to sourdough starter and charoset, and does not deal with pottery.",
  "mishnah-berurah/22:ל":
    "(135) Its law is like pottery etc. — meaning pottery never expels absorption from within its wall except through heating (where concern lest it crack does not apply, as above in seif 62 regarding a small fire); and here heating that they heat from inside [even if they kasher as required] does not help to expel absorption absorbed from above, and it is comparable to what is explained there in seif 62 that something heated from outside — heating does not help to expel what was absorbed from the other side.",
  "mishnah-berurah/22:מ":
    "(136) To place anything on the oven — meaning when the oven is hot it is forbidden even if the matzah is cold; and likewise the reverse, when the matzah is hot even if the oven is cold. And when both are cold — by fixed use it is forbidden; by temporary use there is no prohibition if he scrubbed and cleaned the oven so no chametz b'eyna is found there, as explained above at the end of seif 61 s.k. 16. Regarding b'dieved: if he placed matzah when the oven was hot, or when the matzah was hot, or both were hot — it forbids on the underside of the matzah kedei kelipah. All this is when he placed the matzah without interruption beneath it; but if he placed pots with cooked food, even if both are hot — it does not forbid b'dieved, for absorbed prohibition does not exit from the oven wall to the pot wall; and l'chatchila pots are also forbidden to place there in all cases (unless both are cold). And when one places an interruption such as iron etc. beneath it, or plastered with clay finger-thickness — permitted to use everything from above; and all these laws apply also to kakalin made in ovens from the side, except there iron interruption or clay plaster below alone does not help unless he plastered with clay also on the sides and from above; however plaster from above does not hinder b'dieved. And when one places a cover on the pots placed there — permitted l'chatchila even when there is no plaster from above. And now we will explain regarding inside the oven: if they did not kasher beforehand, if one placed matzah inside — its law is like on the oven, as stated. Regarding baking matzot there — its law is as explained in siman 461 — see there. Regarding cooking inside — even though l'chatchila one must kasher it also for this like for baking [or plaster its floor with clay finger-thickness] — nevertheless b'dieved one does not forbid the cooked food even if they did not kasher.",
  "mishnah-berurah/25:א":
    "(145) Through rinsing — see above in Mishna Berurah s.k. 49.",
  "mishnah-berurah/25:ד":
    "(149) However some are stringent — meaning l'chatchila; but b'dieved rinsing suffices for them [Rama above in seif 66].",
  "mishnah-berurah/25:ה":
    "(150) And require hagalah — and the same through filling and pouring, as above s.k. 131.",
  "mishnah-berurah/26:ו":
    "(156) And in these countries — nevertheless in a place where glass vessels are not available and one has no cups and other vessels, Chayei Adam wrote one may rely to be lenient to clean them very well and kasher through pouring three days; and this applies specifically to vessels whose mouths are wide from above; but bottles whose mouths are narrow from above and sediment adheres at their bottom and one cannot insert hands inside to clean them well — and likewise any vessel into which one cannot insert one's hand — they have no remedy to kasher them. And even regarding cups, in a place where new ones can be bought — one should not change the custom they practiced not to use them.",
  "mishnah-berurah/26:ט":
    "(159) It does not harm — for one does not use such important vessels with boiling water at the fire, that we should be concerned lest through this chametz be absorbed throughout the vessel; and through pouring that they poured boiling water into it — behold, it absorbs only kedei kelipah and absorption of chametz does not enter into the glass at all; therefore hagalah helps like other metal vessels, as below s.k. 135.",
};
