/** siman 451 part 2 — beur-hagra batch 2 */
export const HAND = {
  "beur-hagra/14:א":
    "Seif 14 — cover etc. that covers — as written in chapter 2 of Machshirin: an impure bathhouse, its sweat is impure; and a pure one in a householder's pool in the house — etc.; and we derive prohibition from tumah as written above seif 8.",
  "beur-hagra/15:_":
    "Seif 15 — cover — for its use is through fire; see Magen Avraham.",
  "beur-hagra/16:א":
    "Seif 16 — mortar etc. and there are those who are stringent — their dispute depends on what is written in chapter Kol Sha'ah there 'except for a yeast container' etc., and Rashi explained even through hagalah; Arukh and Rabbenu Yonah and all the poskim explained without hagalah — see above siman 452; and likewise for a mortar; and even though Rosh in his rulings wrote that Rashi concedes regarding a mortar at the end of the chapter — he did not write so, and so all the poskim.",
  "beur-hagra/17:א":
    "Seif 17 — the board etc. and likewise — from what is written there 'these troughs of Mechoza' etc., and specifically that kneading is always done in them as written in the Gemara there; and so too Mahar\"i Weil and Mordechai; except that Mordechai wrote one should not be lenient after they already practiced custom, because of permitted things that became forbidden through custom.",
  "beur-hagra/18:א":
    "Seif 18 — the sieve — see above siman 442 from what is at the end of Avodah Zarah that linen garments are cleaned — meaning with water and ash; and all the more so regarding something that adheres as written in Zevachim daf 79b and as written above.",
  "beur-hagra/21:א":
    "Seif 21 — barrels etc. permitted through hagalah or etc. — as written regarding yayin nesech in Avodah Zarah daf 33a, halacha lema'aseh, one fills them — etc.; and there daf 75a one who wants to purify them immediately hagels them in boiling water; and they said there daf 34a; and in chapter Kol Sha'ah there is mention of yayin nesech and chametz etc. — there its use etc.; if so, in chametz for something whose use is cold it is equivalent to yayin nesech; and even though hagalah does not help for pottery vessels except when its use is hot, as Rosh wrote in the mishnah there daf 44b regarding ne'ivah artachu in pottery that pouring does not help without peeling — therefore he commanded to hagal them for then peeling is not needed; and as written daf 33a that even pouring helps for pottery; and all the more hagalah as Rosh wrote Shabbat chapter 3 siman 11 that hagalah is better than pouring, for pouring does not help for something whose use is hot even in other vessels; and in Jerusalem Talmud end chapter 2 of Pesachim Rabbi Ami taught regarding cheese baskets, one fills them with water three days from erev Pesach; and all the more hagalah as above; and so Hagahot Oshr\"i chapter 2 of Avoda Zara siman 105 s.v. betashmisho etc.",
  "beur-hagra/21:ב":
    "And b'dieved — there in Hagahot Oshr\"i and see Magen Avraham in the name of Mordechai; and what Mordechai wrote: since permitted absorbs — etc., meaning as written in chapter 3 siman 477 that we estimate against the whole; and since sometimes it absorbs and sometimes emits one cannot stand on the matter — etc., meaning that even if it is known how much exits from it, nevertheless it returns and absorbs and what was absorbed becomes nevelah and returns and emits — not so in permitted that it becomes nevelah as Tosafot wrote Avodah Zarah daf 76a s.v. bat; but in a vessel of permitted — etc., and Beit Yosef wrote; and it was already explained that for most poskim chametz is not called permitted and therefore they omitted it in Shulchan Aruch; and likewise nitelaf we hold in siman 447 seif 10 that it is forbidden; and Magen Avraham; and see Tehudah siman 201.",
  "beur-hagra/22:ג":
    "Except for a yeast container etc. forbidden — as Rosh's text 'all vessels' etc. and we do not read 'in cold' but it deals with hot.",
  "beur-hagra/22:ד":
    "But forbidden to knead — Taz; and Rosh wrote that it is possible according to the text 'use matzah in cold' and because of the end regarding a yeast container that even in cold it is forbidden — such as kneading in them.",
  "beur-hagra/22:ה":
    "And all this etc. — as Arukh's explanation and all the poskim as written above in seif 16.",
  "beur-hagra/22:ו":
    "But for charoset etc. — as written in the Gemara there and as written above in seif 1; and this is according to Tur who disagrees with what is written in seif 21 that for something whose use is cold even in pottery hagalah helps as Tur wrote there; and from Rav Hai Gaon's words it appears hagalah does not help for pottery even if one used it only in cold — etc., see there; but according to what Shulchan Aruch ruled in seif 21 that hagalah helps, and likewise yayin nesech even though it is sharp and very strong — likewise here; and so too in Milchamot explicitly there that a house of yeast and a house of charoset have the law like yayin nesech; see there and in Ran who expanded there.",
  "beur-hagra/22:ח":
    "Even in cold — but Bach and Peri Chadash emended in Tur and wrote that it should read 'only in cold' — to exclude Rosh and Rif and Rambam; Tur wrote pottery is equal in this to other vessels; but their words require study, for if so what is 'and even if one did not use' etc., what is its extension — behold in other vessels too the law is likewise; and above where he wrote 'but in cold' etc. he should have written 'and even pottery' as he began 'all vessels even' etc.",
  "beur-hagra/22:ט":
    "And nowadays etc. — there in Rif; and meaning even other pottery even if one used only in cold — the law of a yeast container of pottery.",
  "beur-hagra/22:כ":
    "And forbidden — meaning actual matzah b'eyna; but in a pot there is no prohibition b'dieved as written in Yoreh De'ah siman 92 seif 8.",
  "beur-hagra/23:א":
    "Seif 23 — fused with glass — as Tosafot explained Avodah Zarah daf 33b s.v. konya, that Rabbenu Tam challenged Rashi's explanation there and in chapter Kol Sha'ah regarding coating a limb — why is it worse than if it were entirely a limb where hagalah helps; and so Mordechai in chapter Kol Sha'ah; and they further challenged there that konya does not imply a limb as written in Zevachim siman 60 s.v. vikonya; see there in Tosafot Avodah Zarah; and Rambam and Tur explained like Rashi; and so Tosafot explained Avodah Zarah daf 75b s.v. vehalakhta; and so there in Shulchan Aruch Yoreh De'ah siman 120 seif 1 and there in siman 135 seif 6 he wrote both explanations; and see Tosafot Ketubot daf 107b s.v. hani etc.",
  "beur-hagra/23:ב":
    "And there are places — Magen Avraham and Taz.",
  "beur-hagra/24:_":
    "Seif 24 — and there are places that are stringent — Magen Avraham s.k. 47; and see Gemara Avodah Zarah daf 74b Rava etc.",
  "beur-hagra/25:ד":
    "Whether they are of wood etc. — the above baraita deals with metal; and of wood their law is like metal as written above in seif 8.",
  "beur-hagra/25:ז":
    "However etc. — as above seif 6 in the gloss; and so in Mordechai siman 464 because sometimes they boil in them etc.",
  "beur-hagra/26:א":
    "Seif 26 — glass vessels even etc. — for in such a case kashering is required even in cold as written in Avodah Zarah daf 33a and daf 74b; and even though poskim disagree there whether it deals with pottery specifically or even other vessels — nevertheless for pottery it is not so, and glass vessels are like pottery as written below; nevertheless kashering is not required for they do not absorb as written in Pesachim daf 74b that the heart of a date palm is different; and see Rashi Shabbat daf 15b s.v. bekli zekhukhit etc.; and Yoreh De'ah siman 135 seif 8; and therefore even if one used in hot kashering is not required as Lev wrote there; and explicitly it is taught in Avot derabbi Nathan chapter 41: pottery absorbs and does not emit — etc.; glass does not absorb and does not emit — etc.; in a warm place warm, in a cold place cold; and even though it was asked regarding konya of date palm whether it absorbed — we see it applies there because it is a small coating; but a whole glass vessel does not absorb; Tosafot Avodah Zarah there s.v. hanal konya etc.; see there.",
  "beur-hagra/26:ג":
    "There is no etc. — since it was asked regarding konya and likewise yayin nesech; and Yoreh De'ah siman 135 seif 8; and see Ran chapter 2 there in the sugya.",
  "beur-hagra/26:ד":
    "And there are those who are stringent — because it is like a pottery vessel since the beginning of their creation is from sand as written in chapter 1 of Shabbat; and so we hold in the conclusion in the words of Rav Ashi; and even though its use is in cold, nevertheless sometimes they use them in hot and soak bread crumbs from erev Pesach in them like cooked; Mordechai in siman 465; and as written in seif 25 in the gloss that we are concerned even for use that is not fixed as above; and therefore even hagalah does not help for them like pottery as written in Avodah Zarah there and in chapter Kol Sha'ah there 'and the Torah testified regarding pottery' etc.; Tehudah; and so it is taught explicitly in Avot derabbi Nathan that it does not emit like a pottery vessel; and what is written there that it does not absorb — meaning like pottery in the beginning that absorbs even in cold immediately even if one does not put it away for permanent use as written in Avodah Zarah daf 33b keshai etc.; and proof from what is written 'and does not emit'; and what is written regarding the heart of a date palm does not stand in the conclusion there as Tosafot wrote there s.v. she'ani; and so it appears in Tosafot Avodah Zarah above that hagalah does not help — for they challenged Rashi who explained regarding a limb that if so why does hagalah not help; and they explained regarding glass only that he wrote an entirely glass vessel does not absorb as above.",
};
