/** siman 453 part 2 — chok-yaakov */
export const HAND = {
  "chok-yaakov/1:א":
    "(א) In wheat. And I heard that what they call in these countries tyrchin and weitz is not included in wheat at all, but is considered among kitniyot species.",
  "chok-yaakov/1:ב":
    "And the custom to take wheat l'chatchila. It would appear if he has no wheat he should take in the order they arranged in the Mishnah etc.; Tur wrote below siman 473 regarding maror; but in truth there is no proof from this at all, for the Tanna listed in order of the verse and what is earlier in the verse; also some support from Maharil's language: Maharil preached the essence of the mitzvah is to take wheat, for no Tanna is omitted in language except wheat for Pesach, end quote — he did not say because the Tanna listed wheat first, but certainly the Tanna listed only the order of species written in the verse; see Tur siman 168: spelt is included in wheat species; siman 451: whatever is earlier in the verse is earlier for blessing; nevertheless here according to all, the species beloved to him comes first to fulfill more mitzvot of eating matzah with appetite; perhaps for this reason the Tanna also listed wheat everywhere for Pesach, since presumably it is most beloved to most people.",
  "chok-yaakov/1:ג":
    "In rice and millet — and that is what they call reyz or hirez, and titraki they call heydin (responsa Maharam of Lublin siman 78).",
  "chok-yaakov/1:ד":
    "They do not come to chametz. Rambam wrote chapter 5 laws of chametz law 1: there is no prohibition on account of chametz on Pesach even if one kneaded rice flour and it swelled like dough that chametzed — it is permitted to eat; in Venice edition of Rambam Raavad's hasagot is printed: this is not a simple matter and not all agree; although it does not make full chametz and one is not liable karet for its chametz, nevertheless it becomes hard and is forbidden, end quote — examination needed, for Raavad's words are explicitly against Gemara conclusion and all poskim; see Pesachim daf 114; from Maggid Mishneh it appears he equated Raavad to Rambam law 2 regarding fruit juice; but per Raavad's hasagot printed and language, it appears he refers to kitniyot — examination needed.",
  "chok-yaakov/1:ה":
    "And some forbid. Reason explained in name of poskim: they forbade because grain is cooked-dish item and kitniyot cooked-dish item — decree lest one confuse; also places make bread from kitniyot and confusion with cooked-dish dough; also sometimes grain mixed in them, impossible to separate; Terumat HaDeshen siman 113: they forbade because they are considered grain and confusion with grain; therefore in rice we should permit, for not considered grain; one could say kitniyot here as Gemara Nedarim 4:55 regarding one who vows [abstention] from grain — see there; but from poskim' implication one should not distinguish between rice and kitniyot species; see Bach: reasoning gives more stringency in rice per Rabbi Yochanan ben Nuri as in chapter Arvei Pesachim; but none are concerned; poskim agree all this is only a general stringency, but where practiced forbidden, practiced — one should not change; so Taz wrote.",
  "chok-yaakov/1:ו":
    "If they fell into the cooked dish. From the rabbi's words it implies even without sixty it is permitted even to eat; so Acharonim; however Terumat HaDeshen siman 113 implies specifically in a mixture of something forbidden one does not forbid, but less than sixty one forbids in eating; primary view like Acharonim, since otherwise it is only general distance; see note 5.",
  "chok-yaakov/1:ז":
    "And they do not forbid if they fell into the cooked dish — meaning even if they soaked the seeds initially before making oils; if so close they chametzed — nevertheless permitted, as Terumat HaDeshen there; this is the rabbi's intent here repeating the matter; see Magen Avraham in the name of Darkei Moshe: permitted to light with these oils even if crushed in mortar in which barley is soaked — they do not forbid b'dieved if fell into cooked dish, since already nullified before Pesach; from Maharil permitted to eat olive oil, end quote; above siman 447 seif 5 in gloss note 27 what he wrote there from law of year-round candles how to conduct on Pesach — see there.",
  "chok-yaakov/1:ח":
    "And likewise permitted to keep kitniyot in the house. Slightly difficult: what does this teach, for also the five grain species may be kept in the house? One should not say it teaches even to give them and they fell in water — this too is heard from what he permitted even benefit and lighting from oils even if given initially, as note 7; also the rabbi's amplification is missing from the book; perhaps needed to teach permitted to keep in house and we are not concerned lest one err to cook and eat them, since no prohibition by law; in five grain species we are not concerned he will cook them because it is full chametz and people distinguish; also no way to cook them so and eat, only groifen types called groifen, which in any case are forbidden to keep, as Magen Avraham wrote, for they soak in water before crushing; as I heard, immediately after soaking in water they crush and bran and flour dust flies out that is full chametz; if Pesach passed, forbidden; Maharash in Shaarei Az wrote: he heard his ancestor the Gaon permitted selling to a non-Jew; I debated this law with him and he said he also investigated it is full chametz; listener heard and erred, end quote.",
  "chok-yaakov/1:ט":
    "And anise and coriander are not kitniyot and permitted to eat on Pesach. Taz wrote: nevertheless require examination that there not be one of the five species; so they practice when putting them in drink called kritz; correct that each homeowner examine himself and not rely on examination of women and children; see books of Mishnah Berurah general rule 46 note 32; also in caraway called kimmel they practice leniency; some are stringent in these species; see responsum Maharil siman 25: two views in caraway; Taz wrote to distinguish krems kimmel forbidden, peled kimmel permitted, end quote; in my opinion one should not be more stringent, for kitniyot itself is only a general stringency — do not add; above siman 464 from law of mustard.",
  "chok-yaakov/2:א":
    "If it has taste of grain — even without olive-bulk within time of eating a meal, per Rambam, Ramban, Rosh, Tur, Mishnah Berurah — not like Rashba and Raavad who require specifically olive-bulk within time of eating a meal (in Magen Avraham siman 168 note 15 a printing error wrote in the name of Rashba the opposite — see Beit Yosef); Maharshal in Shaarei Az wrote: from Beit Yosef in the name of Rashba, in rice specifically olive-bulk within time of eating a meal is required; YD siman 324 wrote in his name all this is specifically in rice and wheat; accordingly in other species specifically majority grain — not as above; examination needed, end quote; in truth per Rashba his words are correct, and I saw explicitly in his challah rulings brought from Yerushalmi; so too per Rambam and his supporters: in rice even without olive-bulk within time of eating a meal one fulfills if so; in other species olive-bulk within time of eating a meal suffices; clear from Mishnah Berurah's language brought in Beit Yosef; this is the intent of the author — see there and in Magen Avraham: one should be stringent, olive-bulk within time of eating a meal even in rice — extra stringency against Rishonim and Acharonim here and YD siman 324.",
  "chok-yaakov/3:ב":
    "That there not be sixty against it from the permitted — this refers only to sprouted grain; so Magen Avraham and Acharonim agree: primary law per poskim, flour in flour is called dough in dough, mixes and nullifies before Pesach, permitted to bake even during Pesach — not like Semag (see Terumat HaDeshen siman 114 and his rulings siman 146 — appears contrary to what he wrote in his name siman 150 regarding challah; seems equal; see there); a person of spirit should be stringent for himself to bake everything before Pesach; see above siman 451 note 1; nevertheless certainly permitted to cook from those matzot during Pesach — not as above; as Magen Avraham challenged below siman 458 — see there; if flour became moist and crumbled, nullification does not help even to bake beforehand, as below siman 467.",
  "chok-yaakov/4:א":
    "Matzah of mitzvah — good to guard them. Implies only matzah of mitzvah requires guarding to eat first nights; other matzot do not require guarding at all, and permitted to take flour from marketplace even without duress; above siman 467; even guarding from kneading and baking we do not require, as Gemara and poskim: even in their doughs one fills his belly, only he must eat an olive-bulk of matzah; per R' Chaim and poskim' agreement: only three before Israel in our water, and see no se'or was mixed, only guarding le-shem matzah was not done — even if baking was also by a non-Jew and Israel stands over, permitted, only not guarded matzah to fulfill first night obligation, as below siman 460; and that he listed \"in their doughs\" not \"matzah\" is inclusive: even if baked by Israel, guarding for baking alone is not called guarding; must eat olive-bulk of matzah of mitzvah at the end; therefore he listed doughs, because matzah is forbidden on account of decree of their dough, unlike dough which is permitted (as Peri Chadash YD siman 112, challenged on Ran there, see Tosafot chapter 1 Chullin regarding chametz of sinners); but certainly other matzot' baking does not require guarding, nor kneading; proof from Gemara Chullin beginning regarding Kutim's matzah — see there; only Israel must be at kneading and baking lest chametz mix — all this plain and clear, not as above who was not precise; all this by law; but Israel are holy and practice guarding in all matzot from grinding, at least from kneading; therefore poskim wrote all our matzot are presumed guarded, as below siman 477.",
  "chok-yaakov/4:ב":
    "Flour from the marketplace. Implies only flour, but clean semolina forbidden to take, for full chametz, as Terumat HaDeshen siman 119: they moisten and are not careful in their moistening, brought in Beit Yosef siman 442; however Kol Bo daf 91b: they buy semolina from marketplace — more astonishing how they ruled simply to buy marketplace flour in duress because we do not establish prohibition, behold explicitly chapter 8 of preparing food year 2 and Rambam chapter 7 of food impurity: all flour and semolina from marketplace are presumed moistened; one must say: we do not establish prohibition of their moistening in the way it chametzes, for by Gemara law moistening is permitted, but Geonim decreed and forbade; in duress they did not decree; so Taz wrote; however Tzitz Eliezer siman 32 is stringent: when known clearly some always launder wheat — worse than moistening — even if most sellers do not launder, forbidden on kevu'a like half-and-half; even to keep forbidden; from bakers do not buy at all, certainly they launder; he concludes: however my custom not to forbid keeping flour, also not to forbid eating on Pesach in duress, since not known certainly that some flour sellers always launder — then kevu'a is not recognizable in its place; from bakers do not buy, certainly they launder; but grain flour they buy from them, end quote; so Magen Avraham in the name of a great one in our country where they wash wheat and soak in water, forbidden marketplace flour like sunk grain; so all Prague sages; once a teacher erred to take marketplace flour and decreed fast on his error, end quote; it appears to distinguish: only from city millers or regular flour sellers do not buy, especially bakers; permitted to buy from village people without clean semolina, as explicitly chapter Kol Sha'ah (Pesachim daf 40): originally why not — not because they do not moisten; if moistened we do not establish prohibition of moistening in the way it chametzes; also Tzitz Eliezer's kevu'a reason does not apply, for they travel daily — these go, others come, all left fixed place; so appears to the eye their semolina is not so clean; I heard also in Mochachaz days the Gaon Maharash was once pressed for Pesach flour and permitted marketplace buying; perhaps in the way I wrote; do not be stringent against Rishonim and Acharonim, especially non-mitzvah matzah — above note 15; Maharil wrote: flour peddlers make called krapat — above full chametz.",
  "chok-yaakov/4:ג":
    "From the marketplace. Taz wrote: where they grind wheat in millstones in which they grind malt, forbidden even in duress, for full chametz, end quote; it appears in duress even so one may permit, for even if something of malt remains and mixes, certainly mixed and nullified before Pesach; all the more if not known certainly malt was ground — we do not establish prohibition in duress, as all poskim; nevertheless correct in duress to bake everything before Pesach, as note 13; Kol Bo wrote: we need not fear lest chametz crumbs mixed into flour, since custom to shake flour in a sieve, and if there is chametz the sieve catches it, end quote; learn: if chametz crumbs mixed into flour, remedy by sifting; but not time of duress and general doubt — proof certainly mixed; nevertheless permit benefit to keep until after Pesach.",
  "chok-yaakov/5:א":
    "Nowadays forbidden to moisten. Meaning moistening: Rambam wrote they soak wheat in water; Aruch explained soaking language; since we are not expert in moistening, Geonim forbade; nevertheless appears permitted to keep wheat in homes, since by Gemara law wheat in moistening permitted as long as not near splitting, as below siman 467 seif 8 — see there; namely slight soaking or little rinsing; but much soaking is full chametz like sunk grain, explained siman 467; see Beit Yosef; so Terumat HaDeshen siman 119 and Tzitz Eliezer siman 32 and other Acharonim; see note 16; so Maharil in responsum siman 59: if something was in water it is full chametz, end quote; Taz wrote: forbidden to buy wheat from mill-owner, for they regularly rinse wheat first, end quote.",
  "chok-yaakov/5:ב":
    "Whether wheat whether barley. Mechaber's language is not precise, implying wheat and barley are equal; in truth barley, since their way is, also by Gemara law forbidden to moisten; perhaps nowadays forbidden to keep moistened in house even if not near splitting — unlike wheat; see below siman 467 note 7 etc.; see Tur and Gemara Pesachim daf 46: rye is barley species for this — Eliyah Rabbah.",
  "chok-yaakov/6:ב":
    "And they launder them. Taz wrote: better to buy new ones; from law it appears forbidden through laundering; proof from Rosh: if they rubbed a goose in bran, since there are holes it is forbidden — all the more sacks with weave holes; also cloths for matzot; such is his content. I do not know why from afar he brought his proof and did not bring proof from sieve and Rashi and sacks the rabbi himself brought above siman 451 seif 19 in gloss that hagalah does not help; he wrote there: in sacks they practice leniency — but certainly sacks laundered well inside and outside by hand rubbing differ from sieve etc.; all the more in goose, laundering does not apply since chametz enters inside through rubbing — clear.",
  "chok-yaakov/7:א":
    "Forbidden to place on an animal. Reason Terumat HaDeshen siman 118: flour heats in animal body; also not clear to us if animal sweat makes fit and chametzes; even though by reasoning unlike human sweat, nevertheless do not be lenient in unclear matter, end quote; therefore b'dieved appears forbidden flour moistened from animal sweat — doubt; however Magen Avraham wrote: it appears b'dieved one should rule animal sweat does not chametz, end quote; primary: what Terumat HaDeshen doubted whether animal sweat makes fit — certainly not for examination in chapters 2 and 6 of preparing food and Rambam chapter 8 food impurity; above siman 467; nevertheless examination needed whether permitted to knead matzot from them — like fruit juice when water is mixed it chametzes; one could say it is its own derivative; also when fruit juice dried inside it no longer chametzes; this is reason of first view in Tur in this sign regarding mouse eating as fruit juice; Hagahot Semak brought in Beit Yosef in the name of Rif implies even so it chametzes; above siman 462, 466; notes 7, 8 — see there.",
  "chok-yaakov/7:ב":
    "And likewise be careful l'chatchila; if he transgressed and placed sacks one on another, there is still remedy to leave them a day or two before kneading; so Shiltei Giborim compares law of placing many sacks to kneading the day flour was ground; so Magen Avraham this section; if he transgressed and kneaded — no prohibition b'dieved, as rabbi's language; so Tzitz Eliezer.",
  "chok-yaakov/8:א":
    "They practice picking millstones. Responsum Nachalat Shiva siman 12: thirty days before Pesach permitted to grind without picking — see there where he elaborated; question 13: if cannot easily pick because close to Pesach or other need — for them too time of duress, permitted without picking, end quote; nevertheless bake everything before Pesach as above note 13; in any case grind everything before Pesach.",
  "chok-yaakov/8:ב":
    "They guard it. Maharshal in Shaarei Az: now they cover millstones in flax; therefore possible to permit first flour, end quote; Magen Avraham in the name of Machatzit HaShekel: when grinding grain for moistening in mill, do not grind in that house that time even in another mill, dust flies and mixes; small child should not guard millstones, end quote; I have not seen carefulness; they grind in that house for Pesach other flour — one must say because possible the other grain is also not for moistening; if you say it is for moistening, perhaps not moistened in way that chametzes, as note 15; also b'dieved no prohibition, since nullified before Pesach as seif 3 explained; during Pesach be careful — it appears to me.",
  "chok-yaakov/9:א":
    "A day or two. Mahariwe in responsum siman 193: kosher custom not to grind for Pesach within three days beforehand; Mechaber wrote a day or two — intent is twenty-four hours, as Rashi explained in parashat Mishpatim regarding \"a day or two he shall stand\"; so poskim parsed, as YD siman 70 and Terumat HaDeshen general rule 6; see Mishnah Berurah note 59; Choshen Mishpat siman 306 seif 8 in Semag — all clear, not like Magen Avraham who wrote not twenty-four hours, only overnight; appears he compared to water requiring overnight; from poskim' language it appears as we wrote; if he transgressed and kneaded — appears not forbidden b'dieved; guard well; see note 23.",
  "chok-yaakov/9:ב":
    "At grinding time it is hot. Kenesset HaGedolah wrote: heard from one sage no concern, since when they shake flour it cools; I do not rely on this report — against poskim' implication, end quote.",
};
