/** siman 153 garbled-block hand fixes */
export const FIXES = {
  "baer-heitev/part-001.txt": {
    "5:א": "(1) From me The difficulty of the KM Ha KIL invitation to Milta is a ss and the reason of the MA Ha forbidden to change the Ma'at is because the city's rabbis did not give the Ma'aat but an adeta that they would build in the HC and it is forbidden to change it without their consent and the MSH siman 8 of the invitation to Milta is an ayri that the congregation bought from minor fees that they collected for nothing. And the new whites are to be changed as 33. And simply Dej Tobi of the city in the position of the people of the city Shari for the changes of the Ma'at end of his words MA. And 16 26 Dodai M.S. an invitation, whether or not it is a milta, is not a matter here. In everything that belongs to a vow of holiness, one must fulfill it on the part of his vow, and if he comes to fulfill it and is invited to do so, he has in his hand to change the invitation, whether or not it is a milta, and he fulfilled it in another matter, as what he vowed in the siman 18. Pray in it, there is no holiness in it, and in it, new devlabs are really like that, they must keep their vows and make of them in the HC, but they are preceded by an act, there is no holiness in them, but the vower must keep his vow, and in the Mish, here it is due to the sin of the sins, but to a severe sanctity, not because there is holiness in the sins themselves. But they didn't go out until they brought them to the Church. And if they want to take out those who are wronged for something else and give others under them to the Church, surely it is permissible here to sanctify the body of the wrongdoers they collected, but the mitzvah they did not fulfill what they had to do until they built the Church and also It is explained in this chapter, siman 13, that a mitzvah can be removed from a mitzvah, meaning that a mitzvah means a minor mitzvah than this, and we mean that in the way of a loan, he removes the mitzvah until he pays the mitzvah, and all this is nothing but a thing in which there is nothing but a separate invitation. But in a thing that already has an act of holiness in it, or that the body of the thing is holy, it is forbidden Afi' to speak of a mitzvah from the Old Testament in the Old Laws who were already in the beit haknesset'ah, it is forbidden to take from them through a loan and give others under them, so far as the language of the 16th A.S. And the Ram Khaa C. 13 wrote Dagbayit Ma'aat is an act and not an invitation, etc. And the MA made it difficult for him, and the hand of Aharon, who lived there.",
    "5:ג": "(3) trees and stones. 26 16 The words of the Rama C. Dakhion wrote in the siman 18 that the dead were sanctified. Even Mash here, bringing wood from their home for the purpose of building a house in the Dish, divided whether he came near a collector or not. And that for Bia near Gabai, she was excluded from any invitation to Milta. And regarding the main point of the matter, we have already learned that there is no endowment in the body of the ma'at, whatever it is at all, an invitation to a milta kavya dagbo ma'at, except that the obligation on his part to do precisely this thing and it is not easier than it is, if so Afi' did not come to the collector of the end of his words P.S. and look at the MA:"
  },
  "beur-hagra/part-001.txt": {
    "4:ב": "(2) VIM 20. Demshem has no proof that it is the same for the beginning as Mishsh from Tani' Diabd 20 and apparently M. Dediabd is allowed in all of them. He consulted the Rabbin of that year and wrote in the Sefer Ha'Maor 20 Ha Mathani, a question of Risha Asifa 20 but 20 because it is not above me that it is forbidden 20 and of course Hakim 20 Alma even in the future S. forbidden and considered that Dabgm said in raids because it is not above me Lia it is not permissible that S.M. To begin with, it is certainly not allowed in the KA and even in the SAT, the opinion of the judges is material, but in retrospect, in the SAT, it is certainly allowed, as there is in the GM:",
    "5:ב": "(2) And if when they collect, etc. The GA there (Da Efi' no) in the name of the 17th and ZA not from the second name as the 3rd:",
    "5:ד": "(4) And if they bought etc. Shem 26 2 But in Hadatta 20 and the difficulty in 11 Mish Megbo Ma'ot Dasor to change them as above and also in the Shenkah from Ma'ot for bricks and trees and t' in Hadatta 20 we were first that he came near Gabai and Km She in Arkin 6 and Atos' there and more. And R. T. P. 20 and A. D. C. R. N. H. S. V. C. R. N. T. A. and A. M. A. siman 5 and 17 siman 2:",
    "7:ה": "(5) And the 5th 20th. Ral such as that of individuals such as Tarsei, seven of the citizens of the city as citizens of the city Ral as the citizens of the city unaware of their livelihoods, what is it that they accepted for them Afi' a single Nami Ral that they accepted for them in the interpretation of this sale and they did not accept Afi' how much no but just a Ral that they put on them just to supervise the business of Tzbur and KML A'G that they did not accept in P. for these things R.I. and ZS but if they agreed 20 And if they accepted 20 and Ral Efi' one of them is better and like 7 the good of the city in the status of the people of the city since they agreed on the p':",
    "7:ל": "(30) And likewise, etc. — and per Ran's explanation that if they have another beit haknesset, the reason of negligence does not apply, as explained in siman 152.",
    "10:ב": "(2) And there are others. as in Gm' there and the Rabbi's writing in S. Rapu Dharambam Sal Dala they said except in beit haknesset and not for other things of holiness as much as they do not take them down they are themselves for minor sanctity from Shhak in beit haknesset as Kesh in Sat and Ksh to the 7th books Degarsi' Efi' to Mishti Bia Shikra and to the surface Bia Piri Dakai Abakh and M. In the above-mentioned addendum and more from the deshris as a gift of pleasure clothes that they have already received and the first s. meaning DMMSH will not sell SAT 20 because of many Iiri Dela Kai Ha'ba'ya there and 13 said 20 20 and 22 Mordechai in the name of Rabi'ah:",
    "13:_": "CG Gabu 20. BB 3 2 AL Rabina 20 and 3 Rambam Barisha Dalma materimi mid and Sipa PS and ZAS Shirigi Delbani 20 Ral D2H3 not Mitzvi Mezvani to speak of a mitzva May 20:",
    "14:ב": "(2) And if Reuven etc. As in the scroll there, but in Hadatta 20 and the same 20 and end of his words in Archin Israel who volunteered 20 until he did not settle down 20 there we use it:",
    "18:_": "Sih has the same thing. As a rabbi in the rabbi, he just poured into the content a rabbi from a grifter, a rabbi, and the rabbi who wears a Shabbat and in the rabbi the same yes, in vain, they bring to the rabbi:",
    "19:_": "CIT Yes 20. As the Mish the name of the finder is a vessel 20 and it is written on it Karban 20 K Karban 20 and even to Rabbi there is Ishtakad 20 and also Yerushalmi R. Yonah 20 and they brought Tos. 25 45 Imor 20 not here and likewise the MS in the DBM in the Samphon that comes out from under the hand of Melva 27 does not belong here:",
    "22:א": "(1) Sakab if at the hour 20. AC Kanin and even in his face and was silent, be strong as a mash in Spagh DBA and close immediately 20 that there is no 20 and Aham C. Kana:",
    "22:ב": "(2) But if when they gave to the other, etc. — not specifically for the sake of Heaven; one who has a tenancy to pray the congregation in his home and because of coercion they gathered elsewhere, his tenancy is not lost and when coercion ends they pray there [responsa Ranah and Ateret Tzvi]; and all of this in siman 22.",
    "12:_": "(12) There they sold a handkerchief taking books — each chumash by itself, as well as prophets and scriptures; see there at length.",
    "14:ג": "(3) Standing and screaming — since they consecrated with intent and for the beit haknesset, even the owner may change it per Choshen Mishpat; see Meiri who is not a city member.",
    "21:ג": "(3) Returning to his mitzvah — see there in siman 22."
  },
  "biur-halacha/part-001.txt": {
    "7:י": "(10) With the consent of the tsabur - refer to the Magen AvrahamM.A. in the name of the MA and per this, it means that the sale was not in the status of the people of the city, the sale does not apply at all to the tsabur whose permission was not their opinion in this way, but from the interpretation of the Gra, it means that we were like the ZA without the status of the people of the city in the villages of their sale, but then it is necessary to raise the blood in sanctity:",
    "7:כ": "(20) A single person who built, etc., a law as the court of a congregation, etc. - the rabbi just did not interpret May Iiri here, whether in the village or even in the book, and here in Or Zroue the source of the island of Dina is explained in Dabin in the volume and between the village of Meiri and APA they have a sale per the congregation itself [and at the most in conjunction with the giver as Dina Desifa] Indeed, the Uor Zroue wrote so because it was a dazil to her taste, the name of Dediputa Dakhrach is because of they gave From Alma to the expenses of the building and the Shura in this regard, which was in the court of an individual, but the dedication, even the dedication to the people of Karach Nami did not win it Alma and they do not have any part in it, only the people of the city themselves or also the grantor has power in it if he leaves to himself no right in it as a basipah and therefore, Mashak is sold to a friend of per the method of Heni rulings that even in our own without the assistance of Malama Nami there is For a portion of it , the dedication is also Adeta 20, so Heaven is allowed in this matter, the only one who dedicated the Bihchan to the people of the city, if they are the sons of Karach, the dedication is also possible for Adeta 20, and nothing else is enjoyed by the opinion of the giver and the opinion of the public per the law of the Bihchan of volumes, and I found in the book Olat Tamim that he wrote yes really for the student of Ish, and also means a little furniture for a second answer Maharash Duran c. The volume will be sanctified in any case also to the Ḥaṭa they are justifying it by this Daha already wrote in the answer of Mashat Binyamin Deduka during the construction of Amrinan yes because his son Adat yes but it is not clear to us whether he meant at the time of building no amarinan at all it will be sanctified in any case after the building end of his words that many of the sons of alma come to it to pray and as we copied in the Mishnah Barura siman 33 and 15 regarding Didan and also the language tends to The Gra, in its commentary, sections 24 and 25, to refer to it and M.M. Tsa in this:",
    "7:נ": "(50) To change it, etc. — This follows Rashba; and apparently per Magen Avraham we do not establish minor holiness in its light — specifically when it is forbidden to change entirely even to weightier holiness [such as when the dedicator commanded thus], then proclamation is required; but if they have permission to change to weightier holiness, such as through the seven good men of the city not in the presence of the people of the city, as explained, then it is considered as their own and no proclamation is required; and truly Rashba's intent is proven, for he hangs the reason on one can give it as a gift, and he holds in his novellae in chapter Bnei HaIr that for a gift we require only the seven good men alone, and so too Ramban. However there is a difficulty: per this, per Magen Avraham's own ruling below s.k. 26 that for a gift one needs specifically seven good men in the presence of the people, it follows that for sale through seven good men not in the presence of the people proclamation should be required; and it is possible Magen Avraham relied mainly on Ran's reason cited in s.k. 18, that we find proclamation only in a matter incumbent on the court, such as the court selling to collect for others; but in a matter we do of our own accord without needing the court, proclamation was not mentioned — end of his words; and this implies clearly that seven good men alone also do not require proclamation, for they are the people of the city themselves and sell on their own; and so too Tur and Rama in Choshen Mishpat siman 103 s.k. 1 in the gloss. And truly it is explained in Ran and other rishonim that at minimum seven good men alone are not weaker than all the people of the city without seven good men; and if we say that through seven good men alone proclamation is required because it is forbidden to change to minor holiness, then if all the people of the city sold without seven good men proclamation should also be required, for they too may not change to minor holiness — and this is unreasonable that the people of the city need proclamation on their own; rather it does not depend on this: the sages were stringent regarding sanctity not to lighten for them or their money unless the people of the city agree in the presence of their leaders — nevertheless this is not a reason to require proclamation for sellers on their own to upgrade holiness; and likewise regarding seven good men who are the core of the people of the city — the sages decreed not to annul holiness unless all the people of the city stand at annulment, but from this there is no proof regarding sale money; and it appears Rashba agrees with Ran's reason but did not need it for his view regarding gift; we elaborated because I saw R' Shmuel objects to Magen Avraham and forces our version to require proclamation when forbidden to change to minor holiness; I disagree — the essence is as Magen Avraham and as we wrote.",
    "9:_": "And if they sell it 65, etc., the taker will do even these 4 Deuteronomy - that is the opinion of the Rambam and the Rash, and the Tor and Rivu were followed after them. And Rabad Pelig AZ and as in the rulings and the rabbis did not sing in the Shas to use a derogatory device except for Tel Harev in the LA, but it was upheld by the High Court earlier, but not that they should be allowed to desecrate a house of prayer and make it a Borski house, etc. And here the Rabbin and Meiri brought these opinions to B. and did not decide and the Rashbaz HC C. KA held the opinion of the Rabad AZ and in truth Decula Yatrata is per what the Ramban and Rashba and Ritbaa of the siman 20 decided it is like the rest of the mitzvah uses such as a sukkah and lulav and shofar and the like, but only if they agreed in the Ma'a to the seller, or they revealed their opinion that they no longer need it, and it is like the mitzvah uses after a time of their mitzvah that they throw away per their words, etc. per what the author ruled in C. 21 The Sabbat of a mitzvah that is not to be used together is derogatory, but to be thrown away, and they are a klin, and in our case, it is not true, and per the Rabbinical method, that they imposed sanctity on it, from their words, it is more than the rest of the mitzvah, and of course it is permissible to use it as a derogatory use. He is the Rabbad and as it is stated there, in the 22nd and it is possible that Dazil to her taste here and it is possible for the Rambam to really fly there Adin the above [Aish B. 21 in the commentary of the Graa the source of Hai Dina Sugya p. All the vessels and in truth the Rambam there interprets a dream in all clothes and in the 4th Tallits of a mitzvah and the Sugya there is explained in a different way see the Rashba and Meiri there] indeed the author It was ruled in Ha Darabd in the above C. 21 and also in C. 1434 S.H. It is brought to the court of this law Gabi Hoshana in the name of OZ P. Bnei Ha'ir Aish in the OZ who brings the same in the name of S. Hakadmon Shear A.G. The city in the Maa'a because all devote their knowledge and oh, as they dedicated it on condition, it is possible for Delfi Sbara, even with the use of insults, because they agreed to it, but it is still difficult, because it is not likely that the whole of the Adeta Didho was so afi' to the servant in the court. What comes out of our words is , as in Dafski' in B. 21 regarding the matter of Tzitzit And in B. 1744 regarding the matter of the Hoshana that one should not use any of the blasphemies of Heaven 22 and 26 because it is a permanent and obvious thing and it is a great blasphemy to use it lightly, and the 24th of the Ritbaa in the matter of Daogra and the pledge of is more severe in the 168 of the rest of the uses of the mitzvah:",
    "10:_": "And there are those who forbid, etc. — see Magen Avraham that this refers only to a sefer Torah and its tashmish; and in Beur HaGra it appears the one who forbids is Rambam's view that even sacred tashmishim may not have their money taken for secular use except through seven good men in the presence of the people, and only for beit haknesset was this permitted; and Peri Megadim holds one cannot attribute this to Rambam — see there; and in Yoreh De'ah siman 282 seif 17 Rama ruled likewise that through seven good men in the presence of the people one may take money of sold sacred tashmishim for secular use, and did not bring disputants; as he brought in seif 18 it appears all agree it is permitted.",
    "11:א": "(1) And they can replace with others — this is Tur's language, originating from Bava Batra 26; and the seven good men of the city in the presence of the people have power to sell and buy and change for whatever they wish, and even to secular use, and even if the people of the city protest — see there at length.",
    "13:_": "They will not sell it in a court of law — see Mishna Berurah that the law is to sell, and even to the rest of the people of the city it is permitted when the seven good men sold in the presence of the people; and in any case when the seven good men sold not in the presence of the people it is forbidden to sell to the rest of the people of the city, for they did not reveal their intent that they have no more need for it [as Magen Avraham wrote in s.k. 37, and so Meiri] — see there.",
    "16:ד": "(4) But if he stipulated from the outset, etc. — the reason is since his stipulation stands — end of his words; meaning his stipulation was that he could object even to an individual.",
    "21:ג": "(3) But these are the vacant ones, etc. - apparently it should not be made easy except by a promiscuous dedication to Israel alone, but those prostitutes who sit in the houses of dedication who are self-desecrated to everyone should not be made easy per the opinion of the above-mentioned additions meaning Dakhl that one becomes a prostitute by the introduction of a ban again, even if she is married later to be allowed to have sex, it is forbidden and yet in the houses of dedication that are self-dedicated to everyone one is already a prostitute bringing in a lawyer and a slave [And as explained in Ibn Ezer Siman 6] And so we even know that this Athanan was received from Israel, Nami, Athanan, and even per the Rambam, I believe that the Athanan itself brings the prohibition of GAC.",
    "22:ג": "(3) Returning to his mitzvah — apparently even the first lessee within the second lessee's time also returns to his mitzvah immediately when the coercion leaves; and regarding payments he pays per the value of remaining time; and so in the Gemara in the name of Mordechai that it belongs to inheritance of the mitzvah; and whoever gives more to charity wins; see siman 33 that wrote the custom in the city that whoever is seized by the public for some mitzvah, it is for him and his descendants per their custom; see Barchi Yosef letter 12 and Sefer Mechkarim HaLev siman 19 extended on this."
  },
  "chatam-sofer/part-001.txt": {
    "2:_": "There in Magen Avraham s.k. 2 and 12. P.S. And in Matani' there is also a difficulty why he did not mention the division between chumashim and books as Taz in Tur there. And it appears there are three divisions: (1) regarding reading verses — words of prophets are holier per Ran in Beit HaRif; (2) regarding sanctity of the book there is no difference whether sanctified by prophets' words or Scriptures, and therefore Mechaber wrote in chapter Bnei HaIr that prophets and Scriptures are one; (3) chumashim are also sacred since they can be completed to a full Torah, and it appears the entire Shas lacks only one letter repairable, and the Gemara forbids wrapping chumashim in a handkerchief; and regarding selling there is no difference between Torah scroll dealers and prophets/Scriptures books except Shas commentaries where he did not divide — all difficulties resolve with this division; and similarly regarding beit haknesset sale when there is no cancellation of prayer but selling for prayer at need when no other beit haknesset exists is forbidden per Rambam as Magen Avraham s.k. 1 and 27 bring.",
    "6:_": "There, § 9, as well as the above is proven. N.B. T.A. in Thos. Gitin there and in B.B. page 13 per Sodah that it was said. And K.L. meaning because of a woman, but because of the Shabbat, Kabbalah words are not recognized. The above is to advance and not to postpone, and it seems to me that the mitzvah of charity is first to remove its shame from helping an orphan to fulfill a special marriage contract to sell a Shabbat in their eyes that they will fulfill a rabbi mitzvah because they are honoring the holy and simple. And know DK 7 when it is not possible to learn Torah and to carry in another way but other than this, ag Dedayin Mitzvah is in any case a kill from the remnants of MA KMS the Tos' in the name of Shaletot P. Amor PK D 7 page 13 AA But when it is not possible in a matter other than the Teacher of Shaletot as from Mash by name Spek Dbak and Dok well in 27:",
    "8:_": "There s.k. 22. P.S. It is explained here in Beit Yosef that per all opinions he does not see a sign of blessing; and this settles Magen Avraham's difficulty; and so Eliyah Rabbah s.k. 22; and further it appears to me they dispute only when he has a sefer Torah or the like, but if he has no substitute the Talmud and poskim do not deal with this; and even for beit haknesset alone it is not sold by seven good men in the presence of the people if they have no substitute; and so this Bava Batra passage deals thus; and since all his life he cannot sell it, it is not included in his general assets for living expenses — it may be given to another as gift of shekhinah; and so Meiri in Shulchan Aruch Yoreh De'ah; and this resolves Magen Avraham s.k. 23 — clear to me. However in any case Bava Batra implies Rashbam had a different version, as in Chemed Moshe.",
    "10:_": "In AD Daha . N.B. and A.S.",
    "11:_": "There in Magen Avraham s.k. 40 and in our texts. P.S. See my responsa Choshen Mishpat at end of this and siman 25 and 277 regarding matters of siman 38 and burial — see Choshen Mishpat part Yoreh De'ah simanim 26–27.",
    "15:_": "There in Magen Avraham s.k. 17 and Taz in Bishash. P.S. And also the difficulty of Laham — see there. And it appears immediately: one goat equals the dog, therefore the difficulty to Madd Dish is choice precisely, and secondly there is none equal to the dog; but Rambam holds only one goat among them equals the dog — siman 20, we admit it is against the dog because none equals the dog except the goat; and this is correct; and it is also forbidden by beit haknesset; see Tosafot s.v. But Timah, etc.",
    "16:_": "Name from GA s.k. MT and their words. P.S. And it appears to reconcile their words: meaning in other appointments the first does not return at all; and so if the first high priest returns to his work, the second will not resent it if he too serves, since in other appointments the first has nothing; but R' Yossi in all appointments judged most that the first returns, so they resented — therefore halachic ruling was needed; see responsa Chasam Sofer Orach Chayyim simanim 12–13.",
    "7:_": "There s.k. 12, and if they are not. P.S. This law requires study and contradicts s.k. 17; I examined Beit Yitzchak — not relevant here; they already placed it in the beit haknesset and made it a residence illegally; now permitted to sell after a deed was done; see Chasam Sofer Orach Chayyim siman 31."
  },
  "chokhmat-shlomo/part-001.txt": {
    "14:_": "(siman 14) P.S. Refer to the Magen Avraham, siman 66, what made it difficult from here to the Jud and refer to my essays to the Jud from the 4th edition in response to KK Kazlav MS to settle this on correctness in Aza'i and how many differences of law arise from there and from the MS the author Reuven who said this land I give, etc. Refer to the MS that belongs to it in my essays on the HOM of the 4th edition C. Rcha in the answer Neighbor Laws C. KG to KK Tarnapal per:"
  },
  "eliyah-rabbah/part-001.txt": {
    "3:_": "[c] any material, etc. A dhumesh in a cover and a phumesh made in a shein scroll are always Olat, and refer above to our KMG Dhumeshin sign if five phumshes together equal one pentagram made as a correction to a Torah book:",
    "4:_": "[d] And also prophets, etc. The writing of Olat always means from here on Dehumesh and prophets and scriptures that they are, so far. And Tima from Shas Megillah page 27 of where Dasur took the blood of prophets and scriptures with the blood of the Prophets and scriptures, but with the blood of the prophets and scriptures they take the blood of the prophets, and so did Magen Avraham. And it should be said that the Shulchan Aruch and clothe is precisely for the matter of the Sefer Torah handkerchief Kamari Dashoin, both the Prophets and Scriptures Daf are about 500 Kaddish more than the Torah Sefer handkerchief, and in the blood of the Prophets and the Torah a handkerchief is not allowed for the Torah Book, but for the purpose of the 500 Kaddish and Prophets and Scriptures it is more Kaddish and that is clear. The Rabbis and Ketubim Shein wrote in every matter, and what Magen Avraham wrote about this, refer to the Tosaf Yom Tov siman 4 of Darash Hashanah:",
    "6:_": "[And] there are prohibitions, etc. It means even in retrospect that they have already sold, it is forbidden to buy with his blood as stated in it, and it also means in Matintin's Divani Ha'ir, see there, and also it means siman 11 of the prayer laws, and it also seems to be in line with the words of the BH written by Abuhab that there is a metirin, and this one admits at the outset and does not disagree with the Rabbin on this, so far. This means that the Rabbinate does not disagree with this, but regarding diabd he disagrees because the Rabbin even forbids diabd and duk. And Della, as I wrote in Eliyahu Zota at the beginning of the view, as well as Magen Avraham understood the words of the Bah and Shulchan Aruch yes and Lita but as I interpreted. Who is in the Sefer Torah, like a lift, a lift, after us, it is permissible to sell a sefer Torah in a different image when they have already sold the first one to all of Alma Yayinta in the scroll, page 27:",
    "8:_": "[H] The deformed back, etc. All of the latter brought a silver puzzling in the name of R. Moshe Cohen Deza Hoy Ketvi Larog Delika Laman Milta Ho. And I am amazed at their bewilderment Dashtmittia Tos' Sanhedrin page MH 45 Momot, etc. that they wrote tears of Adifa twisted for weaving because I was pressed for Mikneh every word. But it is difficult in any place, it is not better than a weaving, it is permanent, there is no invitation to Milta, and this is how the Ram's answer was difficult, Siman Ng. siman 8, so far. And what shall I do if I do not refer to Rabbi Gofia's answer which makes it difficult, and excuses Dain's intention to forbid him except after the prayer, and if he does not pray, he will remain weak, which is not the case when the giver of the disobedience near the collector discourages him, refer there at length. Also, what was difficult for Magen Avraham Debssanhedrin Ita Dakhshgabo from the death of the dead because of an invitation rather than an act, it is not too difficult to dehatam meiri from the permissible from the death's disfigurement and not from the death's necessity of the dead body. And here is the 16th siman 3 of the Rama in the division mentioned above from the Shas Megillah page 26 Dafrich Abei of Barita per them it was a condition and not from two of my demeiri that came to the collector therefore in their eyes it was a condition only but a dayin division, so far. It is possible to change the most. Also what he extended in siman 2 Dagbo Ma'aut is not to be changed because of an invitation but because of a vow and if he wants to borrow and pay it is permissible to change it see there and he took a method for himself, and what he brought evidence from the fact that the dead man was entitled to the need of the dead man himself is not evidence since it came to the hands of a collector as I interpreted it. And simply an oath of the good people of a city in the status of city people is allowed to change the ma'aut as follows, and the same is true when they brought wood to the collectors:",
    "14:_": "of volumes, etc. And if it is known that they have done nothing except with a people and no guests enter it, it is like a village that is mentioned in the scroll, page 26, in the beit haknesset of Artisans:",
    "18:_": "[18] It is forbidden to mine, etc. This is the language of Magen Avraham if they do not want to buy with blood another kind of delicah for the sake of crime or they want to buy severe holiness, as well as the meaning of the Rabbin in the name of the Ramban, so far as his language is concerned. And let's not be afraid that it is of the Haishinan volumes, lest there be one who does not desire severe sanctity, and he also wrote in the response of Mashat Binyamin there, and it should be said Demgan Avraham Akfraim Kamer, and this also needs to be studied. Mashat Binyamin wrote there Dafilo in the volumes Hika Debnavah and another Tova, it is allowed to cross the first Dodai Kuli alma let him rest in this, and also trees and stones from the beginning are allowed to use them, up to this point. And we were because in a different navah and hoi as they sold each other all of them were left alone, but if not in a different navah also stones and trees are forbidden, and Avraham's protection was obtained for him for free see ibid. The Magen Avraham sak 17 wrote this to his language, in the reply of the Rabbi of Lublin, he allowed the sale of the land of the Dakhila Kadusha Lokavi beit haknesset on behalf of Dakhshabanava to the beit haknesset, with the permission and advice of state leaders, and all Alma and other state leaders Geriri, and more will be given to everyone to be sold because Dain will again build a beit haknesset on the same place, etc. And he will make a green garden in it so ugly as other uses so far. And it is necessary to study that sowing is an obscene use, as it is written in Kana, siman 11, and it is necessary to say that I do not need plowing, that is so obscene. And I did not get to the end of his opinion, Daharm wrote There, even on the back of sowing, you will use obscene, it is in any case not ugly, etc. After all, Dirk's model of sowing will be used obscene, but he wanted to say that it is not ugly like four things that he considers in siman 9 that are worse than sowing. I also wondered about him saying that the ancient left the place of the Ark of the Covenant free, etc. And let but this is his language, the place on which the beit haknesset stands for the people is the main thing of holiness will be left free, etc.:"
  },
  "eshel-avraham/part-001.txt": {
    "18:א": "(1) And for the seller of an amulet bag of money after the amulet is , one is not allowed to enjoy the bag to be used in the sand, refer to Sam Chaim Siman MV Dematir and reference Mordechai C. 2012:"
  },
  "kaf-hachayyim/part-001.txt": {
    "12:_": "12) There they sold a handkerchief, taking books in their image, i.e. each Pentateuch by itself, as well as prophets and scriptures, and so on, the clothing, and from the meaning of DSl Dchomshin and prophets and scriptures that Hadadi Ninhu and Tsa Dabiod C. Rapab Sai' 19 Ita Dchomshin their sanctity is severe from prophets and scriptures etc. In the Demi chumashim of the Prophets and the Scriptures and the N'ach as Haddi Ninhu as a mash in the Yod Shem Behaga, MA SKB. And the HR O. D. wrote the model of the Sha'a and clothed precisely for the purpose of the Sa'at handkerchief Kamri Dashoin both the Daf of the Prophets and the Scriptures are more like a Dakdishi chumashim than the Sa't handkerchief and in the demi of the Prophets and the Scriptures a handkerchief is prohibited for the Sa'at but for the purpose of the chumashim and the Prophets and the Scriptures, Kaddish There are more fives and this is clear from end of his words, and so on in the Hanash O. 1. 15 on MA SKAV:",
    "19:_": "19) The text of the 16th SKA in our time we see a lot of people selling books and taking others with their blood, and it seems now that when the book is bought, first of all, it is his opinion that he will have as long as he needs it, and if he gets a better opportunity, he will sell it and take the beautiful one, even though he did not condition it in the interpretation and in this sense, we find it further in the rest of Dukti and in the Scanad sah in the context of end of his words and above, the reason is because if the other one has a priority in it, it is permissible to sell it in order to buy the other one, and also If the other person was better as a mash in the Sahak Kol Ya'akov on the Yod C. A. R. O. 2, but it is necessary to deposit his money in the hands of another until he buys it due to negligence as in the Yaosh. And in the Mosh. A. R. O. 7 the reason is because an individual's desperim is allowed to be sold as a mash in the Sai' Yod.",
    "1:_": "(1) There — but not from beit midrash to beit haknesset together in one's home; see siman 154 and siman 18."
  },
  "levushei-serad/part-001.txt": {
    "3:_": "Siman 161 in the addition of R' Makdimin — verses of Scriptures to verses of prophets.",
    "9:_": "There, however, L. Rambam. Now he begins to settle the words of the B. Da'ag HaTor and the Hari'a, it is not proven that there is a flight of Aharon, and per the words of the BH, the Rambam is certainly a flight, and therefore 20 and there is a reason:",
    "11:_": "There — and we were MS CG. Magen Avraham came to say: how did Mechaber find this law from Rambam? Indeed many disagree; see there.",
    "21:_": "There — see responsa on this matter.",
    "1:_": "Siman 154 — whether one may make a beit midrash from a beit haknesset; see there."
  },
  "machatzit-hashekel/part-001.txt": {
    "1:א": "(1) (SKA) Mothor 20 and Esi' Kana Ka'if 2. Demshema Dbhamm Dashidh Kalisha Kadushti' Makdusht 2h Shem DIA Dbhamh Dshidhid It should be easier to use a name than to use Bhakh and Akh Asso' to make from Bhakh Bhm dshidhid Hord':",
    "2:ו": "(6) And per Rabbi Hadar II, 20, and in the opinion of Rabbi Rabbi Rabindranath, it is forbidden to lay down scriptures against prophets, as well as regarding the matter of Kanin and Dela as in the scroll:",
    "4:א": "(1) (SKD) 11 and 28 20 20 Dalchaor 11 Dhimm 20 21 are the Rabbin Dawser and the Hari'a is the one who permits the rabbi brought in the name of the Rabbi from ' here in the scroll, page 27 AA, what is it to sell an old Torah book, he took a new one in it because it is not above me? And the conclusion is that it is forbidden for crimes, because it is written and laid down in the scribe's house, and it is not prohibited, except for the giving of blood, as in the 3rd of May, and not ifest. And the rabbi and the late rabbi brought the late 20th rabbi that the words of the column above (as the Sha'a in siman 2) but ifka take them down from their sanctity does not mean that they are not strict, but rather that they do not take them down from their sanctity but to buy as stated in them by the priests of end of his words and from this it means a meaning to the rabbi of Dharan and the rabbi disagree and they are the second opinion that was brought forth in the Sha'a and the za'ak MA Dhabh 20 Not like the Rabbi except that the Rabbi and the Rabbi do not disagree. Dalkathal' is certainly forbidden and admitted by the RA, and in this Meiri Haran Daha gave me evidence from the above-mentioned issue, Demeiri Lechthal':",
    "4:ד": "(4) But the language of the 20th wanted to settle ' the words of the BH. And without a doubt the Rabbi also finally went back on it and per the 20th in the siman 19 there is a metirin of the rabbi of the RL Lachkhal' Dadiabd likha man dauser. 15 And there are those who permit the RL to begin, and the AJG do not cite the words of the BH, whoever permits to begin, to this 21 MA Dharambam, OT permits to begin, 12 11 Dhimm are the Rambam, and KMS MA 1 Ahzaz:",
    "4:ה": "(5) The villagers, etc., in their blood, otherwise, it should be stipulated on the taker that he shall not bathe him, as explained in the Sha'a, siman 9 of the end of his words, it is explained that it is permissible for the first to sell with the second and to buy with the second, otherwise it is a dekdush, as stated in the Shari Lach'al:",
    "4:י": "(10) And from siman 152 s.k. 2 Shach like this opinion; however this reason does not apply to beit haknesset as explained in siman 20.",
    "4:ל": "(30) And the rabbi Delharambam's 18th of the Laws of gifts to the poor and was brought to Kman, siman 13. That is, when they do not have a beit haknesset other than Daha, KH3 Afi', it is forbidden to contradict, and KMSH Rama, siman 7, and end of his words, it is forbidden to conceal, Afi' they have a different beit haknesset, such as the MASH MA, RAS KN2, and the HC in the 26th siman 16 and in the Shlomo, to replace the HC with another 11 To replace it with another, which has already been built, and KMS MA, the above-mentioned Rama's words in the 16th chapter, as well as the Rambam's words, PIA, from the laws of Tiflah, A.G., to build with blood in beit haknesset. As in the 3rd Epistle, it is forbidden to contradict, and because it is a sacred necessity, the prohibition is not from the side of the law, but the best. To a priest from any place, he will never be negligent, and it will never be for them, but if the beit haknesset is one, but for the saint, Hamor, I will not feel that they will never be negligent, and they will not build at all in the beit haknesset otherwise. Let there be a place for them to pray, and so Afi' Lika beit haknesset, otherwise only Ika Dukhti for the toasts of Gach Shari and A. But then, I do not minister to the MD because I am a priest, and I am a priest, but when they contradict the old, in order to build a new one, and for the time being, I may not be a priest. And the above-mentioned M.D. Dharbi in his long book No. 15 also stated that the Rambam is forbidden to sell an epitaph for a \"holy\" purpose, and it is permissible to buy a box \"because it is faded, a\" serious\" and the Rambam says that it is forbidden to mutilate, and that the Rambam's \"meiris\" were used only when they have already sold it, and the rabbis of the M.A.",
    "5:א": "(1) (SKA) There is no dakhtoh to weave RL 's fees in the Sanhedrin page MH A A AJ Dafligi Abiy and Raba weave a garment for the death of Abiy S.L. The shrouds of the dead are forbidden in pleasure per the law. Dela hoi hazman' and a'ag dalhad ti' hatos' there are motar hamat', etc. they wrote tears because all my hair is better than a fabric and it is possible to be faded as a fabric. Tears were like a cloth. Ha KIL Karba and Aphi Arig hazman' lao Malta and AKP not arif ma'at marig.",
    "6:_": "(SK 6) to all 20. 20 in Gm' page 27, this is their religion, and also in their permissiveness (R.L. that remains from the mutilation that needs to be sanctified, there is no removal of the mutilation permitted to the saint' is easy) and Rabbi L.S. said except that they sold a holy thing and bought from the mutilation of the one who knows it is holy for a consideration and the mutilation is permitted, but they collect mutilation for the purpose of holiness and buy it holy and the mutilation is permitted from the mutilations those mutilations are permitted Itabi' Abi Datanya Bariata Datanya on the above-mentioned matani' as well as in their permissiveness. In the DA we didn't give, but we gave Afi' to Dokhsosi' (RAL to hire a messenger for public needs) it is allowed and in May we are not dealing with his acquaintance and they left it not from mehani a condition but in His Highness Ma'aat and APA in A' condition and how did Raba allow in his back Afi' without condition and secondly for ever and ever Meiri in his acquaintance and they left it and a condition we were ZTA in MA and A. Mitzvah Ak Mai Utiv Abei Danyahu dela bai a condition to speak a mitzva MM to Dokhsosi' faded thing a permission in their eyes a condition AO Dabei s.l. Madaram Raba just collected from a misdemeanor and what is left is permissible. It means that you are completely free of what the authority says. But the 16th divide is not allowed except to speak of a mitzvah who is for the purpose of duchess' or other needs of a gathering of cases of a mitzvah:",
    "9:ו": "(6) And the 5th 20th for the redemption of captives, and the Shas , there are no salesmen except to study the Torah and marry a wife, and neither did the redemption of a captive of Heaven say that there is nothing that stands in the way of the control of the soul, and the whole captive is with him, and he is the control of the soul, and there is no need to ask them:",
    "12:א": "(1) (Seq. 12) A.K. Telo, K. De Danhalko, the rulings on the basis of this, sell volumes. The seller is not entitled to a D.A. on behalf of the seller, since the volumes are there with him to pray from other places. No one except in their own Naoho, they are also the Bnei Karach may sell them as in the village, but most of the rulings are reasonable for them to have dafi' in their own Naoho and no Saiyam, a person is prohibited from selling , since many come from other places to pray there, as the Bnei Karech, when their son in the beit haknesset, certainly in the Naoho, also per the opinion of the whole world, they came to pray in her name, and the most KIL for the material, I will say more in the Maglah, page 26, said Rav Ashi Hai bi knishta aag ato la kyun dadaiya didi katu e bainya mazbanina la and from that the column was written as a mash here in the Sha'a but due to the volumes Efi' built it from their own it is not sold but hanged it in the individual's opinion. In the opinion of the individual, it was an epitaph that they could have sold, and perhaps because it is a large volume, one should be aware that one would be missing during the sale, etc. And it is not enough because there is a problem about him and from the words of the Rash and the New Testament we have learned the truth of this law that the Rash 20:20 seems to be the only one in his generation like Rabbi Ashi whose opinion all of Israel etc. In singular A and also Afi' it depends on everyone's opinion, it will not be useful, as end of his words Mahar'i Habib, etc., the rabbi, per the words of column 1a, should burden me with this, therefore, 20 Rabbi Da Dakh, the Rash, rather, a faded ra, a single person in his generation at that time, simply, I did not depend on me, in the opinion of the Rabbi, I say that everyone agrees with his opinion, but if it depends on P, in the opinion of a single person, it is easy, easy, easy. And the Ha-Ha hung in their own opinion and this Dankt the Tor hung in a single opinion and as the Kash' invented 20 as above 20 the Rabbi T. Ehad D'orah' Demlata Nekt Del Harov The rabbis do not agree with opinion A. Therefore he took Talo in a single opinion Ekt44 and henceforth per MA per the simple meaning of the words of the Tor and Sha'a 70 but of volumes 20 Efi constructed it from their own as Efi' 20 means Dakhsh in his son Oth from the example of others Dkan Teva L' Efi' and ala kai mash aak hang it in the opinion of the individual meaning of Dakai Gach Atroyehu Efi' in his son an example of others Mahni when it hangs in the opinion of the individual for this it was necessary for MA to say Daino Yes:",
    "12:ב": "(2) Dabshlama Mr. Bar RA (Rabbi Ashi Ketzel) Mastama Kuch Dakshiya Lia Dak Mata Makhashi' his son from the example of others Daha there are rulings DHT Dashal volumes is not sold also others who come there gave to our sons and Ak Mata Makhsasi' faded vol. Surely others helped our sons and Niho dal ki kal most dal tali' by giving Ma'ot all others but the 19 Dakrachs is not It is sold. All the people who come to pray there, as mentioned above, will not share with the first judges in the reality that others also help in giving our children, but meaning Dla Tli' Baha'a Dma't said RA Bamta Mahsya' Dhua Mtzvi Dida Dbmata Mahsya their own dak. The above reason for the RA and the SHS to interpret mahsiya' in their own way since their Dastam vol. others also help and a model in the mahsia mahsiya there were others who help as per vol. and APA said Rav to Zevoni. And for this, MA needs to divide between DA Dafi' simply from Tzi Lazboni' and Afi' in Nauho from the example of others.",
    "12:ג": "(3) And Rambam in the name of Mordechai — even Rambam and Rosh agree regarding a beit haknesset built not for prayer but for residence, that if the good men of the city agreed to change it, they have authority even for secular matters.",
    "16:ה": "(5) As a rabbi in the HC of the siman 19, it is forbidden to extort an afi' to pay a beautiful thing from him end of his words:",
    "16:ז": "(7) Hereafter L.L. in the status of K. RL 500 MB 2 of the trees and stones should be sold in the AH status:",
    "17:ג": "(3) And and from SD in the name of Rambam 20 and in the same name and and from Baa in Sec 33:",
    "17:ד": "(4) 20 HaMb 20 20 Abel Ei Brir Lan 20 and end of his words Demlashon the Rash and Ri'u Mesme 20 Mestem' the citizens of the city dedicated in their opinion:",
    "17:ה": "(5) And LB 20 at the time of building 20 mm from the language of the 20 20 and I didn't understand it from the 100 Efi' it was built just 20' we see Dabin MA Devri 500 from 2 meaning Dedat HaTos' and the Ramban and the Haran if it was built in the same way through this parable for many days forty and fifty years and now at the time of familiarity' they don't remember who built it or the people of the city alone or all Those who come to pray in this Amerinan Mastama Nao' begins with P. A.D. All those who come to pray, but there is no choice between the people of the city, but the opinion of the people of the city. And end of his words Dahzi' Debain many to pray from the Alma, I did not say' end of his words Della Ha'at during the building when they were building, I will know the whole world, MM AHZ when they came from other places to pray, they dedicated it to know 20. But the cases of Kfar. The endowment applies at the time one begins to pray and not at the time of construction (Kashmash siman 8) and 27 MA Dainu yes Dainu there is a dispute about this. And also the opinion of the Torah, Ramban, and Rabbi Dachel that we built just for nothing and did not allow that we built it precisely on behalf of the people of the city alone has a volume of law, and in the answer of MB, it is explained a little more:",
    "19:א": "(1) (siman 19) And there is no such thing as \"we were in the land\". And the end of his words wrote in the Sha'a Satma MM Satma as the meaning of Demeiri Duka on immovable land Dekarz Demeiri on movable land We did not find any place of declaration in it. On the contrary, it is explained in HM C. KT, Section C. Debts and bills and chattels are not declared. For taste:",
    "22:א": "(1) (siman 22) It is permissible to sell it as 'because it is not voluntary' as it is in the final'. Ral Delfi MS Rashbam there in Tractate 22 page KNA Aa to KM there is a tefillin akri nakshi and if one said tefillin to a certain one also a tefillin in general. And I asked him what is a non-proprietary item and wrote the Rashbam and Zal Sat who is a non-proprietary item and a fee tefillin or a tefillin dilemma. And if possible for the seller of non-equity property cases:",
    "4:ח": "(8) And the seven good men of the city may annul holiness; we were precisely per Taz in siman 10 when between minor and beit haknesset holiness they leave their sanctity.",
    "9:ד": "(4) And if they sold, etc. — see there."
  },
  "magen-avraham/part-001.txt": {
    "2:_": "as well as prophets and scriptures. The meaning of meaning Dhumshin and prophets and scriptures is that Hadadi Ninhu and Tsa David 3. Rabb CIT I. Dhumshin their sanctity is more severe than prophets and scriptures, etc. In the name of the the Master and the Haran and Tsa Daharan himself wrote a severe sanctity of the prophets from the sanctity of the scriptures. The B. C. 1998 and it is possible that DMM is not so severe that it would be forbidden to put A. Deshri, because it is not possible in a matter that has a material side, why would it be permitted in the and from Sakh, and per Daran in the Magila Hadar Biya from the Mash in the siman 19 and the Salvation of Dechi Hadadi, they are only the preliminaries of the scriptures because David the the Master precedes the prophets:",
    "7:ה": "(5) Sacred words. P. Dam, they sold Zeta in the Ma'a in the villages, it is permissible to use blood, and in any place you shall use a sacred object in its purification. It exists as Mash C. Kand, S3 and and from SI, but in the 25th and the use of Mitzvah, it is permissible to use them as Mash Set 9 (Ran in the name of the Ramban):",
    "7:ח": "(8) Not allowed to sell. If they don't want to buy in a different image in a different color to illustrate the crime or who want to buy a grave holiness (KM Baran in the name of the Ramban) and and from Sd in the name of the Rambam and KM CJ A.S. and in the Begum there, and Iiri when they don't have another beit haknesset and AbiD C. RNB SA: The writing of the M.B. Seaman 33 on the site of the Dla Chachihi many Dathi Malama is called Kfar Af On the back of Dashchihi, many people pass and return from time to time, since they do not regularly pass through the city, but pass and return through Arai, it is called a village. Indeed, any place that is frequented by many people who do not pray there, such as a place where merchants gather there frequently for goods, or a place where there is a great sage who gathers there many who need him and his teachings, vol. They were not helped by other village cases, and even on the back that the language of the Rash and Ri'u means Dachal that many come to pray there. I understood that I was a child of my father.",
    "7:כ": "(20) for easy sanctity. The TS is and the Tsal that it is forbidden to change requires a declaration and the 15th in the DM and in the answer of the Rashba, such as one who commands that this house be for the poor to eat the fruits and commands that the congregation not smuggle from it, and yet the public cannot give it as a gift after the the Master has given it. If they need to, they may collect more until they are satisfied, and the same is the case with the beit haknesset's candle. When there is satisfaction for the beit haknesset, besides that, they may change it, but while there is no collection, they give more to the poor, if they have an annuity and stand one and dedicate land to its fruits, and add to the simple annuity that the collection is not allowed to change, and so everything that they did not declare is wrong in the matter of Mishna end of his words, refer to the 24th sign of RNU SD:",
    "10:ב": "(2) And there are those who forbid. And per him, even a Zeta in the MA and a member of the city are forbidden to sell their blood and use their blood unless it is to study Torah, etc. And from all of the above-mentioned Dabatshemishi's, the only one is allowed to sell their blood and use their blood, the main thing is proven by the Rabbis of ' that one does not sell a Sabbatical except to study Torah, etc. The Rabb except that he wrote there, in the siman 19, also in the Shamishi' and Tsa, and it is possible in the Dmash, there are those who forbid Kai only the Tsa, and as in the 4th Sessi, ar. B.D. Siman R.F.A.S.H.:",
    "11:ג": "(3) Dai Lao etc. — But to give to a distant city that certainly will not enjoy it is prohibited; and for those who forbid selling a sefer Torah, it is forbidden as a trick to give the sefer Torah as a gift and they give money as a gift — forbidden [Ribash]; and from Taz's words, giving a sefer Torah as a gift does not lower its sanctity, as in the gloss and Tosafot and Rashi when they wish to annul beit haknesset sanctity they need a stipulation that sanctity applies; but when giving to many who will pray in it, sanctity still applies — see there.",
    "14:ג": "(3) standing and screaming. Since Datihab Adeta Dakhlahu and Tsa to the BHM Afi' the owner Mikabin Shari as BID C RNT SB and KM Bars this and BSO Dlakdosha serious not in the BMA and Tzal DMM if one stands and her mind is not allowed to change it and in the BID Meiri who is not a member of the city:",
    "14:ד": "(4) Their right as city members — and since Rama did not write this gloss above in s.k. 37, it implies only here the seven good men of the city help, for the people of the city accepted them for everything; but above regarding cities where people come from elsewhere and volunteer for the beit haknesset, what the people of the city accepted about them does not help; and likewise Beit Yosef in Choshen Mishpat siman 109 in the name of Ritva that one court cannot stipulate for another city; nevertheless for minors they may stipulate here as Ran wrote; and Mishna Berurah wrote that nowadays the seven good men may sell even in cities, and likewise Beit Yosef in the name of Mordechai Yeshan — end of his words; and this is specifically when they built it themselves as Beit Yosef wrote and as explained in s.k. 7; and likewise in responsa Rama Lublin siman 59, and nevertheless he permitted there to sell beit haknesset land in the community of Luka because when they built the beit haknesset everything was done with permission and counsel of state leaders and all follow state leaders; and further presumably it is agreeable to everyone to sell because there is no remedy to build a beit haknesset again on that place because priests obstruct, and also one should fear if it remains vacant priests will build their house of prayer on it; therefore certainly for everyone it is agreeable to sell and it is a merit for them and one may benefit a person not in his presence; nevertheless for the spirit of the matter they should leave a place for the holy ark vacant and make it a vegetable garden that is not so disgraceful as other tashmishim and it is also in purity — end of his words; and it requires study, for sowing is a disgraceful tashmish as in siman 151 seif 11; and one must say it deals with vegetables that need no plowing that is not so disgraceful.",
    "15:_": "It is nothing — meaning from the regulation; but by law one can forbid as in Yoreh De'ah siman 224 — see there. It is written in Hagahos Maimoniyot in the name of R' Shmuel: a community that had a box in which they placed tithes and one forbade his portion and permitted them for the rest — end of his words. The difficulty is what he wrote from beit haknesset; possibly what they place in the box was already set aside from his mind and stands to be taken per the will of the community leaders, and it is as not his own to forbid them; not so in beit haknesset that stands forever and each seeks to merit forever in his share; nevertheless it is good to ask about his vow (Yeshuot Shach 5:165); it appears to me tithe is not his own as in mishnah chapter 1 of Nedarim.",
    "17:א": "(1) Who was, etc. Gabi Irov Dafi' where there is some point in changing it, there is no reason to change it because of suspicion and the Han Ika suspicion that they will say that the members of his household are not Mahogany, he can also say that he does not want to go far to the HC, even though they earned more (Maharik):",
    "21:א": "(1) A zonah — and it is when in siman 15 a man came to her and then gave her payment; see there.",
    "21:ב": "(2) Price of a dog — for example he exchanged a lamb for a dog; two partners whose share one took ten patches and will clear one under the dog — see there.",
    "21:ג": "(3) Prohibition of nudity. A Kutish zonah or a slave or a debtor to the enemy [Rambam and Rivu] and above from the judge a Kutish zonah and did not just take a Kutit meaning that this is the first time he came to her A. She became a prostitute and so on when he came to her after A. and he gave her Atnan Hoi Atnan a prostitute and so on Rashi page AO A and so on And so on in Bimmot, page 91, end of AA and Zal Darba, he did not sail, but he fornicated her, he gave her Israeli food, but she did not fornicate. And in the Gam' it means Dahona and Atnan Shein, they are Daha in exchange, Yilif to Ho Raba, what we have specified from Mahdadi and the Rambam to Shettia, Azil meaning, a model liable to enemy, Hoi Zona, etc. And the Rash Sibira to him is absolutely obliging circumcisions O harlot, but obliging to the enemy not cases of harlotry, but that priests are forbidden from another scripture, as the Tosaf wrote in the extraction of page MD 4, see there (and the rabbi's difficulties are explained, therefore he wrote in return, Dam comes upon the obligees of circumcisions, oh, we are Afi' in the seta, because she was brought by a harlot, but now that she became a harlot, it came later and came upon her) No, I will not let you go, but I will give you this walk, and here Rama wrote in the DM and A. BA what cases of adulterers, called Daf Datos' wrote here Davmofkerat hoi etnan not ki'l kvtya but 15 demsme bahdia in the gemara datnan and kohuna shein and the words of the toss 14 Lishvan, etc. As above, it is clear and A. in the book 17 and refer to the firstfruits on page 19 2b:",
    "5:א": "(1) From what is permitted, etc. — meaning after they have not yet come to use of weightier holiness; see there.",
    "5:ג": "(3) And if they bought with this money, etc. — see end of Rama's opinion there.",
    "6:_": "There — see there regarding building a house for residence."
  },
  "mishnah-berurah/part-001.txt": {
    "5:א": "(1) Or Sat - Amma no mshinin kai or danktiya for the name of the people who it for providing students and as dalkamiya in the S.O.:",
    "7:ב": "(2) And even his son - , others gave them the opportunity to do whatever they wanted with them, since they are not used to coming there, and therefore even those others do not agree later on the sale is allowed for sale:",
    "7:ט": "(9) (Lg) They even built it on their own - Dachion with it, apparently the townspeople dedicated it also in the opinion of those who enter, and therefore they do not have permission to sell it in case there is someone at the end of the world who was near this town and used to enter it and in his opinion it was dedicated and he does not agree to the sale and therefore they even agreed to the sale, in the position of the townspeople, there is no sale, a sale is not fun for the townspeople and pensioners, and even if they want to later raise the blood from it in sanctity, such as buying 17 and 23, they have no permission for this, lest others will not agree to it. 27, in the end, but if it is clear that they did not build, but I will let them know their city alone [such as they were allowed at the time of their building, or at the time of building it was a village, and later there were many inhabitants in it, nor did others help them. It was judged as a village.",
    "7:פ": "(Ma) when they have another church - the MA interpreted the DR when they built it differently now, but when they have two churches from before, it is forbidden to sell one, but in the siman 16, in Rish Siman Knav, it is allowed even in this way, as well as the opinion of the Rabbi there, as well as the meaning of the interpretation of the Gra, but 27 precisely when the same church is spacious and it holds for everyone, it is simply forbidden. Otherwise, it is permissible to contradict the first one, Dudai 15, let him have it [and we have already copied this above in the Kanav sign], and trees and stones from the beginning are allowed to be used and taken out to the holin per the 175 in the case of the people of the city of , he does not care about the sons of Alma because they have a good place to pray:",
    "8:ב": "(2) (Met) is not holy — for we hold invitation is not a thing, and it is permitted to change money collected for a beit haknesset to another mitzvah in the manner of a loan until repaid; see there.",
    "8:ג": "(3) (n) Even if in Naoho, etc. - Daf that was a non-accidental Gach act, only an invitation to Alma:",
    "9:ד": "(4) (No) And if they sold it seven times, etc. — then taste has completely expired from that place; see there.",
    "10:ב": "(2) (S) Even the OT - the writing of the OT Daf, per this opinion, is a domtar and the blood is not to be taken in holiness, MM 100, there is no sign of blessing in these bloods, etc.",
    "12:ב": "(2) (o) He cannot sell — the congregation did not rule over that mitzvah except for that man and his heirs; see there.",
    "13:א": "(1) (Eaz) a mitzvah - from their mitzvah means any mitzvah such as charity etc. 22 even though it is not severe sanctification in 29 and AJ above in the 50th he ruled against ma'ot Dain Shnin but for severe sanctity 21 Meiri by 25 in the position of the people of the city it is desirable to exclude the ma'ot even for minor sanctity and even for minor ones and as above in 37 [MA] and 16 Muki La although not Zeta in the status of an ana, but the Dashkili of the Ma'ot through the loan and later will return other Ma'ot to the building of the Court of Justice and Azil to her taste in the SKB meaning there on his back from the Ma'ot of Domtar he took through the Lo'a:",
    "14:א": "(1) (Fa) Not from a fleet, etc. - Daneshah vowed from Mechi and said this land to the church and as in your mouth this is charity:",
    "14:ג": "(3) (Peg) are not allowed — one who can prevent them from building on it even in summer; see there.",
    "18:ב": "(2) (C) They can't - since they didn't interpret Bahdia, they discuss this only in the Torah of a question in Alma, if we use them, Aliyah is holy, and the MA wrote that now the custom is simply that they remain in the possession of their owners, and if so, those who bring the utensils bring Adeta , and as it was stipulated in the interpretation, it does not apply to Aliyah, and it is better to stipulate in the next hour that it is only in Torah of question in Alma:",
    "5:ט": "(9) And if they sold, etc. — see there."
  },
  "mishnah-berurah/part-002.txt": {
    "21:ג": "(3) (Kg) To use for holiness - but for the mitzvah Sheri etc. above in the sign of Kanz 11 Bmb and invalid books of the OG that are bound in shiraiim for decoration it is not permissible for the shiraiim to make a Talit out of them like idol clothes and KU forbidden to make them into holy things etc. It is forbidden to take the bindings and bindings on our holy books:"
  },
  "peri-megadim/part-001.txt": {
    "1:ה": "(5) For the poor man, there is a problem here, in section D, he did not decide. The Rabbi Ya'ash and Man said that other things in Shuh are also allowed there in matfachets, it is allowed and to say that a liya mission to renew is faded, a little elevated, etc. And also apparently the rest of the words of Daikha Elioi are prohibited as the 2nd chapter of the KNG Ha Likha Elioi Sharii in other Deuteronomy (Lehbi Medla brought 21 Rish of the words of the RN) and Mtefhat Sath to another Likha Elioi after us. Also in the Gemar, there is a description of chumashim, not in the Sat Ha Torah Torah Shari, and in the Lak Ha chumashim in a chumashim scarf, otherwise Shari apparently means all of this, Daikha, for the lifting of the Peshita Dasor, and Dika Ha Torah in the Torah Shari, and Tsa in all of this, and there is no need to extend:",
    "2:ב": "(2) And above all, the interpretation of this law is here in his long book, the Rabbi brought two excuses, A. He collected a mutilation and came to a tax collector, the deed of which the mutilation itself is forbidden to change them lightly, even if they later want to give other blood in return (but it will be replaced immediately and the holiness applies to the B. And also in the sale of the SAT, if the mutilations were exchanged, they were the first to go to the holin) and it is permissible, per the words of the late Ram Zal Pia Mahat The 14th sold SAT in no muridin and in the 15th and also collected Ma'aw meaning similar to this, it is forbidden to change the sacred mutilations like the Tamm (and what is permitted is not similar) and the column 22 and also 20 and 16 the hard Ramach BKM brought there Del HaGamara Raba Megillah 27 a. 20. For severe, etc., but from severe to mild, and not to buy later, as a general rule, a serious one, I will not cross, but surely the molestations have no holiness in them, and they have no sanctity. Other bloods to come out by Nadram MM since they have already bought SAT and sold it In sanctity, like the citizens of the city, who sold 200 and without giving the permitted affi, it is forbidden to detract from its sanctity, as it was written. And he held this sabra from Ha Darba Megillah 26 2 Livni Atikta that it is forbidden to lend them, but Hadti Sheri (see siman 11 mentions Din Atikta) and I do not distribute the Haddi in person when they come to a collector, it is forbidden to lend them anything that does not have an immediate exchange, a holy renunciation, Alyahu Shm. The sanctity of the Aaliyah is at the request of Lau Malta. They came to the tax collector, the hard part of the money, why for the dead, but per his method, Didi Nader Kamiiri A.S. and he is per the method of Rashi of the Israel Defense Forces, surely not, etc. We admit it as he was before, but it is difficult from there. It turns out that Kela will have the same negotiations. And A'R letter H and LMS A'S. And M.S. Baha Dafrich gave what to me and T. D.S.D. Dokhsusya Mitzvah. We have already written above what he asked for it. And the letter of the A. R. letter T. Dufi' for Doxusia, the language of Efi', means LM Kleh Tani and Ha Makhamoru Lakle A.C. This is what Afi' Dokhsousi said, that it is a permission that is enjoyable and without conditions from a burden to a light soul. And Ama Ha, what request did you make to Rabbi Maram and Ran, and not from the YAS:",
    "3:_": "And if the 17th rabbi ruled that excuses for the rabbi came near Gabbai, there is a sanctity for those deformities and it is forbidden to take them down, Efi will later give others, and even before they came near gabai, one should observe a vow of M. and the 16th difficulty for what purpose did Rabbi Davnim write 20 Dakhsh he is from mischief. To the tax collector, this time, he collects his money and they come to the tax collector. And here YL Dlau 29 is a DL Ma'at as an Arig Demi KMS the Tos' Sanhedrin MH A. D. Ha Momot and S. A invitation because the island came to the collector of Malta is an Mashak of stones griei Dakhtvi to Arig Demi Demush building and no invitation at all Hoi and Ima even came to the collector there is no holiness applicable to them KML and MSH DKAL from Megila 27 A. H. P. Daf per the method of the 16th Didi, a vow did not come out as a 1911 when they came to a collector, one needs a condition on what is permitted, and so what is frich Delma Rabbi Meiri did not come to a collector, they only collected it among themselves and did not hand over to the collector the deed of the deformity. The Rabbi even came to the collector of the permitted sub-collector from Dela Moki, as well as in their permits as 33 and Moki specifically in his sale as 11 and also means that the tax is equal to the body of the fund and in the permitted Mahani condition Shm in his sale 20, except that Shm Dain brings up the rule of what came to the collector and A'er Aut 8 and Mash A's and this son and IA in the MA will further:",
    "7:ב": "(2) And here I have some reflections here, I said in conversation and it will be good for me to know that the Ramban and the Ramban are divided in the sanctity of the Ramban. The Ramban has no sanctity in it. At all or to borrow them religious ministers use a mitzvah if they want a minor thing and he is a delibani to borrow them is forbidden ZTA without Bama Deshama they do not want them to deny the mitzvah completely the author of the BSA the ancient Afi' by ZTA and did not end with the BMA probably from Bbi who copied the words of the Ramban and the Harban brought only the head of his words etc. Yas means his opinion as the Ramban. But the MA letter 28 wrote even ZATA in the MA is forbidden the first dekdosha AA for blasphemy if it is not for ma'at and the like etc. And here is 11 Nem also in his sale Zetta in the MA just and we did not allow at the time of the sale that the blood would be minor and then want to change the mitzvah to the minor to the Ramban Sheri Kion Dabiah Gopa only use the mitzva 24 the mitzvah is only the zetta not in the maa 11 lest he should not allow him to deny the mitzva completely like this everything they agree to Or about the disobedience that went out to Holin Shari and Rabbi Megillah 26 A. L.S. which they sold as 1. L4, but with the consent of ZTA in MA in their eyes, revealing their opinion, and those to R.N. 11 gave in their eyes at the time of sale precisely and ZTA without MA, or for a non-interesting reversal, they gave Dain Kacham such a large only ZTA in MA, but when they sold just even ZTA in MA They can't later be changed to minor and so on The 18th prayer is also given in the MA for the permitted blood to be small, which means we gave it in our eyes and the EB in the name of Rabbi Dr. Ram Havba Kamer did not even give it at the time of sale for all the blood that I am happy with. And the author wrote that if the sons of the city accepted them in the interpretation of the sale, this is even a singular what he did may and the author wrote the letter 9 and the letter 13 in the interpretation that they will be chulin 20 A.C. And in the language of the author, he did not mention at all the agreement and seemingly means everything that the ZA agreed to in the sale of the Holy Paka, even if they bleed, and did not stop the sale of the blood, Rafa? To both of them, for the bloody ones and for all this:",
    "7:ג": "(3) In a moment I will talk about the source in Baal HaMaor, Megillah 27:2, Aleah , a parable of the plural to the singular, and on the condition of Tirtz Dodai, Ha Dbei, a sacrifice in blood. to apply to the chastity if he did not go to the holin of the Holy Church, even when he did not go to the holin, desparims in their being take the holy chastity) and A.S. 2 Mishniot YAS and PZ Rabbanan and Ram Peligi Delrabbanan parable plural to singular Nemi kadosah with it in it and this is the opinion of the 16th in the letter VI and Khar there Pelig and Sober Dailoi always in their eyes even though the HaKach remains in holiness And Rabbanan Sal of a single sand and this is the opinion of Rashi Shem and Rabbanan. And here in the Gemara 26:1 Rashbag Ari Lash, but the bihak of books and the Rabbi of Nami when they sold their bihak to plural singulars and built another bihak to pray in them Deshata lash All 3 of the reasons that we wrote in the letter VI and Ju Shlama for the Baal Ha'or aak Dak a'C Eloi in the blood Mash'ak for the Harar:",
    "7:ה": "(5) And if they sold in the church of volumes and even deobed, there is no sale of them from sale and it is proven, yes, it is said there (Megillah 27) for s, but villages, but no volumes, and no mother, no debrokhs, and it settles for the second, deobed, that they sold s.m. The seller canceled the end of his words Davmzid was (Debashogg Hoi takes a mistake) AAHM Raz Makha in the prohibition of the YASH and in section B we were satisfied with the YASH. And here is the Maha 27 A. Sat that they sold later 11 Amai the sale will not be canceled and as 33 the rabbi the rabbi imposed on the Ramban as a gift and here is 11 that they sold the fruits diabd they sold for the purpose of Pash and the like and so on and so on and so on and so on and so on and so on and so on and so forth and so on and so forth and so on and so forth and so on and so on, there is no evidence and the Rabbi's difficulty is justified by that. And in the PZ the law is divided into G. If he sold a sat for a minor mitzvah 11 the seller cancels AHM 17 and in the Sama there and if he sleeps he takes a new one 11 Kim liya and who is in ayya dela ipsta 11 dain the taker can say kim me dhashta in the days of the Gemara we do not strip and in the falluta darvuta 11 Kim me your priest and in the new one takes a new 11 dodai isura abid DAK mibaia liya bishen ahadesh is faded a bit and you see from the rabbinate that he interpreted his sale as a dyab kai diabd that the sale will not be canceled and there is no disagreement between the rabbinate and the aharan. And BHM Ramah in Sama LT Ba'ya Nami Y'l Kim Li Ya'Sh:",
    "9:_": "It is not 17 and per its methods in the letter 2 YAS and AMA here is the letter 21 per its methods in the letter 5 but the Rabbi and Bush have a difference between bao near gabai or not. And and from in the sign 13 Ea because from the words of Thos Baba in Tera 3 2 4 1 1a it means that there is a division between those who prayed there is no mocharin for the Pash and between those who did not pray and in the siman 19 it does not mean yes and IA Yevor in the 17th and 18th there:",
    "10:_": "And there is — some forbid per Rambam; see Beit Yosef and Mechaber seif 7; see there.",
    "12:א": "(1) And siman 17 came to me — the poor man needs observation of his words; know this section deals with two l'chatchila questions; see there.",
    "12:ב": "(2) And here the late 16th wrote a DAT for the Mish B. B. D. R.N.B. and his version was Delma Matermi Mitzvah 20. And the High Court asked us not even to Pash, and they let Efi learn but DIL and say that they will collect their redemption from the public, and AHN BHA Masha'k bought stones from Efi's meaning, the mitzvah will be canceled now it is difficult. And here is justified in no other way (and per her methods in the KNB A. Degars Dokhta and A. N. B. Knishta Y. L. D. M. D. Pashiota not S. L. Tsloyi and Shafir said and AMS in Tidhushino Megillah and BSO Bish another and PZ Ha Dbia'K to PSH Nami it is not possible even they have nothing to charge Diritya Dainish I do not slander MM if it is not possible they sell And per the meaning of the language, they will say that there is nothing that stands in the way of soul control. The 16th Demiry in no other court:",
    "15:ג": "(3) There is a difference between the Torah and the prophets, and the writings of the Torah are forbidden in a forbidden use until there is a partition as explained in Ram KV and other books, a vessel within a vessel. And in the 4th R.B.S.H. 20, chumashim are enough for a vessel within a vessel, and in the siman 18, the Ram wrote the Pentateuch as a set and had to divide whether or not it was done with scrolling. And it also appears from B. A. H. R. M. Datos. in the Meiri scroll and B. Hachi Meiri there, in the S. and B. D. in the Galila and EB there interprets the D. A. in the Galila and the halakha as the head and the M.M. Hamir in the A. H. in the Ma'an in the Galila. And it should be seen that davgalila means the same as the SAT literally for all its laws, here Menlan Dhomshin in the scroll in the case of a partition to use, since the Davit has in it SAT Itamar s.m. Dasva is really only that there is no korin in the chumashim in the public because of the respect of the public and this is the opinion of the Rabbi in the answer. In the Haga Sab Hamishin our OT to stand and so on the clothing Dain may be as canonized in the scroll as SAT and PZ HH that there are no Mocharin KA to study Torah and marry a woman in Hamoshin as canonized and standing before them. And the opinion of the late Rambam, the tenth chapter of the Psalms 1a and 2b is not true. Anything that has a mistake in A and is missing one letter does not have the sanctity of the Psalms, and you see that in the BH Ram and in the 24th Rabbinical ruling, and what the Rambam recorded, we were everything that is not made as a correction. And in the rabbinic rabbi c.t. chumashim on the s'at asor dalla karshba and tsa for the shba 27 a and in the kald s.o.",
    "15:ה": "(5) And what they said regarding sanctity of Heaven to erase — when written not for the sake of sanctity but for correction, it is forbidden to erase; see Mail Tzadka 323 in the name of Or HaChaim; see Rambam Laws of Foundations 11:11 and 15 regarding a name on his flesh not written for sanctity; Israel wrote in kiddush we do not intend to sanctify him.",
    "6:_": "And there is — Beer HaGolah notes: some forbid per Rambam; the inquirer in Beit Yosef will see per Beit HaTefillah 1:11 it is permitted only through seven good men in the presence of the people; see there at length."
  },
  "rabbi-akiva-eiger/part-001.txt": {
    "1:_": "Magen Avraham s.k. 2 — Prophets and Scriptures; here it necessarily deals also with chumashim made as a scroll, as proven from seif 3 regarding a sefer Torah in which there is an error — its law is like chumashim.",
    "3:_": "Ateret Zekenim s.k. 1 (from Maharshal) — see in Magen Avraham siman 154 s.k. 14.",
    "4:_": "Magen Avraham s.k. 4 — meaning when they have no other beit haknesset. The words are very puzzling, for Magen Avraham himself below s.k. 33 writes it is a mere stringency but by law it is permitted. And even if we say Magen Avraham's intent from Rambam's language chapter 1 of Laws of Prayer that they wanted to sell, etc., implying even no stringency — he wrote to distinguish that below it deals when they have no other beit haknesset. And so from Magen Avraham s.k. 17 it appears clearly from his words there that he brings proof that for weightier holiness it is permitted to sell even when they have no other beit haknesset, from that sugya in Bava Batra which is this law of seif 13 implying it is not proper to do so, for we say a person's residence is not sold implying it is not customary; but there is no prohibition, and there it deals when there is no other beit haknesset — see there. But truly it is difficult for me, for Magen Avraham per my method in siman 152 s.k. 1 holds that even if there is a beit haknesset it is forbidden, not like Taz there — see there; and so is also clear Magen Avraham's view in this siman s.k. 16; examine — behold the sugya in Bava Batra deals even when they have another beit haknesset and nevertheless forbidden to sell; it requires study.",
    "6:_": "Magen Avraham s.k. 18 — I did not understand and I am puzzled at their puzzlement. It seems simply Mishna Berurah's intent from Ran and Ramban who wrote they built it with everyone's intent, meaning if at the time of building it was a village, even though later many gathered from other places to pray, nevertheless it is a village and we follow the beginning; but from Rosh who wrote presumably they consecrated — meaning it does not depend at all on time of building but whatever was done later as villages they consecrated later with everyone's intent, as it appears simply in Mishna Berurah's intent; and in the essential law this was already mentioned in Beit Yosef in the name of Nei regarding the plain sugya of R' Ashi: this town comes with my intent, meaning since they came only with his intent to study and later became villages, but at time of building it was a village permitted to sell — see there.",
    "10:_": "Seif 10 — there are those who say an individual in his own [beit haknesset] — in responsa Ra'ananach part 2 siman 64 he doubts whether one may say selling a sefer Torah is forbidden only to one commanded regarding its writing; but a woman who is not commanded regarding writing, perhaps she is not included in the prohibition of sale — end of his words.",
    "8:_": "Magen Avraham s.k. 27 — it is written in Mishna Berurah: if they built a new beit haknesset, seemingly puzzling, for already in the gloss seif 7 all this deals when they have another beit haknesset; and see Magen Avraham there that now they built another beit haknesset for this; but in any case even to sell in the default case in the presence of the people is forbidden. If so, the dispute regarding gift is also when they built another beit haknesset and nevertheless without this reason that if not for making it restful for them it would be forbidden; and we do not say the holiness expired on the other beit haknesset. And if so Mishna Berurah's reason is hidden; and per him truly Meiri's dispute is gift in the default case alone. But per Ran who permits drinking beer there, holiness applies to the money and that holiness is minor and they may remove to unconsecrated. Otherwise the difficulty why forbidden to demolish, for that case is different since there are no substitutes on which holiness can apply; and one may say the dispute regarding gift deals without building another beit haknesset, therefore the reason is needed that if not for making it restful for them. But if they built another beit haknesset, one may say that in any case holiness expired on the other beit haknesset; and per this one may say this law of Mishna Berurah is from Manip permitted per Ramban, permitted to annul holiness for nothing if they built another beit haknesset; and per Ran annulment is on the other beit haknesset. And that they ruled in the gloss seif 6 like Ramban and here ruled gift specifically default case in the presence of the people like Ran — meaning we go here stringently and there stringently; but Mishna Berurah's law is permitted from Manip; see.",
    "12:_": "To sell his right to another — see Magen Avraham above siman 136.",
    "2:_": "In the AD — therefore it appears to me forbidden to take, etc., with ak; even per those who permit buying a sefer Torah to purchase other holiness like it, nevertheless this is forbidden as lowering from holiness. But truly there is clear proof to permit, for it is explained in Megillah daf 27 that it is permitted to roll in a handkerchief for chumashim — see in that sugya that they compared them to one another for the matter of sale; and per Ran who forbids buying like it, and where there is upgrading — certainly forbidden to roll in a handkerchief; therefore here where it is permitted to roll chumashim, which is upgrading, it is also permitted for sale as it appears to me.",
    "7:_": "Seif 7 — unless they hung it on the individual's opinion; and if there is a city member see Beit Yisrael and responsa Penei Moshe part 1 siman 32.",
    "13:_": "There — and if he gave. There.",
    "14:_": "There — and if she did. Temurah 30.",
    "15:_": "Seif 15 — he cannot forbid it; if there is another beit haknesset in that city he can forbid it — Tashbetz part 4 in Tur part 1 siman 7."
  },
  "shaarei-teshuvah/part-001.txt": {
    "14:_": "The only one, Abhat. And refer to the discussion of the face of Yehoshua Seaman 4 in the matter of the house that was burned and they want to build in another place and leave the place vacant and treat it as holy, surely a minister. If they want to make a vegetable garden there, in their eyes, it should be zatah in the siman 10 and in the majority of the zatah segi. If they want to sell and the majority of the townspeople agree even without the zatah segi s. In the matter of HC DKK Horadn' and the guests sometimes sit there for like half a year, but for sometimes they don't. And also wrote Shil Model in the volume that the ZA are chosen and they are like the heads of Galiot and none of the people of the city interferes in their business. It is possible that Dufi' in the volumes can sell even without the people of the city. However, since there is an obstacle of the hol as a rabbinic mitzvah and it is to be trusted that he will be allowed to sell at least in the status of the people of the city per:"
  },
  "turei-zahav/part-001.txt": {
    "4:_": "A different holiness as in it — Beit Yosef ruled in Bava Batra Rishonim; as for other sanctities it is permitted to sell and buy the same; see there.",
    "5:א": "(1) From what is permitted, etc. — Muridin has not yet come to use of weightier holiness; see there.",
    "5:ב": "(2) And if they bought with this money, etc. — I did not reach the end of Rama's opinion on this; see there.",
    "7:ב": "(2) Efi built their own Oth. Debnauoho Adeta DKA and the whole world won it, and it is not known that they did, except for a few people who can sell Afi' in a volume like in the beit haknesset of Teresim and Afi' of volumes. There is no prohibition except in selling it in the matter that there will not be an AHC in the beit haknesset, but if it is a beit haknesset it is permissible Afi' from the plural to the singular as Rabbanan Dram page 25 page 27:",
    "7:ג": "(3) But they hanged him in the individual's opinion. The difficulty in the name of Mahari Habib, if this was the condition at the time of the building, why did he say that it was in the individual's opinion that it was in their opinion that it was permissible for them to sell, and he extended it with the excuses of the 19th and the 19th of the siman 19. Mahsya Adeta Didi Kathy We were what they let him do his will end of his words. In this there is a manifestation of the opinion that he had the ability to sell Heaven, Heaven seems to him to benefit from this and he has the power of Heaven, and this does not belong if many are engaged and commanded in the building business as above simply:",
    "12:_": "He cannot sell his right — Mordechai chapter HaChovel brings proof from the Gemara; it appears this is only when the congregation honored one for this matter; but if one bought this right from the congregation he acquired all rights therein; nevertheless he may not sell except to one suitable as they intended — end of his words.",
    "13:_": "And a mitzvah came to them in our Gemara in Rish 22, page 3, it is written in most books, Gebo Zozi and Mahti Mai Al Delma from the Termi Pash and love him Shregi Livni 20 May Al Dilma from the Termi Pash and Mezvani and Yahbi Leho. It means Efi' in the covenants that he collects, they are not taken out except for the Pash and thus the Rambam wrote here a mitzvah just a VS written in them first Delma Matermi From the hands of Demtzvah and he gave it to him and this was the Rambam's version in any case, meaning all from the hands of Demtzvah Efi' is easy since he did not weigh but through the loan until he pays it and the and from in the 5th and the Mash Dabekno Avni will not make a difference to the word of a difficult commandment Daha in siman 6 Dimkar ruled to provide for students, etc. B. Y. wrote in this that it is a different matter:",
    "8:_": "There — see there."
  },
  "yad-ephraim/part-001.txt": {
    "1:_": "In Magen Avraham s.k. 4 and 4 of Eliyah Rabbah — from the box; in siman 20 up to sign ED belongs to another matter; see there.",
    "3:_": "s.k. 5 — but there is a reason, etc. — meaning when they sold a beit haknesset not in the presence of the people of the city, presumably the people of the city do not want their mitzvah forgotten entirely and beit haknesset sanctity would apply to the money; therefore forbidden to change money from beit haknesset sale; but money collected plainly has no sanctity; and what is forbidden to change is because of the people of the city, etc.; see there at length.",
    "5:_": "In Magen Avraham s.k. 16 and it seems the questioner holds thus — see Magen Avraham s.k. 20 and Levush s.k. 20."
  }
};
