/** siman 452 part 1 — mishnah-berurah */
export const HAND = {
  "mishnah-berurah/1:א":
    "(1) One should be careful etc. — the reason: hagalah works by boiling water expelling what was absorbed in the vessel; but one must be concerned that after expelling the absorption it will return and absorb in the vessel what it expelled; because of this concern poskim wrote one may kasher only a vessel that is not ben yomo, for then even if it absorbs what it expelled it is noten taam lifgam, or there should be sixty in the water to nullify the expulsion of prohibition; and on this the Mechaber says that if one kasher before the fifth hour one need not be careful in all this, for then it is still the time of chametz heter and it is noten taam bar noten taam d'heter — meaning the chametz taste the vessels received initially was heter taste, and the water taste they now receive from the vessels is also heter, and what returns and gives taste in vessels is also heter.",
  "mishnah-berurah/1:ב":
    "(2) Before the fifth hour — from the beginning of the fifth hour, since it is forbidden in any case d'rabbanan, it is no longer called noten taam bar noten taam d'heter.",
  "mishnah-berurah/1:ג":
    "(3) Whose absorption is slight etc. — such as spoons and cups with bowls and pots; one must be concerned that after they finish expelling their slight absorption they will return and absorb from the expulsion of other vessels whose absorption is great; but before the fifth hour, which is entirely heter, one need not be concerned even if they absorb, for it is noten taam bar noten taam d'heter.",
  "mishnah-berurah/1:ד":
    "(4) And similarly if one leaves them etc. and does not etc. — meaning if one kasher a forbidden vessel to kasher it or a chametz vessel after the time of prohibition one must be precise not to leave them long in the water, for one must be concerned that after finishing expulsion it will return and absorb; and also not to leave them at all but remove immediately is not correct, for one must leave a little until it expels its absorption, and this is hard to measure; but if one kasher them before the time of prohibition one need not measure and may leave them longer in the water [and if one kasher them after the time of prohibition — from the fifth hour on erev Pesach until evening, or generally a forbidden vessel — one must be precise that the vessel not be ben yomo or that there be sixty in the water to nullify the absorption, for then also there is no concern if one leaves them long in the water].",
  "mishnah-berurah/1:ה":
    "(5) That the water not cease boiling etc. — meaning all the time they are boiling they are busy expelling and do not absorb from hagalah water; and when they cease boiling they absorb.",
  "mishnah-berurah/1:ו":
    "(6) However many dispute etc. — Acharonim challenged the Rama, for the Mechaber view is also that hagalah helps only when the water is boiling; rather he wrote that after the time of prohibition it is forbidden to leave the vessels after the water ceases boiling, for then they return and absorb from hagalah water; not so beforehand — one need not be concerned for this since the hagalah itself was at the time of their boiling.",
  "mishnah-berurah/1:ז":
    "(7) If the water is not boiling — meaning even if yad soledes bo, all the time the water does not raise boiling they do not expel.",
  "mishnah-berurah/1:ח":
    "(8) All the time one is kashering — meaning the large pot in which one places vessels every hour to kasher — the water should not cease boiling all the time one continues kashering in it, for a vessel one places there after the water ceased boiling — hagalah does not ascend to it [unless one leaves the vessel in it until the water boils again]. The nature of water is that it ceases boiling when one inserts cold vessels to kasher; therefore one must wait in each vessel until the water bubbles; and one must warn those who kasher, for they practice lightly and kasher quickly one after another and do not check if boiling rises; and one may learn merit for them, for the way of kashering is only bowls and spoons used by irui, for which hagalah in water at yad soledes bo alone helps; however in a copper pot and things whose use is via kli rishon it appears that even b'dieved this hagalah does not help and one must return and kasher [but regarding forbidding the food if one used it on Pesach the Peri Megadim is uncertain; and it appears if it is not ben yomo from when chametz was used in it one may lean lenient]; Acharonim wrote it is proper to place at hagalah a Torah scholar expert in hagalah laws.",
  "mishnah-berurah/1:ט":
    "(9) And that one not insert etc. — meaning if one kasher after the time of prohibition it is not proper to insert the vessel before the water boils, even if one leaves it inside until it boils, lest it absorb then from hagalah water containing vessels expulsion [and even though afterward when the water boils it will also expel this absorption — nevertheless l'chatchila one should not add chametz absorption]; not so if one kasher before the time of prohibition — one need not be concerned for this.",
  "mishnah-berurah/1:י":
    "(10) So that one need not etc. — meaning if one kasher after the time of prohibition one must kasher first the pot in which one kasher vessels, pour out the hagalah water, boil other water in it, and insert the vessels [for if one does not kasher it first, the water in the pot becomes forbidden from the pot, for there is not sixty in the water against the whole pot, and the forbidden water returns and forbids the vessels kashered in it]; and also at the end after kashering all vessels, when one wants to use the pot, one must kasher it again so it expels hagalah water absorbed in it; not so if one kasher vessels before the time of prohibition — one need not kasher the pot first, for then it is noten taam bar noten taam d'heter as above; and only if one wants to use the pot after the time of prohibition must one kasher it at the end.",
  "mishnah-berurah/1:כ":
    "(11) Until Pesach etc. — because of chol ha-moed he needed this reason, for on Yom Tov itself, even on other Yamim Tovim, it is forbidden to kasher, as below siman 509 [Taz].",
  "mishnah-berurah/1:ל":
    "(12) For then chametz is in any amount — meaning and hagalah does not help even if one wants to kasher it inside a large vessel that has sixty in its water against the vessel to nullify the expulsion; and even though the vessel is not ben yomo from when chametz was used in it, and also the large vessel is not ben yomo — nevertheless for us who hold siman 447 seif 10 to be stringent on Pesach even in noten taam lifgam — it is forbidden.",
  "mishnah-berurah/1:מ":
    "(13) After six — not specifically, for even after four one must be careful, as in s.k. 2; so wrote several Acharonim; except they wrote that what the Rama wrote that one must be careful in all matters is not specifically d'oraita until night in one of two matters as below; and some resolve that therefore he specified after six, for then it is proper to be careful in all matters mentioned in the Mechaber's words; not so if one kasher after four until six — it suffices to be careful in one of two matters: (a) see that the vessel one kasher and also the large pot in which one kasher are both not ben yomo; (b) if the vessel one kasher is ben yomo there must be sixty in the water against that whole vessel to nullify it [and if one kasher many vessels one after another there must be sixty in the water against all, for chametz prohibition in the expulsion returns and reawakens and joins together]; however if the large pot is ben yomo there is no remedy to kasher in it unless one kasher it beforehand per law, for the water in it does not have sixty against the vessel itself, as explained in Yoreh De'ah in several places. All this is d'oraita; but already the practice is l'chatchila to be stringent in all stringencies even if one kasher at the fourth hour or before [Magen Avraham and Bach]; and see in Biur Halacha where we explained in the name of several Acharonim who hold these two matters — requiring vessels not be ben yomo or sixty in water to nullify them — are d'oraita even before the time of chametz prohibition. It is permitted to kasher a forbidden knife in a kosher pot if there is sixty in the water against it and it is not nullifying prohibition, since one's intent is only to remove absorption; nevertheless one may not afterward use the water in the pot [Acharonim]; and see in Chokhmat Adam klal 47 seif 8.",
  "mishnah-berurah/2:א":
    "(14) One should be careful — and per Rama in Yoreh De'ah siman 95 seif 3 in the hagahah, even b'dieved it is forbidden.",
  "mishnah-berurah/2:ב":
    "(15) To kasher — and even before the fifth hour, since it is because of meat and milk.",
  "mishnah-berurah/2:ג":
    "(16) Together — meaning one inserts them at one time into the pot; the reason is that meat and milk expulsions mix together and are absorbed in the vessels and become forbidden.",
  "mishnah-berurah/2:ד":
    "(17) One of them etc. — ben yomo is permitted, for it receives from what is not ben yomo only impaired taste; and what is not ben yomo is also permitted, for the taste absorbed from ben yomo is noten taam bar noten taam d'heter and is not considered taste; and after hagalah one may use each for what he wants — meat or milk.",
  "mishnah-berurah/2:ה":
    "(18) Is not ben yomo — and the same even if both are ben yomo but there is sixty against one vessel, for then its expulsion is nullified and it is as if it does not exist. All this during the rest of the year and because of meat-milk prohibition, or on erev Pesach before the fifth hour; not so afterward — one must be careful in each that it not be ben yomo or that there be sixty against all, as in s.k. 13.",
  "mishnah-berurah/2:ו":
    "(19) Forbidden vessel — meaning even though one kasher it itself one must be careful that it not be ben yomo from when forbidden food was used in it, or that there be sixty in the water against it, lest it become forbidden if it again absorbs its expulsion.",
  "mishnah-berurah/2:ז":
    "(20) Any ben yomo vessel — meaning whether from meat to milk or chametz to matzah; even if one kasher it alone and before the fifth hour and there is sixty, because of a decree lest one kasher a forbidden vessel with less than sixty, for there hagalah does not help all the time it is ben yomo, for it returns and absorbs from hagalah water. And even counters one should scrub well and wait after scrubbing twenty-four hours so they not be ben yomo, and dried well from cold water lest they be cooled from boiling ones; and be careful to pour on them quickly, not by throwing in air, for that is not considered irui; and be careful to pour on them from the vessel in which one boiled the water, but not draw with another vessel from the pot and pour on them to kasher, for that is kli sheini — if one kasher without a white-hot stone — unless one leaves the vessel with which one draws inside the pot until the water raises boiling in a small pot, then it is properly kli rishon [Magen Avraham in the name of Maharil]; and see what we wrote above siman 451 in Mishna Berurah s.k. 114 in the name of Mahariw.",
  "mishnah-berurah/3:א":
    "(21) Into a vessel — meaning a perforated basket or net; in a non-perforated vessel one may not kasher even one vessel, even when it floats and does not touch the bottom, unless one leaves them in the pot until the water raises boiling in the vessel one wants to kasher.",
  "mishnah-berurah/3:ב":
    "(22) If they touch one another — for at the place of contact boiling does not reach, even though regarding tevilah there is no chatzitzah; regarding boiling it is different.",
  "mishnah-berurah/4:_":
    "(23) One should rotate the vessel — meaning one opens the tongs inside the boiling water and grasps the vessel in another place so boiling rises on the place the tongs held. It is better to kasher in a net or perforated basket.",
  "mishnah-berurah/5:א":
    "(24) One may kasher in them — or in hot-spring waters.",
  "mishnah-berurah/5:ב":
    "(25) In any liquid — for their nature is not to expel absorption.",
  "mishnah-berurah/5:ג":
    "(26) However b'dieved — because some dispute that liquids also expel like water, and we rely on them for b'dieved; and poskim wrote the same regarding water mixed with ashes called lye, or what smiths practice heating the vessel via wine lees or vinegar-stein mixed in water — one may not kasher in them l'chatchila, only in water alone; b'dieved hagalah helps in them; and see in Peri Megadim whose view is that if it is before Pesach one should kasher a second time in water alone; however if Pesach arrived it is permitted l'chatchila to use this hagalah.",
  "mishnah-berurah/5:ד":
    "(27) One may kasher no more — for they no longer have power to expel absorption; and it is possible that even b'dieved this hagalah does not help.",
  "mishnah-berurah/5:ה":
    "(28) In that water — and even if one kashered in them vessels that are not ben yomo, the law is the same.",
  "mishnah-berurah/6:א":
    "(29) A large vessel etc. — meaning one wants to kasher it and is concerned perhaps there is chametz absorption on its lip where the water does not reach; and the same law for a pot after one kashered vessels in it and wants to use it on Pesach — one must make a lip or white-hot stone; but initially before kashering the vessels and kashering the pot first from the prohibition in it — one need not make a lip.",
  "mishnah-berurah/6:ב":
    "(30) One makes a lip at its mouth — meaning around its mouth and not on it directly, for the vessel mouth must be exposed so boiling water reaches there.",
  "mishnah-berurah/6:ג":
    "(31) With clay — and during the rest of the year when one wants to kasher from prohibition one makes a lip of dough. The reason for making the lip is because it is impossible that boiling not splash once from chametz cooked in it onto the lip from above, and perhaps at hagalah time boiling water will not splash enough to expel chametz absorbed in it; therefore one makes the lip so water reaches there. All this in a vessel that cannot be inserted into a kli rishon of chametz but is used with boiling inside — therefore this remedy suffices; but a vessel used from outside, like a bowl sometimes inverted on a pot, or a vessel with which one draws from the pot — has no remedy this way, for the outer side was not kashered; therefore one must insert it entirely into the pot. A vessel whose mouth is narrow so one cannot scrub inside, or that has cracks [called rarerin] — forbidden in hagalah.",
  "mishnah-berurah/6:ד":
    "(32) Or one takes — meaning one fills it well at first.",
  "mishnah-berurah/6:ה":
    "(33) A white-hot stone — for cold cools the water.",
  "mishnah-berurah/7:_":
    "(34) Immediately — so it not return and absorb from boiling water on it that contains chametz expulsion; nevertheless b'dieved even if one did not rinse at all one need not be concerned, for one kasher only before the time of prohibition, or it is not ben yomo, or there is sixty in the water against it, as above.",
};
