/** siman 453 part 1 — mishnah-berurah */
export const HAND = {
  "mishnah-berurah/1:ג":
    "(3) But not in rice — and likewise millet; the Gemara derives from a verse that one fulfills the obligation of matzah on the first night, which is obligatory, only with something that comes to chametz; and these do not chametz, as he concludes below.",
  "mishnah-berurah/1:ו":
    "(6) And some forbid — not from essence of law but a stringency they imposed; reason of this stringency: sometimes grain is mixed in kitniyot species and impossible to separate well, and it comes to chametz when baked or cooked; also often they grind rice and other kitniyot to flour, and often bake bread from them; there are common people not expert to distinguish between this flour and grain flour, between bread and grain bread — therefore they forbade all bread and cooked dish, even to cook whole rice and kitniyot, on account of lo pelug; also lest grain seeds be found in them; see Beur Halacha.",
  "mishnah-berurah/1:ז":
    "(7) And one should not change — even on the last day of Pesach one should not lighten; nevertheless in duress when one has nothing to eat, permitted to cook all species except the five grain species; even then he should precede kitniyot to rice, millet, and ritzkale, for they resemble the five species more; plainly so too for an ill person without danger — permitted to cook for him if needed, but must check and separate well that no seeds of the five species be found; Chatam Sofer in responsum siman 122: even where there is room to permit, l'chatchila boil them, for whatever can be repaired we repair; so Chayei Adam.",
  "mishnah-berurah/1:כ":
    "(11) And they do not forbid if etc. — meaning one need not be careful to hang an oil candle far from the table lest it drip on food; even if it dripped, we do not forbid, for in such a case they did not practice stringency, as Darkei Moshe explains; he further concludes there: even if groifen from which oil is made were crushed in a mortar in which chametz is soaked — we have no concern, for even if something mixed it is nullified in sixty before Pesach; one should not say it absorbs taste from chametz mortar, for cold does not expel and absorb; however all this is in sesame oil and the like that are not sharp; but olive oil if olives were crushed in a vessel of moistening etc., certainly absorbs taste of chametz soaking, for olive is sharp as above siman 447 seif 8; in sharp items we say under duress of crushing the mortar gives taste to olives, and there is not sixty in olives against the taste — as above siman 447 seif 8; therefore in olive oil all agree one must be careful not to hang the candle near the table lest it drip on food.",
  "mishnah-berurah/2:_":
    "(14) If it has taste of grain — and it implies even if the dough does not have enough wheat that there be an olive-bulk within the time of eating a meal, one also fulfills when eating an olive-bulk from the dough, although the main part is rice; and rice alone does not fulfill matzah, as above — here is different, since joined together rice is drawn after wheat, and when wheat chametzes, rice too chametzes; therefore its law is like wheat; so in wheat and rice; but if he mixed wheat flour with millet flour etc., or mixed flour of other grain species with rice flour and made matzah from it — he does not fulfill his obligation by taste of grain unless there is grain flour such that in every meal-portion there is an olive-bulk of grain flour — then we consider the whole dough as grain and he fulfills eating an olive-bulk from the dough. Some say even in wheat and rice one fulfills matzah obligation only if there is wheat in rice for the measure of eating a meal; in other grain species, even for eating a meal, not — for we do not consider the whole dough as all grain unless majority grain and minority rice or other species, then rice is nullified in majority and it is as all grain; l'chatchila correct to be stringent like the latter view; in duress rely on the first view.",
  "mishnah-berurah/4:ד":
    "(24) Permitted to take etc. — for we rely on those poskim who hold the essence of guarding is from kneading onward; before kneading we do not require explicit guarding, and even by default we do not establish prohibition; even where they moisten wheat — usually they do not soak until it chametzes, only sprinkle water and rinse and immediately grind; although Mechaber in seif 5 forbade nowadays to moisten — here is time of duress, and perhaps these wheats were not moistened; Acharonim wrote: now that the custom is to launder wheat and soak in water, forbidden to take wheat flour from marketplace even in duress, literally like sunk grain explained siman 467 seif 2 — even b'dieved forbidden by Gemara law, worse than moistening, forbidden all Pesach days, all the more to take for matzah of mitzvah; many poskim hold even to keep them in the house forbidden because of bal yera'eh, as siman 467 seif 2 in gloss there; even if he transgressed and kept, some forbid; Agur in the name of his ancestor permits selling to a non-Jew after Pesach, for at most it is chametz doubt.",
  "mishnah-berurah/4:ה":
    "(25) Flour from the marketplace — and wheat is permitted to take even not in duress, if he will guard from grinding onward; however forbidden to take wheat from the mill-owner who measures all year for grinding wages — even b'dieved, for millers regularly launder them in water first; one should warn the multitude (Taz); Taz further wrote: where they grind wheat in millstones in which they grind malt, forbidden to take marketplace flour even in duress (even where there is no way to moisten them initially), for malt is full chametz and mixes; Acharonim wrote: in duress even this is permitted, for even if something of malt remains and mixes, certainly nullified before Pesach; flour in flour is dough in dough and does not return and awaken (and must shake them lest malt crumbs remain inside); nevertheless correct in duress to bake everything beforehand, as seif 2 in Mishna Berurah; Acharonim wrote: although by law guarding le-shem matzah is only for first nights, other days when no chametz concern — Israel are holy and practiced guarding le-shem matzah in all matzot from grinding, at least from kneading; see below siman 460 what we wrote.",
  "mishnah-berurah/5:א":
    "(26) Nowadays etc. — meaning although in Gemara times they forbade only moistening barley because they are soft [and likewise oats and rye are included in barley for this matter], and they quickly chametz and one should fear lest they come to chametz at time of moistening; but wheat, being hard by nature, does not quickly chametz and was permitted to moisten; nowadays they forbade because we are not expert in moistening, as below.",
  "mishnah-berurah/5:ג":
    "(28) Whether wheat whether barley — Mechaber's language is not precise, implying wheat and barley are equal; in truth barley, since their way is also by Gemara law forbidden to moisten; perhaps nowadays forbidden to keep in the house while moistened even if not near splitting — unlike wheat; see below siman 467 note 7 etc.; see Tur and Gemara Pesachim daf 46: rye is a type of barley for this matter — Eliyah Rabbah YD siman 324 Magen Avraham.",
  "mishnah-berurah/6:ג":
    "(31) They must untie etc. — reason: flour in the stitching does not leave through laundering, and worse: water enters partially and moistens flour there and sticks in the folds and can later mix somewhat into flour; Magen Avraham siman 451 note 36: also must scrape chametz well with a knife before laundering where there was stitching.",
  "mishnah-berurah/6:ד":
    "(32) At the corners — and likewise the reinforcement called zoyem [Acharonim]; Acharonim wrote: l'chatchila better to buy new sacks, for even if the whole sack is hard to launder well, lest a little chametz remain in weave holes; b'dieved even if he did not untie stitching at all before laundering and put flour — do not forbid the flour; Chayei Adam wrote: if found inside stitching like dough that dried — even b'dieved forbidden even before Pesach, for crumbs are not called moist and return and awaken; whether shaking flour helps here — see below siman 466 seif 4 in Mishna Berurah and Beur Halacha there.",
  "mishnah-berurah/8:א":
    "(37) To pick millstones — also to cover all vessels in linen garment or wash vessels well that no flour from chametz of the whole year remain; correct to make a new sack to shake flour for Pesach need, not store year to year the mill sack; all the more not use an old sack even by rinsing, rubbing, and hagalah, as above siman 451 seif 18 in gloss; no distinction whether he grinds for Pesach after Purim or before Purim [so several Acharonim].",
  "mishnah-berurah/8:ה":
    "(41) To go themselves — for the mitzvah is greater than sending; in any case fit to place at the mill a God-fearing man expert somewhat in laws, not a minor, lest it come to chametz concern; all the more not seat a child to guard.",
};
