/** siman 452 part 1 — machatzit-hashekel + magen-avraham */
export const HAND = {
  "machatzit-hashekel/1:_":
    "(s.k. 1) If etc. nevertheless permitted — meaning that if one kasher after the time of prohibition in such a manner hagalah does not help, for in such a case the hagalah water becomes forbidden from the expulsion of the vessels kashered in it; and after the vessel finishes its expulsion they return and absorb from the hagalah water; and even though the water did not cease boiling one may not rely on this, as written below; nevertheless before the time of prohibition there is no concern because it is noten taam etc. of things cooked in a chametz vessel and not etc. as should be.",
  "machatzit-hashekel/2:_":
    "(s.k. 2) Whose absorption etc. and one must be concerned they will absorb etc. — meaning that all the time the vessel expels it does not absorb; but a vessel whose absorption is slight one must be concerned that after finishing its slight expulsion it will absorb from another vessel that is still expelling. And see s.k. 6.",
  "machatzit-hashekel/3:א":
    "(s.k. 3) However etc. — for Rabbeinu Yehuda also agrees to this even before the time of prohibition hagalah does not help in water at yad soledes bo unless it raises boiling.",
  "machatzit-hashekel/3:ב":
    "Forbidden to boil them a second time — meaning if one kashered the vessels when the water was boiling, nevertheless one should be careful that the water not cease boiling all the time the vessel is in it, for after the water ceases boiling the vessel again absorbs from the hagalah water, even though the vessel is not ben yomo and there is also sixty in the water; nevertheless l'chatchila where possible one may not rely on this. And as written in s.k. 6; and even if one's intent is to boil them again — then again they will expel what the hagalah water absorbed — one may not rely on this where there is no need. Also one must be concerned not to be precise as required regarding boiling again, since he knows they already boiled once and will not consider that they again absorbed hagalah water.",
  "machatzit-hashekel/3:ג":
    "And so too Rashal in responsum siman 26.",
  "machatzit-hashekel/4:_":
    "(s.k. 4) That he not insert — so that it not absorb from the hagalah water, for hagalah water is kli sheini and absorbs; and since they are not yet boiling they do not act to expel to kasher; and this is an excessive stringency, for afterward when they boil, just as the vessels expel their own absorption they also expel the hagalah water they absorbed.",
  "machatzit-hashekel/5:_":
    "(s.k. 5) First etc. — meaning when one wants to use the pot on Pesach; but because of the vessels one kasher in it, the pot needs no hagalah at all.",
  "machatzit-hashekel/6:א":
    "(s.k. 6) One must etc. that the vessels not be ben yomo — then even if there is not sixty in the water it is permitted, for they will not again absorb from the hagalah water, for the vessels are not ben yomo and noten taam lifgam; and even after four when chametz is already forbidden, nevertheless noten taam lifgam is permitted until night as above siman 447, and it is like noten taam bar noten taam d'heter.",
  "machatzit-hashekel/6:ב":
    "Sixty against it — then even if the vessels are ben yomo it is permitted, for the expulsion is nullified in the water; and even though we do not nullify prohibition l'chatchila, nevertheless here since one's intent is not to nullify but rather to remove the prohibition — it is permitted. And for this reason if the vessel is not ben yomo, even if there is not sixty it is permitted; and even though noten taam lifgam is forbidden l'chatchila. But if the vessel is ben yomo and also there is not sixty, even b'dieved hagalah does not help, for the hagalah water becomes forbidden and the vessels again absorb after their expulsion from the hagalah water; and even if one is careful that the water not cease boiling — then they do not absorb — and also one removes them immediately after they expel; and all the time they expel they do not absorb; nevertheless one may not rely on this, for perhaps one removes them immediately after finishing expulsion — and certainly one may not rely, for there is no fixed time but according to estimation, as Beit Yosef wrote in the name of Rashba; and also regarding that the water not cease boiling one may not rely, lest it ceased somewhat without his knowledge — so in Chokhmat Shlomo. For the prohibition returns and reawakens — for at first vessel A's expulsion taste was nullified when there was sixty against it and the taste of expulsion was not sensed in the water; nevertheless when one kasher vessel B, vessel B's expulsion joins with vessel A's expulsion and again the taste of expulsion is sensed in the water and the water becomes forbidden; for also in food if an olive of milk fell into sixty olives of heter and was nullified, and again another olive of milk fell into the sixty-one first olives — it too is nullified, and we do not say the first milk returns and reawakens — for we do not hold thus; nevertheless in vessels in our case one may rely on them.",
  "machatzit-hashekel/6:ג":
    "And Shach in Yoreh De'ah disagrees etc. and holds that vessel and food have one law — see there siman 121.",
  "machatzit-hashekel/6:ד":
    "And it appears to me that if vessel etc. as written Yoreh De'ah siman 98: a pot in which there is noten taam of sixty olives of heter and two olives fell into it, one of blood and one of milk — each joins with the noten taam olives of heter to nullify its fellow. And so noten taam of sixty olives of heter into which fell an olive of milk (per those who say regarding other prohibitions we do not say chanan), and in another pot there were thirty of heter and an olive of blood fell and they mixed b'shogeg — permitted since they are distinct tastes; and the same here.",
  "machatzit-hashekel/6:ה":
    "And in Chokhmat Shlomo he wrote it is not comparable to there, and these are his words: there it speaks of two prohibitions nullifying one another because each is a prohibition in itself; not so here where both their prohibitions are because of chametz taste absorbed in them — if so the name of chametz prohibition is on both of them, and how will they nullify one another? And it appears one should not be lenient in this — end of his words. However Magen Avraham's view is that it does not depend on their being two forbidden types but on their tastes being distinct; and so the Rosh brought in Shach there s.k. 33: it is logical that any prohibition is nullified when it cannot give taste in heter, and blood taste and milk taste are not equal — behold the milk taste is nullified in sixty and blood taste in sixty; what difference to me prohibition nullifying prohibition or heter nullifying prohibition — only that the taste of prohibition be nullified and it no longer have power to give taste in heter — end of his words. And even though here between a meat vessel and fish vessel the hagalah is because of chametz taste absorbed in them — nevertheless also the taste of prohibition is equal, for both are chametz taste. It must be that Magen Avraham's view is that chametz taste absorbed in meat changed its taste through the meat, and so chametz taste in fish changed through the fish — if so the two chametz tastes are not equal and they nullify one another.",
  "machatzit-hashekel/6:ו":
    "And one should kasher first — and this is only a stringency l'chatchila; for what of it that vessels of slight absorption after finishing expulsion will absorb from another vessel — we do not rely on the water boiling as above; nevertheless the vessels are not ben yomo or there is sixty in the water and also the absorbed matter expels as a vessel of great absorption expels; and nevertheless they are stringent l'chatchila. And so what is written: and one should not leave too long — they are concerned that after finishing expulsion it will again absorb from hagalah water; and this too is only a stringency l'chatchila; for what of it — for from this reason it requires sixty in the water or the vessel not be ben yomo; but whatever is possible to do so we need not rely on noten taam lifgam or on there being sixty — we do, for we do not nullify prohibition l'chatchila; and even though here one does not intend to nullify, nevertheless Taz wrote Yoreh De'ah siman 137 s.k. 4 that where possible in another matter, even though one does not intend to nullify prohibition — nevertheless it is forbidden.",
  "machatzit-hashekel/6:ז":
    "And one kasher the pot first and last — hagalah first because the pot absorbed chametz and there is not in what is in the vessel sixty against the vessel as explained in Shulchan Aruch Yoreh De'ah — if so the water in which one kasher vessels becomes forbidden from absorption of the pot; and so too when the vessels finish expelling they absorb from hagalah water forbidden because of the pot. And also at the end after finishing hagalah one must kasher the pot if one wants to use it on Pesach, for again the pot absorbed from hagalah water; and from this I did not understand what Taz wrote s.k. 5: and for this reason it appears also that one who comes to kasher a forbidden knife in a pot on the fire that is large and has sixty up to the knife may take a kosher pot for this and it is not nullifying prohibition l'chatchila — end of his words — for regarding the vessel one kasher we say this reasoning that it is not nullifying because one's intent is not to nullify; but regarding the vessel in which one kasher — we do not say so, for even though one kashered the pot first one must kasher it also at the end; even though through the first hagalah the pot is kosher, nevertheless one must kasher at the end — specifically regarding the vessel one kasher, since it is impossible otherwise; not so vessels one kasher in it — here it is possible to kasher again; and the same in a pot; and it is forced — Taz deals with an earthenware pot that has no remedy in hagalah — what of it — nevertheless it is called l'chatchila; who forced him to kasher in an earthenware vessel? However his intent is per the custom that one does not kasher ben yomo vessels — if so necessarily the forbidden knife is not ben yomo; and if so in such a pot if one kashered first one need not kasher at end since the vessels are not ben yomo, as Magen Avraham wrote. However per this view also sixty was not needed in the pot against the knife — and why did Taz require sixty in the pot if he goes per the custom that nevertheless they are stringent in all stringencies as Magen Avraham wrote — also in this it was not placed for my humble opinion. Kaf HaChayyim wrote in the name of Terumat HaDeshen and Agur: when one inserts the vessel into the pot to kasher it, even though the water is above boiling, nevertheless through this insertion the water ceases boiling; therefore one must be careful not to kasher quickly until one sees the water boiling again; and see there what he wrote to resolve the custom. However in any case one must leave them at least the measure of expulsion according to estimation.",
  "machatzit-hashekel/6:ח":
    "On siman 447 etc. — not as one who asked for those who hold it returns and reawakens on Pesach; if so of what use is hagalah if there is sixty in the water? Nevertheless on Pesach it returns and reawakens and then it is in any amount; and per Magen Avraham's reason in general taste — all agree it does not return and reawaken — end of his words.",
  "machatzit-hashekel/7:א":
    "(s.k. 7) One must be careful etc. — see Yoreh De'ah, meaning there the Mechaber wrote: a meat bowl rinsed in a pot of milk etc. even though both are ben yomo — permitted, for it is noten taam bar noten taam d'heter; and Shach challenged from Rabbeinu Yehuda's words here. Therefore he wrote there for b'dieved and here he wrote one must be careful l'chatchila.",
  "machatzit-hashekel/7:ב":
    "And this is that l'chatchila one is concerned for Rama's view there who wrote that in such a case taste of two substances is forbidden — the bowl received meat taste and the heter expels taste into the water, and the pot received milk heter taste and expels taste into the water; if so in the water there are two tastes of meat and milk mixed and the second taste is forbidden and they return and are absorbed in the vessel; if so here b'dieved depends on the dispute of Rabbeinu Yehuda and Rama there.",
  "magen-avraham/1:א":
    "If the vessels ben yomo — that even though the vessel is ben yomo and there is not sixty in the water against it, nevertheless it is permitted because it is noten taam bar noten taam d'heter, which is not so after the fifth hour. It is difficult — for above in siman 447 seif 5 the Rama forbids things cooked and did not permit from noten taam bar noten taam; and why does he permit here l'chatchila? One may say that here since there are many taste transfers from food to vessel and from vessel to water and from water to vessel — it is permitted.",
  "magen-avraham/1:ב":
    "Whose absorption is slight — such as spoons and cups; one must be concerned they will absorb from what bowls and pots expel.",
  "magen-avraham/1:ג":
    "However many dispute etc. — the words of the Rama are puzzling, for Rabbeinu Yehuda also agrees to this except that after its prohibition, once the water ceases boiling it is forbidden to boil them a second time, for all the time they are boiling they did not absorb from hagalah water; and if they ceased boiling they absorbed; but before the time of prohibition it is permitted, for it is noten taam bar noten taam d'heter; and so in Peri Megadim; and so Rashal in responsum.",
  "magen-avraham/1:ד":
    "And similarly if one leaves them too long — one must be concerned that after finishing expulsion it will again absorb from hagalah water.",
  "magen-avraham/1:ה":
    "And similarly so that one need not be careful — that the water not cease boiling.",
  "magen-avraham/1:ו":
    "One must be careful in all etc. — meaning one should see that the vessels not be ben yomo; and if they are ben yomo there must be sixty in the water against it; and if one kasher many vessels one after another there must be sixty against all, for the prohibition returns and reawakens (Beit Yosef and Darkei Moshe in the name of Rashba siman 462); and in Orach U'Mussar Shaarei Nitzchon wrote that b'dieved it is permitted, for some say also in food it does not return and reawaken, and if so in vessels one may be lenient; and so the Acharonim and Shach Yoreh De'ah siman 99 disagrees with them — see there. And it appears to me that if one vessel absorbed meat and the other fish it does not return and reawaken since they are distinct tastes, as written Yoreh De'ah siman 98. And one should kasher first vessels of slight absorption and afterward of great absorption; and one should not leave them too long; and the water should not cease boiling; and one should kasher the pot first and last. It appears to me that if the pot is not ben yomo one need not kasher it first, for it is no worse than the vessels themselves; and if one kashered it at the beginning one need not kasher at the end, for the vessels are not ben yomo; nevertheless the practice is to be stringent in all stringencies even before the fifth hour — so too Bach. And requires study why the Rama specified after six, for even after four one must be careful as stated, for even though the prohibition is d'rabbanan, nevertheless noten taam bar noten taam does not apply — see siman 447 seif 3 that regarding something containing only chametz taste we do not say it returns and reawakens — not as one who asked.",
  "magen-avraham/1:ז":
    "And last — when one kashered at the beginning or end.",
  "magen-avraham/2:א":
    "Together — meaning one inserts them at once into the pot and there is not sixty in the pot against any one of them.",
  "magen-avraham/2:ב":
    "Unless one of them — or there is sixty against it; all this during the rest of the year or on erev Pesach before the fifth hour; not so afterward — one must be careful in each that it not be ben yomo or sixty, as explained.",
  "magen-avraham/2:ג":
    "Any ben yomo vessel — even alone and before the fifth hour, and even if there is sixty, because of a decree regarding a forbidden vessel that hagalah does not help all the time it is ben yomo, for it returns and absorbs from hagalah water and noten taam bar noten taam does not apply. And even counters one should scrub well and wait after scrubbing twenty-four hours so they not be ben yomo, and dried from cold water lest they be cooled from boiling ones; and be careful to pour on them quickly, not by throwing in air, for that is not considered irui (see Yoreh De'ah siman 92); and be careful to pour from the vessel in which one boiled the water and not draw with another vessel from the pot and pour on them to kasher, for that is kli sheini (and Avnei Nezer Yoreh De'ah 92 elaborated on this); however if one leaves the vessel with which one draws inside the pot until the water raises boiling in a small pot — then it is properly kli rishon (all this in Maharil); and Mateh Moshe wrote to kasher three days before Pesach; and all this depends on custom. Written in Shaarei Chaim siman 470: a Torah scholar expert in hagalah should kasher.",
  "magen-avraham/6:א":
    "One makes a lip — because it is impossible that boiling not splash on it once, and perhaps at the time of hagalah it will not splash on it; therefore one makes a lip; and even though the water drips through the clay — we hold as it absorbs in sparks so it expels in sparks (Gemara); and Maharil wrote: if it is a vessel with which one draws boiling water it has no remedy in this manner, for the outer side was not kashered; therefore one must insert it entirely into the pot. A vessel whose mouth is narrow so one cannot scrub inside, or that has cracks — forbidden in hagalah — end of his words. And it appears to me the same regarding bowls with which one covers the griddle — the outer side also needs hagalah.",
  "magen-avraham/6:ב":
    "Or one takes — meaning one fills it well at first.",
};
