/** siman 451 part 3 — eshel-avraham, kaf-hachayyim */
export const HAND = {
  "eshel-avraham/1:ב":
    "Without kashering. A vessel that requires libun — if one kashered it and used it boiling, the dish is forbidden (Rashba and Orchot Chayim); cold is permitted even l'chatchila; see Yoreh De'ah siman 91.",
  "eshel-avraham/3:_":
    "And they are permitted: see in Eshel Avraham note 10 — because regarding a knife where there are still sides to be lenient we rely even though one holds chametz is called permitted absorption; and one may say regarding spits b'seder Chayei Adam; and there are those who practice placing a white-hot stone on a knife and pouring boiling water on it — and it is a complete prohibition according to the Acharonim.",
  "eshel-avraham/4:א":
    "Straw burns. Since chametz is on it, it is called prohibited absorption and hagalah does not suffice. And Taz challenged from the implication of Shulchan Aruch 447 seif 7 and 452 that it is called permitted absorption; see there. And furthermore what he wrote from a pan in seif 11 — it should read that here it deals where they roasted chametz b'eyna in it, which is like an oven in which they baked. And Chayei Adam struck with an axe that one cannot decide in this matter — for sometimes they ruled it as permitted absorption and sometimes etc.; see there.",
  "eshel-avraham/4:ב":
    "Libun is required. And he challenged Yoreh De'ah siman 18 — behold we frequently use a trivet for meat and milk vessels. And one may answer: the concern is perhaps porridge spilled from the pot onto it b'eyna; from now on all year there is no concern — behold it is only peel-thickness and the pot remains in place; see there.",
  "eshel-avraham/5:א":
    "In kli sheini. And Bach is stringent with them; see Peri Chadash.",
  "eshel-avraham/5:ב":
    "Libun. And there are sages who ruled: when they coated it anew with tin one need not kasher it; and R' Shlomo challenged them with three challenges; and Peri Chadash elaborated for his sake and concluded in practice one may not rely on them — for sometimes due to speed the coating does not rise on the entire vessel; and he wrote that such is the practice in Jerusalem. And so Chayei Adam — the great ones of the land are stringent on themselves; and he wrote they should immerse after coating without a blessing.",
  "eshel-avraham/6:_":
    "Chayei Adam wrote: specifically for general kashering of vessels — not so chametz, for one may retain them — it is not called b'dieved; and it requires study.",
  "eshel-avraham/8:_":
    "In hagalah — Mahari Weil wrote that a copper vessel does not absorb via pouring and does not require hagalah; and Shach Yoreh De'ah siman 98 rejected his words; see there.",
  "eshel-avraham/10:א":
    "Hagalah. And that meat is permitted in siman 447 seif 5 — because it was nullified in sixty — this is not in a vessel; see Yoreh De'ah siman 105.",
  "eshel-avraham/13:_":
    "Coals. See Baer Heitev note 434 what he wrote in the name of Maharam Chalavah Chayei Adam siman 43. And see in Maggid MaReishit siman 1 who wrote they did not agree with him all the sages of his generation; and so Maharal agreed in Eretz Yisrael that hagalah is required; and in Mahari Metrani. See Peri Chadash and Kenesset HaGedolah.",
  "eshel-avraham/16:א":
    "In hagalah. And in siman 446 seif 7 regarding unripe grapes — it is different, for it is nullified one in a hundred; and here on Pesach its prohibition is in any amount.",
  "eshel-avraham/16:ב":
    "Copper waste. Bach warns regarding those made from copper waste — one should not whiten with filling coals, lest they are alive on them and crack.",
  "eshel-avraham/16:ג":
    "To whiten. And in Peri Chadash he wondered whence this — behold the implication is truly the law applies only to a mortar and bowls whose use is only in kli sheini; see there.",
  "eshel-avraham/19:_":
    "The bellows. See Baer Heitev; and see responsum of Chayei Adam siman 58.",
  "eshel-avraham/22:_":
    "And the charoset house — see Yoreh De'ah siman 69 that in any event chametz was not used in it. And even if we say since its vinegar is sharp it absorbs even when cold — nevertheless one may say not to use them hot. One may rely and permit without rinsing first — go and learn from now: certainly if chametz hot was used in it, rinsing is required to use cold matzah in it. And yayin nesech vessels require rinsing because they are very sharp. If so, due to the stringency of yayin nesech — see responsum Bach Beit Moed siman 18.",
  "eshel-avraham/27:א":
    "That was not checked. L'chatchila libun is required; and b'dieved we rely on one view that it suffices — for the taste does not return and revive, it is already nullified; and even though in a vessel we do not nullify a prohibition — which is not so — for it is merely a safek.",
  "kaf-hachayyim/1:_":
    "(1) [Seif 1] Pottery pots, etc. — not specifically pots; likewise bowls whose use is via pouring and kli sheini vessels — the law is the same. Chayei Adam note 1, Kaf HaChayyim note 1 — meaning: even though their use is not through fire like pots, one must also scrub and hide them.",
  "kaf-hachayyim/3:_":
    "(3) There — that they were used with chametz, etc. But new vessels bought from the market — even pottery vessels — one need not be concerned lest perhaps they were used, for there is no general way to use new vessels. But metal vessels bought from a gentile in his home, and one does not know them — that they are certainly new — require concern to kasher or whiten them according to their use. Orach Chayyim general rule 58 siman 46. Chayei Adam note 2, Kaf HaChayyim note 2 — and after hagalah or libun one must immerse them, even though they are old, as written in Yoreh De'ah siman 121 seif 1; see there. And furthermore see there siman 122 seif 11. Nevertheless with clear glass vessels one may permit buying from a gentile from his home even if the gentile does not speak offhand and takes the vessel from among the vessels — for since they are clear, certainly they were not yet used. R' Zalman note 5.",
  "kaf-hachayyim/4:_":
    "(4) There — that they were used with chametz, etc. And he wrote in responsum Chakham Tzvi siman 75 a practical halachic ruling to permit a dish cooked on Pesach in a clean chametz pot over which twelve months passed — even for us who forbid nitelaf (as written above siman 447 seif 10) — nevertheless after twelve months there is no taste at all; and nevertheless his heart was not filled to permit cooking in it l'chatchila; and the Gaon R' Naftali Katz z\"l agreed with him there in siman 76; see there. And Beit Din above siman 447 note 10 — also we wrote there the reasoning of Shibolei Leket who permits after two months; see there. However in responsum Panim Me'irot part 1 siman 24 he disagreed; see there. And so Radbaz siman 739 — they did not permit retaining twelve months except regarding wine alone, not other prohibitions; see there. Eshel Avraham note 6 — and so in responsum Chaim Sha'al part 2 siman 38 — he wrote the words of Rashba in responsum siman 575 are not like Chakham Tzvi who wrote there that aging helps only for wine vessels; and he wrote an incident came to his hand in Israel that he was sent a gift of nice porcelain vessels and it was not discernible whether the gentile sender had already used them and two years passed — and they are expensive vessels; and he wrote that at first glance one should not permit l'chatchila as Chakham Tzvi himself wrote; and also from Rashba's words it appears even b'dieved it is forbidden; but here where there is a safek-safek perhaps they were not used — and if we say they were used, safek to be lenient — and still requires answer; until here. And it appears to me that if it is possible to kasher them in boiling water three times one should do so; and if they are vessels there is no way to use boiling — yad soledes bo — one may also be lenient. Shaarei Teshuvah note 1; and see Yoreh De'ah siman 113 seif 16 and siman 121 seif 1 and siman 122 seif 11 — these laws; examine.",
  "kaf-hachayyim/6:_":
    "(6) There — even those in which they make porridge, etc. — meaning then they absorbed much chametz; and if one cooks in them after Pesach there will not be sixty — nevertheless it is permitted; and the reason: we are lenient like Rashi who holds chametz after Pesach is not forbidden except due to a mere penalty, and he is penalized only when the chametz exists b'eyna; but what was absorbed in the vessel he is not penalized — therefore it is permitted even l'chatchila to cook in them. Orach Chayyim note 1, Magen Avraham note 1.",
  "kaf-hachayyim/7:_":
    "(7) There — scrub them well, etc. And if one did not scrub — if one scrubs during Pesach or after Pesach, it is not as if he nullified, as explained above siman 435; see there. Chayei Adam note 4, Kaf HaChayyim note 4, R' Zalman note 3 — and that one scrubs during Pesach — this is outside Israel; but on Shabbat and Yom Tov it is forbidden to touch chametz even to destroy it, as written in siman 446; see there. R' Zalman there.",
  "kaf-hachayyim/9:_":
    "(9) There — and it is permitted to retain them, etc. — Pesachim 30a — there is a dispute: Rav said break them and it is forbidden to retain them after Pesach and to use them even not in its kind — a decree lest in its kind; and Shmuel said give them after their time and use them whether in its kind or not in its kind; see there. And the poskim ruled like Shmuel; and even though we are lenient — the halachah is like Rav in prohibitions — this case is different because Shmuel relies on Rashi. Beit Yosef. Bach. Eshel Avraham note 1.",
  "kaf-hachayyim/10:_":
    "(10) There — and one hides them on Pesach, etc. And recently they began placing tin chametz vessels in the winter-house for a gentile, and they say there is no concern lest he use them since they are at height; and likewise Pesach vessels they stand at height all year — this is a complete error; and one must guard them in a place where there is no usual habit lest they err to use them on Pesach. Bach. Shach Kenesset HaGedolah in Hagahot Tur note 1; see there note 1 — and possibly they practiced thus because they are not ben yomo; and even if the master uses them, the majority permit, as written siman 447 seif 10; and all the more so in those whose majority use is in kli sheini or cold, such as flasks — there is no concern; and one who is stringent — a blessing upon him. Magen Avraham note 2. However Chayei Adam note 7 and Eshel Avraham note 1 — to permit simply; see there. But Peri Chadash wrote it is good to be concerned for Bach's reasoning; and so Birkei Yosef note 2; and so Chok Yosef note 2 like Magen Avraham — one who is stringent, a blessing upon him. And so Mekor Chayyim note 5, R' Zalman note 4.",
  "kaf-hachayyim/11:_":
    "(11) However yayin nesech vessels — taste for detriment does not help in them, as Magen Avraham wrote siman 447 note 25; if so, one should forbid; and likewise a gentile's vessel that he has as collateral in a place where they are accustomed to cook in them with vinegar and the like — one should beware, for taste for detriment does not help in them, as explained. Eshel Avraham note 2; and see above siman 442 note 65.",
  "kaf-hachayyim/12:_":
    "(12) And where there is no custom — in any event one may permit in kli sheini; and even in pottery vessels whose use is in kli sheini or via pouring — there is room to permit if one places them in a place where no human hand controls. Responsum at the end of the method of Maharash siman 13; see there b'seder. Mechaber note 1.",
  "kaf-hachayyim/15:_":
    "(15) There — but heating, etc. — hagalah does not help for pottery vessels because the Torah testified regarding pottery vessels that they never leave their mouths. Gemara there. And that heating helps if we are not concerned for them or one returns them to the kiln — as explained below — Tosafot wrote there: this is not considered leaving their mouths, for since they were fired it becomes like a new vessel, for such is the way of pottery vessels when making them — one puts them in a kiln to fire them; see there.",
  "kaf-hachayyim/17:_":
    "(17) There — except that one pours boiling water into them. This is Tur's language; and Beit Yosef explained: even if one did not use pottery vessels boiling, only in kli sheini — heating does not help for them; and he wrote so too Rambam chapter 5 equates pottery vessels used with chametz in kli sheini to using them in kli rishon — until here. However Rabbeinu Moshe z\"l in Darkei Moshe note 1 wrote it does not appear to him Beit Yosef's explanation — rather according to Tur kli sheini has a remedy because it does not absorb; but in the name of Hagahot Maimoniyot he wrote that even if one did not use a pottery vessel except in kli sheini — heating does not help for them; see there; and to this Rabbeinu Moshe z\"l wrote in the gloss on Shulchan Aruch's words that it is Tur's language; and one says: even in kli sheini — meaning that although this language of Tur implies specifically if used via pouring from kli rishon it has no remedy — but if used in kli sheini it has a remedy; one says: even in kli sheini it has no remedy through heating. And so Chayei Adam note 8, Eshel Avraham note 3; and regarding the law see below note 37.",
  "kaf-hachayyim/19:_":
    "(19) There in the gloss — and there are those who forbid even in kli sheini. It is proven from here that one holds that even in kli sheini it absorbs something; and so is proven below seif 5; see there note 1 — meaning from what is written below seif 5: and if their use is in kli sheini — kasher them in kli sheini; and if it does not absorb at all — why does it need kashering; rather one must say that in any event it absorbs something — therefore kashering is required.",
  "kaf-hachayyim/20:_":
    "(20) There in the gloss — and there are those who forbid even in kli sheini. And so is Shulchan Aruch's view as written above, or Taz. And so Peri Chadash; and Chayei Adam note 8; and what Magen Avraham note 3 wrote — Shulchan Aruch omitted the law of kli sheini — he retracted from what Beit Yosef wrote; Chok Yaakov challenged him there; and so Eshel Avraham in Hagahot Beit Yosef wrote on Magen Avraham's words mentioned — it requires study; and so HaNe'ehav note 2 wrote to challenge all Magen Avraham's words mentioned; see there. And that which is written in Yoreh De'ah siman 105 seif 2 — heat of kli sheini b'dieved is permitted — and here one holds heating does not help for it — Eshel Avraham wrote there: perhaps regarding chametz he wanted to be stringent; see there. And regarding the law Chok Yaakov wrote there: in a place of great loss and prevention of Yom Tov joy one may be lenient b'dieved if used in kli sheini if it is not ben yomo — even in pottery vessels; see there. And so Eshel Avraham there. Mekor Chayyim note 6, R' Zalman note 33. Chayei Adam general rule 125 note 3 — meaning such as a spoon made for eating in it whose majority use is in kli sheini — they stick it in a bowl after they poured boiling inside from kli rishon; if they did not kasher and stick on Pesach in kli rishon b'dieved it is permitted if it was not ben yomo and there is great loss and prevention of Yom Tov joy. R' Zalman there. And it is simple this deals if it was clean — for if not, chametz on Pesach forbids in any amount, as is known.",
  "kaf-hachayyim/22:_":
    "(22) There — lest one be concerned for them, etc. Bach wrote: an oven and stove of pottery whose prohibition comes through heating — even internal heating does not help for them — and so we rule; see there. And so is Peri Chadash's view in seif 2. However Magen Avraham note 4 and Chayei Adam note 9 and Eshel Avraham note 5 challenged him; and they wrote heating from inside helps — for since such is their way we are not concerned lest they crack; see there. And so Beit Meir siman 461; and so Chok Yosef note 4 agreed — not like Bach. And so R' Zalman note 8, Chayei Adam general rule 125 note 2; and see below note 32 and siman 461.",
  "kaf-hachayyim/23:_":
    "(23) There — however if one returns them to the kiln, etc. I was asked: pottery vessels that remained after burning — meaning if it is permitted to use them on Pesach, for it is known this is more than returning to the kiln — and I permitted; and nevertheless everything according to the matter. Avnei Nezer note 10.",
  "kaf-hachayyim/24:_":
    "(24) There — if one returns them to the kiln, etc. And in Orach Chayyim general rule 58 siman 49 he brought the dispute on this; and wrote therefore we practice not to fire them at all, even in a potter's kiln; see there. And they brought Eshel Avraham note 3; and so Peri Chadash brought the view of those who forbid even to return them to the kiln; and he wrote regarding the law one should be stringent; see there. But Rabbenu Tam in Sefer HaYashar siman 214 wrote they have a remedy through returning to the kiln; and so Mahari Weil Netiv 5 part 2; and in She'eltot of Rav Achai parashat Matot; and so is Tosafot's view (Pesachim 30b); and so Rokeach siman 484; and so R' Menachem chapter 5; see there. And Beit Din Chokat HaPesach note 3; see there. And so R' Zalman note 9; and therefore since there is a dispute — each follows his stream and its plain meaning.",
  "kaf-hachayyim/26:א":
    "(26) There — but for our ovens, no. And see in responsum Be'erot HaMayim part 4 siman 6 who wrote our ovens that are large are permitted; see there. However in derashot of Maharil page 6a he wrote in our ovens it does not help, even the large one of a baker; see there. And so it appears from the stam words of the poskim — one should not distinguish between oven and oven; and in any event even in a kiln some are stringent, as written in the previous note — if so, do not add on it.",
  "kaf-hachayyim/27:_":
    "(27) There in the gloss — forbidden to use it even cold, etc. — meaning in a fixed manner, lest one come to use it hot; and if so, even if they rinsed first it is forbidden; but in an occasional manner it is permitted to use it via rinsing — and not like Orchot Chayim; and a fixed manner — even orally after its prohibition time — it is forbidden to use it. Chayei Adam note 11. Eshel Avraham note 4. Mekor Chayyim note 8. R' Zalman note 2. However with old pottery vessels the custom is not to use them even cold and even in an occasional manner, as written below end seif 22; see there.",
};
