/** siman 451 part 3 — yad-ephraim remainder */
export const HAND = {
  "yad-ephraim/5:_":
    "In Taz note 8 — meaning Mordechai not so regarding spits, etc. — it appears he meant that Mordechai there deals with a pan in which they bake pashitida — the pashitida is not meat or milk b'eyna, but there is also meat or milk inside; and since it is not absorbed from b'eyna literally through fire — properly this reason of permitted absorption suffices with this libun alone; but if what was absorbed is from b'eyna literally through fire — such as an oven in which they baked without liquid, or a spit on which they roasted chametz b'eyna — this reason of permitted absorption alone does not help to permit through hagalah; and by law complete libun is required; and it is close that there is a printing error and Taz's words need emendation; and it should read: except regarding vessels in which they bake things absorbed from permitted, etc.; and nevertheless his words require study — for behold Mordechai's proof is from Avodah Zarah who distinguishes between permitted absorption — and there it deals with spits and skewers on which kodshim meat was roasted b'eyna and became notar — and even so he says one kashered them because permitted was absorbed.",
  "yad-ephraim/6:_":
    "In Magen Avraham note 13 — such as bowls, Beit Yosef, etc. — this is Rabbenu Tam, Beit Yosef — meaning Beit Yosef brought in the name of Rif and Rosh regarding their use in kli sheini, such as bowls, etc.; and what Magen Avraham wrote \"and not bowls literally,\" etc. — meaning Shulchan Aruch here that wrote their use in kli sheini does not mean bowls literally as is the explanation in Rif and Rambam's words; rather here he means bowls are called kli sheini — and if one inserts a spoon, etc.",
  "yad-ephraim/7:_":
    "There note 37 — but if one inserts the side that was not kashered it is forbidden, etc. — his words are wondrous in my humble opinion — for he wrote: and if the spoon was inserted, etc. — this is from the words of Hagahot Orach Chayyim at the end of the siman; and there it is explained not like his words — for behold he wrote one must kasher the spoon l'chatchila another time and insert it entirely into the pot — is it that other times one kashered and it is not like deception — for the food is permitted and the spoon requires hagalah immediately, since it was cooked in a pot that is not ben yomo — until here; and if according to Magen Avraham's words — why need a reason due to deception other times; and also what concern of deception applies here — for behold one must kasher it again and insert it entirely into the pot so as not to come to insert the other side that was not kashered and come to prohibition; rather certainly this is what he said: there is no distinction in the matter; and even inserting in the side that was not kashered is kosher, since that side was not inserted in prohibition — as Hagahot Orach Chayyim wrote there: the reason is because as it absorbs so it discharges.",
};
