export const t = {
  "1:_": `(1) [Seif 1] Window plug, etc. And even on a skylight on the roof permitted — for adding to a temporary tent is permitted. Tosafos. Magen Avraham section 1. Tosafos Shabbos letter 1. Orach Chayyim letter 1. Razah letter 1. And Levush wrote that it is not specifically a window plug from the side that is permitted — rather even a skylight on the roof is permitted because it adds to a temporary tent. So there in Tosafos:`,
  "2:_": `(2) There. Window plug, etc. A house where someone died there — forbidden to close the window facing another house so that kohanim may enter — for it is fixing; and to tell a non-Jew to close it is a dispute among the rabbis. R' Yehuda HaLevi siman 34; Knesset HaGedolah in Hagahot HaTur. However Magen Avraham section 1 disagreed with him and wrote that it is permitted to close even after the deceased died and it is not fixing — see there. And Eliyah Rabbah in section 1 rejected Magen Avraham's words; and likewise some say in Hagahot HaTur that the essence is like R' Yehuda HaLevi — see Tosafos Shabbos. But Tosafos Shabbos siman 15 wrote that the law is with Magen Avraham. And likewise in responsa Beit Yehudah part 2 siman 29 he challenged R' Yehuda HaLevi and permitted plainly like Magen Avraham; and he brought from several later authorities who hold thus; and he also wrote there that hinges and iron locks on a door and window are considered attached — unlike Taz; and he wrote that so agreed Pnei Me'orot part 2 siman 92 and Divrei Shalom siman 223; and he expanded greatly and concluded that it is permitted for a kohen to close the opening even after death and even on Shabbat; and he should watch his doors that they be locked — none goes out and none enters until the deceased is removed — see end of his words. And Birkei Yosef and Sha'arei Teshuvah brought it:`,
  "3:_": `(3) There. Such as a board, etc. Even if it is something that has no beam of a utensil at all and also never plugged with it on a weekday. Razah letter 1:`,
  "4:_": `(4) There. Even if it is not tied. But if it is tied — even if he did not think on it at all — permitted. Bach. See there Orach Chayyim letter 1 Eliyah Rabbah letter 1; and likewise if he plugged with it once from before the day — even if he did not intend on it to plug with it on Shabbat — the status of a utensil descended upon it through this plugging, since it is something whose manner is to designate for this. Razah there:`,
  "5:_": `(5) There. And we do not say that it is like adding, etc. Since its manner is thus to open and close frequently. Tosafos Shabbos letter 2; and likewise Eliyah Rabbah there; but if fixed for distant times — forbidden as adding to a permanent building as Magen Avraham wrote section 7 Orach Chayyim letter 1 Razah letter 1; and perforce if it is fixed for distant times it must be tied there from before the day:`,
  "6:_": `(6) There. And that he intend on it, etc. To exclude from prohibition of handling. And with intent it suffices even if he thought to close with it on a weekday like shards siman 308 seif 20 Tosafos Shabbos letter 3 Levush:`,
  "7:_": `(7) There. And that he intend on it, etc. And the reason is due to muktzeh; and according to this if it was a utensil — a board on which one sets a table whose melacha is forbidden — nevertheless for bodily need permitted and one does not need any intent. Maggid Mishneh siman 15:`,
  "8:_": `(8) There. And that he intend on it, etc. And that which we require his intent from erev Shabbat — namely specifically regarding something whose manner is to nullify there; but something whose manner is not to nullify forever but only temporarily — such as a garment and similar — permitted to close with it even if his intent was not on it from erev Shabbat. Chayei Adam general 39 letter 8:`,
  "9:_": `(9) There. To close with it. Not precise — rather the same applies if he prepared it for some matter — intent suffices. Maggid Mishneh siman 15:`,
  "10:_": `(10) There. And a rod that they fixed to lock with it — also one does not need to tie it to the door — so it should read, Levush:`,
};
