export const t = {
  "1:_": `(a) [Seif 1] Animal may go out etc. — person commanded d'oraisa on animal's rest "that your ox and donkey rest" — ox donkey and all animal beast bird; question: guarded is ornament custom not burden; unguarded is burden — Beit Yosef Rashi; see note 1.`,
  "2:_": `(b) There. If not guarded in it — not guarded by placing this but guarded otherwise — note 2.`,
  "3:_": `(c) Extra guarding etc. — excluding medium guarding slightly less permitted can't minimize — Beit Yosef; Taz s.k. 1; note 3; Aruch Hashulchan note 2; Tosafot note 2.`,
  "4:_": `(d) Ornament etc. — not its custom; usual weekday ornament permitted Beit Yosef Rashi Ran; Bach like Tosafot all ornament forbidden; Magen Avraham s.k. 1.`,
  "5:_": `(e) Therefore cow etc. — na'akah female camel Aruch; donkey luba donkey from Libya Rashi; Tosafot Libya Egypt.`,
  "6:_": `(f) Horse resen etc. — girsa; Tur; donkey forbidden resen promvia seif 3 Bach; Magen Avraham s.k. 2; camel apsar mule donkey apsar — resen promvia not; seif 3 horse resen or apsar; Eshel Avraham note 2; Bach camel promvia not required Magen Avraham; Taz s.k. 2 camel forbidden promvia; Tosafot note 3 Pri Megadim note 1 challenged Avnei Nezer; Shulchan Aruch camel only apsar promvia forbidden.`,
  "7:_": `(g) Not both — if occupation bad both permitted per circumstance Beit Yosef Mordechai; see seif 4.`,
  "8:_": `(h) Move apsar etc. — no tiltul prohibition ready for animal Tur.`,
  "9:_": `(i) Provided not lean — lest use animal Beit Yosef.`,
  "10:_": `(j) [Seif 2] Not guarded — slips from mouth unlike tied apsar Beit Yosef Taz s.k. 3.`,
  "11:_": `(k) [Seif 3] Donkey promvia — explained seif 1 only luba permitted Taz s.k. 4.`,
  "12:_": `(l) [Seif 4] Bad occupation etc. — Rashba Ran Chiddushei Aggadot horse mule nowadays custom weekday promvia Shabbat not burden all — Pri Megadim note 4; see note 7.`,
  "13:_": `(m) Needs etc. — even blocked cow no guarding needed; end seif 17 rebellious rope permitted Gemara Acharonim.`,
  "14:_": `(n) [Seif 5] Chain owners dogs etc. — horse may go out chain mishnah Rambam ch. 8 law 8.`,
  "15:_": `(o) Small animals etc. — custom thus weekday; if not custom like caged cat forbidden small rope enough extra burden Rambam.`,
  "16:_": `(p) [Seif 6] Tying teats etc. — though not for guarding escape — for body health wool permitted like garment not burden Levush.`,
  "17:_": `(q) Specifically tying etc. — even pouch on teats if tightens Gemara.`,
  "18:_": `(r) [Seif 7] Donkey mard'at — cold distress Gemara donkey cold Tammuz Taz s.k. 5.`,
  "19:_": `(s) Gloss small saddle etc. — Perishah note 11 like garment warm; Levush large saddle whole body; mine small saddle whole body not thick like riding saddle; see note 22.`,
  "20:_": `(t) Tied erev Shabbat — untied didn't show need garment Rashi; Rosh Yerushalmi tying uses animal — if transgressed or gentile permitted; Perishah note 12 Tur forbids Rosh too; Avnei Nezer note 6; Shulchan Aruch Yerushalmi seif 8 stringency; Rambam Rif Tosafot note 7; Mishnat Hasidim note 5; not Levush.`,
  "21:_": `(u) Other animals forbidden — no cold distress mard'at burden Tosafot note 8.`,
  "22:_": `(v) Saddle etc. — saddle doesn't help burden Tosafot note 9 only mard'at warms body; Levush.`,
  "23:_": `(w) [Seif 8] Place mard'at etc. — walk courtyard not public domain — donkey only if tied erev Shabbat Beit Yosef.`,
};
