export const t = {
  "1:_": `Song. See Ba'er Hetev regarding bells; see in Sha'arei Efrayim gates of Yoreh De'ah seif 3`,
  "2:_": `In Shulchan Aruch seif 3, clock pair that jingles. And Peri Megadim part 2 siman 122 wrote that in his view it is permitted to pull the chain in a clock on Shabbat, for it is better than a layered cup, see there; see in She'elat Ya'avetz siman 41 that it is forbidden by custom and so we practice; and so in Peri Megadim one should not permit except through a gentile, and for a sick person if impossible through a gentile there is room to permit through an Israelite, see there. And it appears that in such a case he should be zealous to wind and pull the silver cord until the motion that makes sound through rotation of the wheels does not stop — for in this, since the sound-making is from yesterday and he does not innovate in sound-making, only pulling the chain is indirect causation that it not stop and not be nullified, and this is lighter as is explained in this siman; and also it does not apply here that he completes melacha and repairs a utensil. But after the chain wrapped on the wheel returns and the motion stopped, and through his returning to pull and set it goes and jingles again — it appears it should be forbidden on account that it is like completing a utensil and repairing a utensil, as is written in responsa Mayim Rabim; and all the more so in a place where one must make a movement in the iron rod that oscillates constantly while it goes, called in foreign tongue "emrou," etc. I saw in responsa Har HaCarmel who also wrote it is permitted to set it while it is going, see there that there is some hesitation in his words; and his view is to permit on the second day of Yom Tov, and one who permits on the first day should not set it on Yom Tov for another; and he wrote not to rely on him for practice; and it appears that even one who is lenient for himself on the second day of Yom Tov should not set it except for the need of that day, not for the need of the day after, whether on a weekday or Shabbat; and for practice it appears to permit for need of a sick person while it is going even through an Israelite if difficult to find a gentile, and if he does it through a gentile there is room to permit in every case; and so is common practice; see above end of siman 308`,
  "2:_": `Strike. And there are places where they take another utensil to strike on Shabbat`,
  "3:_": `To repair. See Magen Avraham`,
  "4:_": `Regarding clapping. Explanation: since we are not expert in making musical instruments, by law it would be permitted to play with musical instruments, therefore in any case speech to a gentile is permitted, and in any case forbidden to tell a gentile to repair the musical instrument, as was stated. Magen Avraham`,
  "5:_": `And throw. For Rosh Hashana to drive away birds — Rashi. And it is possible that in our time, when there is no Rosh Hashana, it is permitted to pat, for it is a decree for a decree. Magen Avraham`,
  "6:_": `Fairly and unfairly. Meaning "even" or "odd" in German`,
  "7:_": `To cover them. And Rashal ruled that it is forbidden to cover them`,
  "8:_": `To move it. And specifically when he placed it in a place where it is repulsive to him, as is written siman 308 seifim 136–137. Magen Avraham`,
};
