export const t = {
  "1:_": `(a) [Seif 1] One who dwells in a gatehouse — a gatehouse is when the houses are one inside the other and the inner one has no way to exit to the courtyard or public domain except through the outer house. Chayei Adam, general rule, letter alef. And even though it has four partitions — since people pass through there it is not a dwelling. Magen Avraham, seif kaf-alef. Turei Zahav, letter alef. And even though it is also roofed. Avnei Nezer, letter alef. Chayei Adam, letter alef, part 1.`,
  "2:_": `(b) There. One who dwells in a gatehouse — and there is no distinction between a public gatehouse or an individual's, and even a house's gatehouse — such is Maran's view in the Beit Yosef, and he wrote that so we rule. But Tosafos' view is to distinguish: specifically one who dwells in a courtyard's gatehouse does not restrict, for it is not fit for dwelling, but one who dwells in a house's gatehouse restricts. Beit David, Beit Yosef — see there. And so the Bach. And they brought it in Knesset HaGedolah, letter alef — see there, letter alef, Avnei Nezer, letter alef. And so Chayei Adam there, letter bet — an individual's gatehouse, meaning when no one dwells inside except one homeowner, is not so significant and restricts — see there. And perforce one should be stringent and give a share in the eruv but not place the eruv inside it. And see above siman 366, letter 27, and below letter 26.`,
  "3:_": `(c) There. One who dwells in a gatehouse — and even though he also eats there this Shabbos, it is not called a dwelling. Beit Yosef. Turei Zahav, letter alef.`,
  "4:_": `(d) There. And balcony — explained below siman 375.`,
  "5:_": `(e) There. He does not restrict, etc. — if he did not give a share with them in the eruv.`,
  "6:_": `(f) There. That are not considered a dwelling — and the same applies to a sukkah on Sukkot. Yoma daf 10. Magen Avraham, seif kaf-bet. And even though it has four complete walls and a roof. Chayei Adam there. And the same applies to one who dwells in a house that does not have four by four handbreadths — it does not restrict, for a dwelling house is required. Avnei Nezer, letter bet. And see above siman 366, seif 3, and in our words there letters 29 and 30.`,
  "7:_": `(g) There. But one who dwells in a straw house, etc. — and it is made of tree branches and reeds, meaning it is not a permanent house, and nevertheless it is called a house for all matters — Beit Yosef in the name of Rabbenu Yehonatan. And this is if he regularly eats bread there; but if he does not regularly eat bread there, dwelling there does not restrict, as below seif 5. And similarly if the homeowner has a hold in that place, as below seif 2, dwelling there does not restrict, as explained in the Beit Yosef.`,
  "8:_": `(h) There. Restricts — restricts until he gives a share in the eruv with the courtyard residents.`,
};
