export const t = {
  "1:_": `(1) [Seif 1] They do all needs of milah, etc. And that which they did not decree in milah lest one carry the infant or the scalpel through reshut ha-rabbim like shofar and lulav — because it is stringent, for thirteen covenants were cut regarding it; and also a person circumcises only if he is expert, for there is danger in the matter — Tosafos Megillah daf 4b:`,
  "2:_": `(2) There. They do all needs of milah, etc. Milah overrides Shabbat and negaim — even though they are interdependent, for the infant is afflicted and his milah is on Shabbat. Rabbeinu in Knesset HaGedolah in printed responsa Orach Chayim part 2 siman 66 — see there. Berach Yitzchak letter 1:`,
  "3:_": `(3) There. They circumcise, etc. In the gemara we derive from what is written "and on the eighth day" — the extra verse is to teach: if it comes to teach "on the day" specifically — they circumcise and not at night — behold from eight days old it emerges; rather to tell you: on the day, and even on Shabbat. See there letter 1:`,
  "4:_": `(4) There. They circumcise, etc. And if the father denies the Torah of Moses — nevertheless his son's milah overrides Shabbat. Responsum Zakan Aharon siman 29. And see in Yoreh De'ah siman 266 seifim 12 and 13:`,
  "5:_": `(5) Mamzer — they circumcise him on Shabbat. In that passage there. And Shach brought there s.k. 17. And he wrote that so is in Maharil. And so Kesef Sheni on this siman letter 1. And regarding Karaites — Shach wrote there in name of responsum Rabbeinu Betzalel Ashkenazi siman 3 that Karaites nowadays who do not acknowledge priyah — forbidden to circumcise their children on Shabbat — see there; and so Petaḥ HaDevarim on this siman letter 1 in name of several poskim; and he wrote: and even though in our time our eyes see they do priyah and also bless at the time of milah — perhaps because they are subordinate to us that they have no mohel from the Karaites; but among themselves they do not do priyah and do not bless — see there:`,
  "6:_": `(6) There. And perform priyah. This is priyah of the skin covering the head of the gid below the foreskin. See there letter 1. And see in Yoreh De'ah siman 264 seif 3:`,
  "7:_": `(7) There. And perform priyah. For priyah is part of milah. Rabbenu Zalman letter 1:`,
  "8:_": `(8) There. And perform metzitzah. Explanation: he sucks the blood from the place of connection; and even though through metzitzah the blood is detached from its place and it becomes making a connection — nevertheless permitted on account of danger — Rashi in mishnah there and in gemara; and see in Yoreh De'ah there mentioned seif: a mohel on Shabbat who had pimples in his mouth and could not do metzitzah — his friend came and they did metzitzah — he did well; and the mohel who knew he could not suck and circumcised — needs atonement. Admat Kodesh Orach Chayim siman 6. Zekhor LeAvraham part 3 letter 130. And see below letter 12:`,
  "9:_": `(9) There. And perform metzitzah. See in responsum Binyan Tzion siman 23 and 24 that he wrote metzitzah is specifically with the mouth and not through something else as the new doctors introduced; and in responsum Yad Eliezer siman 10 he permits sucking with a sponge, for it is better than metzitzah with the mouth, and even on Shabbat there is reason to permit — see there; and according to what doctors say now — on the contrary through metzitzah he may be endangered — we have only the words of Chazal; and even so it appears to me he should not suck very forcefully on Shabbat. Also he should rinse his mouth after metzitzah on the wound with vinegar he takes in his mouth — Tiferet Yisrael on mishnayot. Adam's sin was through sending the hand, for with hands he took and with mouth he ate — also in this mitzvah with hands they circumcise and with mouth they suck to repair this sin. Chasdei LaAv part 2 Nehar 51, Petaḥ Einayim letter 2:`,
  "10:_": `(10) There. And they place upon it cumin and aspalin (it is like a thick ointment called in Arabic marham — Rambam in commentary on mishnah) or bandage or powder of spices stopping blood — Yoreh De'ah there. And the reason that if they do not apply them the infant will come to danger — Levush. And if he did not have ground cumin from erev Shabbat — see below seif 7. And regarding powder they pour after milah for healing — it appears there is no concern to scatter several times; or better to apply once. Orach Chayim letter 1 in name of one of the great halachic authorities. And regarding earth they place in the foreskin — one must prepare it from erev Shabbat as written in Yoreh De'ah siman 265 seif 10 — see there; and if he did not prepare from erev Shabbat — one throws it in a place where there is loose earth, or takes from earth if he has prepared money from erev Shabbat for another matter as written above siman 308 seif 38 and below siman 498 — see there:`,
};
