export const t = {
  "1:_": `(1) [Seif 1] There is no building and demolishing in utensils. And this is what is not complete building; but complete building and demolishing also applies in utensils. Tosafos Shabbos letter 1; therefore specifically when its fragments were glued with pitch he can break it — for this is not complete demolishing. Levush:`,
  "2:_": `(2) There gloss. That does not hold forty se'ah. And even though one who permits when glued — even a large one; and one who permits a small one — even a whole one (as Beit Yosef wrote) — if so Shulchan Aruch's view is to permit even a large one; nevertheless he noted a gloss to be stringent that we require two reasons for its benefit — Likutei Peri Chadash. And likewise Olat Shabbat letter 2 wrote; except he wrote since it is a d'rabbanan matter — certainly one should not be stringent so much — see there:`,
  "3:_": `(3) There gloss, that does not hold forty se'ah — if it holds forty se'ah it is a tent and has building and demolishing. Levush. Magen Avraham section 1. And he means if it holds forty se'ah — even if its fragments were glued with pitch — forbidden to break it due to demolishing. And all this is according to our master's view who is stringent like both explanations as written in the previous letter:`,
  "4:_": `(4) There gloss. That does not hold forty se'ah. That is one amah by one amah in height of three amot including the walls without the thickness of the decorative bands (it is like a wreath surrounding it at its rim — Levush) and legs. Magen Avraham section 2. Eliyah Rabbah letter 1. Tosafos Shabbos letter 2. And in responsa Me'il Tzedakah siman 27 he wrote regarding spots on a baby's crib — the legs combine for the measure of forty se'ah since the legs are the main part of the crib for rocking; thereby the crib with the baby — see there; and the same applies regarding Shabbat. Machatzit HaShekel. And see Yoreh De'ah siman 200 letter 1 regarding the measure of forty se'ah — see there. And even though it is not made in this form — meaning one amah by one amah in height of three — whatever holds forty se'ah is a tent; and it appears nevertheless we require that its roof be a tefach — otherwise even if long and short it is not a tent. Mishnat Zekenim letter 9:`,
  "5:_": `(5) There. Such as a barrel that broke, etc. R' Korban Netanel (on Rosh chapter 22 of Shabbos letter 5) wondered at Beit Yosef who did not bring Rif and Rambam's view to permit even l'chatchila without glued fragments — and agreed to permit thus — see there. And likewise Rashba and Ran chapter Chavit; and likewise Ritva in his commentary Eruvin daf 35 — see there. And likewise Rashbatz in his commentary Rosh Hashana that if the shofar is inside a barrel he breaks it like the law of dried figs. And likewise Rashbash siman 165 — see there. And likewise Radbaz in Rambam's language siman 130 permitted to break a box to remove from it what is needed for Shabbat when the key was lost — see there. Eliyah Rabbah letter 1. And likewise Eliyah Rabbah siman 307 end of letter 31 — see there. And it appears that although it is difficult according to Shulchan Aruch's ruling that specifically in a barrel that broke, etc. it is permitted — but whole forbidden — nevertheless it is possible in a time of pressure when he suffers that he has nothing to eat — one may rely on the lenient authorities — provided it does not hold forty se'ah as written above letter 2 — see there; and also if it is a matter where he does not make it a utensil through this breaking — for otherwise it would be makeh b'patish and liable for everyone:`,
  "6:_": `(6) There. And its fragments were glued with pitch, etc. — due to its inferior quality they are not concerned for it and there is no concern lest he intend to make a utensil. Tosafos and Rosh. Magen Avraham section 3:`,
  "7:_": `(7) There. He can break it, etc. — whether by hand or with a utensil. Razah letter 1. And see in Levush who wrote he should break that adhesion; but Mishnat Zekenim letter 1 wrote even if he breaks where the earthenware is whole — also permitted — see there:`,
  "8:_": `(8) There. Provided he does not intend to pierce it a proper hole, etc. — and likewise he should not intend to beautify the break so it has a mouth and still be a utensil. Rashi Beitza 33b s.v. vehatnan:`,
  "9:_": `(9) There. Provided he does not intend to pierce, etc. Rambam wrote chapter 10 law 16: One who makes any hole at all — whether in wood, metal, building, or utensils — is a tolada of makeh b'patish and liable — provided it is made for inserting and removing. And Magen Avraham brought it there. One who makes a hole in the ground of a house so water drains out is liable due to building. Rashdam siman 5. Magen Avraham there. Razah letter 2. And even through a non-Jew forbidden. Chasam Sofer letter 6. And likewise proven from what is written above siman 313 — see there:`,
  "10:_": `(10) There. It would be fixing a utensil. In chapter Chavit (Shabbos daf 146) we say: Any opening not made for inserting and removing is not an opening; and it is the rabbis who decreed due to a chicken coop — that one makes it for letting in air and letting out heat — meaning the foul odor so the chickens do not die. From this it appears this fixing a utensil is not forbidden from the Torah except for a chicken coop. Taz section 1. And likewise Rambam beginning of chapter 23 and Magen Avraham brought it there. And likewise Tosafos Shabbos letter 3. And that which we say he is not liable for piercing unless it is made for inserting and removing — this is in something detached not attached to the ground; but in something attached to the ground liability due to building applies even if not made for inserting and removing. Razah there. And likewise Orach Mishor letter 3:`,
  "11:_": `(11) There. Even in a matter where he does not make a utensil. Meaning if he would pierce for an opening — but he breaks it; and afterward he wrote a further novelty "and even any hole," etc. — meaning he does not intend for an opening — there are two reasons for its benefit that he does not break at all and also it is not an opening; nevertheless forbidden — for we are concerned lest he intend to make an opening; but when fragments were glued with pitch we are not concerned for this due to the reason Magen Avraham wrote section 3. Levush. And see above letter 6 — Magen Avraham's reason:`,
  "12:_": `(12) One who drives a peg into a wall to hang utensils on it and similar — liable due to building; and even if he did not drive the peg but only drilled a hole in the wall to drive a peg into it — liable due to building on this hole since this hole is useful for building — namely for driving the peg. Razah letter 2. And this is from the Gemara Shabbos 103a and Rashi there:`,
};
