export const t = {
  "1:_": `Shulchan Aruch seif 1 na'akah is female camel.`,
  "2:_": `There around neck — Rashi Ran even wrap tight can't insert hand between apsar neck still permitted ornament; Tosafot all ornament forbidden; here loose for guarding can hold rope flee — explains Magen Avraham s.k. 1.`,
  "3:_": `There move apsar — ready for animal not muktzeh.`,
  "4:_": `There not lean — when placing on head careful not lean on head — uses animal.`,
  "5:_": `Taz s.k. 2 luvdekim and camel is donkey luba — guarded in apsar still may promvia not extra guarding — custom thus not burden Tosafot 51a.`,
  "6:_": `Shulchan Aruch seif 7 must be tied — Tosafot Rosh 53 several reasons; if animal use seif 8 should permit if transgressed tied.`,
  "7:_": `There saddle — saddle doesn't help burden — only mard'at on body warms; saddle warms only where placed not garment burden; inside means large saddle whole body.`,
  "8:_": `Seif 5 permitted place — no Shabbat trouble since donkey cold distress; only mard'at permitted saddle forbidden end seif — saddle warms little unnecessary trouble.`,
  "9:_": `Taz s.k. 6 saddle to warm — horse better than donkey even pressing permitted since horse not cold like donkey; saddle warmth enough trouble; mard'at on horse too; Tur saddle teaches horse permitted though donkey forbidden.`,
  "10:_": `There when tying — Yerushalmi reason forbid tying; question without tying possible use.`,
  "11:_": `There all the more not place — Gemara now take teaches placing.`,
  "12:_": `There permitted place saddle — small no animal use; horse too; mard'at without tying some use only donkey; Tur only saddle not Bach mard'at — needs study.`,
  "13:_": `Shulchan Aruch seif 6 on neck — only animal pleasure unnecessary trouble.`,
  "14:_": `Taz s.k. 8 fear lean — Gemara compares traskal mard'at — Tur animal use explains traskal too.`,
  "15:_": `There manger tied cow — tied to manger cow so girsa.`,
  "16:_": `Shulchan Aruch seif 11 fox tail — no need burden; sandal lest fall carry.`,
  "17:_": `Magen Avraham s.k. 15 possible meaning so girsa.`,
  "18:_": `s.k. 16 leading to market sell — Tosafot 54 burden not batel apsar lest fall woven garment Tosafot.`,
  "19:_": `There cats — no market still burden.`,
  "20:_": `There all ornament — separate matter tied apsar Tosafot; my view all ornament burden though weekday custom Magen Avraham s.k. 1 note 3.`,
  "21:_": `There Gemara 53 Tosafot etc. so girsa.`,
  "22:_": `There on animal permitted — human shevut permitted animal; no animal rest karmelit; if not woven concern human carry; market human shevut suspect sell.`,
  "23:_": `Shulchan Aruch seif 12 seal — Rashi 58 reason appears going market like zog.`,
};
