export const t = {
  "1:_": `Shulchan Aruch seif 1 movable on Shabbat. Know from here until siman 312 four muktzeh parts explained. Part one: muktzeh because of loss — particular not to damage. Part two: not vessel, not human/animal food — stones, reeds, coins, wood, beams, dust, sand, corpse, animals, drying figs/raisins — not fit, muktzeh because of itself. Part three: forbidden-work vessel seif 3. Part four: permitted-work vessel with muktzeh on it; even removed Shabbat, twilight designated all day (and two more: twilight attached/lacking preparation; muktzeh because of mitzvah — sukkah wood/decorations explained in Yom Tov and Sukkah laws). Bach explained these simanim — examiner understands each law and which muktzeh part; each has leniencies unlike muktzeh because of loss. Mechaber "all vessels movable" — even forbidden-work for bodily/place except muktzeh because of loss — since particular fixes place:`,
  "2:_": `Magen Avraham s.k. 2 as seif 3. Meaning all depends on person's mind; gold pestle seif 3 — if not particular, not muktzeh because of loss; same spice/metal pestles if not particular — permitted:`,
  "3:_": `S.k. 7 with feet in walking manner. Magen Avraham explained siman 333 s.k. 3: muktzeh grain — foot-path — indirect for permitted need (eating); siman 311 indirect for permitted permitted; forbidden only for muktzeh itself:`,
  "4:_": `There siman 310 seif 11. Magen Avraham s.k. 9: body-moving not in hands — for Ran like other indirect; other poskim hold better than indirect — foot-path even for muktzeh:`,
  "5:_": `Magen Avraham s.k. 11 as Tosafot ch. 5 Yom Tov: Rav Sheshet permitted sending tefillin Yom Tov since no prohibition placing; Shabbos 60 Tosafot Rav Sheshet admits forbidden placing Shabbat except he holds forbidden-work vessel permitted sending Yom Tov:`,
  "6:_": `There: Mishnah "shall not go out with tefillin Shabbat" — perhaps for "Shabbat is tefillin time" or not; implies house permitted even "not time" — contradicts Tosafot Menachot. Magen Avraham answered: Tosafot intent only for "time" view — house permitted lest forget and go to public domain since obligated to touch — remembers; "not time" — we rule Shabbat not tefillin time — house forbidden rabbinic decree (Mishnah states going-out prohibition; house also forbidden carrying concern — see): forbidden-work vessel — so appears to me continuing Magen Avraham:`,
  "7:_": `S.k. 12 Gemara there: trumpets taught like R' Yehuda, movable like R' Shimon — for R' Shimon trumpets unlike shofar, permitted bodily/place per Tosafot:`,
  "8:_": `Shulchan Aruch seif 5 via loaf. Though we rule loaf/child only for corpse siman 311 — only similar to corpse, muktzeh because of itself; forbidden-work vessels permitted via loaf/child:`,
  "9:_": `Seif 6 move fragments. Fragments part two muktzeh — like pebbles when broken except vessel name remains while fit for something such as covering; pebbles though fit to cover not vessels as next seif:`,
  "10:_": `Taz s.k. 5 through parent — twilight vessel existed not muktzeh:`,
  "11:_": `There kindle with vessels Yom Tov — fit to move and put in fire; fragments muktzeh forbidden:`,
  "12:_": `There dispute: Taz holds R' Yehuda nolad forbidden, first tanna R' Shimon nolad permitted; Taz challenged and answered first tanna also nolad forbidden except fit for some work; fragments for kindling all nolad forbidden:`,
  "13:_": `There gloss lest harm. Prior public harm — no shevut seif 8:`,
  "14:_": `Magen Avraham s.k. 6 original work. Magen Avraham like Taz note 13 first tanna is R' Shimon; "some say" nolad forbidden require original work else nolad as made Shabbat:`,
  "15:_": `Taz s.k. 5 woman not enter wood storage. Explained siman 367 seif 3:`,
  "16:_": `There Rava like R' Yehuda. Taz: first tanna could also forbid fragment kindling; challenged Tur siman 301; Taz preferred explain R' Yehuda only not first tanna — requires study:`,
  "17:_": `Magen Avraham s.k. 6 forbidden to move. See Magen Avraham siman 301 s.k. 12:`,
  "18:_": `S.k. 7 pottery forbidden. Harm not common:`,
  "19:_": `There see seif 46. Prohibition only if repairing to vessel; if breaking not for vessel — siman 318 Magen Avraham:`,
  "20:_": `There however siman 337 seif 2 should be so:`,
  "21:_": `Taz s.k. 6 in question — appears Tosafot like Taz note 13:`,
  "22:_": `There with vessels that broke. Fragments fit for work — move for that work not original, not nolad; here piece broke from vessel still original use, piece new use — nolad:`,
  "23:_": `There follows Tosafot: first tanna permits only courtyard common vessels, move shard to cover — not nolad; here public domain, shard to wipe shoes — vessel status not lost, still nolad forbidden. Difficult: Taz first held first tanna is R' Shimon permitting nolad note 21 — public domain should permit; now retracted? Tosafot also forbid public domain nolad; Taz now against Rosh who omitted Tosafot; "Tur follows Tosafot" — against Rosh:`,
  "24:_": `There for permitted as below. For seif 4 not for need forbidden; no proof from Tur; requires study:`,
  "25:_": `Magen Avraham s.k. 17 Bach like Taz s.k. 6 Tosafot public domain nolad; Magen Avraham holds first tanna R' Shimon — public domain permitted; Tur not settled in this answer; Tosafot correct as stated; necessarily "weekday" for thrown to ash heap ending:`,
  "26:_": `Taz s.k. 5 then nolad. Unlike broken erev Shabbat prepared other work:`,
  "27:_": `Magen Avraham s.k. 19 even vessels fit for other use forbidden — not prepared for that:`,
  "28:_": `There wondered on Tosafot s.k. 8: vessel doors prepared through parent moving; house doors not — Magen Avraham answered opening/closing like moving, prepared through parent moving; Tosafot Shabbos erred; Chaim Mad Moshe erred:`,
  "29:_": `There now not muktzeh. Door detached still vessel; twilight muktzeh for moving forbidden after detach; siman 310 seif 3 twilight designated; Magen Avraham s.k. 1 imagine broken loss muktzeh if no longer particular other use — not muktzeh:`,
  "30:_": `Magen Avraham s.k. 21 lest drive in. Drive firmly — building even in vessel, unlike Rashi striking final blow; Rambam disputes Rashi; Taz s.k. 9 not settled since vessels attached to ground — building/demolition not settled; Bach:`,
  "31:_": `Shulchan Aruch seif 10 pit cover. Not attached — placed to cover; removing no building/demolition; ground covers appear building unlike handle — evident for weighing/returning not building; vessel covers first vessels then clay attached (if attached from start forbidden Taz s.k. 9) — no building appearance:`,
  "32:_": `There or used them. Prepared to cover erev or repaired or used; buried barrels — whole barrel underground invisible — law like ground cover:`,
  "33:_": `Magen Avraham s.k. 23 taught: forbidden to move them — do not think only take from pit/building forbidden but moving permitted when took without placing Shabbat or prepared erev — teaches forbidden in moving too; reason not prepared for moving like house doors Magen Avraham s.k. 19; even not on pit Shabbat only prepared erev — forbidden muktzeh; Mechaber "not taken" — moving forbidden; ends "unless handle" — permitted moving with/without handle if prepared (Mechaber "prepared" covers pit/cistern covers with handle need prepare cover); "repaired" — without repair forbidden muktzeh; first clause without handle — moving forbidden muktzeh even not placed Shabbat. Settled Magen Avraham; others' difficulties answered; understand well:`,
  "34:_": `Shulchan Aruch seif 11 whole needle. Needle for sewing — forbidden-work vessel; permitted bodily — remove thorn:`,
  "35:_": `Magen Avraham s.k. 24 on fragments. Fragments: if fit some work permitted though not vessel for impurity without designation; needle point removed/pierced — ch. 3 Kelim designated for stretching (weavers put broken needle in garment edge to stretch); Tosafot: where thought helps impurity without repair — Shabbat permitted without designation; needle needs repair for impurity — Shabbat without designation; Zevachim wet hide thought helps impurity, forbidden Shabbat without designation though customary throw; Tosafot Shabbos 123 requires repair; Mordechai ch. 29; Rabbenu Yerucham ch. 13; Rambam no proof:`,
  "36:_": `S.k. 65 sometimes changes mind. For impurity not finished if may not pierce; for Shabbat vessel since sometimes won't pierce, wants unpierced for thorn — thought helps impurity therefore vessel Shabbat without designation — customary; requires study:`,
  "37:_": `Taz s.k. 13 place need. Place of last is shoe:`,
  "38:_": `There set specifically. If not set, trouble removing shoe — shoe itself not vessel:`,
  "39:_": `Shulchan Aruch seif 15 lest fall from foot. Karmelit permitted lest lost:`,
  "40:_": `Magen Avraham s.k. 28 see seif 11. Answer Tosafot fragments customary throw; shoe customary throw:`,
  "41:_": `Shulchan Aruch seif 16 may remove even must move cane — indirect permitted siman 311 seif 8; Tosafot Shabbos; difficult seif 14 forbidden if not last — full moving; Eliyah Rabbah: can remove without moving cane:`,
  "42:_": `There not for that. Muktzeh because of itself forbidden even place:`,
  "43:_": `There forbidden-work — permitted place like shoe seif 14:`,
  "44:_": `Magen Avraham s.k. 38 see seif 2. Human dignity did not nullify vessel status; like doors designated for loft ladder:`,
  "45:_": `S.k. 39 even below three. Siman 336 permitted use attached under three handbreadths — sit; use forbidden muktzeh unless tied to bucket:`,
  "46:_": `S.k. 40 therefore requires act. Our wood never for sitting:`,
  "47:_": `S.k. 41 shaking reed permitted — body-moving not moving; small stones permitted; must arrange lest touch to move for sitting:`,
  "48:_": `Shulchan Aruch seif 22 whether. Both need eternal designation; some add stones cover need act:`,
  "49:_": `There designation suffices. Siman 259 seif 1 reeds designation eternal:`,
  "50:_": `Magen Avraham s.k. 44 Rashba cited. Some in Shulchan Aruch: nut-cracking stone not subject to act yet requires eternal designation — first view disputes because nut-cracking customary; non-customary always needs designation even without act; customary dispute:`,
  "51:_": `There Mordechai implies. Third view Shulchan Aruch: subject to act:`,
  "52:_": `There all agree. Independent matter; Mordechai only on first two views: no act still eternal designation because not customary — explaining Shulchan Aruch dispute:`,
};
