export const t = {
  "1:_": `Shulchan Aruch seif 1 "that he intend on it" — namely due to prohibition of handling; and its law is like shards in siman 308 seif 20:`,
  "2:_": `There "to lock with it — also one does not need to tie it to the door" — so it should read:`,
  "3:_": `Magen Avraham section 1 — skylight on the roof — this is stricter than a window in the wall because it is a tent; and nevertheless permitted since the tent is already made and when they plug it is only adding to the tent — namely covering the hollow that was in the tent; and it is also temporary — see in Magen Avraham beginning of siman 315:`,
  "4:_": `There from the language of Rashi and Ran. At the end of tractate Shabbos on that which the Mishnah states "they plugged the window with a cloth" — they explained that they plugged before the death of the deceased:`,
  "5:_": `There that Tosafos beginning of chapter Kol HaKeilim wrote that it seemed to them that this is, etc. — so it should read; and the explanation of his words: in this law R' Eliezer holds we require tied and hanging because he holds it is forbidden to add to a temporary tent; and the rabbis hold one does not need tied and hanging, for it is permitted to add to a temporary tent; and like them Shulchan Aruch ruled; and we say there in the Gemara that the incident of "they plugged the window" does not follow R' Eliezer — for there it was not tied at all; and Tosafos challenged — perhaps actually like R' Eliezer and there it is different because it was for a mitzvah; and as stated there in that incident that they also made from it because it was for a mitzvah. And they resolved — specifically from it, which is a light prohibition, they permitted for the sake of a mitzvah; unlike adding to a tent according to R' Eliezer which is like building — one may not permit for the sake of a mitzvah; perforce like the rabbis it is permitted even in a private domain — end of his words. And this is what Magen Avraham wrote "it seemed" — namely it seemed to Tosafos that their question was thus; but their conclusion is that it follows the rabbis and a plug is permitted even in a private domain — and all the more so for a mitzvah; and from this it is proven that it is permitted even after his death, since we see that even adding to a tent according to R' Eliezer — Tosafos seemed to permit in a place of mitzvah — only they resolved that building is a more severe prohibition; automatically according to the rabbis who have no prohibition of building — permitted even though there is prohibition of fixing; at least this is not more severe than measuring and permitted in a place of mitzvah — so Tosafos Shabbos explained:`,
  "6:_": `There "a partition that permits." As explained there in Shulchan Aruch seif 1 — and it is Rabbeinu Tam's approach; but according to Rashi any partition is not called a tent and is not called a tent except a roof:`,
  "7:_": `There in Shulchan Aruch "that they fix it for this" — it appears to me and this is also due to prohibition of handling; namely since they somewhat resemble building — intent does not bring it to the status of a utensil, since it is not the status of a utensil but the status of building — therefore greater preparation is required; in a bolt that more resembles building — tying is required to exclude from prohibition of building as Rosh wrote — namely that by tying it there it was prepared for this matter to lock the door and it is not like building:`,
  "8:_": `There "to be carried" — that if he wishes to handle it through that rope it immediately breaks:`,
  "9:_": `There "rather when he removes it" — that it is not tied at all; and when he removes it from the place of locking he places it in this corner — then it does not appear as prepared for locking — it is like building:`,
  "10:_": `Taz section 1 — he should have said "tied and hanging" — so it should read "carried in his belt" — namely with a thick rope fit to be carried with:`,
};
