export const t = {
  "2:א": `Wheat that he planted. And it is not comparable to a candle that went out in siman 279, for there since it became designated at bein hashemashos it became designated for the entire day — end of Bach's words:`,
  "2:ב": `And some say there is no designation, for a gentile does not designate anything with intent [Ran], and since it is prepared for one person it is prepared for all (Kol Bo), and see siman 308 and siman 498 seif 1 and siman 517 — and the latter is not the former:`,
  "6:_": `That he not touch it. Even though muktzeh is permitted to touch, as is written in siman 308 seif 42 — that is when the touching is for the need of a permitted object; but here the touching is for the need of a muktzeh object [Beit Yosef, Terumat HaDeshen], and see siman 311 seif 7:`,
  "7:א": `A bed that has upon it. It is implied even if they were not upon it at bein hashemashos — forbidden to move it; and you find this where a gentile or a child placed coins on Shabbat with the knowledge of an Israelite [Tosafos daf 44], see siman 309 seif 4, and see siman 308 seif 27 whether it is permitted to shake off the coins, and if he forgot coins upon it see siman 309 seif 4:`,
  "7:ב": `However for the need of his body, etc. So too Beit Yosef according to the Rosh — requires further study, for behold the Rosh wrote it is comparable to weaver's combs and spindles, for since he is particular about them he designates a place for them — if so, even for the need of his body it is forbidden, as is written in siman 308 seif 1; and so in Hagahot Maimoniyot he wrote it is comparable to dried figs and raisins — see there; and so Tosafos daf 36a; and what is written in Hagahot Ashri — that is a different view; and so the Ra'avan — all agree in this: if he designated it, it is a utensil whose melacha is for prohibition, as is written in siman 308 seif 6 — forbidden except for the need of his body and its place; therefore it appears to me to be strict:`,
  "7:ג": `For the pocket is batel to it. And it is difficult — for otherwise it is permitted to wear it, for for the need of his body it is permitted as stated above; and one can say this is what it means: even on Rosh Hashana it is permitted to wear it, for the pocket is batel to it — if so, in any case it is permitted to place an object inside it and take from it, for for the need of its place it is permitted; and even according to what is written in the name of the Rosh — here it is permitted, for we see he is not particular about it:`,
  "7:ד": `Since it is not sewn, etc. — meaning the pocket is not sewn along its length to the garment but only its mouth is sewn and it entirely hangs [Beit Yosef]; it is implied that if it is sewn entirely to the garment we say the entire garment became a base; and it is difficult, for we deal with forgetting — if so, even if it rests on the main part of the garment it did not become a base; and one can say nevertheless he needed to shake off the coins, as is written in siman 309 seif 4; but since it is not placed on the main part of the garment he need not shake; but Rambam wrote in tractate Kelim regarding a drawer-board and said: since it is not removable — if so it is impossible to remove the coins unless he moves the drawer with the coins — therefore it is permitted to drag; end of his words; and since this law of a pocket is taken from that of a drawer-board — here too, if it is possible to shake off he must shake off; and know that regarding a drawer-board Tosafos wrote daf 44: even if he placed coins upon it intentionally — permitted to move the drawer since the coins are not on the main part of the utensil — if so, the same applies to a pocket sewn to a garment; and that which Rama wrote "forgot" — that is l'chatchila one should not place it inside, lest we fear he go out with it; and further it appears to me that if he placed coins inside intentionally — forbidden to put his hand in, for in any case the pocket became a base; and further we say in the gemara: when the drawer-board is removable it is an independent utensil, and one does not drag the drawer when there are coins on the drawer-board; and a drawer-board is a board on which the drawer rests [Hagahot Ashri] — if so, here too if a pocket full of coins is tied to a garment — forbidden to move the garment, since the pocket is an independent utensil; and the same when there are coins in a box inside a table — forbidden to move the table unless there is also upon it a permitted object, as is written in seif 9; and see in responsum of Maharam siman 172:`,
  "8:א": `Ash that is permitted. But ash that was kindled on Shabbat — forbidden to all, for it is a new entity that was not in the world; see siman 498 seif 15; and it appears to me that if ash kindled on Shabbat became mixed with yesterday's ash — it is batel in the majority, even though dry in dry is called wet in wet and we require sixty, as is written in siman 453 seif 3 — nevertheless here, since the essence of its prohibition is rabbinic, a majority suffices; and specifically when it was not recognizable before it became mixed, as is written in siman 308 seif 2:`,
  "8:ב": `That a permitted object is important. And even though it is important to the whole world — if it is not important to him it is not called important, as in the gemara; and the same applies in the reverse — see siman 308:`,
  "8:ג": `That it is not possible to gather. Because wood chips are small chips or small coals that it is impossible to take the ash without them [Beit Yosef] — and according to what is written in siman 309 seif 3 in the name of Tosafos, this is unnecessary:`,
  "8:ד": `He shakes. And if there is loss in shaking — he need not shake, as is written in siman 309 seif 3 [Bach]:`,
};
