export const t = {
  "1:_": `Forbidden even to move it. A rabbinic decree on account of Shabbat after Yom Tov, when it is then forbidden d'oraisa on account of preparation (hachanah):`,
  "2:_": `Or before it. The commentator on the Tur did not look at siman 501:`,
  "3:_": `Forbidden on that day. On account of lest he climb and detach; and on account of muktzeh; and see siman 318; and in Tosafos beginning of Beitzah:`,
  "4:_": `His teeth — forbidden. And if he cut it off — he is liable (Rambam chapter 11); and it is implied in the gemara in chapter 1 folio 2b that if his fellow invited him to a meal on Shabbat and it was impossible for him to prepare anything from erev Shabbat to pick his teeth with — permitted to move a splinter to pick his teeth with it if he has no alternative, on account of human dignity, for it is disgraceful to him when sometimes the flesh between the teeth is visible from outside; and see siman 318 and it appears to me that in a place where this is not considered a disgrace — forbidden:`,
  "5:א": `For a sick person. So in the gemara; if so it implies that for a healthy person — forbidden; and it is possible that he stated it as the usual manner of speech; and see siman 308 s.k. 23:`,
  "5:ב": `"And he rubs it." And "he cuts it off" — with the hand but not with a utensil (Yam Shel Shlomo chapter 4 siman 8); and see seif 4 and siman 501 that specifically to add scent — permitted, but forbidden to create a new scent:`,
  "6:א": `Since they are strict, etc. It implies that to divide without lots — permitted; and specifically in an unspecified case we say they are not strict unless they wish to cast lots, for then we see they are strict; but if we know they are strict — even to divide without lots forbidden, for we are concerned they will come to mention measuring and weighing and counting, as is written siman 323; and even to share — forbidden for this reason; and specifically in members of a fellowship; but unspecified neighbors who are not companions — they are strict, and nevertheless permitted to ask one from another, since they are not accustomed to ask one from another frequently they did not decree lest they come to prohibition; so too Tosafos and Beit Yosef siman 501; and it is implied from the plain meaning of the poskim that with lots — forbidden even for neighbors; and so too Rambam chapter 23 — forbidden to cast lots, for it resembles buying and selling, as in siman 338 seif 5:`,
  "6:ב": `On account of gambling (kubya). The author of Shulchan Gadol challenged: Tur ruled in Choshen Mishpat siman 207 that there is no theft in gambling, see there; and siman 34 and siman 310 imply there is some prohibition in the matter:`,
  "6:ג": `That they are not strict. And the plain meaning of the Talmud implies specifically when he gives them from his own and does not do so except to appease them as stated; and see Yoreh De'ah siman 105 seif 8: it is stated in the gemara folio 149 that they cast lots for the weak ones upon the sacred offerings on Yom Tov, but not upon the portions of weekday — Rashi explained of yesterday; and so Ra'avad and Ran explained the words of Rambam; if so, even for a matter of mitzvah one should not cast lots wherever it can be done from erev Shabbat; and on Shabbat in every case forbidden, for behold there is showbread on Shabbat; nevertheless Maggid Mishneh explained Rambam: specifically of non-sacred things forbidden, but of sacred things permitted in every case on Yom Tov on account of affection for the mitzvah; see Taz there; nevertheless it appears to me that all this is to divide some matter — forbidden on Shabbat even where it comes to appeasement, as many in the gemara; but to cast lots for who says Kaddish or who goes up to the Torah — permitted, for many poskim hold that in the Temple they cast lots for who slaughters, who throws, etc.:`,
};
