export const t = {
  "1:א": `(1) On her head — all these refer to this, excluding threads on her neck as in seif 2.`,
  "1:ב": `(2) That she must remove them etc. — lest obligatory immersion occur and she be forced to remove them because of chatzitzah and carry four amos. See Acharonim who wrote the Sages did not distinguish in their enactment — even old woman and virgin may not go out.`,
  "1:ג": `(3) Lest she carry them — specifically with small things like these we are concerned, since even on weekdays she sometimes carries them in hand; but main garments we are not concerned, for her way is not to walk without them and she will certainly wear them after immersion.`,
  "1:ד": `(4) Woven into her hair — permitted, for no concern lest she carry, since forbidden to undo hair braid as in s.k. 26; reason of "some forbid": lest when obligatory immersion occurs she undo braid via gentile and take threads and then carry [Taz]; other reasons see Bach and Beur HaGra.`,
  "1:ה": `(5) Woven work — these do not tighten well and do not interpose; see Yoreh Deah siman 198 where stam in s.k. 3 only when woven work they are hollow need not remove.`,
  "1:ו": `(6) That they not be soiled — when threads soiled in mud, water dissolves mud and soils flesh on ascending from immersion, therefore her way to remove initially; since she removes for soiling she may carry; likewise gilded threads she removes before immersion so threads not soiled in water and then carry. Some add she must remove before immersion for chatzitzah since she is particular about them.`,
  "2:א": `(7) They are loose — she does not tighten strongly, does not choke herself, unlike katlah which is wide strap as below seif 7 and does not choke; threads not forbidden lest remove and show — that applies only to ornament.`,
  "2:ב": `(8) Because she tightens — therefore chatzitzah concern; though below seif 7 implies reason is important item and concern lest remove and show — there deals with loose around neck, still forbidden lest remove and show; here when she tightens to appear fleshy she will not remove, for then not appear fleshy, yet forbidden because must remove for chatzitzah.`,
  "2:ג": `(9) We are concerned etc. — they are types of ornaments.`,
  "2:ד": `(10) No such concern — she does not remove hairnet on Shabbat lest hair be uncovered.`,
  "3:א": `(11) She may not go out etc. — see below start of siman 308.`,
  "3:ב": `(12) Like measure of tzitz — it is ornament, concern lest remove and show.`,
  "3:ג": `(13) Cloth — neither ornament nor garment, like burden hung only to drive flies, for if fly stands on her face she is ashamed to drive it.`,
  "4:א": `(14) Round ornament — even though only important woman goes out with it, still concern lest show off, considered more than kelilah below.`,
  "4:ב": `(15) With which they attach — not full attachment, can remove; since ornament, concern lest remove and show — this reason also for Rabbeinu Tam's explanation.`,
  "5:_": `(16) Whether made etc. — reason: whose way is to go out with this is important woman who does not remove and show [Gemara]; poskim wrote for other ornaments all women accustomed — even important woman forbidden, Sages did not distinguish in enactment.`,
  "6:_": `(17) Forbidden — concern lest fall and carry.`,
  "7:_": `(18) With katlah — lest remove and show; see above what we wrote in s.k. 8.`,
  "8:א": `(19) With nose rings — though ornament, lest remove, show, and carry four amos.`,
  "8:ב": `(20) With ear rings — burdensome to remove and show because ears covered with ties.`,
  "9:א": `(21) She may not go out etc. — even when inserted in garment, way of carrying for woman all agree; for man see above siman 301 seif 8.`,
  "9:ב": `(22) She is liable — it is burden even when fastening knots, inserting needle in kerchief or closing cloak openings — no way to fasten and close with perforated; therefore burden; her way of carrying thus on weekdays to give needles inserted in kerchief or garment.`,
  "9:ג": `(23) Her knots — kerchief knots or closing cloak openings etc.`,
  "9:ד": `(24) Permitted — some Acharonim wrote only when needle not made to adorn; then permitted because used for dressing need — like handle of garments; if made to adorn, e.g. thick head like ornament — rabbinically forbidden to fasten knots lest remove and show. Some permit all cases since for modesty not remove and show lest hair uncovered — Gra sides thus in Beur; main permit reason when fastening knots is modesty; therefore do not protest those lenient, especially our unperforated needle [called shpilke] even if thick head not so much like ornament — possibly all permit; certainly rely to be lenient fastening knots.`,
  "9:ה": `(25) Forbidden — to go out inserted in kerchief or garment even if adorning, e.g. thick head like ornament — no Torah liability, still rabbinically forbidden lest remove and show; all the more if not like ornament — considered burden and liable chatat. Know: when not like ornament, even if needed for some purpose e.g. parting hair — still full burden, person cannot go out with all needed items that are neither garment nor ornament.`,
  "10:א": `(26) She is liable — not woman's way to wear ring with seal; therefore not ornament; nevertheless way of carrying on finger, for sometimes husband gives ring on weekday to hide in box and places on finger until she brings there.`,
  "10:ב": `(27) She should not go out — lest remove and show; b'dieved exempt since ornament for woman; see above siman 301 seif 9 law for man.`,
  "11:א": `(28) She may not go out with kulyar — mishnah: liable chatat on kulyar; see below.`,
  "11:ב": `(29) With which she fastens etc. — kulyar's way is for this; but now she does not close cloak with it but loads thus — therefore liable chatat, not considered ornament but burden only to show wealth; if still closes cloak openings — permitted l'chatchila as ornament, no remove/show concern, for then she would expose flesh; see Biur Halacha.`,
  "11:ג": `(30) It is a knot etc. — woman with bad odor loads it, not liable since ornament; but l'chatchila forbidden lest remove and carry.`,
  "11:ד": `(31) Spice tied in it — likewise may not go out with vial of perfumed oil fixed on arm.`,
  "13:א": `(32) Lest it not fit etc. — she removes and carries.`,
  "13:ב": `(33) Since yesterday — even one hour [Gemara].`,
  "13:ג": `(34) But man permitted — both apply [Bach siman 301 and Shulchan Pesak].`,
  "13:ד": `(35) And other garments etc. — no concern lest remove those, as above s.k. 3.`,
  "14:א": `(36) With hair threads — she tightens on head; this is not foreign braid explained below seif 18 forbidden in public domain as ornament there; here only plain threads.`,
  "14:ב": `(37) Even animal hair — we do not say repulsive and she removes.`,
  "14:ג": `(38) Provided old woman not etc. — reason in all: they mock her and she removes and carries.`,
  "15:א": `(39) For healing eye-stroke etc. — appears because in their time this was proven remedy, like expert amulet; no remove/show as not adornment.`,
  "15:ב": `(40) Tied and tightened — otherwise concern lest fall and carry.`,
  "15:ג": `(41) In her ear — made to absorb ear discharge.`,
  "15:ד": `(42) In sandal — for comfort; also need tie lest fall and carry; unlike menstruation cotton — even if falls will not take at all since repulsive.`,
  "15:ה": `(43) Tied in sandal — Shulchan Aruch wording implies here not required tightened; likewise Tosafot Rosh.`,
  "15:ו": `(44) On every side — excluding our pantofle — concern when not tied lest fall and carry.`,
  "15:ז": `(45) And distress her — but if only to prepare soiling to save garments from soiling — forbidden as siman 301 seif 13.`,
  "15:ח": `(46) Handle — for her cotton she can hold by handle; teaches even so repulsive to take.`,
  "15:ט": `(47) And pepper and salt grain — pepper for mouth odor, salt for tooth ailment.`,
  "15:י": `(48) And provided etc. — this "provided" refers only to what she puts in mouth; but regarding cotton above even l'chatchila permitted Shabbat; many Acharonim likewise permit l'chatchila putting straw in our fully closed shoes; good to be stringent unless need.`,
  "15:כ": `(49) She not put initially etc. — all healing they decreed lest crush spices, or appears scheming to carry; unlike above cotton where need evident and not scheming [Ateret Zekenim].`,
  "15:ל": `(50) If fell she not return — appears scheming to carry; likewise some say main reason like initial placement, decree crushing spices; per this reason forbid return only on ground, not on utensil as siman 328 s.k. 25 regarding rag; Gra Beur implies likewise.`,
  "15:מ": `(51) They tie etc. — even if salve is adornment, not ornament lest remove and show — need for garment, like garment handle; certainly won't remove lest ankle houses fall.`,
  "15:נ": `(52) With salve — in Shibolei Leket and Rishonim: salve or strap; fits ending "not concerned lest slip" — salve and strap referred; clear in Semak.`,
  "15:ס": `(53) With etzba'ah on arm — see Biur Halacha: placed and tightened on flesh not on shirt above — permitted, no concern remove and show lest arm uncovered; same reason on leg; some say only leg lenient not arm.`,
  "15:ע": `(54) That adheres etc. — if loose, concern fall and carry.`,
  "16:_": `(55) She may untie — e.g. belt etc.; reason: things usually removed, Sages forbade going out wearing them lest when removing later on Shabbat forget and carry; but permitted to go out wearing — not usual to remove — permitted to tie and untie Shabbat; if remembers Shabbat when untying won't carry; if forgets, prohibition to untie won't help [Tosafot].`,
  "17:א": `(56) In house courtyard — even joined courtyard; this is second view seif 18 below: whatever forbidden to go out wearing in public domain forbidden to walk even in house and joined courtyard.`,
  "17:ב": `(57) Only in hand etc. — where permitted in hand to courtyard, no forget and take to public domain concern; otherwise no utensil could move in house lest forget; but permitted wearing on belt — common to forget and go everywhere even public domain without removing — this is reason of second view seif 18: ornament forbidden public domain as wearing — forbidden adorn at home and courtyard.`,
  "18:א": `(58) To go out to courtyard etc. — house to courtyard; likewise not adorn in unjoined courtyard as resembles public domain; but to joined courtyard permitted, all the more in house.`,
  "18:ב": `(59) Except koveles etc. — wool cap seif 3, likewise itztima there; reason: permitted these ornaments so she not repulsive to husband if not adorn at all.`,
  "18:ג": `(60) Hair braid — detached hair she piles on hair above to appear hairy.`,
  "18:ד": `(61) Except koveles etc. — permitted all courtyards so not repulsive to husband as above; see Beur HaGra sides with first view.`,
  "18:ה": `(62) Accustomed to go out — even our public domain; then Mechaber explains custom: some say by law forbidden, for even if permit unjoined courtyard, our public domain even if not full public domain per "banners in desert" — at least karmelit, no Gemara view permitting karmelit; some merit: now no public domain per many poskim, no decree lest resemble public domain — our karmelit like unjoined courtyard and permitted — Shulchan Aruch explanation for Beit Yosef inquirers though wording slightly strained.`,
  "18:ו": `(63) However etc. — when wearing, no burden, only rabbinic even full public domain lest remove and show — therefore lenient in our areas; unlike this case.`,
  "18:ז": `(64) Even in karmelit — likewise even courtyard forbidden [Gra].`,
  "18:ח": `(65) It is for them etc. — in Chiddushei R' Akiva Eiger: though need not protest those with whom to rely, baal nefesh should concern not go out with ring at all — besides eruv.`,
  "18:ט": `(66) It is for them etc. — per what wrote initially per latter view ornaments permitted.`,
  "18:י": `(67) Nevertheless etc. — even per all lenient views only ornament not non-ornament; therefore what permitted seif 9 needle for knots — no more needles in kerchief than needed for knots; needle not fastening knots not ornament at all as explained seif 9.`,
  "19:_": `(68) Needle point removed etc. — unperforated needle with thick knot [shpilke], called eye; when point or eye removed utensil name nullified; see Magen Avraham disputes Mechaber — holds perforated: one of point/eye nullifies as siman 308 seif 11; unperforated: both needed; designation before Shabbat helps all for perforated if both removed.`,
  "20:א": `(69) Permitted to go out with them — their way thus, not burden.`,
  "20:ב": `(70) Dyed forbidden — important, lest remove and show; see Magen Avraham sides even dyed only forbidden virgin whose ears exposed; married covered — not usual remove, burdensome like ear rings seif 8; see Biur Halacha many Rishonim forbid married dyed threads too.`,
  "21:_": `(71) Except face — Aruch and Rashi: except eyes; teaches also this is way of dress.`,
  "22:א": `(72) She ties etc. — wraps in tallit with strap on one end, ties nut or stone on other, wraps strap so tallit not fall; does not appear intending to take nut/stone, all know she needs — unlike salt grain seif 15 not all know, therefore some forbid there.`,
  "22:ב": `(73) She designated for this — from before day; otherwise stone muktzeh like coin; Acharonim: round stone their way to tie — designation one Shabbat helps as Magen Avraham siman 308 s.k. 47; non-round — one Shabbat designation insufficient unless forever — helps even coin as below.`,
  "22:ג": `(74) Designation does not help — one Shabbat; if designated from erev Shabbat forever — helps even coin, muktzeh prohibition removed [Tosafot Rosh; Chiddushei R' Akiva Eiger].`,
  "22:ד": `(75) Tied before Shabbat — action effective to remove muktzeh name.`,
  "23:_": `(76) Forbidden — rabbinically to do though way of dress, not way of carrying, appears scheming to take out Shabbat. Know: both seifim though woman — likewise man [Ateret Zekenim].`,
  "24:א": `(77) With standing stone — what we call stone pregnant women carry [Taz]; Beur Maharshal on Semag: copyist found hollow flint with small stone inside like bell clapper — created thus; brought in Bereishit Rabbah; custom weigh something against stone — also helps; this is "weight weighed against it"; Gemara: if intended and scale found object naturally matches weight without subtracting/adding — has segulah; reason: permit as expert amulet.`,
  "24:ב": `(78) Even not yet pregnant — but fears lest become pregnant and miscarry [Gemara].`,
  "25:א": `(79) Serak — red dye; Tosefta: she not wipe face with cloth containing serak — implies even without dye intent, psik reisha; reason: woman accustomed to beautify by face dyeing — appears like dyer; man not accustomed — not called dyer as end siman 320 permits eating staining fruits though colors face and hands while eating; nevertheless woman passing serak on face only rabbinic — no Torah dyeing on human skin; see Biur Halacha.`,
  "25:ב": `(80) To apply kohl — on eyes.`,
  "25:ג": `(81) To smear dough on face — some practice forbidden smoothing hair with milk curd mixed with spices called pomade — I fear chatat, appears memareiach; warn household [Maamar Mordechai].`,
  "26:א": `(82) To braid — rabbinically like building [homiletical: God built Eve's side]; but braiding detached strands liable weaving per Rambam — here hair attached, not weaving; also will not endure, stands to undo [Magen Avraham; Shulchan Aruch in Tosafot]. Detached foreign braid [paruk] — though no building, forbidden weaving; if not enduring still rabbinic; nevertheless not worth protesting where they won't listen.`,
  "26:ב": `(83) Not to untie braid — resembles demolishing.`,
  "26:ג": `(84) Some forbid parting hair — concern uprooting; first lenient view: no intent, not psik reisha.`,
  "26:ד": `{Rama: Some forbid parting hair — meaning making the part (Rashi and Or Zarua); so practiced to forbid with utensil; with finger alone practiced lenient.}`,
  "27:א": `(85) Forbidden to comb — uprooting body hair, tolada of shearing.`,
  "27:ב": `(86) That impossible etc. — therefore even without uproot intent forbidden psik reisha; Gemara: all who comb to remove dangling hairs [partially detached] intend to separate hairs well; from this even soft comb forbidden if not manner without removing those hairs. Yeshuot Yaakov: saw people lenient combing Shabbat nearly permitted — woe to eyes; scholar should warn; they answer need fix hair for dignity — can do permitted way above; also seif 87; besides can smooth with hand — why violate serious prohibition.`,
  "27:ג": `(87) Lest uproot hairs — nevertheless permitted fix little head hair with pig-hair utensil — only combing forbidden as removes hair; fix little permitted; comb forbidden even for little; practice designate pig-hair utensil for Shabbat lest appear weekday work.`,
  "27:ד": `(88) And to arrange with hand — separate hairs one from another; Rambam: smooth hair with hand, scrape nails; even if hair falls not concerned, no intent to remove; possibly won't remove; see siman 326 seif 9 and Yoreh Deah and Mishnah Berurah there — not smooth with something that certainly removes hair.`,
};
