export const t = {
  "1:א": `(1) That is permitted to take supplies from it — for his food and for his animal's food, for it is not muktzeh, for we rule like Rashi who has no muktzeh except in dried figs and raisins that he set aside to dry by hand and they are not fit until they dry, as is written in siman 310 seif 2; nevertheless, if he does not wish to take supplies from it but only to begin emptying it — forbidden for a matter of reshus; and the reason is on account of tircha or weekday activities:`,
  "1:ב": `(2) Forbidden to begin, etc. — that is, even less than four and five kufot; and it implies that if he began from erev Shabbat — permitted to empty it on Shabbat, even less than four and five kufot, even for a matter of reshus:`,
  "1:ג": `(3) To empty it — but permitted to make a path with his feet to here and to there along his walking path and his going out, for this is not included in emptying:`,
  "1:ד": `(4) For a matter of mitzvah — and even in a matter where there is extra tircha, such as to raise them and lower them through windows in the wall, or to lower them on ladders, or to move them from roof to roof:`,
  "1:ה": `(5) Five kufot — and not more, on account of tircha, as stated in s.k. 1:`,
  "1:ו": `(6) Lest he come, etc. — that is, lest he see bumps in the floors of the storehouse and come to level them; and even if there are only three or four kufot — forbidden [Acharonim]:`,
  "1:ז": `(7) And every shevut, etc. — see siman 307 seif 5:`,
  "1:ח": `(8) For guest need — the host who invites them performs a mitzvah, as they said: great is hosting guests more than receiving the Divine Presence:`,
  "1:ט": `(9) But when he invited, etc. — nevertheless, if he invites his friend to come to honor the guest — then he too is considered as a guest for this matter, and if the meal itself is a seudat mitzvah — certainly it is obvious that it is permitted to empty according to the calculation of all of them:`,
  "3:א": `(10) That were brought — even from erev Shabbat [for otherwise they are forbidden anyway lest one come from outside the techum, as above in siman 325]; and his intent is expressly from erev Shabbat to drink from them — nevertheless forbidden to unload them on account of weekday activity or extra tircha; rather he draws there from them while standing on the wagon; and if impossible in another manner and he needs to drink from them — permitted to unload them, for honoring Shabbat is included in a matter of mitzvah [Acharonim]:`,
  "3:ב": `(11) For guest honor — and nevertheless, if it is more than fifteen se'ah — forbidden, as is written in seif 1 regarding a storehouse. Fifteen se'ah is if the barrel is a cubit by a cubit in height a cubit and three fingerbreadths [Magen Avraham]; and if it is a place of loss if permitted in this — tell a non-Jew, see siman 307 seif 5 and siman 334; and if the non-Jew unloads on his own on Shabbat — one need not protest his hand [Peri Megadim]:`,
};
