export const t = {
  "1:א": `(1) A man's wife, etc. — because his wife is like his body, and they were lenient even when he protested to her, because Chazal were concerned lest he intend to provoke the residents to forbid them; and therefore they were lenient that his wife may make an eruv without his knowledge, and they did not further concern lest both intend to provoke, for that is an uncommon matter:`,
  "1:ב": `(2) Makes an eruv for him — from his own:`,
  "1:ג": `(3) When he forbids them — the courtyard if he does not make an eruv with them:`,
  "1:ד": `(4) When accustomed and forbids, etc. — as below in siman 386 seif 9 see there:`,
  "1:ה": `(5) Accustomed to make an eruv, etc., without his knowledge — meaning even when he protested to her; and the reason is because of darkei shalom, since until now it was his practice to give a share in the eruv, therefore the eruv takes effect in every manner and afterward it is permitted to carry utensils that rested in his house to this alley:`,
  "1:ו": `(6) But she may not, etc. — meaning even for members of the courtyard who forbid them and he is accustomed to make an eruv with them:`,
  "1:ז": `(7) To grant ownership from his own, etc. — and from her sustenance she may grant ownership, for it is hers:`,
  "1:ח": `(8) Without his knowledge — meaning the husband does not know of this:`,
  "1:ט": `(9) Members of the household may, etc., without his knowledge — and if they know from him that he does not want, even though he did not protest to them explicitly, they may not make an eruv:`,
  "1:י": `(10) To one courtyard — for it is a benefit to him and certainly he will not object to them; but if it is open to two courtyards they may not make an eruv for him without his knowledge, for it is certainly not a benefit to him, for perhaps he does not wish to make an eruv with this courtyard but with that one, unless as the Mechaber concludes:`,
  "1:כ": `(11) Accustomed to make an eruv, etc. — for presumably his intent is also now for this:`,
  "1:ל": `(12) Without the knowledge of one member of the household, etc. — meaning without the knowledge of one member of the household; for if it were with their knowledge it would be permitted as long as they did not hear from the homeowner that he does not want an eruv; and see in Biur Halacha that we brought in the name of several Acharonim who rule that members of the courtyard may take his bread without his knowledge [as long as they do not know that he objects to the matter] and even without the knowledge of members of the household:`,
  "1:מ": `(13) But if he says he does not want, etc. — even if the house is open only to one courtyard, who forbid them by his preventing the eruv:`,
  "1:נ": `(14) To make an eruv with them, no — and even if he said so after she made an eruv, her eruv is void retroactively:`,
  "1:ס": `(15) Members of the courtyard, etc. — and the same applies to his wife; and it deals when by his preventing the eruv he forbids them:`,
  "1:ע": `(16) But they would compel him in beit din — meaning even though they themselves may not judge for themselves, beit din would compel him to make an eruv with them so he should not forbid them; and this law that beit din compels is according to all, even according to the first view:`,
  "1:פ": `(17) They descend to his property — and make partnership:`,
  "1:צ": `(18) And he retracted from his eruv — meaning that he said "I retract from the eruv and I do not want to make an eruv and participate with you anymore":`,
  "1:ק": `(19) Must return and grant ownership — for his eruv and previous partnership are void even though the bread is still in its place; and therefore if he wishes to be a partner with them again he must participate anew; and see in Biur Halacha:`,
  "1:ר": `(20) It is an eruv against his will — meaning he cannot return and void his eruv, as above, for where he is accustomed to make an eruv with them members of the courtyard come and take from him against his will; and all the more here where the bread is already in their possession; and even according to the first view who holds that without his wife's knowledge members of the courtyard may not take from him against his will — here it is lenient because the bread is already placed under their control:`,
};
