export const t = {
  "1:main": `The laws of borrowing and acquiring Shabbat needs, rinsing utensils, fixing them, and immersing them on Shabbat. And in it 10 seifim: It is permitted to say to one's fellow, "Fill this vessel for me," even if it is designated for measuring — and this is when the buyer takes the seller's measure and brings it to his house, and he need not say so; if the buyer brings from within his house and says to him, "Fill this vessel for me" — permitted; but to measure with the vessel designated for measuring and to pour into the buyer's vessels — forbidden: {Rama: And some are lenient to say that anything where he does not intend for the measure entirely, and he diminishes or adds a little — permitted [Hagahot Ashiri and Mordechai chapter Ein Tzedin], and so is the widespread custom to measure with the vessel designated for measuring and to pour into the buyer's vessels; and furthermore you will be explained nearby the reason of those who are lenient:} The law of Shabbat loans — its law is like on Yom Tov, and see above siman 525 and above siman 307 seif 11:`,
  "2:main": `It is permitted to say to one's fellow, "Fill this vessel for me, and tomorrow we will measure it" [but he may not say, "Give me such-and-such a measure"] [Tur]:`,
  "3:main": `It is permitted to say to one's fellow, "Give me eggs and nuts by count":`,
  "4:main": `It is permitted to say to the shopkeeper, "Give me four eggs and five pomegranates," provided he does not mention to him the name of a sum of money, nor a sum of measure, nor a sum of count, to say, "Here, you have fifty nuts in your hand — give me fifty others, and here you have a hundred": {Rama: And similarly with a sum of money — it is forbidden only in such a case where he says, "Give me for such-and-such a sum of money, and you will have such-and-such in your hand"; but otherwise permitted; and similarly a sum of measure — forbidden specifically in such a case, but otherwise permitted; and even though it is forbidden to mention money at all, that is regarding a matter whose purchase price is not known; but regarding a matter that is known, only that he says to him how much he needs — permitted, if he does not mention to him a sum [Or Zarua and Hagahot Ashiri chapter Ein Tzedin]; and even though some are stringent in this matter, already the custom has spread in these lands to be lenient, in accordance with the reasoning mentioned:}`,
  "5:main": `One who brings wine vessels from place to place may not bring them in a basket and box in the manner of weekday, but rather he brings them before him or on his shoulder and the like, that he changes from the weekday manner; even if there is no lightness in the burden of carrying; and if it is impossible for him to change — such as when he invited many guests and needs to hurry to bring before them — permitted; and some say that to diminish in walking is preferable, and it is better to bring them in a basket and box once than to bring each one alone before himself:`,
  "6:main": `One rinses utensils for the need of that day — such as when he still has a meal left to eat; but after the third meal one does not rinse; and drinking vessels one rinses all day, since all day is fit for drinking:`,
  "7:main": `It is permitted to immerse a new utensil that requires immersion; and some forbid; and one who fears Heaven goes out from all of them and gives the utensil to a non-Jew as a gift and returns and borrows it from him, and it does not require immersion: {Rama: And if it is a utensil fit to fill with water, he fills it with water from the mikveh and its immersion is fulfilled [Magid chapter 4 laws of Yom Tov and Hagahot Maimoniot chapter 23 laws of Shabbat]:}`,
  "8:main": `A cup from which a non-Jew drank — permitted to rinse it, according to all:`,
  "9:main": `It is permitted to scrub utensils with anything except silver utensils with geratekan, which is wine dregs when they have dried and hardened, because it erases silver utensils, which are soft:`,
  "10:main": `One may not scour utensils with salt, because the salt melts when one scours forcefully:`,
};
