export const t = {
  "1:main": `Things forbidden on Shabbat on account of making sound. And in it are 8 seifim: Making sound with a musical instrument is forbidden, but to knock on the door and the like when it is not in the manner of song is permitted: {Rama: And likewise if he does not perform an action it is permitted, therefore those who call their friends and whistle in their mouths like a bird are permitted to do so on Shabbat (Hagahot Alfasi). And forbidden to strike on Shabbat on the door with the ring fixed in the door even though he does not intend for song, nevertheless since the utensil is designated for that it is forbidden, therefore forbidden for the servant to strike the door to call to the synagogue by means of the utensil designated for that, rather he strikes with his hand on the door. (Agur and Beit Yosef in the name of Peskei Tosafos of Eruvin)}`,
  "2:main": `Some permit to tell a gentile to play with a musical instrument at weddings: {Rama: And even to tell a gentile to repair the musical instrument is permitted on account of honor of bridegroom and bride, but otherwise forbidden (Mordechai chapter "they lower"). Nevertheless in our time they were accustomed to be lenient from a reason that will be explained in the siman after this regarding clapping and dancing}`,
  "3:main": `The clock pair that jingles for hours made by a weight is permitted to set it and prepare it from while it is still day so that it will go and jingle all Shabbat`,
  "4:main": `One who guards his fruits and seeds from beast and bird should not clap hand to hand nor pat his hands on his thigh nor dance to drive them away — a decree lest he take a stone and throw to them`,
  "5:main": `One does not play with nuts nor with apples and the like on account of leveling bumps: {Rama: And specifically on top of the ground, but on top of a table it is permitted for there is nothing to decree there on account of bumps (Rabbenu Yerucham). Permitted to play with bones called "tashich" even though they make sound, since they do not intend for song (Hagahot Alfasi end of Eruvin). And all this is when playing in a manner of mere jest (Beit Yosef). But when playing in order to profit it is forbidden even when playing fairly and unfairly for it is like buying and selling (Agur and Beit Yosef and Rambam chapter 23). Nevertheless one should not protest women and children for it is better they be inadvertent and not intentional [Tosafos and Semag and Hagahat Maimoniot chapter 21]. And regarding playing with a ball see above siman 308 seif 45}`,
  "6:main": `Forbidden to draw water with a wheel — a decree lest he fill his garden and ruin or the soaking pool of flax. Therefore if there was neither garden nor ruin nor pool to soak flax there — permitted. And some say they forbade only a large wheel that draws much water together without exertion, which are wheels fixed with many buckets around, but our wheels that do not fill except a little — permitted for there is nothing to be concerned about`,
  "7:main": `One who has fruits on the roof and sees rain coming — forbidden to lower them on Shabbat through the roof hatch, but permitted to cover them, and even bricks that are muktzeh — permitted to cover them on account of the leak`,
  "8:main": `Permitted to place a vessel under the drip on Shabbat, and if it filled he may pour it out and return it to its place — provided the drip is fit for washing. But if it is not fit — forbidden on account that one does not make a graf shel re'i l'chatchila. And if he placed a vessel under a drip not fit for washing — permitted to move it with the repulsive water in it`,
};
