/** OC siman 475 — mechaber (7 keys) */
export const t = {
  "1:main": "Continued laws of the Seder. Containing 7 sections: One should wash their hands and bless \"Al netilat yadaim\" and pick up the matzot in the order that they were placed down - the broken one between the two full ones - and grasp them in one's hand, and bless \"Hamotzi\" and \"Al achilat matza\" and afterward break up the upper, whole one and the broken one, both of them together, and dip them in salt. and eat them while leaning, together, an olive-bulk of each. And if one cannot eat two olive-bulks at once, one should first eat the one from \"Hamotzi\" and afterward the one from \"Achilat matza.\" And afterward, one should take an olive-bulk of marror and submerge it entirely in charoset, but not let it sit inside it, so that the flavor of its bitterness will not be cancelled out. And for this reason, one must shake the charoset off of it. And one should bless \"Al achilat marror\" and eat it without leaning. And afterward, one should pick up the third matza and break it up and sandwich it with marror and dip it in charoset {Rama: But the custom is not to dip it in salt on the first night, since refined-flour bread does not require salt Rema: And some say that one should not dip it, and this is aligned with customs, and I have seen it practiced] and says \"Zecher lemikdash keHillel\" and eats them together while leaning. And from when one blesses \"Al achilat matza\" one must not interrupt with anything unrelated to the meal until one eats this sandwich, in order to have the blessing of \"Achilat matza\" and the blessing of \"Achilat marror\" count for this sandwich too.}",
  "2:main": "If one has no greens to dip at first (for karpas) except marror, one should bless at the first dipping \"Borei peri haadama\" and \"Al achilat maror,\" and at the second dipping one should dip it in charoset and eat it without a blessing.",
  "3:main": "One who swallowed matza (without chewing) has fulfilled their obligation. But if one swallowed marror, they have not fulfilled their obligation, since the flavor of marror is necessary, and it is lacking. And even if one swallowed matza and marror as one, they have fulfilled their obligation of matza but not their obligation of marror. And if one bundled them in fibers and swallowed it, they have not even fulfilled their obligation of matza, since this is not the normal way to eat.",
  "4:main": "One who ate matza unintentionally, for example, if non-Jews or thugs forced them to eat it, has fulfilled their obligation, since they were aware that the night was Passover and that they were obligated to eat matza. But if they believed that it was a regular day, or that this was not matza, they have not fulfilled their obligation.",
  "5:main": "One who ate an olive-bulk of matza while they were overcome by a period of insanity and then later became healed is obligated to eat it after being healed, since that act of eating occurred at a time when they were exempt from all commandments.",
  "6:main": "One who ate half an olive-bulk and later ate another half olive-bulk has fulfilled their obligation, as long as one does not pause between the two acts of eating longer than the time it takes to eat a loaf of bread. {Rama: (And see below 612:3)}",
  "7:main": "The obligation to eat matza only applies on the first night. And even on the first night, one fulfills their obligation with one olive-bulk. {Rama: And the custom is to make the three Seder matzot out of an issaron of flour, as a commemoration of the Todah loaves, and they make a mark on them to indicate which is first, second, or third, and they place the first on top, the second in the middle, and the third at the bottom, for the sandwich. But if one deviated, they have not ruined it. (Tur citing Rosh) And they bake them in order as well (Kol Bo and Avudraham). And if one of them breaks, they choose that one to be the second one, because in any case it will be split. (Agur) (And on the measure of an olive-bulk, see below 486)}",
};
