export const t = {
  "1:main": `Which partition is called a partition for carrying. And in it are 12 seifim: Every partition that was not made for dwelling within it but for modesty or to guard what they place within it or to sit in it in order to guard the fields — it is a partition for carrying what is within it, but it is not a partition to make what is within it enclosed for dwelling if it is more than beit se'atayim; therefore a tree whose branches descend downward — if they are not three [tefachim] high from the ground and their base in the place where they are attached to the tree is ten high — it is considered a partition and it is permitted to carry throughout all of it; and this is when he fills the airspace between the branches with wood or straw and ties the branches so the wind does not move them, for every partition that cannot stand in a common wind is not a partition; and specifically up to beit se'ah, but more than beit se'ah — not, even if he planted it for this, since it is not made for dwelling within it but only to rest in its shade to guard the fields:`,
  "2:main": `A tel that is five [tefachim] high and he completed it to ten by making upon it a partition five high — it is considered a partition for carrying and for every matter:`,
  "3:main": `A partition standing by itself — that is, which was not made for the sake of a partition — is valid like a partition made on Shabbat is valid; and this applies when it was made on Shabbat unintentionally; but if intentionally it becomes a partition to be stringent — to render liable one who throws from reshus ha-rabbim into it, but not to permit carrying within it; and this applies when there was no partition there initially; but if there was and he removed it and it returned and was made, even intentionally it returns to its original permission — such as two or three who surrounded themselves with mats in reshus ha-rabbim and also separated between themselves with mats and joined in an eruv together — they are permitted to carry from one to the other; if the mats rolled up they became forbidden; if they returned and were spread out, even intentionally they return to their original permission:`,
  "4:main": `A ship — it is permitted to carry throughout all of it even if it is more than beit se'atayim, for it is considered enclosed for dwelling (and see above siman 366 and end of siman 482); if its deck is for dwelling beneath it, it is reshut ha-yachid; but on its deck, if its deck is for tar — one may not carry in it except within four amot if it is more than se'atayim:`,
  "5:main": `With anything they make a partition — with vessels and with saddles, whether of warp alone such as of ropes, or of woof alone such as reeds stuck in the ground — and they are permitted up to se'atayim even for an individual in a settled area, provided there is not between one rope and its fellow nor between one reed and its fellow three tefachim; and even with animals, provided they are bound; and even with people standing one beside the other within less than three [tefachim], and even when they are walking — they are considered a partition and between them is reshut ha-yachid; and this is when they did not know they were stood for the sake of a partition; and even if one of them knows — it is forbidden; and even if he did not inform them that he is making partitions now — if it is likely they will know, such as if he once made a partition from them — he should not make a partition from them again:`,
  "6:main": `If they came initially without knowledge, even though afterward they became aware — there is no concern:`,
  "7:main": `There are those who say that the person who wishes to use this partition should not stand them himself but another should stand them without his knowledge: {Rama: And one should not make a partition of people except at a time of need and at a time of pressure; and if one forgot one item in reshus ha-rabbim, it is preferable to bring children there to bring the item without a partition rather than to make a partition of people and have an adult bring it (Beit Yosef in the name of Shibbolei HaLeket and Semag and Semak):}`,
  "8:main": `Breach greater than standing — forbidden, unless each breach among them is less than three tefachim:`,
  "9:main": `Breach equal to standing — permitted, whether of warp or of woof, provided there is not in one place a breach more than ten; but up to ten amot it is permitted because it is like a doorway:`,
  "10:main": `If he made tzurat ha-petach, even for a breach greater than ten — permitted; and even if he only planted four posts at the four directions and made tzurat ha-petach upon them — permitted; and this applies in a courtyard and alley that have residents; but in a field it does not help with all the directions by tzurat ha-petach; and for Rambam tzurat ha-petach does not help for a breach more than ten unless standing is greater than the breach (then it helps even in a field in all the directions) (Beit Yosef in the name of Semag and Semak):`,
  "11:main": `What is tzurat ha-petach? A reed from here and a reed from there and a reed upon them — even if it does not touch them but there are several amot between them, provided the height of the reeds from here and from there is ten and they are aligned opposite the upper reed; and if he attached the upper reed to the two reeds or to one of them from the side — it does not help; and the reeds at the sides must be strong enough to receive a door of any kind, even of straw or of reeds; but the reed upon them suffices with any amount, and even a rope of palm branches helps:`,
  "12:main": `An arch (meaning a roof made like an arch — Rashi) — if at its legs, that is before it began to curve, there are ten tefachim — it is permitted by reason of tzurat ha-petach:`,
};
