export const t = {
  "1:main": `Moving a door, window, and lock on Shabbat. And in it 10 seifim: A window plug, such as a board or any other thing with which they seal the window — they may seal with it even if it is not tied, and we do not say that it is like adding to building; provided that he intend upon it from erev Shabbat to seal with it and acquires it — that he fixed it to be locked with it — he need not tie it to the door. And a reed that they fixed to be locked with it — he need not tie it to the door; and nevertheless it resembles building more than a window plug, and thought that he intended it from yesterday is not sufficient; he must fix it for that purpose. According to Rashi, this means he fixes it as a utensil fit for some use, that it should be fit to turn olives in it or to crack nuts with it. And according to Rabbeinu Tam, it need not be fit for another matter; rather once he fixed and did an action and prepared it for that purpose, it is sufficient. {Rama: And thereby it is called a utensil whose melacha is permitted, and it is permitted to move it, as explained above siman 308 seif 2 (Beit Yosef and Rambam).} And a door bolt, which is a peg with which they lock and insert it into the threshold below — it resembles building more; this is not sufficient, and they do not lock with it unless it is tied. And how must it be tied — if its head has a glostera, meaning that it is thick at one of the heads and fit to pound with it so that it resembles a utensil — it is sufficient even if tied with a thin rope that is not fit to be carried by it, and even if not tied to the door itself but to the door bar, and even if the rope is long and not suspended at all in the air but all of it lies on the ground. And if its head does not have a glostera — if it is tied to the door itself it is sufficient, even with a thin rope not fit to be carried by it, and even if all of it lies on the ground. And if it is not tied to the door but to the bar, the knot must be strong that it be fit to be carried by it; and even so it need not be suspended, rather even if all of it lies on the ground it is permitted, for it is forbidden only when they remove it and place it in a corner.`,
  "2:main": `All door bolts that we said apply when the threshold is high and when they insert it in the door sill it does not pierce the ground; but if the threshold was diminished such that when inserting the door bolt in the hole it pierces below into the ground, it is boneh and forbidden to lock with it.`,
  "3:main": `A courtyard behind the houses that people do not regularly enter and exit — if he made a door for its opening or hangs a reed mat on it, and likewise a breach that he fenced with thorns like a door — if they have a hinge (explained: they pierce the door and set in it a single piece of wood in order to insert it in a socket back and forth), or even if they do not have a hinge now but they had a hinge — they may lock with them even if they are dragged on the ground, only that he tied them and hung them to lock with them, and it is not considered building since it is recognizable in them that it is a door, since they had a hinge. {Rama: And all the more so if they still have a hinge, provided the hinge does not return to its place as will be explained later siman 519 (Beit Yosef).} But if they have no hinge and never had a hinge — they may not lock with them unless they are raised from the ground; and an opening made for regular entering and exiting — they may lock with it even if it never had a hinge, and it is dragged.`,
  "4:main": `A door made from a single board, or that has no lower threshold and when they open they remove it and uproot it — they may not lock with it even if it has a hinge. {Rama: But a door made from many boards is permitted even though they remove it when opening, if it has a threshold; and the same in a place where they lock with many boards and there is carving above and below into which they insert the boards, that their law is like a door, since they are not a single board for the entire door (Beit Yosef).}`,
  "5:main": `A chest, box, and tower whose openings are from the side and have two hinges, one above and one below — if the lower came out entirely from its place, it is forbidden to return it lest he hammer; but if part of it came out he may force it until he returns it to its place, since the upper remained in its place he can easily return the lower. But when the upper came out it is forbidden even to force it to return it to its place.`,
  "6:main": `A folding bed — it is forbidden to return it and tighten it, and if he hammered he is liable for a chatat; but if it (is its way to be) loose it is permitted l'chatchila (provided he does not tighten). And a folding cup — it is permitted to disassemble and return it on Shabbat; and some say the law of the cup is like the law of the bed. {Rama: And if its way is to be tight, even though now it is loose it is forbidden (Rambam chapter 25, Hagahot Ashiri, Kol Bo, and so the words of the Tur appear).}`,
  "7:main": `A beam that broke — it is permitted to support it with the long parts of the bed, which are utensils, not in order that it rise, for then it would be boneh, rather so that it not descend more; and this is provided they are loose so he can take them when he wishes; but if he tightens them there it is forbidden.`,
  "8:main": `A bench from which one of its legs fell out — it is forbidden to return it to its place; and to place the fallen side on another bench — some are stringent to forbid (and see above siman 308).`,
  "9:main": `One who drives wood into wood, whether he drove with a nail or drove into the wood itself until they became joined — this is a tolada of boneh.`,
  "10:main": `A courtyard that was ruined by rain waters — he may scatter straw in it and it is not considered like adding to building, provided he changes — that he not scatter neither in a basket nor in a hod, rather on the rim of the hod that he turn it over and bring straw on its rim, i.e. by change; but by hand it is forbidden.`,
};
