export const t = {
  "1:main": `Several particular laws practiced on Shabbat. And in it are 7 seifim: One does not ride on an animal: (and see above siman 305 seif 18 regarding the law of walking a carriage):`,
  "2:main": `One does not swim on the surface of the water, even in a pool in a courtyard, because when the water is displaced and goes outside the pool it is considered like a river; and if it has a rim around it — permitted, for even if the water was displaced the rim returns them to their place, it is like a vessel and there is no room to decree lest one make a float:`,
  "3:main": `One does not clap hand to hand nor slap hand to thigh nor dance — a decree lest one fix a musical instrument; and even to tap with a finger on the ground or on a board or one against one as singers do, or to rattle a nut for a child or to play with it with two nuts so he will be quiet — all this and the like is forbidden, a decree lest one fix a musical instrument; and slapping with the back of the hand is permitted: {Rama: And this that they clap and dance nowadays and we do not protest — because it is better that they be unintentional transgressors etc.; and some say that in our time all is permitted because we are not proficient in making musical instruments and there is no room to decree lest one fix a musical instrument because it is uncommon; and possibly on this basis they were lenient in everything. (Tosafos end of chapter HaMevi Kadei Yayin):}`,
  "4:main": `One does not judge: {Rama: And therefore it is forbidden to seize and bring into prison one who was liable for some punishment so he not flee, and all the more so it is forbidden to lash him because it is included in judgment; and if he flees we bear no liability (Beit Yosef end of siman 253 in the name of Shibolei HaLeket)} and one does not betroth: {Rama: And there are those who permit to betroth where he has no wife and children (Rabbeinu Tam); and it is possible the same applies to entering the chuppah — permitted (Semag); and even though we do not rule thus, nevertheless we rely on this in time of need because great is human dignity — as is customary that sometimes they could not settle the dowry on Friday until nightfall, that they make the chuppah and kiddushin on Shabbat night since they already prepared for the feast and marriage and it would be embarrassing for the bride and groom if he not enter then; and nevertheless l'chatchila one should be careful that it not come to this (and see Tur Even HaEzer siman 63):} and one does not perform chalitzah nor yibum nor does one bring in [to chuppah] nor dedicate [to Temple] nor vow valuations nor declare cherem nor separate terumot and maaserot nor redeem the firstborn nor divorce unless it is a deathbed get (because the world weighs heavily upon him) — and all of them if done unintentionally or intentionally or under mistake — what was done is done:`,
  "5:main": `One who marries a widow should not have first intercourse with her neither on Shabbat nor on Yom Tov (see above chapter 280):`,
  "6:main": `It is forbidden for a person to float something in water to convey it from himself or to bring it to himself; and therefore woodchips that are on the surface of the water — forbidden to spread them here and there in order to clean the water that they be beautiful:`,
  "7:main": `A boat — if it sits on the seabed and does not float at all — permitted to enter it; and if it is tied as is the custom of boats standing in port, even though it floats on the surface of the water — permitted to enter it:`,
};
