export const t = {
  "3:_": `(Seif kaf-gimel) Due to, etc. And in Maggid Mishneh, etc. — muktzeh. Meaning: forbidden to carry even for the sake of their place, as the Shulchan Aruch wrote — meaning they are muktzeh due to monetary loss or that they do not have the status of utensils, as above siman 308.`,
  "5:_": `(Seif kaf-hey) And they bring, etc. to others — for if they place the eruv with them, they need not give any bread at all, for the house in which the eruv is placed need not give bread, as above siman 366 — rather they bring it to others. And the reason: since the others restrict, they too restrict.`,
  "7:א": `(Seif kaf-zayin) Or there are not — and what is the reason here: when each has an opening to the gatehouse, even though from gatehouse to courtyard they all have only one opening — nevertheless it is as if each has an opening to the courtyard and each is considered like the homeowner alone and must make an eruv.`,
  "7:ב": `What is the reason also: if the eruv was damaged, etc. — forbidden to carry also from room to room (and this is when a different homeowner dwells in each room, as stated in this seif) — just as they are forbidden to carry from house to house. And even though those two rooms have only one opening to the alleyway — nevertheless, since each room has its own opening to the house before the rooms, but from house to alleyway the two rooms have only one opening — even so they are considered as two and forbidden to carry without eruv.`,
  "7:ג": `If two dwell there — this applies also to the beginning where he wrote forbidden to carry from room to room.`,
  "7:ד": `See end of siman 365 that also if the lechi or beam of the alleyway was damaged, they are forbidden to carry from room to room or to the house when two homeowners dwell in them, for the eruv placed in the synagogue is nullified — there.`,
  "8:_": `(Seif kaf-chet) Tutor, etc. And if the place, etc., and each uses, etc. — his intention is that both reasons are required for them to restrict: one, that the place be owned by them — for otherwise one would permit based on the second reason of Tosafos that he does not lend, etc., to restrict him, etc. And we also require that each use independently — for otherwise they are permitted based on the first reason of Tosafos since they all use, etc. — for each alone of Tosafos' reasons suffices to permit. But one cannot say thus, that he disagrees with the Beit Yosef. And Maharik's responsum without proof — and he did not bring their words at all. For the Beit Yosef wrote one should not rely on reason one of Tosafos alone — meaning their baking and cooking place in one place — on this reason alone one should not rely except combined with reason two that he did not lend, etc., to restrict, etc. — the Taz also brought reason two. Perforce Magen Avraham holds that according to the Beit Yosef, perforce also on reason two alone — meaning he did not lend, etc., to restrict, etc. — we do not rely except combined with reason one — meaning their baking place and cooking in one place — for otherwise to what purpose did Tosafos mention this reason of their baking place, etc., since this reason alone does not help except combined with the reason he did not lend, etc., to restrict, etc. And with the reason he did not lend, etc., to restrict, etc. alone it does not suffice except combined with reason one of their baking, etc., in one place. And both are required to be lenient — that their baking place, etc., be in one place and that he did not lend, etc., to restrict, etc. And what Magen Avraham wrote "and each uses, etc." — this vav of "and each uses" is a dividing vav, meaning: either they restrict or the rooms are owned by them — then even if they use according to Magen Avraham they restrict; or when each uses independently, even though the rooms are not owned by them — nevertheless they restrict.`,
};
