export const t = {
  "1:_": `Even Taz in Magen Avraham letter 13 in the name of Peri Megadim letter 13 and in Tosafos Shabbos 248 letter 13 in the name of responsum Shev Yaakov: when the gentile conveys the boat and the Jew does nothing — permitted; and requires study, for in Shabbos 139b and so too in Tur — even though the gentile conveys the boat it is forbidden unless through a ruse for a Torah scholar; and if not so at the end of the siman I will explain:`,
  "2:_": `That it is better — Taz and so too Magen Avraham letter 1; and see there; and this is for all, even though some are stringent nowadays — nevertheless for honor of the Torah it is permitted; and bells on a Torah scroll which Taz forbids in Yoreh De'ah 282 — is not so much honor of the Torah; only to inform the people to stand; also rattling nuts is worse because it resembles a musical instrument — see there; unlike clapping and dancing; and the same for honor of the Torah one should not permit except clapping and dancing:`,
  "3:_": `Because the matter — Taz; and see in siman 316 in Taz 1 and in Tosafos Beitzah chapter 1:`,
  "4:_": `And one does not — Taz: some are stringent in Mishnah cherem in Beit HaLevi — see siman 306 in Magen Avraham 13 and so he wrote — see there:`,
  "5:א": `One who marries — Taz in Yoreh De'ah 197 (Taz 193) letter 6: regarding a widow we require actual entry from while it was still day (even though Israel are holy and do not have relations by day — they permitted the High Priest where there is compulsion and the feast was prepared); and she should not immerse on Shabbat; and regarding what is written some are stringent not to distance — see there; and if the night of immersion falls on Motzei Shabbat — permitted to marry on Shabbat so he not have intercourse with her on Shabbat and she should do the hair-washing on Friday and also on Motzei Shabbat; and see siman 199 seif 4; and I found here letter 5:`,
  "5:ב": `What Tosafos Shabbos wrote in 248 letter 13 in the name of Shev Yaakov — I brought it in letter 1:`,
  "5:ג": `If the chuppah was delayed on erev Shabbat and the groomsmen have candles — he must remove and give to a gentile, for muktzeh as long as it is in his hand he may take wherever he wants not all day; and whatever is possible to remove he is obligated to remove, like a shofar in the synagogue chazzan on the roof — and see Tosafos:`,
};
