export const t = {
  "eshel-avraham:1:_": `Free bird (deror). Rif and Rambam and Tur and Rosh did not distinguish between free bird and other birds, and the later authorities strained to reconcile. And in Eliyah Rabbah he answers at length — see there:`,
  "rabbi-akiva-eiger:1:_": `Magen Avraham s.k. 3 "exempt" refers to seif 2 "or old — exempt":`,
  "rabbi-akiva-eiger:2:_": `Magen Avraham s.k. 11 "and nevertheless one should not be lenient" — and thus is implied the view of Rama seif 3 that it is forbidden to close the box, for it is psik reisha regarding flies, even though he closes the box to guard other things inside it:`,
  "rabbi-akiva-eiger:3:_": `Magen Avraham s.k. 14 that implicitly they are trapped — and the essence of the distinction between the eight sheratzim that implicitly [trapped] and the language of Shulchan Aruch "not for need or without specification" — thus when explicitly not for need, even for the eight sheratzim — exempt:`,
  "rabbi-akiva-eiger:4:_": `There in Beit Aharon David — for behold they are not in the manner of harming; but other sheratzim that harm — implicitly trapped so they will not harm. And it is difficult to me: how did he write "and according to Rambam liable" — for behold he wrote earlier in seif 7 that so it not bite him — permitted, for Rambam too permits; requires study:`,
  "shaarei-teshuvah:7:_": `The skin — see Baer Heitev; and see in responsa Beit Efrayim siman 22 at length on this matter and resolving the words of Rashi and Rambam that appear to be against the Gemara in Chullin — see there:`,
  "yad-ephraim:1:_": `(In Shulchan Aruch seif 8) "The eight sheratzim," etc. — see what he wrote in my book responsa Beit Efrayim siman 22 in explanation of the words of Rashi on Shabbos daf 150 and the words of Rambam, and I brought there the words of the Yerushalmi on this and they are fine words with God's help; and see there siman 23 and siman 24 what he wrote there from the words of Aa"z the Gaon R' Elazar Margoliyot may he rest in Eden in the gloss Masat Binyamin who brought a proof for Mishna Berurah regarding the permission of slaughtering animals from Rashi on Shabbos daf 75 — see there what he wrote on this; and now I found in responsa Penei Meivin part 1 siman 75 also writing from these words of Rashi and like the words of the aforementioned Aa"z:`,
};
