export const t = {
  "1:א": `If it is more than two se'ah. Then it is called karmelit; but if it is two se'ah it is called karpef and it is one domain with the courtyard for utensils that rested in them and not for utensils that rested inside the house, as written in siman 372:`,
  "1:ב": `Provided its length not be etc. Like the courtyard of the Tabernacle which was one hundred amot long and fifty wide:`,
  "4:_": `It is not a reduction. For such is the way of a karpef to have trees in it:`,
  "9:_": `If there is in it only two se'ah — permitted. Since without dwelling it is permitted on its own, here too it is permitted; and even though a sown place is called karpef and what is not sown is a courtyard and they are breached to each other with no partition between them — nevertheless they do not forbid each other, since it is one person — for we rule like R' Shimon who said courtyard and karpef do not forbid each other regarding utensils that rested in the courtyard but not regarding utensils that rested inside the house — end quote Rashi; and it appears there is a scribe's error and it should read "even though not one person" etc. — see there in Rashi; and it is implied that when a minority is sown, at least the sown place is forbidden for there is no dwelling on it; but in more than two se'ah it is karmelit and there is no permission from courtyard to karmelit in any matter according to all; and it is explained in the words of the Tur that two se'ah and less than two se'ah are equal; therefore what is written here in Shulchan Aruch "even if there is in them only two se'ah" — the intent is likewise less than two se'ah:`,
  "10:א": `One who has a garden etc. Explanation: and there is no fence between the courtyard and the garden; and if there is a fence between them the distinction is this — in the garden itself: if the garden is more than two se'ah — forbidden to carry from courtyard into it in every manner; and if it is two se'ah or less — permitted to carry within it even all of it, and from the courtyard into it with utensils that rested in the courtyard but not with utensils that rested in the house; therefore it is fitting not to eat or drink in the garden on Shabbos, for it is impossible to be careful in this; and Rama already mentioned this in siman 336 for another reason; and even to carry knives or a key in one's belt from courtyard to garden is forbidden, for these are utensils that rested in the house; and here enclosed for dwelling does not apply, for seeds nullify the dwelling — and many stumble in this:`,
  "10:ב": `Forbidden to take out from it to the house. It implies but from courtyard to house is permitted; even though the garden is forbidden in itself from it to the house — nevertheless it does not forbid the courtyard to forbid it upon the house, and we do not say it is breached fully to the forbidden place but rather forbidden from its own side:`,
  "12:_": `It is written in the Tur: even if the roofing is sloped we consider it as if a partition etc. See on this in siman 361:`,
};
