export const t = {
  "2:א": `A place enclosed by partitions. In siman 363 it will be explained how many partitions are required there:`,
  "2:ב": `And it has four tefachim, etc. Implies partition thickness is measured with the hollow — and so Rosh explicitly in the first chapter of Shabbat regarding a beehive that the walls combine with the hollow of the beehive for four width, etc.; and so Tosafos in the first chapter daf 8 unlike R' Meir who explained four within the beehive — rather the thickness also combines as in a ditch-chain where it combines to the hollow of the ditch since it is fit to place something upon it, etc.; and they conclude as Rashi explained; and what Rashi wrote Beit Yosef brought: and likewise a fence — we say from four sides gud asik the partition faces to its top and its head is enclosed from four sides and its hollow is four — end of his words; do not err — specifically in the hollow there must be four tefachim without the partitions; therefore Rashi wrote "partition faces" to indicate the outer edge rises and gud asik partitions — the partition thickness is included in the hollow between this outer edge and the opposite edge; this is proven — if you wish to explain Rashi's words on the hollow itself, the explanation would accord with R' Chiya and Tosafos conclude Rashi accords with their explanation; and Rambam wrote in chapter 14 "enclosed by four high partitions and between them four" — his intent is also with wall thickness; and "between them" means between all as above; however a question — from what is written in chapter HaZorek (Shabbos daf 99): R' Yehudah asked — a wall in reshut ha-rabbim ten high and not four wide enclosing karmelit and he made it reshut ha-yachid and threw and it rested on top — what is the law? Do we say since it is not four wide it is makom patur, or since he made it reshut ha-yachid it is as one who filled it? Rashi explained: and its head is like adjacent ground — the whole hollow; Ulla said a fortiori for others he makes a partition — for himself all the more so; Rashi: the wall head is before us — since he made it reshut ha-yachid we say it is as one who filled — reshut ha-yachid rises until the firmament; unlike here where without thickness it is not reshut ha-yachid it does not rise until the firmament and is not like adjacent ground; and likewise in what he concluded "for others he makes reshut ha-yachid" — this is not clear here and requires study:`,
  "3:_": `Upon reshut ha-yachid. Meaning even though they are not four wide they are reshut ha-yachid — since they make with their enclosure the enclosed ground reshut ha-yachid that was karmelit, a fortiori they themselves are reshut ha-yachid; and see above what was difficult from this:`,
  "6:_": `Even a vessel. See siman 356 regarding a pool of water in reshut ha-rabbim or reshut ha-yachid:`,
  "7:א": `And their doors are not locked. It appears that if one door is locked it also nullifies reshut ha-rabbim since it is not open:`,
  "7:ב": `And some say that whenever there are not 60 myriads, etc. Beit Yosef wrote the latter view is Rashi and Tosafos and Rosh and Tur and Semag and Semak and Sefer HaTerumah (and Mordechai chapter Kol Kitvei) and Rokeach and the last Mahari Weil in a responsum; and the first view is Rambam and Ramban and Rashbam and Maggid Mishneh and Ran and Rivash; and I wonder — here Beit Yosef wrote in the name of Maggid Mishneh and Rambam and Rashba that 60 myriads passing are not required, but above siman 334 Tur wrote to challenge Sefer HaTerumah from this reason that there is no d'oraisa prohibition for us since we have no reshut ha-rabbim, etc.; and Beit Yosef wrote this challenge Maggid Mishneh brought in the name of Rashba — if so it implies he holds there was no reshut ha-rabbim until 60 myriads; and Rashal in chapter Ein Tzrichim seif 18 and likewise Mahar R' Binyamin in responsum siman 92 that one should be stringent like the first view; and Rama wrote in siman 346 that all our domains are karmelit — implies like the latter view; and among the public it is customary now that we have no reshut ha-rabbim, which is like the view of "some say" and they are many — especially since in the view of Maggid Mishneh and Rashba we also find the reverse as written — therefore one who is stringent should be stringent for himself and cannot protest what is practiced now like those many who are lenient as above:`,
  "9:_": `Thirteen amot and a third. Even though reshut ha-rabbim width is sixteen amot as between the wagons in the desert, nevertheless here since both ends are to reshut ha-rabbim this is also reshut ha-rabbim; and the reason for this measure is as we find in pasei bira'os — the space between each post was this measure, namely so two teams of four cattle can pass when they meet — one enters and one exits — then its use there is comfortable like reshut ha-rabbim; and every head of cattle is an amah and two-thirds; as explained in chapter Osin Pasin:`,
  "10:_": `It is karmelit. For it is not ten high — for here the use is by constraint and is not called use:`,
  "14:_": `And they do not have a lechi, etc. For if there were a lechi it would be complete reshut ha-yachid, for lechi is because of partition; and if there were a korah — for Rambam it is not a partition but for recognition — nevertheless it would be reshut ha-yachid for moving within; and now that there is neither this nor that, we treat it as karmelit:`,
  "16:_": `A roof that projects, etc. The reason — since the roof became reshut ha-yachid through gud asik we do not say so (rather, the place where the partitions are recognizable:`,
  "19:_": `And all this is specifically, etc. Meaning in reshut ha-rabbim we say when it does not have four it is not karmelit but makom patur; but when standing in karmelit, even though it does not have four it is like karmelit — "the kind found its kind"; and there are those who disagree and hold that even in karmelit this is makom patur:`,
};
