export const t = {
  "2:_": `Each one must make an eruv. For since these others restrict, they also restrict those dwelling in the house where the homeowner has a hold. And the Beit Yosef wrote in the name of Maharik: even if there is a corner designated for the homeowner it is called a hold on the house. And see siman 382, seif 13.`,
  "3:א": `Only the two innermost. Meaning: they together give one eruv to those to whom the courtyard residents give, as stated in the latter part. And here he comes to exclude Shmuel in the Gemara — that the innermost alone gives to the eruv and all the others are considered a gatehouse for that innermost one. But according to R' Yochanan — an individual's gatehouse is not called a gatehouse; also the one before the innermost has the law of the innermost. And what is outside these two innermost ones is called all gatehouse since many tread there. And the Magid wrote that these inner ones are only obligated if they divide with partitions reaching the ceiling. And in my humble opinion it is not so — for here there is no distinction between reaching the ceiling or not, for the entire hall is considered as one house for all matters since they have only one opening, and they have no eruv obligation except when there are other residents in the courtyard where they make the eruv — then the entire hall gives one eruv, meaning the two innermost give it even if their partitions do not reach the ceiling, and the rest are exempt since they have only one opening. And if you ask: when partitions do not reach the ceiling they are exempt — how much more so the entire hall should give nothing to the eruv that the other courtyard residents give — this is certainly not so, for the entire hall is not better in having only one opening than what he mentioned in the latter part where there are many openings and partitions do not reach — at least one eruv is required where there are residents, for we hold: since these restrict, these too restrict. And if two inner ones have partitions reaching the ceiling, nevertheless they give only one eruv since they have only one opening. Only in the latter part where each has a special opening — then if partitions reach and there are courtyard residents, each is obligated separately; if partitions do not reach, they all give only one eruv, meaning the two innermost as in the beginning when there is only one opening. And therefore he did not mention at one opening any distinction at all between partitions reaching the ceiling or not — all this appears simple. And the Magid, in passing, was not precise to exempt the inner ones when their partitions do not reach the ceiling.`,
  "3:ב": `Each one has an opening to the courtyard. In Semag and Semak they wrote for R' Huna.`,
  "3:ג": `Each and every group must give, etc. For since those courtyard residents restrict, they also restrict those in the hall, and those in the hall themselves are divided since the partitions reach the ceiling.`,
  "3:ד": `They are as joint. Meaning: then they all give one eruv.`,
  "3:ה": `Even though each has one opening, etc. The reason: since they all use the homeowner's for baking and cooking and everything, they are all considered as eating and sleeping in one place. And even though they have an opening toward the public domain, they are called members of the homeowner's household. And further: he does not lend them his rights to restrict him — so Tosafos. And the Beit Yosef wrote that the main permissibility is through combining the second reason specifically, and one should not rely to permit because of the first reason alone where the second reason is not applicable.`,
  "4:_": `Since no partition separates their eating place. Meaning: even though each eats at his own table, nevertheless since there is no partition between table and table, it is considered one place.`,
  "5:_": `And this applies when the courtyard residents give, etc. For since they needed an eruv, we say: since the other residents restrict, they too restrict.`,
  "7:_": `The two innermost, etc. Meaning: both give one eruv since they have only one opening, as stated above in seif 3.`,
  "8:_": `Except for thirty days. It implies more than thirty days restricts. And this deals with an individual dwelling in his father's place. But in a place where there is a community and they made eruv chatzerot orally as is our custom — then he is exempt also in this, since the court's heart stipulates on all who will be added as residents, as stated in siman 366, seif 9. And see end of siman 368.`,
};
