/**
 * One-shot: writes magen_avraham_en_parts/01.txt … 45.txt
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(__dirname, "magen_avraham_en_parts");

const en = [
  `Forbidden to him forever. It implies in Rashba (siman 375) that the pot is likewise forbidden.`,
  `Immediately after Shabbat. Specifically for a gentile doing [the work] we require “kedei she’asu,” lest we suspect one might tell him to do it — but a Jew would not listen even to Rashi’s reason that one not benefit from Shabbat labor — siman 319 — still here it is permitted because in an uncommon matter they did not decree [Tosafot Chullin 15a], unlike Bach: if it was Motza”ei Yom Tov it is forbidden because Shabbat does not prepare for Yom Tov [Lekutei Mahari”v siman 2]. Even Ha’ezer siman 102: if that substance mixed with others it is nullified and is not “nisraf labechirut” like terumah — see there — and it requires analysis: the case is not like terumah proof — terumah is not “nisraf” for anyone: for a kohen even today permitted; for Yisrael forever forbidden — but here once the name of something that is “nisraf” for others applies to him, for him too it is not nullified as Bikkurim chapter 3: if bikkurim mixed — forbidden even to zarim even though for them it would be “she’ela” since for kohanim it is “nisraf” — zarim forbidden — so Ra’avad and Rambam in Mishnah commentary and in his work chapter 4 Bikkurim; however Rosh wrote it is not “nisraf” since forbidden to zarim — still one should be stringent; what Yoreh De’ah siman 102 says perhaps speaks when mixed after Shabbat — then truly like terumah — this is main; and even if Rambam commentary implies specifically mixed to kohen forbidden to Yisrael — in Mishneh Torah it does not imply so — and his commentary words can be read thus. It appears to me that one for whom it was cooked has the same law as himself — Yoreh De’ah siman 99:5 — same reason because of penalty; however from Rabbeinu Yerucham there it implies only there we suspect telling gentile to nullify — but here in any case must wait kedei she’asu when gentile cooked — and for Jew we do not suspect “adam choteh,” Rema 103:1.`,
  `And unintentionally. Doing on a sage’s instruction is called unintentional; same if one forgot [Radbaz Bayit 26 chelek 2].`,
  `He fell ill that day. Even though the animal was muktzeh from shechita prohibition — still permitted because we rule like Rabbi Shimon: muktzeh from prohibition only when actively rejected, e.g. lamp lit on it [Maggid Mishneh chapter 2]; difficult — then muktzeh from attached produce should be permitted when fruit fell? Answer: there reason is lest climb and detach — beginning Beitzah — see Beit Yosef more reasons.`,
  `Raw on Shabbat. And without salting [Tur]; Even Ha’ezer siman 67:2 that rinsing is required; and see siman 325:1.`,
  `Lest he increase. This is Torah prohibition when he increases for him even before putting pot on fire; some say rabbinic — Rema.`,
  `Even if he cooked, etc. But after Shabbat permitted immediately [Shach]: reason — since gentile cooked permissibly one need not wait kedei she’asu.`,
  `Because it grows. Discusses fruit not finished cooking [Beit Yosef]; but if finished cooking we do not say “grows” — else why need first chapter Beitzah to forbid attached lest climb/detach or muktzeh — see Tosafot pushed there — should be because grows — rather when finished cooking no longer grows — then preparation helps; so Achronim analyzed Tosafot Bava Kamma 69a about what grows nullified in majority; Shach; Beitzah Tosafot 37b implies this is not muktzeh even for Rabbi Yehudah — animal also “grows and goes” and permitted shechita on Yom Tov — see Tosafot.`,
  `That cooking is forbidden. One who cooks with fire derivatives is liable.`,
  `To bury in sand on chol. Even from erev Rema 256:3; even to roll on sand so it roasts forbidden [Rosh]; question why Tur omitted we rule like Rabba [Bach]; appears Rosh follows Rabbi Yehudah — see — but we rule like Rabbanan — obvious forbidden — decree fire derivatives — Ran — still Responsa Rashbash permitted roast on hot roof from sun — not confused with fire — not compelling — Taz argues; Yerushalmi explicit forbidden; Rambam: cooking in Tiberias hot springs exempt — like sun derivative — Gemara; Mishnah Negaim chapter 9; Sanhedrin says leftovers from flood — perhaps still sun derivative; Ran wrote forbidden to place food on Tiberias springs — erev permitted; inside forbidden siman 326:3. Rambam chapter 9: meat on coals if roasted like figs liable — half-cooking Ra’avad; Rambam not liable half-cooking until whole meat half-cooked. Melting metal types or heating metals until charcoal; waxing wax or milk or tar and sulfur; cooking earthenware until pottery — liable — rule: burning hard body or hardening soft — liable — see this siman — question chapter 12 Rambam heating iron to forge liable kindling — Ra’avad cooking — Maggid Mishneh resolves — did not note Rambam contradicts — question — can distinguish.`,
  `There is an issue of cooking. Know: all laws forbidden because of cooking — even to put on stove/oven before heating forbidden — end siman 258.`,
  `It cooled. Beit Yosef — implies anything hand recoils called boiling — Magen Avraham siman 6; Rivan: if not cooled even if changed from boiling permitted — see Hagahot.`,
  `Some say only, etc. Bach ruled first opinion — see Magen Avraham.`,
  `Permitted to soak. Even kli rishon — siman 15 no cooking after cooking — Tosafot Mordechai Ran — unlike Bach stringent — Shulchan Aruch wording: if not cooked erev only soaked in hot — forbidden soak hot on Shabbat — good to be stringent if hand recoils from hot water.`,
  `They rinse it. Meaning pour from kli sheini [Even Ha’ezer: even wet item]; forbidden to soak even kli sheini — appears like cooking — unlike spices siman 9 — spices sweeten pot — not like cooking [Tosafot 39; Shach Bach]; appears onion law like spices for taste — see Rema.`,
  `Any hard item. Same salted item unable to eat without rinsing [Beit Yosef first explanation]; Gemara: if rinsed liable.`,
  `Because of cooking. Even though no cooking after cooking — still cooking after roasting — same roasting after cooking — therefore forbidden put cooked item by fire without gravy [Piskei RaKn”t Ra’avan Semag]; but all agree no roasting after roasting — roasted item permitted by fire even if cooled — same baked; cooked item permitted soak hot siman 4.`,
  `Even kli sheini. Some things cook in it — we are not expert — other things also be stringent siman 9.`,
  `They permit kli sheini. Hold kli sheini does not cook — per siman 4 Tosafot should be stringent — appears like cooking — those lenient rely Tosafot second answer — Shulchan Aruch — be stringent.`,
  `Even kli rishon. Since dry — no cooking after baking.`,
  `Hand recoils. See siman 4 and 15 Hagahot — need not Aruch HaShulchan words.`,
  `In dough. But spreadable item forbidden siman 314:14:11.`,
  `One may not leave, etc. Dry item permitted — see Magen Avraham.`,
  `Forever forbidden. Like placing on stove lechatchilah Shabbat [Rivan]; therefore per siman 258:2 if removed from stove after dark may put on pot — see there.`,
  `Like placing on stove. Even item without cooking issue forbidden on stove — decree lest stoke.`,
  `First view primary. Since pot interrupts — not like stove — there pot stands on fire [Maggid Mishneh ch.22]; question why Rav Beit Yosef did not decide permit siman 67 — he himself siman 258:3 — answer: only roasting permitted lechatchilah on cleared stove — cooked food forbidden on stove (pot better than stove — proof) — even hot without cooking — decree lest put when cold — permitted only chazarah — so Rivan — still can lenient: Maggid Mishneh implies pot interrupting better than cleared stove — permit hot dish.`,
  `Metzamek veyafeh lo. Rivan wrote — Rema Hagahot siman 4 — question: Rabbeinu Yerucham plain siman 4 unlike him — implies even metzamek vera lo cooking if cooled — forbidden put on kettle — why wrote metzamek veyafeh lo — question — perhaps relied what wrote here.`,
  `Such that hand recoils. Appears if no recoiling permitted — regarding prohibition/permissibility some forbid — see Taz kelal 57 — swallowing emission — some forbid kli sheini — but all agree not cooking; Yerushalchi distance kli rishon even no recoiling — Teshuvot Taz Rema 94 in Taz Rashbash.`,
  `Ox meat. Granted meat does not cook — moisture in it cooks [Tur].`,
  `Blood in it. When rinsed after salting — else still forbidden blood in salt — unlike Bach; Rav Beit Yosem plain only while salty salt aids cooking — Bach Rivan; Even Ha’ezer siman 68 — Bach decided like Rema — final Ra’avan wrote even salted anew — retracted first words [Bach] — see RaMaZim Tur Taz kelal 1-2.`,
  `Salt nullifies in 60. Even though “for taste” not nullified — here zuzei — presumably salted erev — even “nisraf” not nullified — nullified before forbidden — melts immediately — not cooked immediately — needs cooking like ox meat — must say salt put now insufficient separate from yesterday salt — if enough taste forbidden Yoreh De’ah 87; Mishnah Orlah chapter 2; Avoda Zara chapter 5. Appears salt made from boiled water no cooking — no cooking after cooking — see siman 15.`,
  `Forbidden to put, etc. If poured — peel forbidden cooked Shabbat — Rabbeinu Tam from mishnah Shabbat — see Tosafot — obvious even one who says kli sheini swallow emit — only item that cooks forbidden — mishnah but put in bowl Even Ha’ezer siman 68.`,
  `Full of hot water. Even Tiberias water forbidden put cold in tub fed from spring — take with kli sheini then put [Gemara].`,
  `It is kli sheini. Since for bathing presumably very hot — cold mixed cooks [Tur]; Maggid Mishneh like Bach unlike Beit Yosef — see there.`,
  `But one puts. Even pour kli rishon into cold — lower overcomes upper cools [Tur]; even though forbidden pour on spices siman 10 like kli rishon — here different — mixes hot cold heat nullified since cold majority — Tosafot Shabbat Ran Tosafot Pesachim 40b; appears forbidden put hot meat chunk into cold gravy — not mixing — cooks peel — Yoreh De’ah 91:4 Gemara Pesachim 76b.`,
  `Majority. We do not say vessel combines — unintentional not psik reisha — Maggid Mishneh: anything unintentional not psik reisha — when intends melacha when not intends no melacha — not like trimming splinter — even Rabbi Yehudah unintentional — one intends combine some say Torah some rabbinan — see Maggid Mishneh chapter 20; siman 334; siman 316:3.`,
  `Eaten as live. Still forbidden near fire — far even not edible raw permitted — therefore forbidden put iluntis or lead vessel near fire if close enough melt/burn — see siman 43 — can answer: there does not want burn/melt — unintentional.`,
  `Permitted lean opposite bonfire. Like leaning on stove permitted — even nothing between — sages required distance — recognition — will not stoke — Rosh.`,
  `Even cooled permitted. Holds no cooking after gravy even boiled cooled.`,
  `Where hand recoils. Levush text error should read where no recoiling — where recoils forbidden cooking Rabbeinu Yerucham oil — not difficult here since already cooked dry no cooking siman 15 Rema 258:5 explicit; Mordechi lenient permit even recoiling — good avoid recoiling — pastete — not Beit Yosef oil question; Kol Bo explicit Rabbeinu Mordekhai; Gemara Rashi 45a soak hot to soften — even after soft still dry law — same fat — Mordechai Kol Bo concerned Rabbi Bechor — therefore not recoiling lest melt much flows — far — Rabbeinu Yerucham; Semak hagahot roast pastete same.`,
  `All the more pot that has, etc. permitted — still forbidden stringency cooking siman 15.`,
  `Some stringent. Fat floats visible — nolad — unlike snow permitted siman 320:9 — melts in water not recognizable — implies bedieved forbidden eat fat nolad — still pastete permitted fat absorbed — Rabbeinu Yerucham warm meat; perhaps forbidden fat returns absorb pastete Yoreh De’ah 113:3 — bedieved lenient Rema. Appears permitted put pastete before oven heated siman 258 — putting pot before heating exempt forbidden — more here some permit after heated — at least before heating — not lenient before audience — use gentile; Rambam chapter 9:1 one brings fire wood pot water meat stir — all liable cooking — one puts pot water fire wood — last two liable (but fire putter not liable if fire would die — wood needed) — first case both fire wood together [Ri bar Rav] — must discuss brought flame not lit — if lit liable kindling — Rashi moving coal liable kindling — see Rabbi Levi Chibbat siman 21; Maggid Mishneh: stirring liable only first stir — after boiling without stir exempt — Ramban Rashba — certainly fully cooked stirring exempt — Beit Yosef siman 258 Kol Bo stir liable even fully cooked while on fire — see there.`,
  `Forbidden stir. Because dyeing.`,
  `Lechatchilah, etc. People permit legumes removed with spoon — unavoidable — rely Rema 258:4.`,
  `Opposite bonfire. Not literal — same boiling recoiling siman 5 and 29 — Rashi poskim Yoreh De’ah solid even kli sheini cooks — roasting — appears fat permitted smear — no cooking siman 15 — no nolad since not visible — provided not crush by hand — little by little melts itself — question visible like pot with gravy — question.`,
];

if (en.length !== 45) throw new Error(`Expected 45 entries got ${en.length}`);
fs.mkdirSync(dir, { recursive: true });
en.forEach((text, i) => {
  const fn = path.join(dir, `${String(i + 1).padStart(2, "0")}.txt`);
  fs.writeFileSync(fn, text.trim() + "\n", "utf8");
});
console.log("Wrote", en.length, "files to", dir);
