import { readFileSync, writeFileSync } from 'fs';

function fixLines(file, fixes) {
  let t = readFileSync(file, 'utf8');
  const lines = t.split('\n');
  let count = 0;
  const result = lines.map(line => {
    for (const [start, replacement] of fixes) {
      if (line.startsWith(start)) { count++; return replacement; }
    }
    return line;
  });
  writeFileSync(file, result.join('\n'), 'utf8');
  console.log(`Fixed ${count}:`, file.split('/').slice(-3).join('/'));
}

const BASE = 'C:/Users/binya/Documents/Shulchan aruch/newtry/YD_001/output';

// siman_153/beer-hagolah
fixLines(`${BASE}/siman_153/beer-hagolah/part-001.txt`, [
  ['Change the Starwork page as "B:', 'Mishnah Avodah Zarah folio 22b.'],
  ['The name of the second:', 'There in the mishnah.'],
]);

// siman_153/beur-hagra
fixLines(`${BASE}/siman_153/beur-hagra/part-001.txt`, [
  ['There is no morality as well. B:', 'One may not hand over, etc. Folio 15b.'],
  ['He was a star worker. Thor and Rashi, but the Rambam ruled the following:', 'He belonged to a gentile, etc. Tur; and like R. Yosi; but Rambam ruled like the first opinion.'],
  ['Even they are many. G-d is called "B":', 'Even if they are many. Gemara there 25b.'],
]);

// siman_155/baer-heitev
fixLines(`${BASE}/siman_155/baer-heitev/part-001.txt`, [
  ['Epicorrus. P. is an epic star worker for many. The Bible:', 'Apikoros. Meaning a gentile physician, even if he is expert for the many. The Rosh.'],
  ['hanging. The Bible writes that who does not even say in meaning, but that is how we detest from the meaning of His words, and He is in the same water or Ilan, and that the work of the stars says, "Take from those who are forbidden from the name of Hashem\'s work is when there is nothing but those who say that Hashem\'s work is forbidden, but when there is no more and no one has ever said of the work of stars." "Third:', 'Hanging. The Bach wrote that even if he does not say explicitly — but this is how we learn from the implication of his words. And he is of two ways: first, when those waters or that tree are more available and the gentile says "take from these" — forbidden even if he did not say explicitly "take from those of idolatry"; the second is when only these are available and he said "take from those of idolatry" — also forbidden. There is only a leniency when they are not more available and he also did not say "take from those of idolatry" — unlike the Shulchan Aruch. And to me it seems the Mechaber concurs. Shach.'],
  ['Even. You have agreed to be the first minister and the UN. "Third:', 'Even. The consensus of the decisors is like the first opinion, and so too Issur VeHeter. Shach.'],
  ['There is no. Even through the hysteria and as the rebeller to eat a sick animal milk that has no danger and who is a healthy person, be careful and not for a healthy person to make him bathe in danger of drinking. or ". But the patient is allowed to know the stars in this manner, and to the workers of the work of stars, and to the S.C. in the G-d, what is difficult for the Bible and the Bible:', 'There is none. Even the Mordechai wrote it is permitted to eat raw fat even for a sick person without life-threatening danger; however a healthy person should be careful; and also it is forbidden for a healthy person to make a bath from their ordinary wine — for anointing is like drinking. Issur VeHeter. But for a sick person it is permitted, for gentiles nowadays are not practitioners of idolatry. And see below siman 108 seif 5 in the Hagah where the Shach raised a difficulty — see there.'],
  ['(Lycott) is no danger. Instead of danger, it is not possible for the first creation of the United States, but also for the last reason that it is made possible for pleasure because of the work of the stars, and it is not permitted, but because of their daughters and the Lord, when it is forbidden, and in all the prohibitions of Hashem\'s creation, it is forbidden to do so because of the work of the stars', '(Likkut) is no danger. In place of danger it is not possible — not for the first reasoning in seif 2, but also for the last reason — that it is permitted for benefit because of idolatry; and it is not forbidden except because of their daughters; and when it is forbidden as in all idolatry prohibitions, it is forbidden'],
  ['And it is forbidden only to drink, but not to do so, but rather, as a result of Hashem\'s promise', 'and it is forbidden only for drinking, not for benefit, as stated siman 134 seif 2 (end).'],
]);

// siman_155/beur-hagra seif 1 marker ג
fixLines(`${BASE}/siman_155/beur-hagra/part-001.txt`, [
  ['Not a quaint. A. A. is called "A":', 'That he is not, etc. Gemara 27a, 28a.'],
  ['And all the Maccabees are. "Essss" every blow and a b', 'And all who let blood, etc. Tosafot s.v. kol makah; and Shach.'],
  ['My soul is in the fire. His intention is to give him a name for his life:', 'For his life, etc. in this. His intention refers to what Tosafot wrote there s.v. lechayei, etc.'],
  ['It will not be taken as a. Jerusalem is an intriguing nature in danger and in the daughter of a kind of medicine that makes it from the pygine and the danger is to get them from the Dalai Lau:', 'That he should not take, etc. Yerushalmi: that preparation is dangerous — explained in Torat HaAdam as a type of medicine made from poppies, and there is danger to receive from them the theriac, etc.'],
  ['And if he\'s called. Jim is there:', 'And if he is, etc. Gemara there.'],
  ['And yes, no. A.J.C. (J.A.) is adversity even to understand and order:', 'And likewise forbidden, etc. Gemara end of chapter 7 of Shabbat (75a) — astrology is forbidden even to understand and to teach.'],
  ['P.S.A. The fire there:', 'Even though, etc. The Rosh there.'],
  ['I will not eat anything. [R.] In all the prohibitions of Hashem, we have no idea that a speech of Torah failure should not be healed in place of danger', '(Likkut) Provided he does not eat, etc. [Meaning in all rabbinic prohibitions.] The Ran in chapter 2 of Avodah Zarah — nevertheless regarding eating we have nothing, for perhaps they made them like Torah law not to be healed by them except in life-threatening danger (end).'],
  ['And so, as "the Lord." As a result of Hashem\'s promise, Hashem\'s promise is not to be done, but to Hashem\'s mercy, and to be given to Hashem\'s mercy, and to be given to them, and they have not yet seen that "Hashem is there."', 'And so, as permitted, etc. As stated there 66b; but Tosafot there s.v. Abaye wrote sprinkling is certainly forbidden, etc., and it is full benefit — and see siman 108 seif 8 in the Hagah where he wishes to distinguish between yayin nesech and stam yeinam; it does not seem correct; and the Shach already challenged him there s.k. 25.'],
  ['And every patient is so. As the P. B. B. B. B. D.C., and in medicine known as the P.D. (P.P.A.) in which a dog is decorated with a dog and a', 'And every sick person, etc. As stated in the last chapter of Yoma (mishnah 82a) according to experts; and so in known medicine as stated there (83a, 84a) — one bitten by a mad dog, etc. — learn from this.'],
]);

// siman_156/beur-hagra
fixLines(`${BASE}/siman_156/beur-hagra/part-001.txt`, [
  ['But instead of where he is. He said, "And he did not care for him, and he did not care for him."', '(Likkut) But only in places where they are found, etc. As stated there; and he thought the paths, etc.; and he acted and did not regret except regarding the words of R. Meir (end).'],
  ['And there\'s a h. "I will be like a quaint." The name of the Submarine:', 'And there are those who, etc. Like R. Meir, from what is written there 29a "may it come to me," etc. Tosafot there s.v. hamistaper.'],
  ['It is not called. Jerusalem P.S. for the work of stars there and the addition of the PJ and the High Court:', 'Forbidden, etc. Yerushalmi chapter 2 of Avodah Zarah there; and Tosefta chapter 3; and Tosafot in s.v. cited.'],
  ['Or if he\'s broken." J.D. Starwork there:', 'Or if he has his hair cut, etc. Gemara of Avodah Zarah there.'],
]);

// siman_157/baer-heitev
fixLines(`${BASE}/siman_157/baer-heitev/part-001.txt`, [
  ['Wake up. It means that Israelis would practice strips from their shoes, not as the way of starworkers in this and that there is a Jewish side in the words that the way of Israel to be black strips and red-star workers so that the difference in its garments and in the U.S., Dr. Dakara wrote in the "ga that they will not be dressed from the worship of the Star Workers who is covered by Hashem." And he wrote more of this sentence: Aphrasa Delaper, who is a musician, who has been sentenced to the hour of exaggeration, and the Bible has stopped at the time of the exaggeration, even if he is not killed, and will not pass', 'Arka. It means that Israelites practiced with their shoe-straps not in the manner of gentiles in this; and there is a Jewish element in the matter — the way of Israelites is to have black shoe-straps and those of gentiles red, so that there be a distinction in their garments. And the Beit Yosef wrote that Rambam explains specifically in such a case that he should not wear a gentile\'s garment, which is a positive prohibition — see there. And he also wrote that this law of public also applies in the parallel case, equating it with a time of persecution; and the Bach ruled that at a time of persecution even if he intends for his own benefit — he is killed and does not transgress (unlike in public); and the Shach challenged him and wrote that his words are not conclusive and one can say safek nefashot lehakel; and so wrote the Taz; and if the decree was over the entire country, even though Israelites are included, it is not called a time of destruction.'],
  ['A) And he was given to him by the Bible and wrote, "And the Lord has no obligation to make it easier and so that if he has been exalted to all of his country, I will report that the Israelis are at all an hour of destruction:', ''],
  ['Fucking. And as a star worker, such as if his stature was turned into the work of stars as the Rashi:', 'To throw it down. And regarding a gentile — such as if his stature was bent to bow to idolatry — so wrote the Rosh.'],
  ['The exaggeration. The Bible wrote that all who were killed in the name of a Jew, but if they were ordered to learn about anyone who would not wear a Star worker\'s costume would be killed and would not pass as much as Naji and D.C. wrote in the name of J.D. D. D. Even in the time of destruction, it was not forbidden only when the workers knew him and ran away, but to wear a garment that was made of the work of stars', 'The decree. The Shach wrote — meaning they decreed that whoever is called by the name of a Jew shall be killed. But if they decreed destruction on whoever would not wear the garment of a gentile — he is killed and does not transgress. So wrote Nekudot Yosef; and in Darkei Moshe he wrote in the name of Terumat HaDeshen that even at a time of persecution it is only forbidden when the gentiles recognize him and wish to compel him to transgress; but to wear a garment made in the style of gentile clothing is permitted, for there is no desecration of God\'s name since the gentiles do not recognize him.'],
  ['and snow. The letter of the book is simply a report that must be answered by Dao who is subject to the prohibition:', 'And that he thought. The Taz wrote: it is plain that he must nevertheless repent over this, for he himself intended to transgress.'],
  ['Saving. The letter of the High School is an opinion that brings in the S. K. K.C. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S.D. S. S. S. S. S. S. S. S. S.D. S. S. S. S. S. S. S.D.D. S.D.D. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S. S If a lawyer is allowed to commit an offense to save a person who wants to try to convert, and so on, see the SS report:', 'Saving. The Taz wrote regarding the view brought in Shulchan Aruch siman 155 seif 3 that forbids even anonymous branches because of "it shall not cling to your hand" — one should forbid here too. The law of whether one may transgress a prohibition in order to save a fellow whom they wish to coerce to convert and similar — see Orach Chayyim end of siman 307 and siman 328 seif 10.'],
]);

// siman_157/beur-hagra
fixLines(`${BASE}/siman_157/beur-hagra/part-001.txt`, [
  ['Apart from a . There is a name in Sanhedrin and Dr. Ishmael Flyg, John D.M., and his son, and his father, and his wife, and his wife, and his father, and his father, and his father, and his father, and his father, and his father, and his father, and he said:', 'Except, etc. There in Sanhedrin; and although R. Yishmael disagrees we rule like R. Yochanan who said they counted and concluded; and so the sugya in chapter 2 of Pesachim and chapter 2 of Ketubot (19a) and the last chapter of Yoma — learn from this.'],
  ['If he is in a sage. Jim there:', 'If he is in private, etc. Gemara there.'],
  ['A. on a qua. Name:', 'Even upon, etc. There.'],
  ['Israel alone. From your mouth there and Esther Prascia was beaten and not the fruit of the king\'s model was:', 'Upon Israel alone. From the fact that it challenges there "but Esther was in public" — and does not challenge that it was a royal decree.'],
  ['Even so, and not so. Jim there:', 'Even so, and not so. Gemara there.'],
  ['And even the worker has no stars. Hashem\'s people are not allowed to be saved from Hashem\'s people, and they are not Hashem\'s people, and they are not Hashem\'s people. He said, "It\'s hard to write, and it\'s hard."', 'And even if the gentile, etc. For even to be healed from those three matters is forbidden; and we say in Sanhedrin there (75a) an incident, etc. — granted a married woman, etc.; and even though for his benefit; and in the last chapter of Yoma (82a) a pregnant woman who smelled, etc. — there is nothing that, etc. Ran in chapter kol sha\'ah — see there (who wrote it is somewhat difficult, etc., and these difficulties, etc.).'],
  ['And Duke is. Dr. Yosss D. D. D. D. D. D. D. D. and I will be required as \'V.\'', 'And specifically, etc. Tosafot Yevamot 53b s.v. ein ones, etc.; and Ketubot 3b s.v. velidrosh, etc.; and Sanhedrin there 74b s.v. veha, etc. — learn from this.'],
  ['And I\'m not able to escape like him. And even if you wish to rape as a "sevent" in the cellar, we will surely be able to do so. The Bible:', 'And specifically that he cannot flee, etc. For even if originally coerced, as stated end of chapter 4 of Ketubot (51b): these women who were seized, etc. — certainly abandon them, etc. The Rivash (end).'],
  ['It is not called, but k. At B.P., two students from R.J. have changed to the cover of their sons and daughters, as well as Hashem\'s children, but rather, Hashem\'s people, and Hashem\'s people, and Hashem\'s people, and Hashem\'s people, and Hashem\'s people, and Hashem\'s people', 'Forbidden, etc. but, etc. In Bereishit Rabbah chapter 82 two of R. Yehudah\'s students changed their attire, etc. — he said to them "My sons," etc. — evidently it avails only unless they ask them; and the Yerushalmi in chapter 2 says one can say "I am a gentile," etc. — the Rosh strained there; but it is a dispute in the Yerushalmi there between R. Bon and R. Chaga — see there and Terumat HaDeshen siman 197.'],
  ['And even by KW. I\'m going to send you to B:', 'And even so, etc. Nedarim 62b.'],
  ['And if he can do so. As a result of Hashem\'s creation, Hashem\'s promise was:', '(Extract) And likewise if he can, etc. As stated in Avodah Zarah 18b — another version in bishulei gentiles, etc. — and it was during a time of persecution.'],
  ['And in the same way. As an artist', 'And likewise on the road, etc. As the incident of Yessi (end).'],
  ['And as a "six." The Bible in KGB:', 'And all this, etc. See the Rosh in Bava Kamma 113a.'],
  ['(Luke) and `A. Despite the first paragraph, Kenneth S.C. said, "No other prohibitions will be killed and will not be passed and the IDF will be killed."', '(Likkut) And some say, etc. For even according to the first opinion in siman 155 seif 2, nevertheless it is no less than other prohibitions that at a time of decree one is killed and does not transgress — and see what was stated above seif 1 (s.k. 7) the dispute of Rashi and Tur (end).'],
  ['That is, Hashem of Israel. Name:', 'That is, etc., of Israel. There.'],
  ['And yes, yes. A gift there:', 'And likewise, etc. Mishnah there.'],
]);

// siman_157/pitchei-teshuva
fixLines(`${BASE}/siman_157/pitchei-teshuva/part-001.txt`, [
  ['They will be sent or killed. In the book of the wise men in the opening of the Starwork Acts, which he said to him that if he was not killed, he would say that he would go and that he would not be killed, and that he would not be forced to say that he would be deprived of the death of any kind that he wanted to kill him. "You have nothing to do with your soul and no doubt."', 'They shall transgress or be killed. See the book Mishneh Chachamim in the introduction to the Laws of Avodah Zarah who was uncertain whether it is specifically in this case — that they told him to transgress and if not he will be killed — that we say he transgresses; or perhaps since the Torah freed one who is compelled, etc.; but if they come to kill him for some matter and do not come to compel him to transgress, God forbid he should say to save his life he will transgress some matter — for such compulsion is not called ones when their intention is to kill him since they do not intend to compel him to transgress. Or perhaps not — since we hold there is nothing that stands before pikuach nefesh, and even doubt pikuach nefesh, because of "and he shall live by them" — what difference whether the danger comes from Heaven or from a person — in any case he can save himself.'],
  ['It is an exaltation of Hashem\'s judgment and life in them what I have brought him out of heaven and what is next to me by man in every matter can save himself and it would seem to be rejected if he is satisfied with his passing if he is exploited because of the punishment of his death, he would doubt that he would not raise anything clear. [See T.J. L.C.] and look at the surprise of D.J. on the additions:', 'And it would seem that even if he is uncertain whether he will be spared by transgressing from the death penalty, it is a case of doubt regarding pikuach nefesh — see there that no clear ruling was reached. [See the Taz below siman 179 s.k. 4; and see the Haflaah Ketubot 4 page 19 on Tosafot s.v. de\'amar mar].'],
  ['"Damn as" A thick quaint, and see the book of cedar trees, which is a sign of a long-term cheque. And in the book of Israel\'s glory, it is possible to bring itself to provide a common detrimental danger that it is not common, and that it is not possible that the guardians who are forbidden to die in the city should be worthwhile', 'Intentionally, etc. See the Baer Heitev s.k. 1; and see the book Atzei Arazim in Even HaEzer siman 16 s.k. 7 at length. And in the book Tiferet Yisrael on the mishnayot chapter 1 of Berakhot mishnah 3 he wrote that nevertheless it is permitted to place oneself in possible danger where harm is uncommon, and a mitzvah one is engaged in protects him — proof from R. Akiva who placed himself in possible danger for netilas yadayim, relying that the prison guard would not let him die of thirst, as stated in Eruvin folio 21 — see there.'],
]);

// siman_157/turei-zahav
fixLines(`${BASE}/siman_157/turei-zahav/part-001.txt`, [
  ['Even on a pile. It means that Israelis would have been driving strips from their shoes, not as the way of star workers in this:', 'Even upon the shoe-strap. It means that Israelites practiced with their shoe-straps not in the manner of gentiles in this.'],
  ['"Do not have any kind of shit." Dea also the Starworkers can cancel it from it such as they will be identified in perception, and will therefore be eliminated from it:', 'Not to fulfill a positive commandment, etc. Yoreh De\'ah — also gentiles can remove it from him, such as if they place him in prison, and automatically he will be prevented from that positive commandment.'],
  ['"Crying skin." Israel does not do anything only that gives him something that the Starworker uses for his night:', 'Lifnei iver, etc. The Israelite does nothing — only gives him something that the gentile uses for his idol.'],
  ['She must be seven years old. It seems to me that the seven-year-old son of Dovdin had no need for his death, but rather from the law of the kingdom that rebels against him from the Lord, forbids him if he is together and believes in our times that he is criminal and rebelled against his kingdom, and that he is held in them, such as he is concerned with the beauty or the other things in which he has a danger of his own nature', 'Liable to death like Sheva ben Bichri. It seems that the reason Sheva ben Bichri was specified — although by Torah law he was not liable to death but only by royal law for rebelling against David — nevertheless they hand him over if they seize him; and from this, even in our time, one who sins and rebels against his kingdom they hand over; and the same for other transgressions such as engaging in forgeries or other matters that pose danger — plainly they hand him over, and it is proper to hand him over even if they did not seize him, since he is like a rodef to other Israelites through his evil deeds done negligently — so it seems to me.'],
  ['This is what I believe in, in the place where there is no morality in which there is no connection between the woman or the rest of her life, or even for the sake of the cursed, that they are worse than her husband, who is not afraid of her or her husband, who is not afraid of her death, and who is not afraid of her', 'And further it seems to me that where they are not permitted to hand him over there is no distinction between handing him over for death or other suffering or even for money — they are clearly worse than death as we say in Aleh Ne\'arot (folio 33): had they flogged Chananiah Mishael and Azariah they would have worshiped the image — learn from this that suffering is worse than death; and we find that lashes are more severe than death; and proof that in the Yerushalmi it does not say the king demanded him for killing but simply "demanded him" — perhaps only for suffering alone;'],
  ['A splatter in a thine saying about it called a priest who fell in the hands of star workers again, there is no mercy on him', 'and we should be stringent out of doubt; and even regarding money we find in the chapter HaGozel batra that the verse says "like a wild ox in a net" — once he fell into gentile hands they no longer have mercy on him — so it seems to me.'],
  ['And yes, women. In the name of the Lord, he wrote a model for women, if one woman were together, and it was seen as a model of a woman, but rather a DNA, one of them, and said, if you did not let the uncleanness of it, then all of you would be killed by a woman, and if they were not killed in any way', 'And likewise women, etc. Beit Yosef in the name of the Ran wrote that also regarding women, if they seized one of them they hand her over; and it seems this too depends on the dispute whether liable to death like Sheva ben Bichri that Rama mentions — according to the second opinion seizure of a woman does not avail; but it seems to me that if they seized one of them and said if you do not give her to us to defile her we will kill all of you — plainly seizure avails and they hand her over, since there is no act on the woman\'s part and it is not in the category of gilui arayot, and therefore she herself is not subject to "be killed and do not transgress" — therefore they hand her over if they seize her — so it seems to me.'],
]);

// siman_158/beer-hagolah
fixLines(`${BASE}/siman_158/beer-hagolah/part-001.txt`, [
  ['In the words of the Rambam, the work of the stars is called "Worship of the Holy One."', 'The language of the Rambam from the baraita Avodah Zarah folio 26.'],
  ['My father was there:', 'As Abaye explained there.'],
  ['Thor and the Rambam in the Book of Humans from Breithin mentioned above in paragraph 11:', 'Tur; and so wrote the Ramban in Sefer Torat HaAdam from the baraita in Gittin, which I cited above in siman 121 seif 12.'],
  ['M.M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M.D. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M.M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M.M.M. M.M.M. M. M. M. M. M. M. M. M. M. M. M. M. M.M.M.M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M. M.D.D. M. M. M. M. M. M. M. M. M. M. M. M', 'Statement of R. Yochanan to R. Abahu there, Avodah Zarah folio 26.'],
  ['There is a killer from Berberya there in the Talmud and there in the closing of the Bible and the morality of the Lord, and the morals of many of their friends, with the hands of the rapists, and the friends who have been accused of "conceiving" the sign of the Lord:', 'There in the Rambam, chapter 4 of Laws of Murder, from the baraita there in the Gemara; and it is there in the version of the Rif and the Rosh — "and the informers"; and Rashi explained "and the informers" are slanderers who hand over their fellow\'s money to violent gentiles. And the authors who omitted it relied on what is written in Choshen Mishpat siman 388.'],
  ['There is a name in the church and a name for it:', 'There in the baraita and as the Amoraim explain it there.'],
]);

// siman_158/beur-hagra
fixLines(`${BASE}/siman_158/beur-hagra/part-001.txt`, [
  ['(Lycott) the episods are. But Rashi and R.R. wrote between Israel and Star Workers and abroad in Berlin in Tel Aviv, but in Israel all the Starworker is a ransom, but in the work of the stars, a priest who is bound up in the work of stars and worshiped in the work of the stars', '(Likkut) The apostates, etc. But Rashi and the Ran wrote — both Israelite and gentile; and as written in Chullin 13b: nowadays, etc. — but among Israelites all who worship idolatry are apostates; but among gentiles — specifically a priest who is devoted to idolatry and worships it. And Tosafot in Avodah Zarah there s.v. eizehu, etc. (end).'],
  ['If he is in his hand, he will be with him. J. D. D. Starwork there, and there is Dr. Dalai Lao:', 'If it is in his hand, he is with him. Gemara of Avodah Zarah there; and Tosafot there s.v. delo, etc.'],
]);

// siman_159/baer-heitev
fixLines(`${BASE}/siman_159/baer-heitev/part-001.txt`, [
  ['arrested. It is because of the fact that he will learn from his actions and that he will be entitled to the darkness. "Third:', 'They forbade it. Because of a decree lest he learn from his deeds; but regarding a Torah scholar there is no such concern. Shach.'],
  ['interested. Because we can\'t be recognized in any negotiations if they don\'t negotiate with them, they don\'t belong to a Barbie who will learn from his actions to the rest of his negotiations. column:', 'The matter. Because it is impossible for us to earn a living in any commerce unless we transact with them — therefore the concern lest one learn from his deeds applies less here than in other commerce. Tur.'],
  ['from him. Because you don\'t drink and because before skin you don\'t have an obstacle:', 'From him. Because of lo tashich and because of lifnei iver lo titen michshol.'],
  ['forbidden. The Bible said, "We were the only ones who were at the time of the Rambam who had a few virtues and so on."', 'Forbidden. The Shach wrote — meaning specifically the Karaites who were in the time of the Rambam who had several good qualities, etc. — see there.'],
  ['forbidden. Even to Man, we were told to accompany the Lord, that he knew his son, and waited for him to rebel against him, but that he would grow up among the Starworkers, and that he had a son from the work of stars, and that he was like a star worker, and that he was a starved to him. "Third:', 'Forbidden. Even to one who says it is permitted to lend to a mumar — that is specifically to the mumar himself who knows his Master and intends to rebel against Him; but this one who grew up among the gentiles is like one who acted in error. And Nekudot Yosef wrote in the name of Rabbeinu Tam that it is permitted to lend to him at interest. And in Darkei Moshe he wrote that it requires study; and a mumar who has a son from a gentile woman — the son is like her and his law is like that of a gentile. And see Even HaEzer siman 16 seif 2. Shach.'],
]);

// siman_159/pitchei-teshuva
fixLines(`${BASE}/siman_159/pitchei-teshuva/part-001.txt`, [
  ['allowed to borrow. A. A.C., and I will see Hashem\'s presence in the Bible:', 'Permitted to lend. See Taz s.k. 1; and see the responsum of my ancestor the Panim Meirot part 2 siman 73.'],
  ['for a star worker. See the book of opinion written by Delaslav as a subject, which is not mentioned:', 'To a gentile. See the book Chavot Da\'at who wrote that to a Canaanite slave it is forbidden — see there.'],
]);

// siman_159/rabbi-akiva-eiger-yd
fixLines(`${BASE}/siman_159/rabbi-akiva-eiger-yd/part-001.txt`, [
  ['(Thomas) complete star workers to the D. By his daughter, D. D. D. D. D. D.D.:', '(Shach s.k. 5) Complete gentiles for all purposes. See Tosafot Yom Tov chapter 7 of Niddah mishnayot 3 and 4.'],
]);

// siman_160/beer-hagolah
fixLines(`${BASE}/siman_160/beer-hagolah/part-001.txt`, [
  ['Change the page by:', 'Mishnah Bava Metzia folio 75.'],
  ['M.M. M.M.D.:', 'Statement of Rava there folio 61.'],
  ['B.B.B.D., B.D., will add a page', 'Baraita of R. Yosi there folio 71.'],
  ['M.M. M.M.D.:', 'Statement of Rava there folio 61.'],
  ['The owner of the donations in the Bible and wrote there according to the GNU, who also pays for the Torah that the father was a reward for learning or the son near his desk:', 'Ba\'al HaTerumot in part 2; and he wrote there that according to our custom of also paying wages for Oral Torah study — all the time the father was paying the teacher\'s wage or the son was dependent on his table.'],
  ['Change the name and the column:', 'Mishnah there; and as Tur explains.'],
  ['M.M. M.M.R.D.:', 'Statement of Rava there folio 69b.'],
  ['The fire there:', 'The Rosh there.'],
  ['There is a bee on which side of these ways is seen as a warrior and forbidden, and as such, the children of the Lord are called Harab:', 'There — on which side of these paths is it seen as his agent and forbidden; and so wrote the students of the Rashba in the name of the Ra\'avad.'],
  ['In addition to this page, it is written on the ground and it is written:', 'Tosafot folio 71, beginning of 72b; and Shach.'],
  ['There in Mordecai and the IDF in response and column in the sign of the X', 'There in Mordechai; and the Ran in responsum; and Tur in siman 169.'],
  ['We will fight in part A:', 'Rabbeinu Yerucham in part 1.'],
  ['There is a dry tongue that the earth is dry and the rains are not removed:', 'Mishnah there. (°) Meaning dryness — that the land is dry and rains do not fall.'],
  ['Rambam in the Bible:', 'Rambam in chapter 5 of Laws of Lending.'],
  ['There is a page of the Lord\'s name and the Holy One in his judgments:', 'Tosafot folio 64b; and the Rosh there in his rulings.'],
  ['The G-d has a page called A:', 'Conclusion of the Gemara there folio 75a.'],
  ['His father\'s name is the Holy One, and as such, the Holy One is the end of the Holy One', 'Tur in the name of his father the Rosh; and so wrote the Rambam at the end of chapter 5 of Laws of Lending.'],
  ['From a dogma and so on', 'From the incident of Ravina and so forth as above.'],
]);

// siman_160/beur-hagra
fixLines(`${BASE}/siman_160/beur-hagra/part-001.txt`, [
  ['There is no such thing. Dr. A. D. Z. said, "Don\'t take a seat and it\'s just a few places:', 'There is no distinction, etc. Meaning even though it states "and if your brother becomes impoverished" — "do not take," etc. — and this is plain in several places.'],
  ['Like in every grill. Named in KGB:', 'Like every theft. Named in mishnah 103a.'],
  ['You need a quaint. There is a saying of Hashem\'s people, but when they pray to Hashem:', 'Needs, etc., provided, etc. Tosafot there s.v. aval, etc. per both resolutions for stringency.'],
  ['And if you are a quaint and a "dead." For the sake of Hashem\'s mercy, Hashem\'s promise is not to do with Hashem\'s mercy, nor is Hashem\'s promise that He has not been given to him, and that He will not be able to do so, nor is it not for him', 'And if, etc. and not like, etc. For granted with hire he owes him a dinar for his labor and what difference whether he pays in money or in work — unlike a loan; and the last reason holds that it is only forbidden when there is an addition in the matter of neshech or tarbis — unlike such a case; and proof from what is stated (75b in mishnah) all the days of drought, etc. even though there are short days and long days — because without neshech and tarbis it is only rabbinically forbidden and such was not decreed; see the Mordechai there. But the first reason is primary, for even speech is forbidden — and all this applies when he would not otherwise have done so.'],
  ['Or a qua. R. A. D. A. D. A. D. A.D. is permitted to teach him a salary as a C.C. Total:', 'Or, etc. Meaning even though regarding one who vowed benefit it is permitted as stated in Nedarim (mishnah 35b) — here since he derives benefit, for he is obligated to teach him for pay as stated above siman 245 seif 4. Sefer HaTerumah.'],
  ['Or finished. HANDWASHPL Place to DJ and CJ:', 'Or Gemara. Be\'er HaGolah; and see above siman 245 seif 6.'],
  ['And from me if you are. How did he give him a son:', 'And nevertheless if, etc. Mishnah 75b — how did he give, etc.'],
  ['and O\'D. This is the case, and even good. It is hard for him to take a vegetable from the market that he has given him his words', 'and even so. This is the case; and (Likkut) And even benefit, etc. In Yerushalmi end of chapter 5, 161a: severe is the ribbit — for even benefit is ribbit; for example if he said "buy me a vegetable from the market" — even though he gave him his money — this is ribbit (end).'],
  ['Oh, no, no. A. A.D. A.A. said on the way that P.D.A. would be called "S.A.," and that he was named "A.," and that he was called "A.," and that he said. But Mordechai and the G-d said, "I will give you a lot of money, and I will be able to do so, and I will not do it."', 'If he lent, etc. Even though in the Gemara it was said as a doubt, nevertheless we rule that we follow the original from what is stated there 62a "but a se\'ah," etc.; and Rashi there s.v. uvedinenenu, etc. (Extract) But Mordechai and Hagahot Ashri wrote that we are uncertain as stated in the Gemara there; but Nekudot Yosef chapter 1 wrote like the Rashba and Shulchan Aruch; and wrote that the reason the mishnah stated two se\'ah for three is that it is fixed interest unspecified without distinguishing whether it became more expensive or not (end).'],
  ['A.D. if they are. A. B.C. (A.A.A.) has been found', 'Even if, etc. Tosafot 71b s.v. matza\'u, etc. (end).'],
  ['And the interest was fixed. Dea Midan is and as a woman sanctifies them:', 'And the interest is fixed, etc. For it is in the law of a guarantor, and as a woman is betrothed with them.'],
  ['A.S. I am reminded of Hashem\'s mercy, and I am Hashem\'s mercy, and I am the same as Hashem\'s people', 'Some say, etc. For it is like give a maneh to so-and-so and I am betrothed to him — she is betrothed from the law of both of them, etc.; and not like the Bach; and the Taz also labored over this in vain.'],
  ['And yes, the rest of the house. My son and m there:', 'And likewise the rest, etc. Mishnah and Gemara there.'],
  ['Those who have to be." He said to him, "He who needs to be." He was praised by all the judgments of Hashem\'s judgment, and he has already achieved it', 'One who must, etc. His words are astounding — and see the Taz and Shach. (Extract) One who must, etc. It is astounding, for regarding all people the law is so as stated in siman 169 seif 25; and the Acharonim have already challenged this (end).'],
  ['The Custodian. His advice is nothing, and the hand of such orphans is not an exalted one:', 'The guardian, etc. For his stipulation made in prohibition amounts to nothing; and we are the hand of the orphans — it is as if they stipulated from the outset.'],
  ['The guardian is also a. Not in the capital of Dahl took nothing just as Sarsara is concerned. Name:', 'And also the guardian, etc. He is not in the reckoning, for he took nothing — only an intermediary of the sin. There.'],
  ['And who is so. by:', 'However, etc. See Shach.'],
  ['And from the ISA. SJ and the Gems there:', 'And nevertheless, etc. SeMaG and Hagahot Maimoniyot there.'],
  ['In orphans. The Bible concludes that it does not have an orphanage in it because it is engaged in ripening as women:', 'In orphans\' money. Beit Yosef concludes that a widow does not have the status of orphans here since she manages her own property like other women.'],
  ['As long as they don\'t grow up. And who is not his father wants to support him and to deal with his needs, he has no judgment on this in the name of the donations he has given:', 'As long as he has not matured, etc. However one whose father does not wish to support him and attend to his needs has no orphan status here. Beit Yosef in the name of Terumat HaDeshen siman 300.'],
  ['Chery. See the Gemara in the letter of the Bible, written in the name of Boley to harvest a Barbie satellite for a Shabbat feast or a feast, and read in the book of Bar Yaakov, whereby is here, and here is that Rabbi Darin and simply is:', 'Permitted. See the Magen Avraham in siman 242 who wrote in the name of Shibolei HaLeket: one may borrow at interest for the Shabbat meal or a mitzvah meal; and see the book Be\'er Yaakov there and here who wrote it means at rabbinic interest — and this is plain.'],
  ['As long as they don\'t grow. See the words of Hashem\'s covenant with Hashem\'s people, and they will be given to Hashem\'s people, and they will be saved from Hashem\'s promise of the Lord\'s promise, and they will be saved from the Lord\'s promise that He will be saved. A. B. S. B. G. B. S. A. B.A. is a sign, but it is possible to say that it is permissible to take away even from the heater that has been poisoned after the grass has increased', 'As long as he has not matured. See the Mishneh Lamelech chapter 4 Laws of Lending halachah 14 who wrote one should be uncertain regarding orphan money given close to profit and far from loss, where the recipient dealt in it until after the orphan was thirteen years old (not precisely so) — and if the orphan may take from the profit earned after he matured since the condition was set at the time of permissibility; perhaps we follow collection; and at first glance this resembles the case of siman 171 regarding a convert; but perhaps here it is permitted to take even from the profit earned after he matured,'],
  ['But close to the wage, this is not a prohibition at the time of giving that there is no prohibition, but rather from the beginnings of Hashem, that it would be near the wages and that there was no prohibition here, but because of the condition that the condition was, but in the rest of the prohibition on the part of the condition of giving it, and therefore it was forbidden to eat the conditions of the fruit', 'because close to profit there is no prohibition at the time of giving — there is no prohibition except from the two divisions together — that it be close to profit and far from loss; but with only one division there is no prohibition, for if it were close to loss as required, close to profit would be permitted; and so the reverse — it turns out there is no prohibition here except because of the condition; and since the condition was set at a time of permissibility it is permitted. But in other interest prohibitions where the prohibition is not from the condition side but from the giving alone — even if the condition was at a time of permissibility we follow the giving — therefore with mashkanta or Narshaan tenancy it is forbidden to eat the fruits or take the tenancy after he matured;'],
  ['Or to take the testicles after the magistrate and write more of the mercenary like a crystal worker, even according to the words of Dr. Hadddsel, from me even to what came up after he was removed from the grasses that he had circulated when he was a star worker, he was not proven to be the same and even though he had been exalted to the mountain if he had not had been removed', 'and he also wrote that registering the amount owed does not avail here as it avails regarding a gentile — even according to the Terumat HaDeshen who holds that registration avails even for what accrued after he converted — because that case is different: all that he registered while a gentile was completely permitted, for it was not apparent he would convert; thus even after he converted, he collects the interest because at the time of registration it was completely permitted. But regarding an orphan, if he registers even what will accrue after he matures, from the time of registration he creates a prohibition.'],
]);

// siman_160/pitchei-teshuva
fixLines(`${BASE}/siman_160/pitchei-teshuva/part-001.txt`, [
  ['But Barbie Darbnan. A. B. A. B. A.D., written by the Witnesses, does not go through Barbie Darin only because of before the skin of the Bible:', 'But in rabbinic ribbit. See Chiddushei Dinim who wrote that likewise the witnesses do not transgress in rabbinic ribbit except because of lifnei iver — see there.'],
  ['His science. See the Bible that Dr. Dudddda first wrote that he was not allowed to receive any more, but when he had already received and found an advantage of the IDF to return, and to the extent of the letter, he said:', 'Willingly. See Chiddushei Dinim who wrote that specifically lechatchilah it is forbidden to accept more when given; but when he already received and found an excess — he need not return it; and with this there is no difficulty from Choshen Mishpat siman 232 — see there.'],
  ['In this rest. A thick and accumulating an educational response in the "Simony" that raised as the mind of clothing and the t" that is not the rest of it at all, and in the S.C., it is possible to say that it is not called R.C. to be released in the words:', 'With this hetter. See the Avnei Nezer; and see the responsum Chinuch Beit Yehuda siman 63 who raised the view of the Levush and Taz that this is no hetter at all; and see there siman 64 where he wrote that nevertheless it is possible to say it is not called fixed ribbit requiring collection in court.'],
  ['It is forbidden to take away. And if he says to his father, the Lord is in favor of the burden of asking me for the loan, and if I don\'t find anyone who will make it possible for you to give them permission to give them to the words of the Zoro deo of their own land. And so, I think of you:', 'It is forbidden for the lender to take. And if he says to his fellow: here is a zuz as your wage for the trouble of seeking a loan for me, and even if I do not find anyone to lend me — it shall be yours; it is permitted for the agent to give it to the lender, for it is as if he gives his own money. So wrote in the book Chavot Da\'at — see there.'],
  ['To the Hellenic Falls. "Give me a great deal of bread, and tell your wife that she will accompany me from her husband, O Lord."', 'To such-and-such, lend me. See the book Lechem Rav siman 12 who wrote: one who says to his fellow "here is a zuz, and tell your wife to lend me money from her nichsei melog" — this is fixed ribbit, for the wife\'s hand is like her husband\'s — see there.'],
]);

// siman_160/turei-zahav
fixLines(`${BASE}/siman_160/turei-zahav/part-001.txt`, [
  ['If the bride is taken to his part, he will be called a quaint. In another person, he did not permit it, but all that was done in the prohibition should not be taken even if he had been killed a lot, but here is what was done in the prohibition, he was as if we were not harmed by the orphans, and as if nothing had been done at the time of the loan, and said to the benefit of the orphans that he had not received much of what he had done', 'If the orphan took to his portion so much profit, etc. For another person, he did not permit this — all that was done in the prohibition should not be taken even if the borrower earned much; but here what was done in the prohibition is as if it was not done to harm the orphans, and it is as if nothing was stipulated at the time of the loan; and for the benefit of the orphans we say, even though they did not stipulate for a permitted matter it is as if he stipulated,'],
  ['At the same time, Hanna has the right to be taken on the better side of this kind, if he is more than the guardian of the prohibition against which the harvest is not considered to be a bridegroom and as if he is not done at all and dressed in the book, he will not take any more than the harvest, and he does not care if he is not allowed to do so', 'and all that is permitted to take is valid. And it seems to me he takes half of all that the recipient earned, even much more than the fixed amount — only deducting his labor wages; since it is as if no stipulation was made at all, the orphan has the right to claim on the better side, as if it were stipulated that he take half, even if more than what the guardian fixed in prohibition — for that fixing counts for nothing, as if it was never done. And the Levush wrote that in any case he does not take more than the fixed amount; and this is very astounding — what do we care about the fixing, since it was done in prohibition it is as if it never was; and it is unlike a transaction done in prohibition which is valid, for there the transaction itself is as it should be only there is a separate prohibition — unlike here.'],
  ['We were half the salary as I wrote:', 'And this is what Beit Yosef wrote: as if he stipulated close to profit — meaning he takes half the profit, as I wrote.'],
  ['exempt from paying. According to them, they did not feed in the same rabbi and did not immediately take place, but rather the bride gives the guardian a widower or an orphan, and even a complete criminal in every manner that he does not have to return as the Gosal and feeds his children as "a rabbi and a guardian, because he is not a guardian, he gives the mind that he will be subject to himself, but to the sin of sin. In the name of the Lord:', 'Exempt from paying. For they did not stipulate for that ribbit and did not receive it directly from the borrower — rather the borrower gives the guardian who stipulated with him, and the guardian gives to the widow or orphan; and even in complete robbery in every such case they are not required to return, as taught: the one who robs and feeds his children — they are exempt from paying; all the more ribbit. And also the guardian is exempt, for the borrower did not give to the guardian intending he keep it for himself, but only to give to the orphan — and the guardian is only an intermediary of sin and is not in the reckoning. So wrote Beit Yosef in the name of the Rashba.'],
  ['But in sight. And he just took a while held in a loyal orphanage regarding the orphans in the oath that the rabbi came to them and they lose what the pig is:', 'But with evidence. And plainly as long as he holds the orphans\' money he is believed regarding the orphans with an oath that the ribbit came to them and they lose what this person returned of the ribbit.'],
  ['And finally, K. Even if they were given protonies, and they were also snailed in the fire of the sages, and they were standing in their hands:', 'And at the end, one hundred twenty. Even if the perutot cheapened; and likewise two se\'ah of wheat for three — even if the wheat cheapened and three stood at the value of two.'],
]);

// siman_162/beur-hagra
fixLines(`${BASE}/siman_162/beur-hagra/part-001.txt`, [
  ['Even as a. Dr. D. D. D. D.C., and I give you to their fates, and I will give you a blessing to the Lord, and he will give you the name of the Lord of the Levites, and he will say:', 'Even, etc. Meaning even though we say there "and I give you at the threshing floor" — it is not precise; and the Rosh and Tosafot there s.v. halveni explained he states a novelty — see there and Be\'er HaGolah.'],
  ['And yes, yes. Name of "A":', 'And likewise, etc. There 45a.'],
  ['If there is no . As a result of the P.D., D. D.D. and P. B.D. in a statement:', 'And if there is none, etc. As stated end of chapter 4 of Gittin (37a) and in the last chapter of Shevi\'it.'],
  ['He was a prisoner, but a quaint. A.C. B. K. B. K.C., and therefore he said credit and credit in the Qur\'an (K.A.) and the S. R. R. R.R.R', 'He had, etc. but, etc. 63b — no need, etc. — teaches us: since, etc. — unlike a deposit; and therefore he said credit, and as stated in the last chapter of Pesachim (113a) and see above siman 258 seif 7.'],
  ['and known as ". A.C.:', 'And it is known, etc. See Shach s.k. 7, 9.'],
  ['Hello, yes. The hand of the owner on the bottom:', 'The borrower, etc. For we rule that the hand of the document-holder is on the lower side.'],
  ['And there is no word like. In the midst of the sages, and in the midst of the sages:', 'And the lender may not, etc. See Choshen Mishpat siman 67 seif 22 — requires study; and so challenged the Taz.'],
]);
