import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import ErrorBoundary from "./lib/ErrorBoundary.jsx";
import "./web.css";

// Register the Workbox service worker (generated by vite-plugin-pwa).
// Standalone native builds (Capacitor / WebView APK) bundle corpus in assets — no SW.
if (typeof window !== "undefined" && !import.meta.env.VITE_STANDALONE) {
  import("virtual:pwa-register")
    .then(({ registerSW }) => {
      registerSW({
        onOfflineReady() {
          window.dispatchEvent(new CustomEvent("pwa-offline-ready"));
        },
        onNeedRefresh() {
          // Silent auto-update — new SW activates on next tab open.
        },
        onRegistered(registration) {
          if (registration?.installing) {
            window.dispatchEvent(new CustomEvent("pwa-installing"));
            registration.installing.addEventListener("statechange", (e) => {
              if (e.target.state === "installed") {
                window.dispatchEvent(new CustomEvent("pwa-offline-ready"));
              }
            });
          }
        },
        onRegisterError(error) {
          console.warn("PWA service worker registration failed:", error);
        },
      });
    })
    .catch(() => {
      // virtual:pwa-register only exists in a Vite PWA build — ignore in dev/test.
    });
}

function showBootError(rootEl, err) {
  const msg = err?.message || String(err);
  rootEl.innerHTML =
    `<div style="margin:2rem;font-family:Georgia,serif;max-width:40rem">` +
    `<p style="color:#a63d3d;font-weight:700">React failed to start</p>` +
    `<pre style="white-space:pre-wrap;font-size:13px">${msg.replace(/</g, "&lt;")}</pre></div>`;
  console.error("[oc-web-reader]", err);
}

const rootEl = document.getElementById("root");
if (!rootEl) {
  document.body.innerHTML = "<p style='margin:2rem'>Missing #root element.</p>";
} else {
  try {
    createRoot(rootEl).render(
      <StrictMode>
        <ErrorBoundary>
          <App />
        </ErrorBoundary>
      </StrictMode>
    );
  } catch (err) {
    showBootError(rootEl, err);
  }
}
